{
    matrix_id: '843',
    name: 'm3plates',
    group: 'Cunningham',
    description: 'FE mass matrix, 3 plates meeting at a line. A. Cunningham',
    author: 'A. Cunningham',
    editor: 'T. Davis',
    date: '2002',
    kind: 'acoustics problem',
    problem_2D_or_3D: '1',
    num_rows: '11107',
    num_cols: '11107',
    nonzeros: '6639',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '11107',
    num_dmperm_blocks: '6641',
    structural_full_rank: 'false',
    structural_rank: '6639',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.628082e-01',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '6639',
    sprank_minus_rank: '0',
    null_space_dimension: '4468',
    full_numerical_rank: 'no',
    svd_gap: 'Inf',
}
