{
    matrix_id: '1201',
    name: 'Hamrle3',
    group: 'Hamrle',
    description: 'Hamrle/Hamrle3 circuit simulation matrix',
    author: 'J. Hamrle',
    editor: 'T. Davis',
    date: '2004',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '1447360',
    num_cols: '1447360',
    nonzeros: '5514242',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '1447360',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'sparse 1447360-by-1
',
}
