{
    matrix_id: '2816',
    name: 'power197k',
    group: 'PowerSystem',
    description: 'power system matrix',
    author: 'anonymous',
    editor: 'T. Davis',
    date: '2017',
    kind: 'power network problem',
    problem_2D_or_3D: '0',
    num_rows: '197156',
    num_cols: '197156',
    nonzeros: '805839',
    num_explicit_zeros: '2892518',
    num_strongly_connected_components: '25628',
    num_dmperm_blocks: '25675',
    structural_full_rank: 'true',
    structural_rank: '197156',
    pattern_symmetry: '0.214',
    numeric_symmetry: '0.024',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    image_files: 'power197k.png,power197k_dmperm.png,power197k_scc.png,',
}
