{
    matrix_id: '379',
    name: 'vibrobox',
    group: 'Cote',
    description: 'Vibroacoustic problem (flexible box, structure only) Andre Cote',
    author: 'A. Cote',
    editor: 'T. Davis',
    date: '1997',
    kind: 'acoustics problem',
    problem_2D_or_3D: '1',
    num_rows: '12328',
    num_cols: '12328',
    nonzeros: '301700',
    num_explicit_zeros: '41128',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '12328',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '4.025729e+11',
    min_singular_value: '3.840941e-08',
    condition_number: '1.048110e+19',
    svd_rank: '12322',
    sprank_minus_rank: '6',
    null_space_dimension: '6',
    full_numerical_rank: 'no',
    svd_gap: '1816974.290323',
}
