{
    matrix_id: '866',
    name: 'barth4',
    group: 'Pothen',
    description: 'barth4, with coordinates.  From NASA, collected by Alex Pothen',
    author: 'NASA',
    editor: 'G. Kumfert, A. Pothen',
    date: '2003',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '6019',
    num_cols: '6019',
    nonzeros: '40965',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '6019',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    aux_fields: 'coord: full 6019-by-2
',    norm: '7.055621e+00',
    min_singular_value: '3.099209e-04',
    condition_number: '2.276587e+04',
    svd_rank: '6019',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'barth4.png,barth4_gplot.png,barth4_svd.png,barth4_graph.gif,',
}
