{
    matrix_id: '867',
    name: 'barth5',
    group: 'Pothen',
    description: 'barth5, with coordinates.  From NASA, collected by Alex Pothen',
    author: 'NASA',
    editor: 'G. Kumfert, A. Pothen',
    date: '2003',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '15606',
    num_cols: '15606',
    nonzeros: '107362',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '15606',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    aux_fields: 'coord: full 15606-by-2
',    norm: '7.109776e+00',
    min_singular_value: '5.009717e-04',
    condition_number: '1.419197e+04',
    svd_rank: '15606',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'barth5.png,barth5_gplot.png,barth5_svd.png,barth5_graph.gif,',
}
