{
    matrix_id: '869',
    name: 'bodyy5',
    group: 'Pothen',
    description: 'bodyy5, with coordinates.  From NASA, collected by Alex Pothen',
    author: 'NASA',
    editor: 'G. Kumfert, A. Pothen',
    date: '2003',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '18589',
    num_cols: '18589',
    nonzeros: '128853',
    num_explicit_zeros: '428',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '18589',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    aux_fields: 'coord: full 18589-by-2
',    norm: '8.040023e+03',
    min_singular_value: '1.021171e+00',
    condition_number: '7.873336e+03',
    svd_rank: '18589',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'bodyy5.png,bodyy5_gplot.png,bodyy5_svd.png,bodyy5_graph.gif,',
}
