{
    matrix_id: '871',
    name: 'commanche_dual',
    group: 'Pothen',
    description: 'commanche_dual, with coordinates.  From NASA, collected by Alex Pothen',
    author: 'NASA',
    editor: 'G. Kumfert, A. Pothen',
    date: '2003',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '7920',
    num_cols: '7920',
    nonzeros: '31680',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '7920',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    aux_fields: 'coord: full 7920-by-3
',    norm: '4.000000e+00',
    min_singular_value: '4.918427e-04',
    condition_number: '8.132682e+03',
    svd_rank: '7920',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'commanche_dual.png,commanche_dual_gplot.png,commanche_dual_svd.png,commanche_dual_graph.gif,',
}
