{
    matrix_id: '876',
    name: 'mesh2em5',
    group: 'Pothen',
    description: 'mesh2em5, with coordinates.  From NASA, collected by Alex Pothen',
    author: 'NASA',
    editor: 'G. Kumfert, A. Pothen',
    date: '2003',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '306',
    num_cols: '306',
    nonzeros: '2018',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '306',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    aux_fields: 'coord: full 306-by-2
',    norm: '2.474846e+02',
    min_singular_value: '1.003257e+00',
    condition_number: '2.466811e+02',
    svd_rank: '306',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'mesh2em5.png,mesh2em5_gplot.png,mesh2em5_svd.png,mesh2em5_graph.gif,',
}
