{
    matrix_id: '884',
    name: 'sphere3',
    group: 'Pothen',
    description: 'sphere3, with coordinates.  From NASA, collected by Alex Pothen',
    author: 'NASA',
    editor: 'G. Kumfert, A. Pothen',
    date: '2003',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '258',
    num_cols: '258',
    nonzeros: '1794',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '258',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    aux_fields: 'coord: full 258-by-3
',    norm: '6.972454e+00',
    min_singular_value: '1.074436e-16',
    condition_number: '64894068214217320',
    svd_rank: '253',
    sprank_minus_rank: '5',
    null_space_dimension: '5',
    full_numerical_rank: 'no',
    svd_gap: '84442454502361.062500',
    image_files: 'sphere3.png,sphere3_gplot.png,sphere3_svd.png,sphere3_graph.gif,',
}
