{
    matrix_id: '886',
    name: 'tandem_vtx',
    group: 'Pothen',
    description: 'tandem_vtx, with coordinates.  From NASA, collected by Alex Pothen',
    author: 'NASA',
    editor: 'G. Kumfert, A. Pothen',
    date: '2003',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '18454',
    num_cols: '18454',
    nonzeros: '253350',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '18454',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    aux_fields: 'coord: full 18454-by-3
',    norm: '1.530871e+01',
    min_singular_value: '9.130960e-05',
    condition_number: '1.676572e+05',
    svd_rank: '18454',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'tandem_vtx.png,tandem_vtx_gplot.png,tandem_vtx_svd.png,tandem_vtx_graph.gif,',
}
