{
    matrix_id: '885',
    name: 'tandem_dual',
    group: 'Pothen',
    description: 'tandem_dual, with coordinates.  From NASA, collected by Alex Pothen',
    author: 'NASA',
    editor: 'G. Kumfert, A. Pothen',
    date: '2003',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '94069',
    num_cols: '94069',
    nonzeros: '460493',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '94069',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    aux_fields: 'coord: full 94069-by-3
',    image_files: 'tandem_dual.png,tandem_dual_gplot.png,tandem_dual_graph.gif,',
}
