{
    matrix_id: '809',
    name: 'shyy161',
    group: 'Shyy',
    description: 'Wei Shyy, Univ. Florida. CFD/Navier-Stokes,viscous flow, fully coupled',
    author: 'W. Shyy',
    editor: 'T. Davis',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '76480',
    num_cols: '76480',
    nonzeros: '329762',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '321',
    num_dmperm_blocks: '25761',
    structural_full_rank: 'true',
    structural_rank: '76480',
    pattern_symmetry: '0.726',
    numeric_symmetry: '0.182',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
}
