{
    matrix_id: '810',
    name: 'shyy41',
    group: 'Shyy',
    description: 'Wei Shyy, Univ. Florida. CFD/Navier-Stokes,viscous flow, fully coupled',
    author: 'W. Shyy',
    editor: 'T. Davis',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '4720',
    num_cols: '4720',
    nonzeros: '20042',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '81',
    num_dmperm_blocks: '1641',
    structural_full_rank: 'true',
    structural_rank: '4720',
    pattern_symmetry: '0.723',
    numeric_symmetry: '0.184',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.886999e+02',
    min_singular_value: '4.934278e-20',
    condition_number: '3.824266e+21',
    svd_rank: '4712',
    sprank_minus_rank: '8',
    null_space_dimension: '8',
    full_numerical_rank: 'no',
    svd_gap: '13091.559175',
}
