{
    matrix_id: '1404',
    name: 'Kaufhold',
    group: 'MathWorks',
    description: 'John Kaufhold, GE.  Triggers bug in LU in MATLAB 6.5 on Windows (not Linux)',
    author: 'Kaufhold',
    editor: 'T. Davis',
    date: '2006',
    kind: 'counter-example problem',
    problem_2D_or_3D: '0',
    num_rows: '8765',
    num_cols: '8765',
    nonzeros: '42471',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '256',
    num_dmperm_blocks: '256',
    structural_full_rank: 'true',
    structural_rank: '8765',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.778',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '999999999989183',
    min_singular_value: '2.066197e+00',
    condition_number: '4.839809e+14',
    svd_rank: '8759',
    sprank_minus_rank: '6',
    null_space_dimension: '6',
    full_numerical_rank: 'no',
    svd_gap: '2.298238',
    image_files: 'Kaufhold.png,Kaufhold_dmperm.png,Kaufhold_svd.png,Kaufhold_graph.gif,',
}
