{
    matrix_id: '1378',
    name: 'Sieber',
    group: 'MathWorks',
    description: 'Default tol and symtol not sufficient. Jan Sieber, Univ Bristol',
    author: 'Sieber',
    editor: 'T. Davis',
    date: '2006',
    kind: 'counter-example problem',
    problem_2D_or_3D: '0',
    num_rows: '2290',
    num_cols: '2290',
    nonzeros: '14873',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '2290',
    pattern_symmetry: '0.727',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 2290-by-1
',
    norm: '4.083798e+05',
    min_singular_value: '8.851824e-04',
    condition_number: '4.613510e+08',
    svd_rank: '2290',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'Sieber.png,Sieber_svd.png,Sieber_APlusAT_graph.gif,Sieber_graph.gif,',
}
