{
    matrix_id: '1328',
    name: 'tomography',
    group: 'MathWorks',
    description: 'The MathWorks, Inc: Earth science matrix, from David Yang',
    author: 'D.Yang',
    editor: 'T. Davis',
    date: '2003',
    kind: 'computer graphics/vision problem',
    problem_2D_or_3D: '1',
    num_rows: '500',
    num_cols: '500',
    nonzeros: '28726',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '37',
    num_dmperm_blocks: '37',
    structural_full_rank: 'true',
    structural_rank: '500',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.933',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.794368e+07',
    min_singular_value: '3.811163e-01',
    condition_number: '4.708190e+07',
    svd_rank: '500',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'tomography.png,tomography_dmperm.png,tomography_svd.png,tomography_graph.gif,',
}
