{
    matrix_id: '283',
    name: 'onetone1',
    group: 'ATandT',
    description: 'AT&T,harmonic balance method, one-tone. Approx Jacobian for SSOR precon',
    author: 'R. Melville, D. Long',
    editor: 'T. Davis',
    date: '2001',
    kind: 'frequency-domain circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '36057',
    num_cols: '36057',
    nonzeros: '335552',
    num_explicit_zeros: '5536',
    num_strongly_connected_components: '203',
    num_dmperm_blocks: '3843',
    structural_full_rank: 'true',
    structural_rank: '36057',
    pattern_symmetry: '0.074',
    numeric_symmetry: '0.043',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '3.924015e+03',
    min_singular_value: '4.179443e-04',
    condition_number: '9.388846e+06',
    svd_rank: '36057',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
