{
    matrix_id: '284',
    name: 'onetone2',
    group: 'ATandT',
    description: 'AT&T,harmonic balance method, one-tone. More typical for direct factor.',
    author: 'R. Melville, D. Long',
    editor: 'T. Davis',
    date: '2001',
    kind: 'frequency-domain circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '36057',
    num_cols: '36057',
    nonzeros: '222596',
    num_explicit_zeros: '5032',
    num_strongly_connected_components: '203',
    num_dmperm_blocks: '3843',
    structural_full_rank: 'true',
    structural_rank: '36057',
    pattern_symmetry: '0.113',
    numeric_symmetry: '0.066',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '3.924015e+03',
    min_singular_value: '1.240005e-03',
    condition_number: '3.164515e+06',
    svd_rank: '36057',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
