{
    matrix_id: '285',
    name: 'pre2',
    group: 'ATandT',
    description: 'AT&T,harmonic balance method, large example',
    author: 'R. Melville, D. Long',
    editor: 'T. Davis',
    date: '2001',
    kind: 'frequency-domain circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '659033',
    num_cols: '659033',
    nonzeros: '5834044',
    num_explicit_zeros: '125238',
    num_strongly_connected_components: '391',
    num_dmperm_blocks: '29282',
    structural_full_rank: 'true',
    structural_rank: '659033',
    pattern_symmetry: '0.332',
    numeric_symmetry: '0.065',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
}
