{
    matrix_id: '286',
    name: 'twotone',
    group: 'ATandT',
    description: 'AT&T,harmonic balance method, two-tone. More off-diag nz than onetone',
    author: 'R. Melville, D. Long',
    editor: 'T. Davis',
    date: '2001',
    kind: 'frequency-domain circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '120750',
    num_cols: '120750',
    nonzeros: '1206265',
    num_explicit_zeros: '17959',
    num_strongly_connected_components: '5',
    num_dmperm_blocks: '13135',
    structural_full_rank: 'true',
    structural_rank: '120750',
    pattern_symmetry: '0.245',
    numeric_symmetry: '0.106',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
}
