{
    matrix_id: '1269',
    name: 'm_t1',
    group: 'DNVS',
    description: 'DNV-Ex 1 : Tubular joint-1999-01-17',
    author: 'C. Damhaug',
    editor: 'J. Koster',
    date: '1999',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '97578',
    num_cols: '97578',
    nonzeros: '9753570',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '97578',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
}
