{
    matrix_id: '1281',
    name: 'shipsec8',
    group: 'DNVS',
    description: 'DNV-Ex 6 : Ship section/detail from production run-1999-01-17',
    author: 'C. Damhaug',
    editor: 'J. Koster',
    date: '1999',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '114919',
    num_cols: '114919',
    nonzeros: '3303553',
    num_explicit_zeros: '3349846',
    num_strongly_connected_components: '49',
    num_dmperm_blocks: '49',
    structural_full_rank: 'true',
    structural_rank: '114919',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
}
