{
    matrix_id: '1285',
    name: 'troll',
    group: 'DNVS',
    description: 'Gould, Hu, & Scott: from Christian Damhaug',
    author: 'C. Damhaug',
    editor: 'N. Gould, Y. Hu, J. Scott',
    date: '2004',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '213453',
    num_cols: '213453',
    nonzeros: '11985111',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '213453',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
}
