{
    matrix_id: '445',
    name: 'garon2',
    group: 'Garon',
    description: '2D FEM, Navier-Stokes, CFD. Square w/ inlet and outlet on opp. sides',
    author: 'A. Garon',
    editor: 'T. Davis',
    date: '1996',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '13535',
    num_cols: '13535',
    nonzeros: '373235',
    num_explicit_zeros: '17372',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '13535',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.673',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '4.486826e+01',
    min_singular_value: '7.324738e-07',
    condition_number: '6.125579e+07',
    svd_rank: '13535',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'garon2.png,garon2_svd.png,garon2_graph.gif,',
}
