{
    matrix_id: '1401',
    name: 'Chem97ZtZ',
    group: 'Bates',
    description: 'Mixed-effects model from D. Bates, Univ. Wisc.',
    author: 'D. Bates',
    editor: 'T. Davis',
    date: '2006',
    kind: 'statistical/mathematical problem',
    problem_2D_or_3D: '0',
    num_rows: '2541',
    num_cols: '2541',
    nonzeros: '7361',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '131',
    num_dmperm_blocks: '131',
    structural_full_rank: 'true',
    structural_rank: '2541',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '1.331548e+03',
    min_singular_value: '5.386110e+00',
    condition_number: '2.472189e+02',
    svd_rank: '2541',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
