{
    matrix_id: '1291',
    name: 'a0nsdsil',
    group: 'GHS_indef',
    description: 'Gould, Hu, & Scott: linear complementarity problem (CUTEr)',
    author: 'M. Ferris',
    editor: 'N. Gould',
    date: '2004',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '80016',
    num_cols: '80016',
    nonzeros: '355034',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '80016',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    image_files: 'a0nsdsil.png,a0nsdsil_graph.gif,',
}
