{
    matrix_id: '1294',
    name: 'blockqp1',
    group: 'GHS_indef',
    description: 'Gould, Hu, & Scott: QP with block structure (CUTEr)',
    author: 'N. Gould',
    editor: 'N. Gould',
    date: '1994',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '60012',
    num_cols: '60012',
    nonzeros: '640033',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '60012',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    image_files: 'blockqp1.png,blockqp1_graph.gif,',
}
