{
    matrix_id: '1424',
    name: 'bloweybl',
    group: 'GHS_indef',
    description: 'MATRIX FOR WHICH EARLY VERSION OF MA57 FAILS',
    author: 'J. Blowey',
    editor: 'N. Gould',
    date: '1992',
    kind: 'materials problem',
    problem_2D_or_3D: '1',
    num_rows: '30003',
    num_cols: '30003',
    nonzeros: '109999',
    num_explicit_zeros: '10001',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '20003',
    structural_full_rank: 'false',
    structural_rank: '30002',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.000075e+02',
    min_singular_value: '4.331520e-19',
    condition_number: '2.308832e+20',
    svd_rank: '20028',
    sprank_minus_rank: '9974',
    null_space_dimension: '9975',
    full_numerical_rank: 'no',
    svd_gap: '1.163963',
    image_files: 'bloweybl.png,bloweybl_dmperm.png,bloweybl_scc.png,bloweybl_svd.png,bloweybl_graph.gif,',
}
