{
    matrix_id: '1295',
    name: 'bloweya',
    group: 'GHS_indef',
    description: 'Gould, Hu, & Scott: Cahn-Hilliard problem (CUTEr)',
    author: 'J. Blowey',
    editor: 'N. Gould',
    date: '1992',
    kind: 'materials problem',
    problem_2D_or_3D: '1',
    num_rows: '30004',
    num_cols: '30004',
    nonzeros: '150009',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '30004',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.000976e+02',
    min_singular_value: '9.025840e-20',
    condition_number: '1.109012e+21',
    svd_rank: '20050',
    sprank_minus_rank: '9954',
    null_space_dimension: '9954',
    full_numerical_rank: 'no',
    svd_gap: '1.089263',
    image_files: 'bloweya.png,bloweya_svd.png,bloweya_graph.gif,',
}
