{
    matrix_id: '1296',
    name: 'boyd1',
    group: 'GHS_indef',
    description: 'Gould, Hu, & Scott: KKT matrix - convex QP (CUTEr)',
    author: 'N. Gould',
    editor: 'N. Gould',
    date: '2004',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '93279',
    num_cols: '93279',
    nonzeros: '1211231',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '93279',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 93279-by-1
',
    image_files: 'boyd1.png,boyd1_graph.gif,',
}
