{
    matrix_id: '1220',
    name: 'c-55',
    group: 'GHS_indef',
    description: 'Schenk: IBM TJ Watson, Yorktown, nonlinear optimization',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2004',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '32780',
    num_cols: '32780',
    nonzeros: '403450',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '32780',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Revised Nov 2006; relative eps changes to A, right-hand-side added.
Note that this matrix should have been placed in the Schenk_IBMNA/ 
directory when it was first added in August 2004, but moving it now
would disrupt exising users of the collection.                     
',
    b_field: 'full 32780-by-1
',
    norm: '9.404468e+04',
    min_singular_value: '1.982253e-04',
    condition_number: '4.744334e+08',
    svd_rank: '32780',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'c-55.png,c-55_svd.png,c-55_graph.gif,',
}
