{
    matrix_id: '1221',
    name: 'c-58',
    group: 'GHS_indef',
    description: 'Schenk: IBM TJ Watson, Yorktown, nonlinear optimization',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2004',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '37595',
    num_cols: '37595',
    nonzeros: '552551',
    num_explicit_zeros: '6',
    num_strongly_connected_components: '4',
    num_dmperm_blocks: '4',
    structural_full_rank: 'true',
    structural_rank: '37595',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Revised Nov 2006; relative eps changes to A, right-hand-side added.
Note that this matrix should have been placed in the Schenk_IBMNA/ 
directory when it was first added in August 2004, but moving it now
would disrupt exising users of the collection.                     
',
    b_field: 'full 37595-by-1
',
    norm: '5.415471e+04',
    min_singular_value: '1.619823e-03',
    condition_number: '3.343249e+07',
    svd_rank: '37595',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'c-58.png,c-58_dmperm.png,c-58_svd.png,c-58_graph.gif,',
}
