{
    matrix_id: '1232',
    name: 'darcy003',
    group: 'GHS_indef',
    description: 'DISCRETIZATION USING MIXED FE OF DARCY.  ARIOLI AND MANZINI 2002.',
    author: 'M. Arioli, G. Manzini',
    editor: 'N. Gould, Y. Hu, J. Scott',
    date: '2002',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '389874',
    num_cols: '389874',
    nonzeros: '2097566',
    num_explicit_zeros: '3676',
    num_strongly_connected_components: '920',
    num_dmperm_blocks: '920',
    structural_full_rank: 'true',
    structural_rank: '389874',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    image_files: 'darcy003.png,darcy003_dmperm.png,darcy003_scc.png,darcy003_graph.gif,',
}
