{
    matrix_id: '1233',
    name: 'dawson5',
    group: 'GHS_indef',
    description: 'FLAP, PART OF ACTUATOR SYSTEM ON AIRPLANE',
    author: '',
    editor: 'N. Gould, Y. Hu, J. Scott',
    date: '2004',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '51537',
    num_cols: '51537',
    nonzeros: '1010777',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '307',
    num_dmperm_blocks: '307',
    structural_full_rank: 'true',
    structural_rank: '51537',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    image_files: 'dawson5.png,dawson5_dmperm.png,dawson5_graph.gif,',
}
