{
    matrix_id: '1302',
    name: 'dixmaanl',
    group: 'GHS_indef',
    description: 'Gould, Hu, & Scott: Dixon-Maany optimization example (CUTEr)',
    author: 'L. Dixon, Z. Maany',
    editor: 'P. Toint',
    date: '1989',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '60000',
    num_cols: '60000',
    nonzeros: '299998',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '60000',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    image_files: 'dixmaanl.png,dixmaanl_graph.gif,',
}
