{
    matrix_id: '1235',
    name: 'exdata_1',
    group: 'GHS_indef',
    description: 'MATRIX EXDATA FROM STEVE WRIGHT . MA57 SLOWER THAN MA27',
    author: 'S. Wright',
    editor: 'N. Gould, Y. Hu, J. Scott',
    date: '2004',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '6001',
    num_cols: '6001',
    nonzeros: '2269500',
    num_explicit_zeros: '1',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '6001',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '3.695657e+08',
    min_singular_value: '3.486051e-04',
    condition_number: '1.060127e+12',
    svd_rank: '6000',
    sprank_minus_rank: '1',
    null_space_dimension: '1',
    full_numerical_rank: 'no',
    svd_gap: '1.141033',
    image_files: 'exdata_1.png,exdata_1_svd.png,exdata_1_graph.gif,',
}
