{
    matrix_id: '1236',
    name: 'helm2d03',
    group: 'GHS_indef',
    description: 'Helmholtz eq. on a unit square: -div grad u -10000 u = 1, B.C. u = 0',
    author: '',
    editor: 'N. Gould, Y. Hu, J. Scott',
    date: '2004',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '392257',
    num_cols: '392257',
    nonzeros: '2741935',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '392257',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    image_files: 'helm2d03.png,helm2d03_graph.gif,',
}
