{
    matrix_id: '1303',
    name: 'linverse',
    group: 'GHS_indef',
    description: 'Gould, Hu, & Scott: matrix inverse approximation (CUTEr)',
    author: 'P. Toint',
    editor: 'P. Toint',
    date: '1991',
    kind: 'statistical/mathematical problem',
    problem_2D_or_3D: '0',
    num_rows: '11999',
    num_cols: '11999',
    nonzeros: '95977',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '11999',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '1.551683e+01',
    min_singular_value: '3.931686e-03',
    condition_number: '3.946608e+03',
    svd_rank: '11999',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'linverse.png,linverse_svd.png,linverse_graph.gif,',
}
