{
    matrix_id: '1241',
    name: 'mario002',
    group: 'GHS_indef',
    description: 'LARGER MATRIX FROM MARIO FOR WHICH MA47 ANALYSE IS SLOW',
    author: '',
    editor: 'N. Gould, Y. Hu, J. Scott',
    date: '2004',
    kind: 'duplicate 2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '389874',
    num_cols: '389874',
    nonzeros: '2097566',
    num_explicit_zeros: '3676',
    num_strongly_connected_components: '920',
    num_dmperm_blocks: '920',
    structural_full_rank: 'true',
    structural_rank: '389874',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'duplicate of GHS_indef/darcy003
',
    image_files: 'mario002.png,mario002_dmperm.png,mario002_scc.png,mario002_graph.gif,',
}
