{
    matrix_id: '1307',
    name: 'ncvxqp7',
    group: 'GHS_indef',
    description: 'Gould, Hu, & Scott: KKT matrix - nonconvex QP (CUTEr)',
    author: 'N. Gould',
    editor: 'N. Gould',
    date: '1995',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '87500',
    num_cols: '87500',
    nonzeros: '574962',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '87500',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    image_files: 'ncvxqp7.png,ncvxqp7_graph.gif,',
}
