{
    matrix_id: '1308',
    name: 'sparsine',
    group: 'GHS_indef',
    description: 'Gould, Hu, & Scott: structurual optimization (CUTEr)',
    author: 'N. Gould',
    editor: 'N. Gould',
    date: '1995',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '50000',
    num_cols: '50000',
    nonzeros: '1548988',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '50000',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    image_files: 'sparsine.png,sparsine_graph.gif,',
}
