{
    matrix_id: '1309',
    name: 'spmsrtls',
    group: 'GHS_indef',
    description: 'Gould, Hu, & Scott: sparse matrix square root (CUTEr)',
    author: 'N. Gould',
    editor: 'N. Gould',
    date: '2004',
    kind: 'statistical/mathematical problem',
    problem_2D_or_3D: '0',
    num_rows: '29995',
    num_cols: '29995',
    nonzeros: '229947',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '29995',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.465600e+01',
    min_singular_value: '1.034655e-04',
    condition_number: '1.416511e+05',
    svd_rank: '29995',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'spmsrtls.png,spmsrtls_svd.png,spmsrtls_graph.gif,',
}
