{
    matrix_id: '1246',
    name: 'stokes128',
    group: 'GHS_indef',
    description: 'Gould, Hu, & Scott: Stokes equation, from Mario Arioli',
    author: 'M. Arioli',
    editor: 'N. Gould, Y. Hu, J. Scott',
    date: '2004',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '49666',
    num_cols: '49666',
    nonzeros: '558594',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '49666',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    image_files: 'stokes128.png,stokes128_graph.gif,',
}
