{
    matrix_id: '1250',
    name: 'tuma2',
    group: 'GHS_indef',
    description: 'Gould, Hu, & Scott: mine model from Miroslav Tuma',
    author: 'M. Tuma',
    editor: 'N. Gould, Y. Hu, J. Scott',
    date: '2004',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '12992',
    num_cols: '12992',
    nonzeros: '49365',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1101',
    structural_full_rank: 'true',
    structural_rank: '12992',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '4.891338e+00',
    min_singular_value: '2.875117e-03',
    condition_number: '1.701266e+03',
    svd_rank: '12992',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'tuma2.png,tuma2_dmperm.png,tuma2_svd.png,tuma2_graph.gif,',
}
