{
    matrix_id: '966',
    name: 'barrier2-3',
    group: 'Schenk_ISEI',
    description: 'Olaf Schenk, Univ. Basel: Integrated Systems Eng., San Jose, semiconductor device',
    author: 'Integrated Sys. Eng.',
    editor: 'O. Schenk',
    date: '2003',
    kind: 'subsequent semiconductor device problem',
    problem_2D_or_3D: '1',
    num_rows: '113076',
    num_cols: '113076',
    nonzeros: '2129496',
    num_explicit_zeros: '1675572',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '113076',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.198',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: Schenk_ISEI/barrier2-4 first: Schenk_ISEI/barrier2-1
',
    b_field: 'full 113076-by-1
',
    image_files: 'barrier2-3.png,barrier2-3_graph.gif,',
}
