{
    matrix_id: '970',
    name: 'nmos3',
    group: 'Schenk_ISEI',
    description: 'Olaf Schenk, Univ. Basel: Integrated Systems Eng., San Jose, semiconductor device',
    author: 'Integrated Sys. Eng.',
    editor: 'O. Schenk',
    date: '2003',
    kind: 'semiconductor device problem',
    problem_2D_or_3D: '1',
    num_rows: '18588',
    num_cols: '18588',
    nonzeros: '237130',
    num_explicit_zeros: '149464',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '18588',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.167',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 18588-by-1
',
    norm: '4.230778e+12',
    min_singular_value: '5.088074e-09',
    condition_number: '8.315088e+20',
    svd_rank: '11912',
    sprank_minus_rank: '6676',
    null_space_dimension: '6676',
    full_numerical_rank: 'no',
    svd_gap: '1.004245',
    image_files: 'nmos3.png,nmos3_svd.png,nmos3_graph.gif,',
}
