{
    matrix_id: '971',
    name: 'ohne2',
    group: 'Schenk_ISEI',
    description: 'Olaf Schenk, Univ. Basel: Integrated Systems Eng., San Jose, semiconductor device',
    author: 'Integrated Sys. Eng.',
    editor: 'O. Schenk',
    date: '2003',
    kind: 'semiconductor device problem',
    problem_2D_or_3D: '1',
    num_rows: '181343',
    num_cols: '181343',
    nonzeros: '6869939',
    num_explicit_zeros: '4193606',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '181343',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.095',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 181343-by-1
',
    image_files: 'ohne2.png,ohne2_graph.gif,',
}
