{
    matrix_id: '344',
    name: 'bcsstm34',
    group: 'Boeing',
    description: 'NASTRAN BUCKLING PROBLEM, DIFFERENTIAL STIFFNESS MATRIX',
    author: 'R. Grimes',
    editor: 'T. Davis',
    date: '1995',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '588',
    num_cols: '588',
    nonzeros: '24270',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '588',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '6.833084e+00',
    min_singular_value: '6.028736e-06',
    condition_number: '1.133419e+06',
    svd_rank: '588',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
