{
    matrix_id: '346',
    name: 'bcsstm36',
    group: 'Boeing',
    description: 'MASS MATRIX, AUTOMOBILE SHOCK ABSORBER ASSEMBLY',
    author: 'R. Grimes',
    editor: 'T. Davis',
    date: '1995',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '23052',
    num_cols: '23052',
    nonzeros: '320606',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '10881',
    num_dmperm_blocks: '3',
    structural_full_rank: 'false',
    structural_rank: '12172',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '6.053850e-01',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '12172',
    sprank_minus_rank: '0',
    null_space_dimension: '10880',
    full_numerical_rank: 'no',
    svd_gap: '1339034.941656',
}
