{
    matrix_id: '341',
    name: 'bcsstk36',
    group: 'Boeing',
    description: 'STIFFNESS MATRIX, AUTOMOBILE SHOCK ABSORBER ASSEMBLY',
    author: 'R. Grimes',
    editor: 'T. Davis',
    date: '1995',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '23052',
    num_cols: '23052',
    nonzeros: '1143140',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '23052',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '1.775394e+08',
    min_singular_value: '2.388500e-04',
    condition_number: '7.433094e+11',
    svd_rank: '23020',
    sprank_minus_rank: '32',
    null_space_dimension: '32',
    full_numerical_rank: 'no',
    svd_gap: '1.028474',
}
