{
    matrix_id: '355',
    name: 'crystm03',
    group: 'Boeing',
    description: 'FEM CRYSTAL FREE VIBRATION MASS MATRIX',
    author: 'R. Grimes',
    editor: 'T. Davis',
    date: '1995',
    kind: 'materials problem',
    problem_2D_or_3D: '1',
    num_rows: '24696',
    num_cols: '24696',
    nonzeros: '583770',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '3',
    num_dmperm_blocks: '3',
    structural_full_rank: 'true',
    structural_rank: '24696',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '9.788258e-13',
    min_singular_value: '3.707217e-15',
    condition_number: '2.640325e+02',
    svd_rank: '24696',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
