{
    matrix_id: '354',
    name: 'crystm02',
    group: 'Boeing',
    description: 'FEM CRYSTAL FREE VIBRATION MASS MATRIX',
    author: 'R. Grimes',
    editor: 'T. Davis',
    date: '1995',
    kind: 'materials problem',
    problem_2D_or_3D: '1',
    num_rows: '13965',
    num_cols: '13965',
    nonzeros: '322905',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '3',
    num_dmperm_blocks: '3',
    structural_full_rank: 'true',
    structural_rank: '13965',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '1.761409e-12',
    min_singular_value: '7.032307e-15',
    condition_number: '2.504738e+02',
    svd_rank: '13965',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
