{
    matrix_id: '356',
    name: 'ct20stif',
    group: 'Boeing',
    description: 'CT20 ENGINE BLOCK -- STIFFNESS MATRIX',
    author: 'R. Grimes',
    editor: 'T. Davis',
    date: '1995',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '52329',
    num_cols: '52329',
    nonzeros: '2600295',
    num_explicit_zeros: '98168',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '52329',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
}
