{
    matrix_id: '361',
    name: 'msc10848',
    group: 'Boeing',
    description: 'SYMMETRIC TEST MATRIX FROM MSC/NASTRAN KNUCKLEF8.OUT2',
    author: 'R. Grimes',
    editor: 'T. Davis',
    date: '1995',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '10848',
    num_cols: '10848',
    nonzeros: '1229776',
    num_explicit_zeros: '2',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '10848',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '6.297483e+11',
    min_singular_value: '6.318636e+01',
    condition_number: '9.966522e+09',
    svd_rank: '10848',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
