{
    matrix_id: '369',
    name: 'pwtk',
    group: 'Boeing',
    description: 'PRESSURIZED WIND TUNNEL -- STIFFNESS MATRIX',
    author: 'R. Grimes',
    editor: 'T. Davis',
    date: '1995',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '217918',
    num_cols: '217918',
    nonzeros: '11524432',
    num_explicit_zeros: '109992',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '217918',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
}
