{
    matrix_id: '1420',
    name: 'ASIC_680ks',
    group: 'Sandia',
    description: 'Sandia, Xyce circuit simulation matrix (base)',
    author: 'R. Hoekstra',
    editor: 'T. Davis',
    date: '2006',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '682712',
    num_cols: '682712',
    nonzeros: '1693767',
    num_explicit_zeros: '635409',
    num_strongly_connected_components: '583771',
    num_dmperm_blocks: '583771',
    structural_full_rank: 'true',
    structural_rank: '682712',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.006',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
}
