{
    matrix_id: '1415',
    name: 'ASIC_100k',
    group: 'Sandia',
    description: 'Sandia, Xyce circuit simulation matrix (stripped)',
    author: 'R. Hoekstra',
    editor: 'T. Davis',
    date: '2006',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '99340',
    num_cols: '99340',
    nonzeros: '940621',
    num_explicit_zeros: '13542',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '399',
    structural_full_rank: 'true',
    structural_rank: '99340',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.003',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    image_files: 'ASIC_100k.png,ASIC_100k_dmperm.png,ASIC_100k_graph.gif,',
}
