{
    matrix_id: '1417',
    name: 'ASIC_320k',
    group: 'Sandia',
    description: 'Sandia, Xyce circuit simulation matrix (stripped)',
    author: 'R. Hoekstra',
    editor: 'T. Davis',
    date: '2006',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '321821',
    num_cols: '321821',
    nonzeros: '1931828',
    num_explicit_zeros: '703536',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '399',
    structural_full_rank: 'true',
    structural_rank: '321821',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.358',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
}
