{
    matrix_id: '1419',
    name: 'ASIC_680k',
    group: 'Sandia',
    description: 'Sandia, Xyce circuit simulation matrix (stripped)',
    author: 'R. Hoekstra',
    editor: 'T. Davis',
    date: '2006',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '682862',
    num_cols: '682862',
    nonzeros: '2638997',
    num_explicit_zeros: '1232776',
    num_strongly_connected_components: '583523',
    num_dmperm_blocks: '583921',
    structural_full_rank: 'true',
    structural_rank: '682862',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.004',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    image_files: 'ASIC_680k.png,ASIC_680k_dmperm.png,ASIC_680k_scc.png,ASIC_680k_graph.gif,',
}
