{
    matrix_id: '1418',
    name: 'ASIC_320ks',
    group: 'Sandia',
    description: 'Sandia, Xyce circuit simulation matrix (base)',
    author: 'R. Hoekstra',
    editor: 'T. Davis',
    date: '2006',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '321671',
    num_cols: '321671',
    nonzeros: '1316085',
    num_explicit_zeros: '511722',
    num_strongly_connected_components: '249',
    num_dmperm_blocks: '249',
    structural_full_rank: 'true',
    structural_rank: '321671',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.289',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
}
