{
    matrix_id: '1059',
    name: 'fpga_dcop_05',
    group: 'Sandia',
    description: 'Sandia/fpga_dcop_05 circuit simulation matrix. Sandia National Lab.',
    author: 'R. Hoekstra',
    editor: 'T. Davis',
    date: '2003',
    kind: 'subsequent circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '1220',
    num_cols: '1220',
    nonzeros: '5852',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '34',
    num_dmperm_blocks: '194',
    structural_full_rank: 'true',
    structural_rank: '1220',
    pattern_symmetry: '0.821',
    numeric_symmetry: '0.360',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: Sandia/fpga_dcop_06 first: Sandia/fpga_dcop_01
',
    b_field: 'full 1220-by-1
',
    norm: '1.234226e+01',
    min_singular_value: '6.660630e-13',
    condition_number: '1.853017e+13',
    svd_rank: '1206',
    sprank_minus_rank: '14',
    null_space_dimension: '14',
    full_numerical_rank: 'no',
    svd_gap: '19.239854',
}
