{
    matrix_id: '1058',
    name: 'fpga_dcop_04',
    group: 'Sandia',
    description: 'Sandia/fpga_dcop_04 circuit simulation matrix. Sandia National Lab.',
    author: 'R. Hoekstra',
    editor: 'T. Davis',
    date: '2003',
    kind: 'subsequent circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '1220',
    num_cols: '1220',
    nonzeros: '5884',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '34',
    num_dmperm_blocks: '189',
    structural_full_rank: 'true',
    structural_rank: '1220',
    pattern_symmetry: '0.819',
    numeric_symmetry: '0.355',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: Sandia/fpga_dcop_05 first: Sandia/fpga_dcop_01
',
    b_field: 'full 1220-by-1
',
    norm: '9.335671e+00',
    min_singular_value: '1.146130e-13',
    condition_number: '8.145387e+13',
    svd_rank: '1209',
    sprank_minus_rank: '11',
    null_space_dimension: '11',
    full_numerical_rank: 'no',
    svd_gap: '15.899521',
}
