{
    matrix_id: '1064',
    name: 'fpga_dcop_10',
    group: 'Sandia',
    description: 'Sandia/fpga_dcop_10 circuit simulation matrix. Sandia National Lab.',
    author: 'R. Hoekstra',
    editor: 'T. Davis',
    date: '2003',
    kind: 'subsequent circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '1220',
    num_cols: '1220',
    nonzeros: '5884',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '34',
    num_dmperm_blocks: '190',
    structural_full_rank: 'true',
    structural_rank: '1220',
    pattern_symmetry: '0.819',
    numeric_symmetry: '0.332',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: Sandia/fpga_dcop_11 first: Sandia/fpga_dcop_01
',
    b_field: 'full 1220-by-1
',
    norm: '4.947726e+00',
    min_singular_value: '6.663443e-13',
    condition_number: '7.425179e+12',
    svd_rank: '1207',
    sprank_minus_rank: '13',
    null_space_dimension: '13',
    full_numerical_rank: 'no',
    svd_gap: '2.278573',
}
