{
    matrix_id: '1106',
    name: 'fpga_trans_01',
    group: 'Sandia',
    description: 'Sandia/fpga_trans_01 circuit simulation matrix. Sandia National Lab.',
    author: 'R. Hoekstra',
    editor: 'T. Davis',
    date: '2003',
    kind: 'circuit simulation problem sequence',
    problem_2D_or_3D: '0',
    num_rows: '1220',
    num_cols: '1220',
    nonzeros: '7382',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '133',
    structural_full_rank: 'true',
    structural_rank: '1220',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.214',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: Sandia/fpga_trans_02 first: Sandia/fpga_trans_01
',
    b_field: 'full 1220-by-1
',
    norm: '2.887701e+00',
    min_singular_value: '2.364205e-04',
    condition_number: '1.221426e+04',
    svd_rank: '1220',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
