{
    matrix_id: '1109',
    name: 'mult_dcop_01',
    group: 'Sandia',
    description: 'Sandia/mult_dcop_01 circuit simulation matrix. Sandia National Lab.',
    author: 'R. Hoekstra',
    editor: 'T. Davis',
    date: '2003',
    kind: 'circuit simulation problem sequence',
    problem_2D_or_3D: '0',
    num_rows: '25187',
    num_cols: '25187',
    nonzeros: '193276',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '107',
    num_dmperm_blocks: '7417',
    structural_full_rank: 'true',
    structural_rank: '25187',
    pattern_symmetry: '0.614',
    numeric_symmetry: '0.003',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: Sandia/mult_dcop_02 first: Sandia/mult_dcop_01
',
    b_field: 'full 25187-by-1
',
    norm: '1.125277e+00',
    min_singular_value: '5.235128e-13',
    condition_number: '2.149474e+12',
    svd_rank: '25165',
    sprank_minus_rank: '22',
    null_space_dimension: '22',
    full_numerical_rank: 'no',
    svd_gap: '2.632687',
}
