{
    matrix_id: '1140',
    name: 'oscil_dcop_29',
    group: 'Sandia',
    description: 'Sandia/oscil_dcop_29 circuit simulation matrix. Sandia National Lab.',
    author: 'R. Hoekstra',
    editor: 'T. Davis',
    date: '2003',
    kind: 'subsequent circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '430',
    num_cols: '430',
    nonzeros: '1544',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '9',
    num_dmperm_blocks: '31',
    structural_full_rank: 'true',
    structural_rank: '430',
    pattern_symmetry: '0.976',
    numeric_symmetry: '0.698',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: Sandia/oscil_dcop_30 first: Sandia/oscil_dcop_01
',
    b_field: 'full 430-by-1
',
    norm: '2.001004e+06',
    min_singular_value: '8.291781e-14',
    condition_number: '2.413238e+19',
    svd_rank: '425',
    sprank_minus_rank: '5',
    null_space_dimension: '5',
    full_numerical_rank: 'no',
    svd_gap: '14.127822',
}
