{
    matrix_id: '1130',
    name: 'oscil_dcop_19',
    group: 'Sandia',
    description: 'Sandia/oscil_dcop_19 circuit simulation matrix. Sandia National Lab.',
    author: 'R. Hoekstra',
    editor: 'T. Davis',
    date: '2003',
    kind: 'subsequent circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '430',
    num_cols: '430',
    nonzeros: '1544',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '9',
    num_dmperm_blocks: '31',
    structural_full_rank: 'true',
    structural_rank: '430',
    pattern_symmetry: '0.976',
    numeric_symmetry: '0.698',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: Sandia/oscil_dcop_20 first: Sandia/oscil_dcop_01
',
    b_field: 'full 430-by-1
',
    norm: '2.001004e+06',
    min_singular_value: '1.603037e-09',
    condition_number: '1.248258e+15',
    svd_rank: '427',
    sprank_minus_rank: '3',
    null_space_dimension: '3',
    full_numerical_rank: 'no',
    svd_gap: '14.172982',
}
