{
    matrix_id: '1169',
    name: 'oscil_trans_01',
    group: 'Sandia',
    description: 'Sandia/oscil_trans_01 circuit simulation matrix. Sandia National Lab.',
    author: 'R. Hoekstra',
    editor: 'T. Davis',
    date: '2003',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '430',
    num_cols: '430',
    nonzeros: '1614',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '9',
    num_dmperm_blocks: '19',
    structural_full_rank: 'true',
    structural_rank: '430',
    pattern_symmetry: '0.974',
    numeric_symmetry: '0.718',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 430-by-1
',
    norm: '2.001004e+06',
    min_singular_value: '2.151446e-05',
    condition_number: '9.300740e+10',
    svd_rank: '430',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
