{
    matrix_id: '936',
    name: 'nd3k',
    group: 'ND',
    description: 'ND problem set, matrix nd3k',
    author: 'author unknown',
    editor: 'T. Davis',
    date: '2003',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '9000',
    num_cols: '9000',
    nonzeros: '3279690',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '9000',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '1.276003e+02',
    min_singular_value: '8.142296e-06',
    condition_number: '1.567130e+07',
    svd_rank: '9000',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
