{
    matrix_id: '863',
    name: 'kim2',
    group: 'Kim',
    description: '2D 676-by-676 complex mesh.  Wonsik Kim, Korea.',
    author: 'W. Kim',
    editor: 'T. Davis',
    date: '2002',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '456976',
    num_cols: '456976',
    nonzeros: '11330020',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '456976',
    pattern_symmetry: '0.997',
    numeric_symmetry: '0.000',
    rb_type: 'complex',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    image_files: 'kim2.png,kim2_APlusAT_graph.gif,kim2_graph.gif,',
}
