{
    matrix_id: '289',
    name: 'epb2',
    group: 'Averous',
    description: 'Plate-fin heat exchanger w/flow redistrib(DAE) David.Averous@ensigct.fr',
    author: 'D. Averous',
    editor: 'T. Davis',
    date: '1998',
    kind: 'thermal problem',
    problem_2D_or_3D: '1',
    num_rows: '25228',
    num_cols: '25228',
    nonzeros: '175027',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '25228',
    pattern_symmetry: '0.671',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '3.339903e+00',
    min_singular_value: '1.275289e-03',
    condition_number: '2.618938e+03',
    svd_rank: '25228',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'epb2.png,epb2_svd.png,epb2_APlusAT_graph.gif,epb2_graph.gif,',
}
