{
    matrix_id: '290',
    name: 'epb3',
    group: 'Averous',
    description: 'Plate-fin heat exchanger (large case)    (DAE) David.Averous@ensigct.fr',
    author: 'D. Averous',
    editor: 'T. Davis',
    date: '1998',
    kind: 'thermal problem',
    problem_2D_or_3D: '1',
    num_rows: '84617',
    num_cols: '84617',
    nonzeros: '463625',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '84617',
    pattern_symmetry: '0.667',
    numeric_symmetry: '0.032',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    image_files: 'epb3.png,epb3_APlusAT_graph.gif,epb3_graph.gif,',
}
