{
    matrix_id: '775',
    name: 'nemeth11',
    group: 'Nemeth',
    description: 'Newton-Schultz iteration, Z_k+1=Z_k+(1/2)*(I-(Z_k)^2)*Z_k. This is Z_11',
    author: 'K. Nemeth',
    editor: 'T. Davis',
    date: '1999',
    kind: 'subsequent theoretical/quantum chemistry problem',
    problem_2D_or_3D: '0',
    num_rows: '9506',
    num_cols: '9506',
    nonzeros: '408264',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '9506',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: Nemeth/nemeth12 first: Nemeth/nemeth01
',
    norm: '2.675364e-01',
    min_singular_value: '9.867074e-02',
    condition_number: '2.711405e+00',
    svd_rank: '9506',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
