{
    matrix_id: '1860',
    name: 'ESOC',
    group: 'Springer',
    description: 'European Space Operations Center orbit estimates',
    author: 'T. Springer and F. Dilssner',
    editor: 'T. Davis',
    date: '2007',
    kind: 'least squares problem',
    problem_2D_or_3D: '0',
    num_rows: '327062',
    num_cols: '37830',
    nonzeros: '6019939',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '482',
    num_dmperm_blocks: '74',
    structural_full_rank: 'false',
    structural_rank: '37349',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '8.049535e+07',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '37349',
    sprank_minus_rank: '0',
    null_space_dimension: '481',
    full_numerical_rank: 'no',
    svd_gap: 'Inf',
}
