{
    matrix_id: '888',
    name: 'fv2',
    group: 'Norris',
    description: 'S.Norris, Univ. Auckland. FEM, Laplace eqn 2D 101x101 mesh',
    author: 'S. Norris',
    editor: 'T. Davis',
    date: '2003',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '9801',
    num_cols: '9801',
    nonzeros: '87025',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '9801',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '4.510050e+00',
    min_singular_value: '5.120235e-01',
    condition_number: '8.808286e+00',
    svd_rank: '9801',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
