{
    matrix_id: '890',
    name: 'heart1',
    group: 'Norris',
    description: 'S.Norris, Univ. Auckland. Quasi-static FEM of a heart',
    author: 'S. Norris',
    editor: 'T. Davis',
    date: '2003',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '3557',
    num_cols: '3557',
    nonzeros: '1385317',
    num_explicit_zeros: '2456',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '3557',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.006094e+06',
    min_singular_value: '2.187613e-03',
    condition_number: '4.599050e+08',
    svd_rank: '3557',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
