{
    matrix_id: '894',
    name: 'lung2',
    group: 'Norris',
    description: 'S.Norris, Univ. Auckland. Coupled temp,water vapour transport in lung',
    author: 'S. Norris',
    editor: 'T. Davis',
    date: '2003',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '109460',
    num_cols: '109460',
    nonzeros: '492564',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '109460',
    pattern_symmetry: '0.571',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
}
