{
    matrix_id: '893',
    name: 'lung1',
    group: 'Norris',
    description: 'S.Norris, Univ. Auckland. Coupled temp,water vapour transport in lung',
    author: 'S. Norris',
    editor: 'T. Davis',
    date: '2003',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '1650',
    num_cols: '1650',
    nonzeros: '7419',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '1650',
    pattern_symmetry: '0.571',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '5.169229e+02',
    min_singular_value: '1.056562e-10',
    condition_number: '4.892498e+12',
    svd_rank: '1549',
    sprank_minus_rank: '101',
    null_space_dimension: '101',
    full_numerical_rank: 'no',
    svd_gap: '1.010601',
}
