{
    matrix_id: '897',
    name: 'torso2',
    group: 'Norris',
    description: 'S.Norris, Univ Auckland. finite diff. electro-phys.  2D model of torso',
    author: 'S. Norris',
    editor: 'T. Davis',
    date: '2003',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '115967',
    num_cols: '115967',
    nonzeros: '1033473',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '115967',
    pattern_symmetry: '0.992',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
}
