{
    matrix_id: '2281',
    name: 'human_gene2',
    group: 'Belcastro',
    description: 'Human gene network, Vincenzo Belcastro, TIGEM, Naples, Italy',
    author: 'V. Belcastro',
    editor: 'T. Davis',
    date: '2010',
    kind: 'undirected weighted graph',
    problem_2D_or_3D: '0',
    num_rows: '14340',
    num_cols: '14340',
    nonzeros: '18068388',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '320',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    notes: 'Human gene regulatory network, from analyzing gene expression profiles.
This version of the human gene network is gene oriented.               
',
    norm: '1.382990e+02',
    min_singular_value: '3.607391e-04',
    condition_number: '3.833767e+05',
    svd_rank: '14340',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
