{
    matrix_id: '2280',
    name: 'human_gene1',
    group: 'Belcastro',
    description: 'Human gene network, Vincenzo Belcastro, TIGEM, Naples, Italy',
    author: 'V. Belcastro',
    editor: 'T. Davis',
    date: '2010',
    kind: 'undirected weighted graph',
    problem_2D_or_3D: '0',
    num_rows: '22283',
    num_cols: '22283',
    nonzeros: '24669643',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '410',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    notes: 'Human gene regulatory network, from analyzing gene expression profiles.
This version of the human gene network is probe-set oriented.          
',
    norm: '1.509565e+02',
    min_singular_value: '3.178024e-05',
    condition_number: '4.750011e+06',
    svd_rank: '22283',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
