{
    matrix_id: '406',
    name: 'ex1',
    group: 'FIDAP',
    description: ' TEST MATRIX FROM FIDAP: EX1.MAT',
    author: 'A. Baggag, Y. Saad',
    editor: 'A. Baggag, Y. Saad',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '216',
    num_cols: '216',
    nonzeros: '4317',
    num_explicit_zeros: '35',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '216',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.998',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.301880e-01',
    min_singular_value: '3.947527e-06',
    condition_number: '3.297963e+04',
    svd_rank: '216',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'ex1.png,ex1_svd.png,ex1_graph.gif,',
}
