{
    matrix_id: '411',
    name: 'ex13',
    group: 'FIDAP',
    description: ' TEST MATRIX FROM FIDAP: EX13.MAT',
    author: 'A. Baggag, Y. Saad',
    editor: 'A. Baggag, Y. Saad',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '2568',
    num_cols: '2568',
    nonzeros: '75628',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '2568',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '1.258419e+10',
    min_singular_value: '1.060273e-05',
    condition_number: '1.186882e+15',
    svd_rank: '1434',
    sprank_minus_rank: '1134',
    null_space_dimension: '1134',
    full_numerical_rank: 'no',
    svd_gap: '1.004037',
}
