{
    matrix_id: '416',
    name: 'ex2',
    group: 'FIDAP',
    description: ' TEST MATRIX FROM FIDAP: EX2.MAT',
    author: 'A. Baggag, Y. Saad',
    editor: 'A. Baggag, Y. Saad',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '441',
    num_cols: '441',
    nonzeros: '26839',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '441',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '6.999644e+08',
    min_singular_value: '6.804357e-02',
    condition_number: '1.028700e+10',
    svd_rank: '441',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
