{
    matrix_id: '419',
    name: 'ex22',
    group: 'FIDAP',
    description: ' TEST MATRIX FROM FIDAP: EX22.MAT',
    author: 'A. Baggag, Y. Saad',
    editor: 'A. Baggag, Y. Saad',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '839',
    num_cols: '839',
    nonzeros: '22460',
    num_explicit_zeros: '255',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '839',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.886',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.507261e+01',
    min_singular_value: '4.602209e-04',
    condition_number: '3.275082e+04',
    svd_rank: '839',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
