{
    matrix_id: '420',
    name: 'ex23',
    group: 'FIDAP',
    description: ' TEST MATRIX FROM FIDAP: EX23.MAT',
    author: 'A. Baggag, Y. Saad',
    editor: 'A. Baggag, Y. Saad',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '1409',
    num_cols: '1409',
    nonzeros: '42760',
    num_explicit_zeros: '943',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '1409',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.939',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.672477e+05',
    min_singular_value: '1.576111e-08',
    condition_number: '1.695614e+13',
    svd_rank: '1408',
    sprank_minus_rank: '1',
    null_space_dimension: '1',
    full_numerical_rank: 'no',
    svd_gap: '6.993880',
}
