{
    matrix_id: '421',
    name: 'ex24',
    group: 'FIDAP',
    description: ' TEST MATRIX FROM FIDAP: EX24.MAT',
    author: 'A. Baggag, Y. Saad',
    editor: 'A. Baggag, Y. Saad',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '2283',
    num_cols: '2283',
    nonzeros: '47901',
    num_explicit_zeros: '836',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '2283',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.862',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '8.923057e+01',
    min_singular_value: '2.402282e-04',
    condition_number: '3.714409e+05',
    svd_rank: '2283',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
