{
    matrix_id: '424',
    name: 'ex27',
    group: 'FIDAP',
    description: ' TEST MATRIX FROM FIDAP: EX27.MAT',
    author: 'A. Baggag, Y. Saad',
    editor: 'A. Baggag, Y. Saad',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '974',
    num_cols: '974',
    nonzeros: '37652',
    num_explicit_zeros: '3130',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '974',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.530',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.597768e-01',
    min_singular_value: '2.527644e-07',
    condition_number: '1.027743e+06',
    svd_rank: '974',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
