{
    matrix_id: '425',
    name: 'ex28',
    group: 'FIDAP',
    description: ' TEST MATRIX FROM FIDAP: EX28.MAT',
    author: 'A. Baggag, Y. Saad',
    editor: 'A. Baggag, Y. Saad',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '2603',
    num_cols: '2603',
    nonzeros: '77031',
    num_explicit_zeros: '750',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '2603',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.988',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '9.231391e+01',
    min_singular_value: '4.655199e-04',
    condition_number: '1.983028e+05',
    svd_rank: '2603',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
