{
    matrix_id: '433',
    name: 'ex37',
    group: 'FIDAP',
    description: 'TEST MATRIX FROM FIDAP: EX37.MAT',
    author: 'A. Baggag, Y. Saad',
    editor: 'A. Baggag, Y. Saad',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '3565',
    num_cols: '3565',
    nonzeros: '67591',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1652',
    num_dmperm_blocks: '1652',
    structural_full_rank: 'true',
    structural_rank: '3565',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.954',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.795387e+02',
    min_singular_value: '1.000000e+00',
    condition_number: '1.795387e+02',
    svd_rank: '3565',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
