{
    matrix_id: '436',
    name: 'ex5',
    group: 'FIDAP',
    description: ' TEST MATRIX FROM FIDAP: EX5.MAT',
    author: 'A. Baggag, Y. Saad',
    editor: 'A. Baggag, Y. Saad',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '27',
    num_cols: '27',
    nonzeros: '279',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '27',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '4.359568e+06',
    min_singular_value: '6.555776e-02',
    condition_number: '6.649965e+07',
    svd_rank: '27',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
