{
    matrix_id: '439',
    name: 'ex8',
    group: 'FIDAP',
    description: ' TEST MATRIX FROM FIDAP: EX8.MAT',
    author: 'A. Baggag, Y. Saad',
    editor: 'A. Baggag, Y. Saad',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '3096',
    num_cols: '3096',
    nonzeros: '90841',
    num_explicit_zeros: '15503',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '3096',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.431',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '4.406614e+07',
    min_singular_value: '9.828421e-04',
    condition_number: '4.483542e+10',
    svd_rank: '3096',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
