{
    matrix_id: '377',
    name: 'thermal',
    group: 'Brunetiere',
    description: 'Noel.Brunetiere@lms.univ-poitiers.fr FEM, thermal problem',
    author: 'N. Brunetiere',
    editor: 'T. Davis',
    date: '2000',
    kind: 'thermal problem',
    problem_2D_or_3D: '1',
    num_rows: '3456',
    num_cols: '3456',
    nonzeros: '66528',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '3456',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.073',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.323503e+00',
    min_singular_value: '1.219998e-01',
    condition_number: '1.084840e+01',
    svd_rank: '3456',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
