{
    matrix_id: '842',
    name: 'k3plates',
    group: 'Cunningham',
    description: 'FE stiffness matrix, 3 plates meeting at a line. A. Cunningham',
    author: 'A. Cunningham',
    editor: 'T. Davis',
    date: '2002',
    kind: 'acoustics problem',
    problem_2D_or_3D: '1',
    num_rows: '11107',
    num_cols: '11107',
    nonzeros: '378927',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '11107',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.999',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.995107e+10',
    min_singular_value: '1.326957e-08',
    condition_number: '1503520329361591040',
    svd_rank: '11101',
    sprank_minus_rank: '6',
    null_space_dimension: '6',
    full_numerical_rank: 'no',
    svd_gap: '765.133679',
    image_files: 'k3plates.png,k3plates_svd.png,k3plates_graph.gif,',
}
