{
    matrix_id: '845',
    name: 'qa8fm',
    group: 'Cunningham',
    description: '3D acoustic FE mass matrix. A. Cunningham, Vibro-Acoustic Sciences Inc',
    author: 'A. Cunningham',
    editor: 'T. Davis',
    date: '2002',
    kind: 'acoustics problem',
    problem_2D_or_3D: '1',
    num_rows: '66127',
    num_cols: '66127',
    nonzeros: '1660579',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '66127',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    aux_fields: 'coord: full 66127-by-3
',    image_files: 'qa8fm.png,qa8fm_gplot.png,qa8fm_graph.gif,',
}
