{
    matrix_id: '448',
    name: 'graham1',
    group: 'Graham',
    description: 'Galerkin FE disc. of Nav.Stokes 2phase fluid flow. D Graham, U Illinois',
    author: 'D. Graham',
    editor: 'T. Davis',
    date: '1998',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '9035',
    num_cols: '9035',
    nonzeros: '335472',
    num_explicit_zeros: '32',
    num_strongly_connected_components: '474',
    num_dmperm_blocks: '478',
    structural_full_rank: 'true',
    structural_rank: '9035',
    pattern_symmetry: '0.718',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '8.201310e+04',
    min_singular_value: '6.747215e-10',
    condition_number: '1.215510e+14',
    svd_rank: '8924',
    sprank_minus_rank: '111',
    null_space_dimension: '111',
    full_numerical_rank: 'no',
    svd_gap: '1.015248',
}
