{
    matrix_id: '391',
    name: 'cavity12',
    group: 'DRIVCAV',
    description: 'Driven Cavity  15 x 15, Reynolds number: 400',
    author: 'A. Chapman',
    editor: 'A. Baggag, Y. Saad',
    date: '1996',
    kind: 'subsequent computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '2597',
    num_cols: '2597',
    nonzeros: '76258',
    num_explicit_zeros: '109',
    num_strongly_connected_components: '242',
    num_dmperm_blocks: '242',
    structural_full_rank: 'true',
    structural_rank: '2597',
    pattern_symmetry: '0.937',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: DRIVCAV/cavity13 first: DRIVCAV/cavity10
pattern is the same as DRIVCAV/cavity10       
',
    b_field: 'full 2597-by-1
',
    x_field: 'full 2597-by-1
',
    norm: '1.890643e+01',
    min_singular_value: '4.397233e-06',
    condition_number: '4.299620e+06',
    svd_rank: '2597',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
