{
    matrix_id: '392',
    name: 'cavity13',
    group: 'DRIVCAV',
    description: 'Driven Cavity  15 x 15, Reynolds number: 600',
    author: 'A. Chapman',
    editor: 'A. Baggag, Y. Saad',
    date: '1996',
    kind: 'subsequent computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '2597',
    num_cols: '2597',
    nonzeros: '71601',
    num_explicit_zeros: '4766',
    num_strongly_connected_components: '242',
    num_dmperm_blocks: '242',
    structural_full_rank: 'true',
    structural_rank: '2597',
    pattern_symmetry: '0.937',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: DRIVCAV/cavity14 first: DRIVCAV/cavity10          
pattern is the same as the transpose of DRIVCAV/cavity10
',
    b_field: 'full 2597-by-1
',
    x_field: 'full 2597-by-1
',
    norm: '2.509930e+01',
    min_singular_value: '3.719499e-06',
    condition_number: '6.748032e+06',
    svd_rank: '2597',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
