{
    matrix_id: '404',
    name: 'cavity25',
    group: 'DRIVCAV',
    description: 'Driven Cavity  20 x 20, Reynolds number: 900',
    author: 'A. Chapman',
    editor: 'A. Baggag, Y. Saad',
    date: '1996',
    kind: 'subsequent computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '4562',
    num_cols: '4562',
    nonzeros: '131735',
    num_explicit_zeros: '6452',
    num_strongly_connected_components: '322',
    num_dmperm_blocks: '322',
    structural_full_rank: 'true',
    structural_rank: '4562',
    pattern_symmetry: '0.953',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: DRIVCAV/cavity26 first: DRIVCAV/cavity16          
pattern is the same as the transpose of DRIVCAV/cavity16
',
    b_field: 'full 4562-by-1
',
    x_field: 'full 4562-by-1
',
    norm: '2.790784e+01',
    min_singular_value: '1.010574e-06',
    condition_number: '2.761584e+07',
    svd_rank: '4562',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
