{
    matrix_id: '387',
    name: 'cavity08',
    group: 'DRIVCAV',
    description: 'Driven Cavity  10 x 10, Reynolds number: 600',
    author: 'A. Chapman',
    editor: 'A. Baggag, Y. Saad',
    date: '1996',
    kind: 'subsequent computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '1182',
    num_cols: '1182',
    nonzeros: '29675',
    num_explicit_zeros: '3072',
    num_strongly_connected_components: '162',
    num_dmperm_blocks: '162',
    structural_full_rank: 'true',
    structural_rank: '1182',
    pattern_symmetry: '0.905',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: DRIVCAV/cavity09 first: DRIVCAV/cavity05          
pattern is the same as the transpose of DRIVCAV/cavity05
',
    b_field: 'full 1182-by-1
',
    x_field: 'full 1182-by-1
',
    norm: '3.534293e+01',
    min_singular_value: '1.076056e-05',
    condition_number: '3.284487e+06',
    svd_rank: '1182',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
