{
    matrix_id: '381',
    name: 'cavity02',
    group: 'DRIVCAV',
    description: 'Driven Cavity   5 x  5, Reynolds number: 200',
    author: 'A. Chapman',
    editor: 'A. Baggag, Y. Saad',
    date: '1996',
    kind: 'subsequent computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '317',
    num_cols: '317',
    nonzeros: '5923',
    num_explicit_zeros: '1404',
    num_strongly_connected_components: '82',
    num_dmperm_blocks: '82',
    structural_full_rank: 'true',
    structural_rank: '317',
    pattern_symmetry: '0.804',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: DRIVCAV/cavity03 first: DRIVCAV/cavity01          
pattern is the same as the transpose of DRIVCAV/cavity01
',
    b_field: 'full 317-by-1
',
    x_field: 'full 317-by-1
',
    norm: '2.492917e+01',
    min_singular_value: '3.069812e-04',
    condition_number: '8.120750e+04',
    svd_rank: '317',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
