{
    matrix_id: '1913',
    name: 'cyl6',
    group: 'TKK',
    description: 'Cylindrical shell, non-linear analysis, 3 RHS vectors at step 6.  R Kouhia',
    author: 'R. Kouhia',
    editor: 'T. Davis',
    date: '2008',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '13681',
    num_cols: '13681',
    nonzeros: '714241',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '13681',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'integer',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    notes: 'Matrix problems from Reijo Kouhia, Structural Mechanics, Helsinki  
University of Technology.   http://users.tkk.fi/~kouhia/sparse.html
',
    b_field: 'full 13681-by-3
',
    norm: '3.219698e+02',
    min_singular_value: '1.423350e-113',
    condition_number: '2.262057e+115',
    svd_rank: '2243',
    sprank_minus_rank: '11438',
    null_space_dimension: '11438',
    full_numerical_rank: 'no',
    svd_gap: '59993988908.975151',
}
