{
    matrix_id: '1907',
    name: 'g3rmt3m3',
    group: 'TKK',
    description: 'Cylindrical shell, R/t=1e3, 3noded MITC elements, gamma=G. R Kouhia',
    author: 'R. Kouhia',
    editor: 'T. Davis',
    date: '2008',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '5357',
    num_cols: '5357',
    nonzeros: '207695',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '5357',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    notes: 'Matrix problems from Reijo Kouhia, Structural Mechanics, Helsinki  
University of Technology.   http://users.tkk.fi/~kouhia/sparse.html
',
    b_field: 'full 5357-by-1
',
    aux_fields: 'coord: full 5357-by-3
',    norm: '4.174793e+01',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '938',
    sprank_minus_rank: '4419',
    null_space_dimension: '4419',
    full_numerical_rank: 'no',
    svd_gap: '185688264549.858612',
}
