{
    matrix_id: '1911',
    name: 'plbuckle',
    group: 'TKK',
    description: 'Double eigenvalue plate buckling; stiffness matrix K and initial stress G',
    author: 'R. Kouhia',
    editor: 'T. Davis',
    date: '2008',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '1282',
    num_cols: '1282',
    nonzeros: '30644',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '1282',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    notes: 'Matrix problems from Reijo Kouhia, Structural Mechanics, Helsinki  
University of Technology.   http://users.tkk.fi/~kouhia/sparse.html
',
    aux_fields: 'G: sparse 1282-by-1282
',    norm: '2.097147e+06',
    min_singular_value: '1.634155e+00',
    condition_number: '1.283322e+06',
    svd_rank: '1282',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
