{
    matrix_id: '1915',
    name: 'tube2',
    group: 'TKK',
    description: 'Tube problem from R. Kouhia',
    author: 'R. Kouhia',
    editor: 'T. Davis',
    date: '2008',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '21498',
    num_cols: '21498',
    nonzeros: '897056',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '21498',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'integer',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    notes: 'Matrix problems from Reijo Kouhia, Structural Mechanics, Helsinki  
University of Technology.   http://users.tkk.fi/~kouhia/sparse.html
',
    b_field: 'full 21498-by-1
',
    norm: '1.730289e+02',
    min_singular_value: '4.054712e-202',
    condition_number: '4.267355e+203',
    svd_rank: '3583',
    sprank_minus_rank: '17915',
    null_space_dimension: '17915',
    full_numerical_rank: 'no',
    svd_gap: '8417601519.588204',
}
