{
    matrix_id: '1848',
    name: 'Dubcova2',
    group: 'UTEP',
    description: 'Univ. Texas at El Paso, from a PDE solver',
    author: 'L. Dubcova, J. Cerveny, and P. Solin',
    editor: 'T. Davis',
    date: '2007',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '65025',
    num_cols: '65025',
    nonzeros: '1030225',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '65025',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    image_files: 'Dubcova2.png,Dubcova2_graph.gif,',
}
