{
    matrix_id: '1847',
    name: 'Dubcova1',
    group: 'UTEP',
    description: 'Univ. Texas at El Paso, from a PDE solver',
    author: 'L. Dubcova, J. Cerveny, and P. Solin',
    editor: 'T. Davis',
    date: '2007',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '16129',
    num_cols: '16129',
    nonzeros: '253009',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '16129',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '4.796329e+00',
    min_singular_value: '4.810182e-03',
    condition_number: '9.971199e+02',
    svd_rank: '16129',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'Dubcova1.png,Dubcova1_svd.png,Dubcova1_graph.gif,',
}
