{
    matrix_id: '1325',
    name: 'robot',
    group: 'Morandini',
    description: 'Marco Morandini, 6 gdl COMAU robot',
    author: 'M. Morandini',
    editor: 'T. Davis',
    date: '2006',
    kind: 'robotics problem',
    problem_2D_or_3D: '1',
    num_rows: '120',
    num_cols: '120',
    nonzeros: '870',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '19',
    structural_full_rank: 'true',
    structural_rank: '120',
    pattern_symmetry: '0.218',
    numeric_symmetry: '0.053',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.505063e+02',
    min_singular_value: '3.478489e-07',
    condition_number: '4.326773e+08',
    svd_rank: '120',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
