{
    matrix_id: '1326',
    name: 'rotor1',
    group: 'Morandini',
    description: 'Marco Morandini, small helicoptor rotor model',
    author: 'M. Morandini',
    editor: 'T. Davis',
    date: '2006',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '100',
    num_cols: '100',
    nonzeros: '708',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '48',
    structural_full_rank: 'true',
    structural_rank: '100',
    pattern_symmetry: '0.514',
    numeric_symmetry: '0.072',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '5.000245e+04',
    min_singular_value: '2.117115e-08',
    condition_number: '2.361820e+12',
    svd_rank: '100',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
