{
    matrix_id: '1327',
    name: 'rotor2',
    group: 'Morandini',
    description: 'Marco Morandini, large helicoptor rotor model',
    author: 'M. Morandini',
    editor: 'T. Davis',
    date: '2006',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '791',
    num_cols: '791',
    nonzeros: '10685',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '7',
    num_dmperm_blocks: '36',
    structural_full_rank: 'true',
    structural_rank: '791',
    pattern_symmetry: '0.234',
    numeric_symmetry: '0.116',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '8.958094e+05',
    min_singular_value: '1.305127e-07',
    condition_number: '6.863771e+12',
    svd_rank: '791',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
