{
    matrix_id: '1422',
    name: 'apache1',
    group: 'GHS_psdef',
    description: 'SPD matrix (finite difference 3D) from APACHE small',
    author: '',
    editor: 'N. Gould, Y. Hu, J. Scott',
    date: '2006',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '80800',
    num_cols: '80800',
    nonzeros: '542184',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '80800',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    image_files: 'apache1.png,apache1_graph.gif,',
}
