{
    matrix_id: '1257',
    name: 'crankseg_1',
    group: 'GHS_psdef',
    description: 'OUTPUT4-Matrix',
    author: 'S. Mayer',
    editor: 'J. Koster',
    date: '2004',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '52804',
    num_cols: '52804',
    nonzeros: '10614210',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '52804',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    image_files: 'crankseg_1.png,crankseg_1_graph.gif,',
}
