{
    matrix_id: '1310',
    name: 'cvxbqp1',
    group: 'GHS_psdef',
    description: 'Gould, Hu, & Scott: barrier Hessian from convex QP (CUTEr)',
    author: 'N. Gould',
    editor: 'N. Gould',
    date: '1995',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '50000',
    num_cols: '50000',
    nonzeros: '349968',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '6',
    num_dmperm_blocks: '6',
    structural_full_rank: 'true',
    structural_rank: '50000',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    image_files: 'cvxbqp1.png,cvxbqp1_dmperm.png,cvxbqp1_graph.gif,',
}
