{
    matrix_id: '1262',
    name: 'ford1',
    group: 'GHS_psdef',
    description: 'Gould, Hu, & Scott: car surface mesh, from Pothen & Kumfert',
    author: 'G. Kumfert, A. Pothen',
    editor: 'N. Gould, Y. Hu, J. Scott',
    date: '2004',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '18728',
    num_cols: '18728',
    nonzeros: '101576',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '18728',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '1.397052e+01',
    min_singular_value: '7.196077e-50',
    condition_number: '1.941408e+50',
    svd_rank: '18194',
    sprank_minus_rank: '534',
    null_space_dimension: '534',
    full_numerical_rank: 'no',
    svd_gap: '9906398194.014740',
    image_files: 'ford1.png,ford1_svd.png,ford1_graph.gif,',
}
