{
    matrix_id: '1311',
    name: 'gridgena',
    group: 'GHS_psdef',
    description: 'Gould, Hu, & Scott: grid generation optimization (CUTEr)',
    author: 'P. Barrera, A. Perez, L. Castellanos',
    editor: 'P. Toint',
    date: '1991',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '48962',
    num_cols: '48962',
    nonzeros: '512084',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '48962',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    image_files: 'gridgena.png,gridgena_graph.gif,',
}
