{
    matrix_id: '1267',
    name: 'inline_1',
    group: 'GHS_psdef',
    description: 'stiffness matrix',
    author: 'S. Mayer',
    editor: 'J. Koster',
    date: '2004',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '503712',
    num_cols: '503712',
    nonzeros: '36816170',
    num_explicit_zeros: '172',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '503712',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    image_files: 'inline_1.png,inline_1_graph.gif,',
}
