{
    matrix_id: '1313',
    name: 'minsurfo',
    group: 'GHS_psdef',
    description: 'Gould, Hu, & Scott: minimum surface problem (CUTEr)',
    author: 'E. Dolan, J. More\'',
    editor: 'N. Gould',
    date: '2000',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '40806',
    num_cols: '40806',
    nonzeros: '203622',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '3',
    num_dmperm_blocks: '3',
    structural_full_rank: 'true',
    structural_rank: '40806',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    image_files: 'minsurfo.png,minsurfo_dmperm.png,minsurfo_graph.gif,',
}
