{
    matrix_id: '1273',
    name: 'pwt',
    group: 'GHS_psdef',
    description: 'PWT: Nasa matrix, but with a diagonal added to the original matrix',
    author: 'NASA',
    editor: 'G. Kumfert, A. Pothen',
    date: '1995',
    kind: 'duplicate structural problem',
    problem_2D_or_3D: '1',
    num_rows: '36519',
    num_cols: '36519',
    nonzeros: '326107',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '57',
    num_dmperm_blocks: '57',
    structural_full_rank: 'true',
    structural_rank: '36519',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    notes: 'Nasa/pwt, GHS_psdef/pwt and Pothen/pwt are identical; Pothen/ has xyz coord.
',
    norm: '9.905274e+00',
    min_singular_value: '8.724673e-19',
    condition_number: '1.135318e+19',
    svd_rank: '35475',
    sprank_minus_rank: '1044',
    null_space_dimension: '1044',
    full_numerical_rank: 'no',
    svd_gap: '4304513987.285983',
    image_files: 'pwt.png,pwt_dmperm.png,pwt_svd.png,pwt_graph.gif,',
}
