{
    matrix_id: '1315',
    name: 'torsion1',
    group: 'GHS_psdef',
    description: 'Gould, Hu, & Scott: optimization problem (CUTEr)',
    author: 'R. Dembo, U. Tulowitzki',
    editor: 'P. Toint',
    date: '1983',
    kind: 'duplicate optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '40000',
    num_cols: '40000',
    nonzeros: '197608',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '5',
    num_dmperm_blocks: '5',
    structural_full_rank: 'true',
    structural_rank: '40000',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    notes: 'duplicate of GHS_psdef/obstclae
',
    norm: '8.199498e+00',
    min_singular_value: '2.000000e-01',
    condition_number: '4.099749e+01',
    svd_rank: '40000',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'torsion1.png,torsion1_dmperm.png,torsion1_svd.png,torsion1_graph.gif,',
}
