{
    matrix_id: '1288',
    name: 'wathen100',
    group: 'GHS_psdef',
    description: 'Gould,Higham,Scott: matrix from Andy Wathen, Oxford Univ.',
    author: 'A. Wathen',
    editor: 'N. Gould, Y. Hu, J. Scott',
    date: '2004',
    kind: 'random 2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '30401',
    num_cols: '30401',
    nonzeros: '471601',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '30401',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    notes: 'rand(\'state\',0); A = gallery(\'wathen\',100,100) ; % (in MATLAB)
',
    norm: '3.696741e+02',
    min_singular_value: '6.356142e-02',
    condition_number: '5.816014e+03',
    svd_rank: '30401',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'wathen100.png,wathen100_svd.png,wathen100_graph.gif,',
}
