{
    matrix_id: '449',
    name: 'b1_ss',
    group: 'Grund',
    description: 'Unsymmetric Matrix b1_ss, F. Grund, Dec 1994.',
    author: 'F. Grund',
    editor: 'F. Grund',
    date: '1997',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '7',
    num_cols: '7',
    nonzeros: '15',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '7',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 7-by-1
',
    norm: '2.012180e+00',
    min_singular_value: '1.019480e-02',
    condition_number: '1.973732e+02',
    svd_rank: '7',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
