{
    matrix_id: '462',
    name: 'd_dyn',
    group: 'Grund',
    description: 'Unsymmetric Matrix d_dyn, F. Grund, Dec 1994.',
    author: 'F. Grund',
    editor: 'F. Grund',
    date: '1997',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '87',
    num_cols: '87',
    nonzeros: '230',
    num_explicit_zeros: '8',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '19',
    structural_full_rank: 'true',
    structural_rank: '87',
    pattern_symmetry: '0.077',
    numeric_symmetry: '0.018',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 87-by-1
',
    norm: '1.129052e+02',
    min_singular_value: '1.522506e-05',
    condition_number: '7.415750e+06',
    svd_rank: '87',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'd_dyn.png,d_dyn_dmperm.png,d_dyn_svd.png,d_dyn_APlusAT_graph.gif,d_dyn_graph.gif,',
}
