{
    matrix_id: '463',
    name: 'd_dyn1',
    group: 'Grund',
    description: 'Unsymmetric Matrix d_dyn1, F. Grund, Oct 1995.',
    author: 'F. Grund',
    editor: 'F. Grund',
    date: '1997',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '87',
    num_cols: '87',
    nonzeros: '232',
    num_explicit_zeros: '6',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '17',
    structural_full_rank: 'true',
    structural_rank: '87',
    pattern_symmetry: '0.077',
    numeric_symmetry: '0.018',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '3.570377e+04',
    min_singular_value: '4.806770e-03',
    condition_number: '7.427809e+06',
    svd_rank: '87',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
