{
    matrix_id: '466',
    name: 'meg4',
    group: 'Grund',
    description: 'Unsymmetric Matrix meg4, 4MB RAM simulation, F. Grund, Oct 1990.',
    author: 'F. Grund',
    editor: 'F. Grund',
    date: '1997',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '5860',
    num_cols: '5860',
    nonzeros: '25258',
    num_explicit_zeros: '21584',
    num_strongly_connected_components: '1318',
    num_dmperm_blocks: '1412',
    structural_full_rank: 'true',
    structural_rank: '5860',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.125729e+05',
    min_singular_value: '5.070994e-06',
    condition_number: '4.191938e+10',
    svd_rank: '5860',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
