{
    matrix_id: '467',
    name: 'poli',
    group: 'Grund',
    description: 'Unsymmetric Matrix poli, FU Berlin, Aug 1993.',
    author: 'F. Grund',
    editor: 'F. Grund',
    date: '1997',
    kind: 'economic problem',
    problem_2D_or_3D: '0',
    num_rows: '4008',
    num_cols: '4008',
    nonzeros: '8188',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '3943',
    num_dmperm_blocks: '3943',
    structural_full_rank: 'true',
    structural_rank: '4008',
    pattern_symmetry: '0.029',
    numeric_symmetry: '0.002',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 4008-by-1
',
    norm: '5.669220e+00',
    min_singular_value: '1.819826e-02',
    condition_number: '3.115253e+02',
    svd_rank: '4008',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'poli.png,poli_dmperm.png,poli_large.png,poli_large_dmperm.png,poli_large_svd.png,poli_svd.png,poli_APlusAT_graph.gif,poli_graph.gif,poli_large_APlusAT_graph.gif,poli_large_graph.gif,',
}
