{
    matrix_id: '2276',
    name: 'circuit5M',
    group: 'Freescale',
    description: 'Large circuit from K. Gullapalli, Freescale Semiconductor',
    author: 'K. Gullapalli',
    editor: 'T. Davis',
    date: '2010',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '5558326',
    num_cols: '5558326',
    nonzeros: '59524291',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '647',
    num_dmperm_blocks: '1094',
    structural_full_rank: 'true',
    structural_rank: '5558326',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.420',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Large circuit from Kiran Gullapalli, Freescale Semiconductor
Little fill-in during factorization, if ordered properly..  
',
}
