{
    matrix_id: '2216',
    name: 'Freescale1',
    group: 'Freescale',
    description: 'circuit problem from K. Gullapalli, Freescale Semiconductor',
    author: 'K. Gullapalli',
    editor: 'T. Davis',
    date: '2008',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '3428755',
    num_cols: '3428755',
    nonzeros: '17052626',
    num_explicit_zeros: '1867721',
    num_strongly_connected_components: '1061',
    num_dmperm_blocks: '1061',
    structural_full_rank: 'true',
    structural_rank: '3428755',
    pattern_symmetry: '0.906',
    numeric_symmetry: '0.395',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
}
