{
    matrix_id: '1213',
    name: 'Lin',
    group: 'Lin',
    description: 'Large sparse eigenvalue problem. Chun-hung (Martin) Lin',
    author: 'C. Lin',
    editor: 'T. Davis',
    date: '2004',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '256000',
    num_cols: '256000',
    nonzeros: '1766400',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '256000',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
}
