{
    matrix_id: '2282',
    name: 'mouse_gene',
    group: 'Belcastro',
    description: 'Mouse gene network, Vincenzo Belcastro, TIGEM, Naples, Italy',
    author: 'V. Belcastro',
    editor: 'T. Davis',
    date: '2010',
    kind: 'undirected weighted graph',
    problem_2D_or_3D: '0',
    num_rows: '45101',
    num_cols: '45101',
    nonzeros: '28967291',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2072',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    notes: 'Mouse gene regulatory network, from analyzing gene expression profiles.
',
    image_files: 'mouse_gene.png,mouse_gene_scc.png,mouse_gene_graph.gif,',
}
