{
    matrix_id: '900',
    name: 'shermanACa',
    group: 'Shen',
    description: 'From Kai Shen, UCSB (now at kshen@cs.rochester.edu)',
    author: 'K. Shen',
    editor: 'T. Davis',
    date: '2003',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '3432',
    num_cols: '3432',
    nonzeros: '25220',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '59',
    num_dmperm_blocks: '59',
    structural_full_rank: 'true',
    structural_rank: '3432',
    pattern_symmetry: '0.164',
    numeric_symmetry: '0.022',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '8.110356e+02',
    min_singular_value: '4.872443e-05',
    condition_number: '1.664536e+07',
    svd_rank: '3432',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
