{
    matrix_id: '902',
    name: 'shermanACd',
    group: 'Shen',
    description: 'From Kai Shen, UCSB (now at kshen@cs.rochester.edu)',
    author: 'K. Shen',
    editor: 'T. Davis',
    date: '2003',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '6136',
    num_cols: '6136',
    nonzeros: '53329',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '92',
    num_dmperm_blocks: '92',
    structural_full_rank: 'true',
    structural_rank: '6136',
    pattern_symmetry: '0.152',
    numeric_symmetry: '0.017',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '3.233259e+01',
    min_singular_value: '5.533851e-06',
    condition_number: '5.842693e+06',
    svd_rank: '6136',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
