{
    matrix_id: '1330',
    name: 'Kuu',
    group: 'MathWorks',
    description: 'The MathWorks, Inc: symmetric positive definite matrix',
    author: 'B. Cheng',
    editor: 'T. Davis',
    date: '2006',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '7102',
    num_cols: '7102',
    nonzeros: '340200',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '7102',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '5.408206e+01',
    min_singular_value: '3.432037e-03',
    condition_number: '1.575800e+04',
    svd_rank: '7102',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
