{
    matrix_id: '1331',
    name: 'Muu',
    group: 'MathWorks',
    description: 'The MathWorks, Inc: symmetric positive definite matrix',
    author: 'B. Cheng',
    editor: 'T. Davis',
    date: '2006',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '7102',
    num_cols: '7102',
    nonzeros: '170134',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '7102',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '8.398954e-04',
    min_singular_value: '1.097383e-05',
    condition_number: '7.653619e+01',
    svd_rank: '7102',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
