{
    matrix_id: '1170',
    name: 'Pd',
    group: 'MathWorks',
    description: 'Matrix problem X=A\B with many sparse right-hand-sides',
    author: 'P. Anderson',
    editor: 'T. Davis',
    date: '2002',
    kind: 'counter-example problem',
    problem_2D_or_3D: '0',
    num_rows: '8081',
    num_cols: '8081',
    nonzeros: '13036',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '7877',
    num_dmperm_blocks: '7877',
    structural_full_rank: 'true',
    structural_rank: '8081',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'sparse 8081-by-12406
',
    norm: '6.589300e+04',
    min_singular_value: '2.513940e-07',
    condition_number: '2.621105e+11',
    svd_rank: '8081',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
