{
    matrix_id: '1171',
    name: 'Pd_rhs',
    group: 'MathWorks',
    description: 'Matrix problem X=A\B with many sparse right-hand-sides',
    author: 'P. Anderson',
    editor: 'T. Davis',
    date: '2002',
    kind: 'counter-example problem',
    problem_2D_or_3D: '0',
    num_rows: '8081',
    num_cols: '12406',
    nonzeros: '6323',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '14549',
    num_dmperm_blocks: '2872',
    structural_full_rank: 'false',
    structural_rank: '4368',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.355413e+05',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '4368',
    sprank_minus_rank: '0',
    null_space_dimension: '3713',
    full_numerical_rank: 'no',
    svd_gap: '67349403.958061',
}
