{
    matrix_id: '861',
    name: 'pivtol',
    group: 'MathWorks',
    description: 'Spline toolbox. Pivot tol 0.1 fails, needs >= 0.26. MathWorks,Inc',
    author: 'B. Cheng',
    editor: 'T. Davis',
    date: '2002',
    kind: 'statistical/mathematical problem',
    problem_2D_or_3D: '0',
    num_rows: '102',
    num_cols: '102',
    nonzeros: '306',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '102',
    pattern_symmetry: '0.990',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 102-by-3
',
    norm: '1.416065e+00',
    min_singular_value: '1.291948e-02',
    condition_number: '1.096070e+02',
    svd_rank: '102',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
