{
    matrix_id: '1197',
    name: 'rajat13',
    group: 'Rajat',
    description: 'Rajat/rajat13 circuit simulation matrix',
    author: 'Rajat',
    editor: 'T. Davis',
    date: '2004',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '7598',
    num_cols: '7598',
    nonzeros: '48762',
    num_explicit_zeros: '160',
    num_strongly_connected_components: '109',
    num_dmperm_blocks: '134',
    structural_full_rank: 'true',
    structural_rank: '7598',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.297',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '3.999990e+05',
    min_singular_value: '3.368438e-06',
    condition_number: '1.187491e+11',
    svd_rank: '7598',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
