{
    matrix_id: '1188',
    name: 'rajat04',
    group: 'Rajat',
    description: 'Rajat/rajat04 circuit simulation matrix',
    author: 'Rajat',
    editor: 'T. Davis',
    date: '2004',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '1041',
    num_cols: '1041',
    nonzeros: '8725',
    num_explicit_zeros: '917',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '67',
    structural_full_rank: 'true',
    structural_rank: '1041',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.040',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.092174e+04',
    min_singular_value: '1.276079e-04',
    condition_number: '1.639533e+08',
    svd_rank: '1041',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
