{
    matrix_id: '1377',
    name: 'rajat28',
    group: 'Rajat',
    description: 'Rajat/rajat28 circuit simulation matrix',
    author: 'Rajat',
    editor: 'T. Davis',
    date: '2006',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '87190',
    num_cols: '87190',
    nonzeros: '606489',
    num_explicit_zeros: '746',
    num_strongly_connected_components: '1178',
    num_dmperm_blocks: '3495',
    structural_full_rank: 'true',
    structural_rank: '87190',
    pattern_symmetry: '0.991',
    numeric_symmetry: '0.107',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
}
