{
    matrix_id: '1189',
    name: 'rajat05',
    group: 'Rajat',
    description: 'Rajat/rajat05 circuit simulation matrix',
    author: 'Rajat',
    editor: 'T. Davis',
    date: '2004',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '301',
    num_cols: '301',
    nonzeros: '1250',
    num_explicit_zeros: '134',
    num_strongly_connected_components: '9',
    num_dmperm_blocks: '15',
    structural_full_rank: 'true',
    structural_rank: '301',
    pattern_symmetry: '0.770',
    numeric_symmetry: '0.706',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '3.839167e+00',
    min_singular_value: '7.119133e-05',
    condition_number: '5.392745e+04',
    svd_rank: '301',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
