{
    matrix_id: '1396',
    name: 'rajat29',
    group: 'Rajat',
    description: 'Rajat/rajat29 circuit simulation matrix',
    author: 'Rajat',
    editor: 'T. Davis',
    date: '2006',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '643994',
    num_cols: '643994',
    nonzeros: '3760246',
    num_explicit_zeros: '1106024',
    num_strongly_connected_components: '4512',
    num_dmperm_blocks: '14307',
    structural_full_rank: 'true',
    structural_rank: '643994',
    pattern_symmetry: '0.686',
    numeric_symmetry: '0.691',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
}
