{
    matrix_id: '1191',
    name: 'rajat07',
    group: 'Rajat',
    description: 'Rajat/rajat07 circuit simulation matrix',
    author: 'Rajat',
    editor: 'T. Davis',
    date: '2004',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '14842',
    num_cols: '14842',
    nonzeros: '63913',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '143',
    structural_full_rank: 'true',
    structural_rank: '14842',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '9.634067e+00',
    min_singular_value: '1.220442e-02',
    condition_number: '7.893915e+02',
    svd_rank: '14842',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
