{
    matrix_id: '1344',
    name: 'rajat17',
    group: 'Rajat',
    description: 'Rajat/rajat17 circuit simulation matrix',
    author: 'Rajat',
    editor: 'T. Davis',
    date: '2006',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '94294',
    num_cols: '94294',
    nonzeros: '479246',
    num_explicit_zeros: '161913',
    num_strongly_connected_components: '5229',
    num_dmperm_blocks: '8546',
    structural_full_rank: 'true',
    structural_rank: '94294',
    pattern_symmetry: '0.990',
    numeric_symmetry: '0.271',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
}
