{
    matrix_id: '1373',
    name: 'rajat24',
    group: 'Rajat',
    description: 'Rajat/rajat24 circuit simulation matrix',
    author: 'Rajat',
    editor: 'T. Davis',
    date: '2006',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '358172',
    num_cols: '358172',
    nonzeros: '1946979',
    num_explicit_zeros: '1256',
    num_strongly_connected_components: '1178',
    num_dmperm_blocks: '3497',
    structural_full_rank: 'true',
    structural_rank: '358172',
    pattern_symmetry: '0.997',
    numeric_symmetry: '0.272',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
}
