{
    matrix_id: '1397',
    name: 'rajat30',
    group: 'Rajat',
    description: 'Rajat/rajat30 circuit simulation matrix',
    author: 'Rajat',
    editor: 'T. Davis',
    date: '2006',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '643994',
    num_cols: '643994',
    nonzeros: '6175244',
    num_explicit_zeros: '133',
    num_strongly_connected_components: '1434',
    num_dmperm_blocks: '11756',
    structural_full_rank: 'true',
    structural_rank: '643994',
    pattern_symmetry: '0.995',
    numeric_symmetry: '0.009',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
}
