{
    matrix_id: '1198',
    name: 'rajat14',
    group: 'Rajat',
    description: 'Rajat/rajat14 circuit simulation matrix',
    author: 'Rajat',
    editor: 'T. Davis',
    date: '2004',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '180',
    num_cols: '180',
    nonzeros: '1475',
    num_explicit_zeros: '28',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '19',
    structural_full_rank: 'true',
    structural_rank: '180',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.025',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '8.625081e+04',
    min_singular_value: '2.682359e-04',
    condition_number: '3.215483e+08',
    svd_rank: '180',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
