{
    matrix_id: '1190',
    name: 'rajat06',
    group: 'Rajat',
    description: 'Rajat/rajat06 circuit simulation matrix',
    author: 'Rajat',
    editor: 'T. Davis',
    date: '2004',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '10922',
    num_cols: '10922',
    nonzeros: '46983',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '123',
    structural_full_rank: 'true',
    structural_rank: '10922',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '9.038033e+00',
    min_singular_value: '1.422329e-02',
    condition_number: '6.354392e+02',
    svd_rank: '10922',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
