{
    matrix_id: '1193',
    name: 'rajat09',
    group: 'Rajat',
    description: 'Rajat/rajat09 circuit simulation matrix',
    author: 'Rajat',
    editor: 'T. Davis',
    date: '2004',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '24482',
    num_cols: '24482',
    nonzeros: '105573',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '183',
    structural_full_rank: 'true',
    structural_rank: '24482',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.071906e+01',
    min_singular_value: '9.507913e-03',
    condition_number: '1.127383e+03',
    svd_rank: '24482',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
