{
    matrix_id: '1375',
    name: 'rajat26',
    group: 'Rajat',
    description: 'Rajat/rajat26 circuit simulation matrix',
    author: 'Rajat',
    editor: 'T. Davis',
    date: '2006',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '51032',
    num_cols: '51032',
    nonzeros: '247528',
    num_explicit_zeros: '1774',
    num_strongly_connected_components: '1568',
    num_dmperm_blocks: '4666',
    structural_full_rank: 'true',
    structural_rank: '51032',
    pattern_symmetry: '0.985',
    numeric_symmetry: '0.327',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
}
