{
    matrix_id: '1403',
    name: 'thermal2',
    group: 'Schmid',
    description: 'unstructured FEM, steady state thermal problem. Dani Schmid, Univ. Oslo',
    author: 'D. Schmid',
    editor: 'T. Davis',
    date: '2006',
    kind: 'thermal problem',
    problem_2D_or_3D: '1',
    num_rows: '1228045',
    num_cols: '1228045',
    nonzeros: '8580313',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '959',
    num_dmperm_blocks: '959',
    structural_full_rank: 'true',
    structural_rank: '1228045',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    b_field: 'full 1228045-by-1
',
}
