{
    matrix_id: '765',
    name: 'nemeth01',
    group: 'Nemeth',
    description: 'Newton-Schultz iteration, Z_k+1=Z_k+(1/2)*(I-(Z_k)^2)*Z_k. This is Z_1',
    author: 'K. Nemeth',
    editor: 'T. Davis',
    date: '1999',
    kind: 'theoretical/quantum chemistry problem sequence',
    problem_2D_or_3D: '0',
    num_rows: '9506',
    num_cols: '9506',
    nonzeros: '725054',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '9506',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: Nemeth/nemeth02 first: Nemeth/nemeth01
',
    norm: '4.307172e+01',
    min_singular_value: '3.078271e-01',
    condition_number: '1.399218e+02',
    svd_rank: '9506',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'nemeth01.png,nemeth01_svd.png,nemeth01_graph.gif,',
}
