{
    matrix_id: '825',
    name: 'utm3060',
    group: 'TOKAMAK',
    description: ' Uedge Test Matrix',
    author: 'Y. Saad',
    editor: 'Y. Saad',
    date: '1996',
    kind: 'electromagnetics problem',
    problem_2D_or_3D: '1',
    num_rows: '3060',
    num_cols: '3060',
    nonzeros: '42211',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '83',
    num_dmperm_blocks: '83',
    structural_full_rank: 'true',
    structural_rank: '3060',
    pattern_symmetry: '0.525',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 3060-by-1
',
    norm: '2.606435e+00',
    min_singular_value: '1.352496e-07',
    condition_number: '1.927129e+07',
    svd_rank: '3060',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
