{
    matrix_id: '384',
    name: 'cavity05',
    group: 'DRIVCAV',
    description: 'Driven Cavity  10 x 10, Reynolds number: 0',
    author: 'A. Chapman',
    editor: 'A. Baggag, Y. Saad',
    date: '1996',
    kind: 'computational fluid dynamics problem sequence',
    problem_2D_or_3D: '1',
    num_rows: '1182',
    num_cols: '1182',
    nonzeros: '32632',
    num_explicit_zeros: '115',
    num_strongly_connected_components: '162',
    num_dmperm_blocks: '162',
    structural_full_rank: 'true',
    structural_rank: '1182',
    pattern_symmetry: '0.905',
    numeric_symmetry: '0.610',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: DRIVCAV/cavity06 first: DRIVCAV/cavity05
',
    b_field: 'full 1182-by-1
',
    x_field: 'full 1182-by-1
',
    norm: '1.300724e+01',
    min_singular_value: '2.254035e-05',
    condition_number: '5.770648e+05',
    svd_rank: '1182',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'cavity05.png,cavity05_dmperm.png,cavity05_scc.png,cavity05_svd.png,cavity05_APlusAT_graph.gif,cavity05_graph.gif,',
}
