{
    matrix_id: '383',
    name: 'cavity04',
    group: 'DRIVCAV',
    description: 'Driven Cavity   5 x  5, Reynolds number: 600',
    author: 'A. Chapman',
    editor: 'A. Baggag, Y. Saad',
    date: '1996',
    kind: 'subsequent computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '317',
    num_cols: '317',
    nonzeros: '5923',
    num_explicit_zeros: '1404',
    num_strongly_connected_components: '82',
    num_dmperm_blocks: '82',
    structural_full_rank: 'true',
    structural_rank: '317',
    pattern_symmetry: '0.804',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: - first: DRIVCAV/cavity01                         
pattern is the same as the transpose of DRIVCAV/cavity01
',
    b_field: 'full 317-by-1
',
    x_field: 'full 317-by-1
',
    norm: '7.122683e+01',
    min_singular_value: '2.010669e-05',
    condition_number: '3.542445e+06',
    svd_rank: '317',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'cavity04.png,cavity04_dmperm.png,cavity04_scc.png,cavity04_svd.png,cavity04_APlusAT_graph.gif,cavity04_graph.gif,',
}
