{
    matrix_id: '388',
    name: 'cavity09',
    group: 'DRIVCAV',
    description: 'Driven Cavity  10 x 10, Reynolds number: 800',
    author: 'A. Chapman',
    editor: 'A. Baggag, Y. Saad',
    date: '1996',
    kind: 'subsequent computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '1182',
    num_cols: '1182',
    nonzeros: '32702',
    num_explicit_zeros: '45',
    num_strongly_connected_components: '162',
    num_dmperm_blocks: '162',
    structural_full_rank: 'true',
    structural_rank: '1182',
    pattern_symmetry: '0.905',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: - first: DRIVCAV/cavity05        
pattern is the same as DRIVCAV/cavity05
',
    b_field: 'full 1182-by-1
',
    x_field: 'full 1182-by-1
',
    norm: '4.660455e+01',
    min_singular_value: '5.799129e-06',
    condition_number: '8.036474e+06',
    svd_rank: '1182',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'cavity09.png,cavity09_dmperm.png,cavity09_scc.png,cavity09_svd.png,cavity09_APlusAT_graph.gif,cavity09_graph.gif,',
}
