{
    matrix_id: '395',
    name: 'cavity16',
    group: 'DRIVCAV',
    description: 'Driven Cavity  20 x 20, Reynolds number: 0',
    author: 'A. Chapman',
    editor: 'A. Baggag, Y. Saad',
    date: '1996',
    kind: 'computational fluid dynamics problem sequence',
    problem_2D_or_3D: '1',
    num_rows: '4562',
    num_cols: '4562',
    nonzeros: '137887',
    num_explicit_zeros: '300',
    num_strongly_connected_components: '322',
    num_dmperm_blocks: '322',
    structural_full_rank: 'true',
    structural_rank: '4562',
    pattern_symmetry: '0.953',
    numeric_symmetry: '0.654',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: DRIVCAV/cavity17 first: DRIVCAV/cavity16
',
    b_field: 'full 4562-by-1
',
    x_field: 'full 4562-by-1
',
    norm: '1.306900e+01',
    min_singular_value: '1.392776e-06',
    condition_number: '9.383416e+06',
    svd_rank: '4562',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'cavity16.png,cavity16_dmperm.png,cavity16_scc.png,cavity16_svd.png,cavity16_APlusAT_graph.gif,cavity16_graph.gif,',
}
