{
    matrix_id: '389',
    name: 'cavity10',
    group: 'DRIVCAV',
    description: 'Driven Cavity  15 x 15, Reynolds number: 0',
    author: 'A. Chapman',
    editor: 'A. Baggag, Y. Saad',
    date: '1996',
    kind: 'computational fluid dynamics problem sequence',
    problem_2D_or_3D: '1',
    num_rows: '2597',
    num_cols: '2597',
    nonzeros: '76171',
    num_explicit_zeros: '196',
    num_strongly_connected_components: '242',
    num_dmperm_blocks: '242',
    structural_full_rank: 'true',
    structural_rank: '2597',
    pattern_symmetry: '0.937',
    numeric_symmetry: '0.640',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: DRIVCAV/cavity11 first: DRIVCAV/cavity10
',
    b_field: 'full 2597-by-1
',
    x_field: 'full 2597-by-1
',
    norm: '1.305274e+01',
    min_singular_value: '4.417072e-06',
    condition_number: '2.955066e+06',
    svd_rank: '2597',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'cavity10.png,cavity10_dmperm.png,cavity10_scc.png,cavity10_svd.png,cavity10_APlusAT_graph.gif,cavity10_graph.gif,',
}
