{
    matrix_id: '382',
    name: 'cavity03',
    group: 'DRIVCAV',
    description: 'Driven Cavity   5 x  5, Reynolds number: 400',
    author: 'A. Chapman',
    editor: 'A. Baggag, Y. Saad',
    date: '1996',
    kind: 'subsequent computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '317',
    num_cols: '317',
    nonzeros: '7311',
    num_explicit_zeros: '16',
    num_strongly_connected_components: '82',
    num_dmperm_blocks: '82',
    structural_full_rank: 'true',
    structural_rank: '317',
    pattern_symmetry: '0.804',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: DRIVCAV/cavity04 first: DRIVCAV/cavity01
pattern is the same as DRIVCAV/cavity01       
',
    b_field: 'full 317-by-1
',
    x_field: 'full 317-by-1
',
    norm: '4.713319e+01',
    min_singular_value: '8.057815e-05',
    condition_number: '5.849376e+05',
    svd_rank: '317',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'cavity03.png,cavity03_dmperm.png,cavity03_scc.png,cavity03_svd.png,cavity03_APlusAT_graph.gif,cavity03_graph.gif,',
}
