{
    matrix_id: '401',
    name: 'cavity22',
    group: 'DRIVCAV',
    description: 'Driven Cavity  20 x 20, Reynolds number: 600',
    author: 'A. Chapman',
    editor: 'A. Baggag, Y. Saad',
    date: '1996',
    kind: 'subsequent computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '4562',
    num_cols: '4562',
    nonzeros: '138040',
    num_explicit_zeros: '147',
    num_strongly_connected_components: '322',
    num_dmperm_blocks: '322',
    structural_full_rank: 'true',
    structural_rank: '4562',
    pattern_symmetry: '0.953',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: DRIVCAV/cavity23 first: DRIVCAV/cavity16
pattern is the same as DRIVCAV/cavity16       
',
    b_field: 'full 4562-by-1
',
    x_field: 'full 4562-by-1
',
    norm: '2.062502e+01',
    min_singular_value: '1.314963e-06',
    condition_number: '1.568487e+07',
    svd_rank: '4562',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'cavity22.png,cavity22_dmperm.png,cavity22_scc.png,cavity22_svd.png,cavity22_APlusAT_graph.gif,cavity22_graph.gif,',
}
