{
    matrix_id: '1562',
    name: 'c-43',
    group: 'Schenk_IBMNA',
    description: 'IBM TJ Watson, non-linear optimization',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2006',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '11125',
    num_cols: '11125',
    nonzeros: '123659',
    num_explicit_zeros: '16',
    num_strongly_connected_components: '9',
    num_dmperm_blocks: '9',
    structural_full_rank: 'true',
    structural_rank: '11125',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 11125-by-1
',
    norm: '6.528955e+04',
    min_singular_value: '7.126682e-05',
    condition_number: '9.161283e+08',
    svd_rank: '11125',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
