{
    matrix_id: '1572',
    name: 'c-53',
    group: 'Schenk_IBMNA',
    description: 'IBM TJ Watson, non-linear optimization',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2006',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '30235',
    num_cols: '30235',
    nonzeros: '355139',
    num_explicit_zeros: '17074',
    num_strongly_connected_components: '42',
    num_dmperm_blocks: '42',
    structural_full_rank: 'true',
    structural_rank: '30235',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 30235-by-1
',
    norm: '5.361887e+03',
    min_singular_value: '1.413217e-04',
    condition_number: '3.794100e+07',
    svd_rank: '30235',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
