{
    matrix_id: '1576',
    name: 'c-60',
    group: 'Schenk_IBMNA',
    description: 'IBM TJ Watson, non-linear optimization',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2006',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '43640',
    num_cols: '43640',
    nonzeros: '298570',
    num_explicit_zeros: '8',
    num_strongly_connected_components: '5',
    num_dmperm_blocks: '5',
    structural_full_rank: 'true',
    structural_rank: '43640',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 43640-by-1
',
}
