{
    matrix_id: '950',
    name: 'c-64',
    group: 'Schenk_IBMNA',
    description: 'Olaf Schenk, Univ. Basel: IBM TJ Watson, Yorktown, nonlinear optimization',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2003',
    kind: 'optimization problem sequence',
    problem_2D_or_3D: '0',
    num_rows: '51035',
    num_cols: '51035',
    nonzeros: '707985',
    num_explicit_zeros: '9856',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '51035',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: Schenk_IBMNA/c-64b first: Schenk_IBMNA/c-64
',
    b_field: 'full 51035-by-1
',
    image_files: 'c-64.png,c-64_graph.gif,',
}
