{
    matrix_id: '953',
    name: 'c-73',
    group: 'Schenk_IBMNA',
    description: 'Olaf Schenk, Univ. Basel: IBM TJ Watson, Yorktown, nonlinear optimization',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2003',
    kind: 'optimization problem sequence',
    problem_2D_or_3D: '0',
    num_rows: '169422',
    num_cols: '169422',
    nonzeros: '1279274',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '169422',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: Schenk_IBMNA/c-73b first: Schenk_IBMNA/c-73
',
    b_field: 'full 169422-by-1
',
    image_files: 'c-73.png,c-73_graph.gif,',
}
