{
    matrix_id: '901',
    name: 'shermanACb',
    group: 'Shen',
    description: 'From Kai Shen, UCSB (now at kshen@cs.rochester.edu)',
    author: 'K. Shen',
    editor: 'T. Davis',
    date: '2003',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '18510',
    num_cols: '18510',
    nonzeros: '145149',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '851',
    num_dmperm_blocks: '851',
    structural_full_rank: 'true',
    structural_rank: '18510',
    pattern_symmetry: '0.149',
    numeric_symmetry: '0.027',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.100002e+03',
    min_singular_value: '6.126961e-05',
    condition_number: '1.795347e+07',
    svd_rank: '18510',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'shermanACb.png,shermanACb_dmperm.png,shermanACb_svd.png,shermanACb_APlusAT_graph.gif,shermanACb_graph.gif,',
}
