{
    matrix_id: '1',
    name: '1138_bus',
    group: 'HB',
    description: 'S ADMITTANCE MATRIX 1138 BUS POWER SYSTEM, D.J.TYLAVSKY, JULY 1985.',
    author: 'D. Tylavsky',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1985',
    kind: 'power network problem',
    problem_2D_or_3D: '0',
    num_rows: '1138',
    num_cols: '1138',
    nonzeros: '4054',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '1138',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '3.014879e+04',
    min_singular_value: '3.516860e-03',
    condition_number: '8.572646e+06',
    svd_rank: '1138',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
