{
    matrix_id: '3',
    name: '662_bus',
    group: 'HB',
    description: 'S ADMITTANCE MATRIX  662 BUS POWER SYSTEM, D.J.TYLAVSKY, JULY 1985.',
    author: 'D. Tylavsky',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1985',
    kind: 'power network problem',
    problem_2D_or_3D: '0',
    num_rows: '662',
    num_cols: '662',
    nonzeros: '2474',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '662',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '4.008114e+03',
    min_singular_value: '5.047169e-03',
    condition_number: '7.941311e+05',
    svd_rank: '662',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
