{
    matrix_id: '7',
    name: 'ash219',
    group: 'HB',
    description: 'UNSYMMETRIC OVERDETERMINED PATTERN OF HOLLAND SURVEY. ASHKENAZI,1974',
    author: 'V. Askenazi',
    editor: 'A. Curtis, I. Duff, J. Reid',
    date: '1974',
    kind: 'least squares problem',
    problem_2D_or_3D: '0',
    num_rows: '219',
    num_cols: '85',
    nonzeros: '438',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '85',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'binary',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '3.484572e+00',
    min_singular_value: '1.151979e+00',
    condition_number: '3.024858e+00',
    svd_rank: '85',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
