{
    matrix_id: '13',
    name: 'bcspwr01',
    group: 'HB',
    description: 'SYMMETRIC STRUCTURE (STANDARD TEST POWER SYSTEM - NEW ENGLAND)',
    author: 'B. Dembart, J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1981',
    kind: 'power network problem',
    problem_2D_or_3D: '0',
    num_rows: '39',
    num_cols: '39',
    nonzeros: '131',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '39',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '3.836363e+00',
    min_singular_value: '7.307345e-02',
    condition_number: '5.250010e+01',
    svd_rank: '39',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
