{
    matrix_id: '15',
    name: 'bcspwr03',
    group: 'HB',
    description: 'SYMMETRIC STRUCTURE OF 118 BUS IEEE STANDARD TEST CASE POWER NETWORK',
    author: 'B. Dembart, J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1981',
    kind: 'power network problem',
    problem_2D_or_3D: '0',
    num_rows: '118',
    num_cols: '118',
    nonzeros: '476',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '118',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '5.105303e+00',
    min_singular_value: '1.018170e-02',
    condition_number: '5.014196e+02',
    svd_rank: '118',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
