{
    matrix_id: '59',
    name: 'bcsstm04',
    group: 'HB',
    description: 'SYMMETRIC MASS MATRIX, OIL RIG, NOT CONDENSED (SAME MODEL AS BCSSTX02)',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '132',
    num_cols: '132',
    nonzeros: '66',
    num_explicit_zeros: '66',
    num_strongly_connected_components: '132',
    num_dmperm_blocks: '68',
    structural_full_rank: 'false',
    structural_rank: '66',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.728286e-01',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '66',
    sprank_minus_rank: '0',
    null_space_dimension: '66',
    full_numerical_rank: 'no',
    svd_gap: 'Inf',
}
