{
    matrix_id: '38',
    name: 'bcsstk16',
    group: 'HB',
    description: 'S  STIFFNESS MATRIX - CORP. OF ENGINEERS DAM',
    author: 'M. Will',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1985',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '4884',
    num_cols: '4884',
    nonzeros: '290378',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '75',
    num_dmperm_blocks: '75',
    structural_full_rank: 'true',
    structural_rank: '4884',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '4.943166e+09',
    min_singular_value: '9.999966e-01',
    condition_number: '4.943183e+09',
    svd_rank: '4884',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
