{
    matrix_id: '45',
    name: 'bcsstk23',
    group: 'HB',
    description: 'SYMMETRIC STIFFNESS MATRIX - PORTION OF A 3D GLOBALLY TRIANGLULAR BLDG',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1984',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '3134',
    num_cols: '3134',
    nonzeros: '45178',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '3134',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '22580407237629408',
    min_singular_value: '8.535284e+03',
    condition_number: '2.645537e+12',
    svd_rank: '3133',
    sprank_minus_rank: '1',
    null_space_dimension: '1',
    full_numerical_rank: 'no',
    svd_gap: '1.673936',
}
