{
    matrix_id: '36',
    name: 'bcsstk14',
    group: 'HB',
    description: 'S  STIFFNESS MATRIX - ROOF OF OMNI COLISEUM, ATLANTA',
    author: 'M. Will',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1985',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '1806',
    num_cols: '1806',
    nonzeros: '63454',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '41',
    num_dmperm_blocks: '41',
    structural_full_rank: 'true',
    structural_rank: '1806',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '1.192322e+10',
    min_singular_value: '9.999985e-01',
    condition_number: '1.192324e+10',
    svd_rank: '1806',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
