{
    matrix_id: '52',
    name: 'bcsstk30',
    group: 'HB',
    description: 'STIFFNESS MATRIX FOR OFF-SHORE GENERATOR PLATFORM (MSC NASTRAN) - PATTER',
    author: 'R. Cigel, R. Grimes, J. Lewis, E. Meyer',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1986',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '28924',
    num_cols: '28924',
    nonzeros: '2043492',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '28924',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '9.530248e+01',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '8935',
    sprank_minus_rank: '19989',
    null_space_dimension: '19989',
    full_numerical_rank: 'no',
    svd_gap: '39606053.827891',
}
