{
    matrix_id: '75',
    name: 'bcsstm25',
    group: 'HB',
    description: 'SYMMETRIC MASS      MATRIX - 76 STORY SKYSCRAPER',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1984',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '15439',
    num_cols: '15439',
    nonzeros: '15439',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '15439',
    num_dmperm_blocks: '15439',
    structural_full_rank: 'true',
    structural_rank: '15439',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '6.977097e+08',
    min_singular_value: '1.151384e-01',
    condition_number: '6.059745e+09',
    svd_rank: '15439',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
