{
    matrix_id: '70',
    name: 'bcsstm20',
    group: 'HB',
    description: 'SYMMETRIC MASS      MATRIX - FRAME WITHIN A SUSPENSION BRIDGE',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1984',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '485',
    num_cols: '485',
    nonzeros: '485',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '485',
    num_dmperm_blocks: '485',
    structural_full_rank: 'true',
    structural_rank: '485',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '4.779555e+07',
    min_singular_value: '1.871542e+02',
    condition_number: '2.553806e+05',
    svd_rank: '485',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
