{
    matrix_id: '30',
    name: 'bcsstk08',
    group: 'HB',
    description: 'SYMMETRIC STIFFNESS MATRIX, FRAME BUILDING (TV STUDIO)',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '1074',
    num_cols: '1074',
    nonzeros: '12960',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '4',
    num_dmperm_blocks: '4',
    structural_full_rank: 'true',
    structural_rank: '1074',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '7.657034e+10',
    min_singular_value: '2.946411e+03',
    condition_number: '2.598767e+07',
    svd_rank: '1074',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
