{
    matrix_id: '33',
    name: 'bcsstk11',
    group: 'HB',
    description: 'SYMMETRIC STIFFNESS MATRIX, ORE CAR (LUMPED MASSES)',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '1473',
    num_cols: '1473',
    nonzeros: '34241',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '9',
    num_dmperm_blocks: '9',
    structural_full_rank: 'true',
    structural_rank: '1473',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '6.556063e+08',
    min_singular_value: '2.964059e+00',
    condition_number: '2.211853e+08',
    svd_rank: '1473',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
