{
    matrix_id: '58',
    name: 'bcsstm03',
    group: 'HB',
    description: 'SYMMETRIC MASS MATRIX, SMALL TEST STRUCTURE',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '112',
    num_cols: '112',
    nonzeros: '72',
    num_explicit_zeros: '40',
    num_strongly_connected_components: '112',
    num_dmperm_blocks: '74',
    structural_full_rank: 'false',
    structural_rank: '72',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '5.403500e+03',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '72',
    sprank_minus_rank: '0',
    null_space_dimension: '40',
    full_numerical_rank: 'no',
    svd_gap: 'Inf',
}
