{
    matrix_id: '24',
    name: 'bcsstk02',
    group: 'HB',
    description: 'SYMMETRIC STIFFNESS MATRIX, SMALL OIL RIG, STATICALLY CONDENSED',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '66',
    num_cols: '66',
    nonzeros: '4356',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '66',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '1.822575e+04',
    min_singular_value: '4.214074e+00',
    condition_number: '4.324971e+03',
    svd_rank: '66',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
