{
    matrix_id: '56',
    name: 'bcsstm01',
    group: 'HB',
    description: 'SYMMETRIC MASS MATRIX SMALL GENERALIZED EIGENVALUE PROBLEM, B MATRIX',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '48',
    num_cols: '48',
    nonzeros: '24',
    num_explicit_zeros: '24',
    num_strongly_connected_components: '48',
    num_dmperm_blocks: '26',
    structural_full_rank: 'false',
    structural_rank: '24',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'integer',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '200',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '24',
    sprank_minus_rank: '0',
    null_space_dimension: '24',
    full_numerical_rank: 'no',
    svd_gap: 'Inf',
}
