{
    matrix_id: '43',
    name: 'bcsstk21',
    group: 'HB',
    description: 'SYMMETRIC STIFFNESS MATRIX - CLAMPED SQUARE PLATE',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1984',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '3600',
    num_cols: '3600',
    nonzeros: '26600',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '3600',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '1.273140e+08',
    min_singular_value: '7.214147e+00',
    condition_number: '1.764783e+07',
    svd_rank: '3600',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
