{
    matrix_id: '77',
    name: 'bcsstm27',
    group: 'HB',
    description: 'MASS      MATRIX BUCKLING PROBLEM (ANDY MERA)',
    author: 'A. Mera, R. Cigel, J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1984',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '1224',
    num_cols: '1224',
    nonzeros: '56126',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '1224',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '3.927163e+03',
    min_singular_value: '5.677107e-07',
    condition_number: '6.917543e+09',
    svd_rank: '1224',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
