{
    matrix_id: '54',
    name: 'bcsstk32',
    group: 'HB',
    description: 'STIFFNESS MATRIX FOR AUTOMOBILE CHASSIS (MSC NASTRAN) - PATTERN ONLY',
    author: 'R. Cigel, R. Grimes, J. Lewis, E. Meyer',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1986',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '44609',
    num_cols: '44609',
    nonzeros: '2014701',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '44609',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
}
