{
    matrix_id: '39',
    name: 'bcsstk17',
    group: 'HB',
    description: 'SYMMETRIC STIFFNESS MATRIX - ELEVATED PRESSURE VESSEL',
    author: 'M. Will',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1985',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '10974',
    num_cols: '10974',
    nonzeros: '428650',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '519',
    num_dmperm_blocks: '519',
    structural_full_rank: 'true',
    structural_rank: '10974',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '1.296062e+10',
    min_singular_value: '9.999981e-01',
    condition_number: '1.296064e+10',
    svd_rank: '10974',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
