{
    matrix_id: '60',
    name: 'bcsstm05',
    group: 'HB',
    description: 'SYMMETRIC MASS MATRIX, TRANSMISSION TOWER, LUMPED MASSES',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '153',
    num_cols: '153',
    nonzeros: '153',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '153',
    num_dmperm_blocks: '153',
    structural_full_rank: 'true',
    structural_rank: '153',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '9.279542e-01',
    min_singular_value: '7.307792e-02',
    condition_number: '1.269815e+01',
    svd_rank: '153',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
