{
    matrix_id: '31',
    name: 'bcsstk09',
    group: 'HB',
    description: 'SYMMETRIC STIFFNESS MATRIX, SQUARE PLATE CLAMPED',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '1083',
    num_cols: '1083',
    nonzeros: '18437',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '1083',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '6.760304e+07',
    min_singular_value: '7.102229e+03',
    condition_number: '9.518566e+03',
    svd_rank: '1083',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
