{
    matrix_id: '41',
    name: 'bcsstk19',
    group: 'HB',
    description: 'SYMMETRIC STIFFNESS MATRIX - PART OF A SUSPENSION BRIDGE',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1984',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '817',
    num_cols: '817',
    nonzeros: '6853',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '817',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '1.922161e+14',
    min_singular_value: '1.434353e+03',
    condition_number: '1.340089e+11',
    svd_rank: '817',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
