{
    matrix_id: '71',
    name: 'bcsstm21',
    group: 'HB',
    description: 'SYMMETRIC MASS      MATRIX - CLAMPED SQUARE PLATE',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1984',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '3600',
    num_cols: '3600',
    nonzeros: '3600',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '3600',
    num_dmperm_blocks: '3600',
    structural_full_rank: 'true',
    structural_rank: '3600',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '1.466056e-04',
    min_singular_value: '6.181870e-06',
    condition_number: '2.371542e+01',
    svd_rank: '3600',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
