{
    matrix_id: '32',
    name: 'bcsstk10',
    group: 'HB',
    description: 'SYMMETRIC STIFFNESS MATRIX, BUCKLING OF HOT WASHER',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '1086',
    num_cols: '1086',
    nonzeros: '22070',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '1086',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '4.474306e+07',
    min_singular_value: '8.535086e+01',
    condition_number: '5.242250e+05',
    svd_rank: '1086',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
