{
    matrix_id: '46',
    name: 'bcsstk24',
    group: 'HB',
    description: 'SYMMETRIC STIFFNESS MATRIX - WINTER SPORTS ARENA',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1984',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '3562',
    num_cols: '3562',
    nonzeros: '159910',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '3562',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '3.069198e+13',
    min_singular_value: '1.574611e+02',
    condition_number: '1.949178e+11',
    svd_rank: '3562',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
