{
    matrix_id: '61',
    name: 'bcsstm06',
    group: 'HB',
    description: 'SYMMETRIC MASS MATRIX, MEDIUM TEST PROBLEM, LUMPED MASSES',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '420',
    num_cols: '420',
    nonzeros: '420',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '420',
    num_dmperm_blocks: '420',
    structural_full_rank: 'true',
    structural_rank: '420',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '7.602410e+03',
    min_singular_value: '2.199084e-03',
    condition_number: '3.457080e+06',
    svd_rank: '420',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
