{
    matrix_id: '66',
    name: 'bcsstm11',
    group: 'HB',
    description: 'SYMMETRIC MASS MATRIX, ORE CAR (LUMPED MASSES)',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '1473',
    num_cols: '1473',
    nonzeros: '1473',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1473',
    num_dmperm_blocks: '1473',
    structural_full_rank: 'true',
    structural_rank: '1473',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '3.157814e+01',
    min_singular_value: '2.670497e-04',
    condition_number: '1.182482e+05',
    svd_rank: '1473',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
