{
    matrix_id: '79',
    name: 'beaflw',
    group: 'HB',
    description: 'U NONSYMMETRIC MATRIX U.S. ECONOMY 1972  -SZYLD-I.E.A.-NYU-',
    author: 'D. Szyld',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'economic problem',
    problem_2D_or_3D: '0',
    num_rows: '497',
    num_cols: '507',
    nonzeros: '53403',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '13',
    num_dmperm_blocks: '13',
    structural_full_rank: 'false',
    structural_rank: '460',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.192232e+05',
    min_singular_value: '8.653984e-31',
    condition_number: '2.533205e+35',
    svd_rank: '460',
    sprank_minus_rank: '0',
    null_space_dimension: '37',
    full_numerical_rank: 'no',
    svd_gap: '65054501.599996',
}
