{
    matrix_id: '80',
    name: 'beause',
    group: 'HB',
    description: 'U NONSYMMETRIC MATRIX U.S. ECONOMY 1972  -SZYLD-I.E.A.-NYU-',
    author: 'D. Szyld',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'economic problem',
    problem_2D_or_3D: '0',
    num_rows: '497',
    num_cols: '507',
    nonzeros: '44551',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '8',
    num_dmperm_blocks: '31',
    structural_full_rank: 'false',
    structural_rank: '459',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.184483e+05',
    min_singular_value: '1.294005e-30',
    condition_number: '1.688156e+35',
    svd_rank: '459',
    sprank_minus_rank: '0',
    null_space_dimension: '38',
    full_numerical_rank: 'no',
    svd_gap: '129631059.369058',
}
