{
    matrix_id: '87',
    name: 'bp_200',
    group: 'HB',
    description: 'UNSYMMETRIC BASIS FROM LP PROBLEM BP',
    author: 'M. Saunders',
    editor: 'A. Curtis, I. Duff, J. Reid',
    date: '1978',
    kind: 'subsequent optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '822',
    num_cols: '822',
    nonzeros: '3802',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '673',
    structural_full_rank: 'true',
    structural_rank: '822',
    pattern_symmetry: '0.006',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: HB/bp_400 first: HB/bp_0
',
    norm: '4.032111e+02',
    min_singular_value: '6.295270e-05',
    condition_number: '6.404985e+06',
    svd_rank: '822',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
