{
    matrix_id: '90',
    name: 'bp_800',
    group: 'HB',
    description: 'UNSYMMETRIC BASIS FROM LP PROBLEM BP',
    author: 'M. Saunders',
    editor: 'A. Curtis, I. Duff, J. Reid',
    date: '1978',
    kind: 'subsequent optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '822',
    num_cols: '822',
    nonzeros: '4534',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '492',
    structural_full_rank: 'true',
    structural_rank: '822',
    pattern_symmetry: '0.005',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: HB/bp_1000 first: HB/bp_0
',
    norm: '4.035913e+02',
    min_singular_value: '2.038649e-04',
    condition_number: '1.979700e+06',
    svd_rank: '822',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
