{
    matrix_id: '107',
    name: 'can_838',
    group: 'HB',
    description: 'SYMMETRIC PATTERN FROM CANNES,LUCIEN MARRO,JUNE 1981.',
    author: 'L. Marro',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1981',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '838',
    num_cols: '838',
    nonzeros: '10010',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '838',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '1.575944e+01',
    min_singular_value: '3.059816e-03',
    condition_number: '5.150453e+03',
    svd_rank: '838',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
