{
    matrix_id: '99',
    name: 'can_268',
    group: 'HB',
    description: 'SYMMETRIC PATTERN FROM CANNES,LUCIEN MARRO,JUNE 1981.',
    author: 'L. Marro',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1981',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '268',
    num_cols: '268',
    nonzeros: '3082',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '268',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '1.445894e+01',
    min_singular_value: '2.406444e-33',
    condition_number: '6.008425e+33',
    svd_rank: '261',
    sprank_minus_rank: '7',
    null_space_dimension: '7',
    full_numerical_rank: 'no',
    svd_gap: '17933816779284.058594',
}
