{
    matrix_id: '106',
    name: 'can_73',
    group: 'HB',
    description: 'SYMMETRIC PATTERN FROM CANNES,LUCIEN MARRO,JUNE 1981.',
    author: 'L. Marro',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1981',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '73',
    num_cols: '73',
    nonzeros: '377',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '73',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '6.327656e+00',
    min_singular_value: '1.775750e-01',
    condition_number: '3.563370e+01',
    svd_rank: '73',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
