{
    matrix_id: '103',
    name: 'can_62',
    group: 'HB',
    description: 'SYMMETRIC PATTERN FROM CANNES,LUCIEN MARRO,JUNE 1981.',
    author: 'L. Marro',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1981',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '62',
    num_cols: '62',
    nonzeros: '218',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '62',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '4.159080e+00',
    min_singular_value: '6.887905e-03',
    condition_number: '6.038237e+02',
    svd_rank: '62',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
