{
    matrix_id: '1174',
    name: 'cegb2919',
    group: 'HB',
    description: 'FINITE ELEMENT PROBLEM. 3-DIMENSIONAL CYLINDER WITH FLANGE',
    author: 'A. Donovan',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1980',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '2919',
    num_cols: '2919',
    nonzeros: '321543',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '61',
    num_dmperm_blocks: '3',
    structural_full_rank: 'false',
    structural_rank: '2859',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.368385e+02',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '444',
    sprank_minus_rank: '2415',
    null_space_dimension: '2475',
    full_numerical_rank: 'no',
    svd_gap: '504883229895.067627',
}
