{
    matrix_id: '118',
    name: 'dwt_234',
    group: 'HB',
    description: 'SYMMETRIC CONNECTION TABLE FROM DTNSRDC, WASHINGTON',
    author: 'G. Everstine, D. Taylor',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1980',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '234',
    num_cols: '234',
    nonzeros: '834',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '7',
    num_dmperm_blocks: '7',
    structural_full_rank: 'true',
    structural_rank: '234',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '4.583099e+00',
    min_singular_value: '1.419682e-02',
    condition_number: '3.228258e+02',
    svd_rank: '234',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
