{
    matrix_id: '114',
    name: 'dwt_193',
    group: 'HB',
    description: 'SYMMETRIC CONNECTION TABLE FROM DTNSRDC, WASHINGTON',
    author: 'G. Everstine, D. Taylor',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1980',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '193',
    num_cols: '193',
    nonzeros: '3493',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '193',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '2.110468e+01',
    min_singular_value: '1.181356e-31',
    condition_number: '1.786479e+32',
    svd_rank: '136',
    sprank_minus_rank: '57',
    null_space_dimension: '57',
    full_numerical_rank: 'no',
    svd_gap: '44226877239338.945312',
}
