{
    matrix_id: '139',
    name: 'dwt_992',
    group: 'HB',
    description: 'SYMMETRIC CONNECTION TABLE FROM DTNSRDC, WASHINGTON',
    author: 'G. Everstine, D. Taylor',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1980',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '992',
    num_cols: '992',
    nonzeros: '16744',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '992',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '1.773855e+01',
    min_singular_value: '2.845467e-19',
    condition_number: '6.233968e+19',
    svd_rank: '496',
    sprank_minus_rank: '496',
    null_space_dimension: '496',
    full_numerical_rank: 'no',
    svd_gap: '1568556940374.101074',
}
