{
    matrix_id: '120',
    name: 'dwt_2680',
    group: 'HB',
    description: 'SYMMETRIC CONNECTION TABLE FROM DTNSRDC, WASHINGTON',
    author: 'G. Everstine, D. Taylor',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1980',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '2680',
    num_cols: '2680',
    nonzeros: '25026',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '2680',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '1.150901e+01',
    min_singular_value: '1.014862e-18',
    condition_number: '1.134047e+19',
    svd_rank: '2640',
    sprank_minus_rank: '40',
    null_space_dimension: '40',
    full_numerical_rank: 'no',
    svd_gap: '247910082197.848358',
}
