{
    matrix_id: '125',
    name: 'dwt_419',
    group: 'HB',
    description: 'SYMMETRIC CONNECTION TABLE FROM DTNSRDC, WASHINGTON',
    author: 'G. Everstine, D. Taylor',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1980',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '419',
    num_cols: '419',
    nonzeros: '3563',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '419',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '9.339130e+00',
    min_singular_value: '1.730096e-19',
    condition_number: '5.398040e+19',
    svd_rank: '370',
    sprank_minus_rank: '49',
    null_space_dimension: '49',
    full_numerical_rank: 'no',
    svd_gap: '12730870843846.937500',
}
