{
    matrix_id: '140',
    name: 'eris1176',
    group: 'HB',
    description: 'SYMMETRIC PATTERN OF ERISMAN, SUMMER 1973',
    author: 'A. Erisman',
    editor: 'A. Curtis, I. Duff, J. Reid',
    date: '1973',
    kind: 'power network problem',
    problem_2D_or_3D: '0',
    num_rows: '1176',
    num_cols: '1176',
    nonzeros: '18552',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '1176',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '8.007389e+01',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '774',
    sprank_minus_rank: '402',
    null_space_dimension: '402',
    full_numerical_rank: 'no',
    svd_gap: '1438563829055.476318',
}
