{
    matrix_id: '145',
    name: 'fs_541_1',
    group: 'HB',
    description: 'UNSYMMETRIC FACSIMILE CONVERGENCE MATRIX',
    author: 'A. Curtis',
    editor: 'A. Curtis, I. Duff, J. Reid',
    date: '1978',
    kind: '2D/3D problem sequence',
    problem_2D_or_3D: '1',
    num_rows: '541',
    num_cols: '541',
    nonzeros: '4282',
    num_explicit_zeros: '3',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '541',
    pattern_symmetry: '0.683',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: HB/fs_541_2 first: HB/fs_541_1
',
    norm: '6.694741e+01',
    min_singular_value: '1.498427e-02',
    condition_number: '4.467845e+03',
    svd_rank: '541',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
