{
    matrix_id: '151',
    name: 'fs_680_3',
    group: 'HB',
    description: 'UNSYMMETRIC FACSIMILE CONVERGENCE MATRIX',
    author: 'A. Curtis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1983',
    kind: 'subsequent 2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '680',
    num_cols: '680',
    nonzeros: '2471',
    num_explicit_zeros: '175',
    num_strongly_connected_components: '446',
    num_dmperm_blocks: '446',
    structural_full_rank: 'true',
    structural_rank: '680',
    pattern_symmetry: '0.511',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: - first: HB/fs_680_1
',
    norm: '7.190792e+13',
    min_singular_value: '2.004708e+07',
    condition_number: '3.586953e+06',
    svd_rank: '680',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
