{
    matrix_id: '152',
    name: 'fs_760_1',
    group: 'HB',
    description: 'UNSYMMETRIC FACSIMILE CONVERGENCE MATRIX',
    author: 'A. Curtis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1983',
    kind: '2D/3D problem sequence',
    problem_2D_or_3D: '1',
    num_rows: '760',
    num_cols: '760',
    nonzeros: '5739',
    num_explicit_zeros: '237',
    num_strongly_connected_components: '17',
    num_dmperm_blocks: '17',
    structural_full_rank: 'true',
    structural_rank: '760',
    pattern_symmetry: '0.651',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: HB/fs_760_2 first: HB/fs_760_1
',
    norm: '3.098609e+08',
    min_singular_value: '5.647661e+04',
    condition_number: '5.486535e+03',
    svd_rank: '760',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
