{
    matrix_id: '155',
    name: 'gemat1',
    group: 'HB',
    description: 'UNSUMMETRIC MATRIX FROM G.E. OPF PROGRAM. WESTERN UTILITY SYSTEM.',
    author: 'R. Burchett',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1984',
    kind: 'power network problem',
    problem_2D_or_3D: '0',
    num_rows: '4929',
    num_cols: '10595',
    nonzeros: '46591',
    num_explicit_zeros: '778',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '4929',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.344606e+04',
    min_singular_value: '1.994312e-04',
    condition_number: '1.175647e+08',
    svd_rank: '4929',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
