{
    matrix_id: '164',
    name: 'gre_216b',
    group: 'HB',
    description: 'UNSYMMETRIC MATRIX FROM GRENOBLE,FRANCOIS CACHARD,MARCH 1981.',
    author: 'F. Cachard',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1981',
    kind: 'directed weighted graph',
    problem_2D_or_3D: '0',
    num_rows: '216',
    num_cols: '216',
    nonzeros: '812',
    num_explicit_zeros: '64',
    num_strongly_connected_components: '1',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.390052e+00',
    min_singular_value: '2.252893e-15',
    condition_number: '617007434647036',
    svd_rank: '215',
    null_space_dimension: '1',
    full_numerical_rank: 'no',
    svd_gap: '73.527446',
}
