{
    matrix_id: '161',
    name: 'gre_115',
    group: 'HB',
    description: 'UNSYMMETRIC MATRIX FROM GRENOBLE,FRANCOIS CACHARD,MARCH 1981.',
    author: 'F. Cachard',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1981',
    kind: 'directed weighted graph',
    problem_2D_or_3D: '0',
    num_rows: '115',
    num_cols: '115',
    nonzeros: '421',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '0.255',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.046669e+00',
    min_singular_value: '2.107206e-02',
    condition_number: '4.967094e+01',
    svd_rank: '115',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
