{
    matrix_id: '168',
    name: 'ibm32',
    group: 'HB',
    description: 'UNSYMMETRIC PATTERN ON LEAFLET ADVERTISING IBM 1971 CONFERENCE',
    author: 'IBM',
    editor: 'A. Curtis, I. Duff, J. Reid',
    date: '1971',
    kind: 'directed graph',
    problem_2D_or_3D: '0',
    num_rows: '32',
    num_cols: '32',
    nonzeros: '126',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '0.085',
    numeric_symmetry: '0.085',
    rb_type: 'binary',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '4.593605e+00',
    min_singular_value: '1.136707e-02',
    condition_number: '4.041151e+02',
    svd_rank: '32',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
