{
    matrix_id: '172',
    name: 'impcol_b',
    group: 'HB',
    description: 'UNSYMMETRIC MATRIX - CAVETT\'S PROCESS (CHEM ENG),1982',
    author: 'D. Bogle',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '59',
    num_cols: '59',
    nonzeros: '271',
    num_explicit_zeros: '41',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '19',
    structural_full_rank: 'true',
    structural_rank: '59',
    pattern_symmetry: '0.095',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '8.639495e+00',
    min_singular_value: '5.288147e-05',
    condition_number: '1.633747e+05',
    svd_rank: '59',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
