{
    matrix_id: '171',
    name: 'impcol_a',
    group: 'HB',
    description: 'UNSYMMETRIC MATRIX - HEAT EXCHANGER NETWORK (CHEM ENG) ,1982',
    author: 'D. Bogle',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '207',
    num_cols: '207',
    nonzeros: '572',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '4',
    num_dmperm_blocks: '164',
    structural_full_rank: 'true',
    structural_rank: '207',
    pattern_symmetry: '0.025',
    numeric_symmetry: '0.011',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '8.554623e+02',
    min_singular_value: '6.329078e-06',
    condition_number: '1.351638e+08',
    svd_rank: '207',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
