{
    matrix_id: '174',
    name: 'impcol_d',
    group: 'HB',
    description: 'UNSYMMETRIC MATRIX - NITRIC ACID PLANT MODEL (CHEM ENG),1982',
    author: 'D. Bogle',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '425',
    num_cols: '425',
    nonzeros: '1255',
    num_explicit_zeros: '84',
    num_strongly_connected_components: '3',
    num_dmperm_blocks: '321',
    structural_full_rank: 'true',
    structural_rank: '425',
    pattern_symmetry: '0.057',
    numeric_symmetry: '0.023',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.018128e+01',
    min_singular_value: '4.938729e-03',
    condition_number: '2.061518e+03',
    svd_rank: '425',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
