{
    matrix_id: '180',
    name: 'jagmesh5',
    group: 'HB',
    description: 'SYMMETRIC PATTERN FROM ALAN GEORGE -  + SHAPED DOMAIN',
    author: 'A. George',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1978',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '1180',
    num_cols: '1180',
    nonzeros: '7750',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '1180',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '6.891487e+00',
    min_singular_value: '1.007815e-04',
    condition_number: '6.838046e+04',
    svd_rank: '1180',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
