{
    matrix_id: '187',
    name: 'jpwh_991',
    group: 'HB',
    description: 'UNSYMMETRIC MATRIX FROM PHILIPS LTD, J.P.WHELAN,1978.',
    author: 'J. Whelan',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1978',
    kind: 'semiconductor device problem',
    problem_2D_or_3D: '1',
    num_rows: '991',
    num_cols: '991',
    nonzeros: '6027',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '146',
    num_dmperm_blocks: '146',
    structural_full_rank: 'true',
    structural_rank: '991',
    pattern_symmetry: '0.936',
    numeric_symmetry: '0.936',
    rb_type: 'integer',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.629198e+01',
    min_singular_value: '1.146959e-01',
    condition_number: '1.420450e+02',
    svd_rank: '991',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
