{
    matrix_id: '188',
    name: 'lns_131',
    group: 'HB',
    description: 'UNSYMMETRIC MATRIX FROM I.P.J. DEC 1982. LINEARIZED N-S. COMPRESSIBLE',
    author: 'I. Jones',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '131',
    num_cols: '131',
    nonzeros: '536',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '48',
    num_dmperm_blocks: '65',
    structural_full_rank: 'true',
    structural_rank: '131',
    pattern_symmetry: '0.703',
    numeric_symmetry: '0.019',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '9.772096e+09',
    min_singular_value: '7.642182e-06',
    condition_number: '1.278705e+15',
    svd_rank: '125',
    sprank_minus_rank: '6',
    null_space_dimension: '6',
    full_numerical_rank: 'no',
    svd_gap: '1.955983',
}
