{
    matrix_id: '190',
    name: 'lns_511',
    group: 'HB',
    description: 'UNSYMMETRIC MATRIX FROM I.P.J. DEC 1982. LINEARIZED N-S. COMPRESSIBLE',
    author: 'I. Jones',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '511',
    num_cols: '511',
    nonzeros: '2796',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '98',
    num_dmperm_blocks: '135',
    structural_full_rank: 'true',
    structural_rank: '511',
    pattern_symmetry: '0.799',
    numeric_symmetry: '0.020',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '4.205522e+10',
    min_singular_value: '1.263206e-05',
    condition_number: '3329243390300590',
    svd_rank: '469',
    sprank_minus_rank: '42',
    null_space_dimension: '42',
    full_numerical_rank: 'no',
    svd_gap: '1.158163',
}
