{
    matrix_id: '1179',
    name: 'lock2232',
    group: 'HB',
    description: 'FINITE ELEMENT PROBLEM. LOCKHEED TOWER PROBLEM',
    author: 'W. Loden',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1980',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '2232',
    num_cols: '2232',
    nonzeros: '80352',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '25',
    num_dmperm_blocks: '3',
    structural_full_rank: 'false',
    structural_rank: '2208',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '4.035526e+01',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '368',
    sprank_minus_rank: '1840',
    null_space_dimension: '1864',
    full_numerical_rank: 'no',
    svd_gap: '488464766968.827271',
}
