{
    matrix_id: '1178',
    name: 'lock1074',
    group: 'HB',
    description: 'FINITE ELEMENT PROBLEM. LOCKHEED GYRO PROBLEM',
    author: 'W. Loden',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1980',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '1074',
    num_cols: '1074',
    nonzeros: '51588',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '37',
    num_dmperm_blocks: '3',
    structural_full_rank: 'false',
    structural_rank: '1038',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '5.722833e+01',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '155',
    sprank_minus_rank: '883',
    null_space_dimension: '919',
    full_numerical_rank: 'no',
    svd_gap: '519121878106.893860',
}
