{
    matrix_id: '198',
    name: 'lshp2233',
    group: 'HB',
    description: 'SYMMETRIC MATRIX FROM ALAN GEORGE\'S L-SHAPE PROBLEMS, 1978.',
    author: 'A. George',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1978',
    kind: 'thermal problem',
    problem_2D_or_3D: '1',
    num_rows: '2233',
    num_cols: '2233',
    nonzeros: '15337',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '2233',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '6.985968e+00',
    min_singular_value: '8.481977e-04',
    condition_number: '8.236250e+03',
    svd_rank: '2233',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
