{
    matrix_id: '205',
    name: 'lshp_778',
    group: 'HB',
    description: 'SYMMETRIC MATRIX FROM ALAN GEORGE\'S L-SHAPE PROBLEMS, 1978.',
    author: 'A. George',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1978',
    kind: 'thermal problem',
    problem_2D_or_3D: '1',
    num_rows: '778',
    num_cols: '778',
    nonzeros: '5272',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '778',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '6.960833e+00',
    min_singular_value: '1.066246e-03',
    condition_number: '6.528355e+03',
    svd_rank: '778',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
