{
    matrix_id: '206',
    name: 'lund_a',
    group: 'HB',
    description: 'SYMMETRIC MATRIX A OF LUND EIGENVALUE PROBLEM, MAY 1974',
    author: 'T. Johansson',
    editor: 'A. Curtis, I. Duff, J. Reid',
    date: '1974',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '147',
    num_cols: '147',
    nonzeros: '2449',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '147',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '2.238541e+08',
    min_singular_value: '8.003511e+01',
    condition_number: '2.796948e+06',
    svd_rank: '147',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
