{
    matrix_id: '208',
    name: 'mahindas',
    group: 'HB',
    description: 'UNSYMMETRIC MATRIX             MAHINDAS ST ERTAR             24OCT84',
    author: 'K. Pearson',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1984',
    kind: 'economic problem',
    problem_2D_or_3D: '0',
    num_rows: '1258',
    num_cols: '1258',
    nonzeros: '7682',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '670',
    structural_full_rank: 'true',
    structural_rank: '1258',
    pattern_symmetry: '0.017',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'sparse 1258-by-55
',
    norm: '2.045108e+07',
    min_singular_value: '9.821293e-07',
    condition_number: '2.082320e+13',
    svd_rank: '1257',
    sprank_minus_rank: '1',
    null_space_dimension: '1',
    full_numerical_rank: 'no',
    svd_gap: '15312.436115',
}
