{
    matrix_id: '1182',
    name: 'man_5976',
    group: 'HB',
    description: 'MANTEUFFEL\'S FINITE ELEMENT PROBLEM (CONDENSED)',
    author: 'T. Manteuffel',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1980',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '5976',
    num_cols: '5976',
    nonzeros: '225046',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '95',
    num_dmperm_blocks: '3',
    structural_full_rank: 'false',
    structural_rank: '5882',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '4.149505e+01',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '2341',
    sprank_minus_rank: '3541',
    null_space_dimension: '3635',
    full_numerical_rank: 'no',
    svd_gap: '135426895606.255310',
}
