{
    matrix_id: '213',
    name: 'mcfe',
    group: 'HB',
    description: 'U NON-LTE PROBLEM ASTROPHYSICS.CODE:M.CARLSSON, ATOM=\'FE  ATMOS=M65GXM.',
    author: 'M. Carlsson',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1985',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '765',
    num_cols: '765',
    nonzeros: '24382',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '5',
    num_dmperm_blocks: '5',
    structural_full_rank: 'true',
    structural_rank: '765',
    pattern_symmetry: '0.699',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '134762224313579648',
    min_singular_value: '3.176989e+03',
    condition_number: '4.241822e+13',
    svd_rank: '759',
    sprank_minus_rank: '6',
    null_space_dimension: '6',
    full_numerical_rank: 'no',
    svd_gap: '2.751847',
}
