{
    matrix_id: '214',
    name: 'nnc1374',
    group: 'HB',
    description: 'U NATIONAL NUCLEAR CORP. FISSION REACTOR SIESMIC STUDIES',
    author: 'National Nuclear Corp.',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '1374',
    num_cols: '1374',
    nonzeros: '8588',
    num_explicit_zeros: '18',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '57',
    structural_full_rank: 'true',
    structural_rank: '1374',
    pattern_symmetry: '0.817',
    numeric_symmetry: '0.592',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.102118e+03',
    min_singular_value: '2.958499e-12',
    condition_number: '3.725261e+14',
    svd_rank: '1308',
    sprank_minus_rank: '66',
    null_space_dimension: '66',
    full_numerical_rank: 'no',
    svd_gap: '5.691356',
}
