{
    matrix_id: '216',
    name: 'nnc666',
    group: 'HB',
    description: 'U NATIONAL NUCLEAR CORP. FISSION REACTOR SIESMIC STUDIES',
    author: 'National Nuclear Corp.',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '666',
    num_cols: '666',
    nonzeros: '4032',
    num_explicit_zeros: '12',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '41',
    structural_full_rank: 'true',
    structural_rank: '666',
    pattern_symmetry: '0.818',
    numeric_symmetry: '0.592',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.086074e+03',
    min_singular_value: '5.313251e-08',
    condition_number: '2.044085e+10',
    svd_rank: '666',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
