{
    matrix_id: '219',
    name: 'nos3',
    group: 'HB',
    description: 'SYMMETRIC MATRIX, FE APPROXIMATION TO BIHARMONIC OPERATOR ON PLATE',
    author: 'H. Simon',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '960',
    num_cols: '960',
    nonzeros: '15844',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '960',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '6.899040e+02',
    min_singular_value: '1.828839e-02',
    condition_number: '3.772359e+04',
    svd_rank: '960',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
