{
    matrix_id: '220',
    name: 'nos4',
    group: 'HB',
    description: 'SYMMETRIC MATRIX OF BEAM STRUCTURE, NOVEMBER 1982.',
    author: 'H. Simon',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '100',
    num_cols: '100',
    nonzeros: '594',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '100',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '8.491378e-01',
    min_singular_value: '5.379528e-04',
    condition_number: '1.578461e+03',
    svd_rank: '100',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
