{
    matrix_id: '225',
    name: 'orsirr_1',
    group: 'HB',
    description: 'U OIL RESERVOIR SIMULATION MATRIX FOR 21X21X 5 IRREGULAR GRID',
    author: 'R. Grimes',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1984',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '1030',
    num_cols: '1030',
    nonzeros: '6858',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '1030',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.409',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '4.580810e+05',
    min_singular_value: '5.938091e+00',
    condition_number: '7.714281e+04',
    svd_rank: '1030',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
