{
    matrix_id: '227',
    name: 'orsreg_1',
    group: 'HB',
    description: 'U OIL RESERVOIR SIMULATION MATRIX FOR 21X21X 5 FULL GRID',
    author: 'R. Grimes',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1984',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '2205',
    num_cols: '2205',
    nonzeros: '14133',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '2205',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.412',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.927246e+04',
    min_singular_value: '4.339703e+00',
    condition_number: '6.745269e+03',
    svd_rank: '2205',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
