{
    matrix_id: '229',
    name: 'plat362',
    group: 'HB',
    description: 'SPLATZMAN FINITE DIFFERENCE MODEL OF ATLANTICOCEAN',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1975',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '362',
    num_cols: '362',
    nonzeros: '5786',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '362',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '7.742794e-01',
    min_singular_value: '3.554638e-12',
    condition_number: '2.178223e+11',
    svd_rank: '362',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
