{
    matrix_id: '231',
    name: 'plskz362',
    group: 'HB',
    description: ' PLATZMAN SKEW-SYMMETRIC FINITE DIFFERENCE MODEL OF ATLANTIC OCEAN',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1975',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '362',
    num_cols: '362',
    nonzeros: '1760',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '3',
    structural_full_rank: 'true',
    structural_rank: '362',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'skew-symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '8.799315e-01',
    min_singular_value: '1.885373e-06',
    condition_number: '4.667147e+05',
    svd_rank: '362',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
