{
    matrix_id: '234',
    name: 'pores_3',
    group: 'HB',
    description: 'UNSYMMETRIC MATRIX FROM PORES',
    author: 'J. Appleyard',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1980',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '532',
    num_cols: '532',
    nonzeros: '3474',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '532',
    pattern_symmetry: '0.742',
    numeric_symmetry: '0.305',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.499228e+05',
    min_singular_value: '2.673386e-01',
    condition_number: '5.607974e+05',
    svd_rank: '532',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
