{
    matrix_id: '235',
    name: 'psmigr_1',
    group: 'HB',
    description: 'UNSYMMETRIC MATRIX . INTERCOUNTY MIGRATION . PAUL SLATER CA, NOV 1983',
    author: 'P. Slater',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1983',
    kind: 'economic problem',
    problem_2D_or_3D: '0',
    num_rows: '3140',
    num_cols: '3140',
    nonzeros: '543160',
    num_explicit_zeros: '2',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '3140',
    pattern_symmetry: '0.479',
    numeric_symmetry: '0.010',
    rb_type: 'integer',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.231924e+06',
    min_singular_value: '4.607339e-04',
    condition_number: '4.844279e+09',
    svd_rank: '3140',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
