{
    matrix_id: '241',
    name: 'saylr4',
    group: 'HB',
    description: 'UNSYMMETRIC MATRIX OF PAUL SAYLOR - 33 BY  6 BY 18 3D GRID   MAY, 1983',
    author: 'R. Kendall, D. Peaceman, H. Stone, W. Watts',
    editor: 'P. Saylor',
    date: '1984',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '3564',
    num_cols: '3564',
    nonzeros: '22316',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '3564',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.327358e+04',
    min_singular_value: '1.934469e-03',
    condition_number: '6.861617e+06',
    svd_rank: '3564',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
