{
    matrix_id: '239',
    name: 'saylr1',
    group: 'HB',
    description: 'UNSYMMETRIC MATRIX OF PAUL SAYLOR - 14 BY 17 2D GRID   MAY, 1983',
    author: 'R. Kendall, D. Peaceman, H. Stone, W. Watts',
    editor: 'P. Saylor',
    date: '1984',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '238',
    num_cols: '238',
    nonzeros: '1128',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '238',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.647',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '4.832495e+08',
    min_singular_value: '6.210969e-01',
    condition_number: '7.780581e+08',
    svd_rank: '238',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
