{
    matrix_id: '242',
    name: 'sherman1',
    group: 'HB',
    description: 'U BLACK OIL SIMULATOR, SHALE BARRIERS  10 BY 10 BY 10 GRID, ONE   UNK',
    author: 'A. Sherman',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1984',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '1000',
    num_cols: '1000',
    nonzeros: '3750',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '318',
    num_dmperm_blocks: '318',
    structural_full_rank: 'true',
    structural_rank: '1000',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 1000-by-1
',
    norm: '5.044869e+00',
    min_singular_value: '3.234871e-04',
    condition_number: '1.559527e+04',
    svd_rank: '1000',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
