{
    matrix_id: '248',
    name: 'shl_200',
    group: 'HB',
    description: 'UNSYMMETRIC BASIS FROM LP PROBLEM SHELL',
    author: 'M. Saunders',
    editor: 'A. Curtis, I. Duff, J. Reid',
    date: '1978',
    kind: 'subsequent optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '663',
    num_cols: '663',
    nonzeros: '1726',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '4',
    num_dmperm_blocks: '663',
    structural_full_rank: 'true',
    structural_rank: '663',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'integer',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: HB/shl_400 first: HB/shl_0
',
    norm: '9.433866e+03',
    min_singular_value: '1.094127e-05',
    condition_number: '8.622274e+08',
    svd_rank: '663',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
