{
    matrix_id: '251',
    name: 'steam1',
    group: 'HB',
    description: 'UNSYMMETRIC - 3D STEAM MODEL OF OIL RES. - 4 X 4 X 5 - 3 DOF  MAY 1983',
    author: 'R. Grimes',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1983',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '240',
    num_cols: '240',
    nonzeros: '2248',
    num_explicit_zeros: '1514',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '240',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.273',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.171198e+07',
    min_singular_value: '7.678860e-01',
    condition_number: '2.827501e+07',
    svd_rank: '240',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
