{
    matrix_id: '252',
    name: 'steam2',
    group: 'HB',
    description: 'UNSYMMETRIC - 3D STEAM MODEL OF OIL RES. - 5 X 5 X 6 - 4 DOF  MAY 1983',
    author: 'R. Grimes',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1983',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '600',
    num_cols: '600',
    nonzeros: '5660',
    num_explicit_zeros: '8100',
    num_strongly_connected_components: '151',
    num_dmperm_blocks: '151',
    structural_full_rank: 'true',
    structural_rank: '600',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.188',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '4.685604e+09',
    min_singular_value: '1.238554e+03',
    condition_number: '3.783125e+06',
    svd_rank: '600',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
