{
    matrix_id: '256',
    name: 'str_400',
    group: 'HB',
    description: 'UNSYMMETRIC BASIS FROM LP PROBLEM STAIR',
    author: 'M. Saunders',
    editor: 'A. Curtis, I. Duff, J. Reid',
    date: '1978',
    kind: 'subsequent optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '363',
    num_cols: '363',
    nonzeros: '3157',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '203',
    structural_full_rank: 'true',
    structural_rank: '363',
    pattern_symmetry: '0.020',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: HB/str_600 first: HB/str_0
',
    norm: '1.460877e+01',
    min_singular_value: '2.271724e-03',
    condition_number: '6.430698e+03',
    svd_rank: '363',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
