{
    matrix_id: '259',
    name: 'watt_2',
    group: 'HB',
    description: 'UNSYMMETRIC MATRIX FROM JOHN SOMERVILLE, HERIOT-WATT. DEC,1983        H',
    author: 'J. Somerville',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1983',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '1856',
    num_cols: '1856',
    nonzeros: '11550',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '65',
    num_dmperm_blocks: '65',
    structural_full_rank: 'true',
    structural_rank: '1856',
    pattern_symmetry: '0.980',
    numeric_symmetry: '0.967',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '8.000000e+00',
    min_singular_value: '5.870212e-11',
    condition_number: '1.362813e+11',
    svd_rank: '1856',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
