{
    matrix_id: '258',
    name: 'watt_1',
    group: 'HB',
    description: 'UNSYMMETRIC MATRIX FROM JOHN SOMERVILLE, HERIOT-WATT. DEC,1983        H',
    author: 'J. Somerville',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1983',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '1856',
    num_cols: '1856',
    nonzeros: '11360',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '129',
    num_dmperm_blocks: '129',
    structural_full_rank: 'true',
    structural_rank: '1856',
    pattern_symmetry: '0.987',
    numeric_symmetry: '0.987',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.000000e+00',
    min_singular_value: '2.293768e-10',
    condition_number: '4.359639e+09',
    svd_rank: '1856',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
