{
    matrix_id: '260',
    name: 'well1033',
    group: 'HB',
    description: 'UNSYMMETRIC LEAST-SQUARES PROBLEM.                  SAUNDERS 1979.',
    author: 'M. Saunders',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1979',
    kind: 'least squares problem',
    problem_2D_or_3D: '0',
    num_rows: '1033',
    num_cols: '320',
    nonzeros: '4732',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '15',
    structural_full_rank: 'true',
    structural_rank: '320',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 1033-by-1
',
    norm: '1.806511e+00',
    min_singular_value: '1.087386e-02',
    condition_number: '1.661333e+02',
    svd_rank: '320',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
