{
    matrix_id: '270',
    name: 'west0989',
    group: 'HB',
    description: 'U 7 STAGE COLUMN SECTION, ALL SECTIONS RIGOROUS  ( CHEM. ENG. )',
    author: 'A. Westerberg',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1983',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '989',
    num_cols: '989',
    nonzeros: '3518',
    num_explicit_zeros: '19',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '270',
    structural_full_rank: 'true',
    structural_rank: '989',
    pattern_symmetry: '0.018',
    numeric_symmetry: '0.004',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '3.191273e+05',
    min_singular_value: '3.236445e-07',
    condition_number: '9.860428e+11',
    svd_rank: '989',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
