{
    matrix_id: '271',
    name: 'west1505',
    group: 'HB',
    description: 'U 11 STAGE COLUMN SECTION, ALL SECTIONS RIGOROUS ( CHEM. ENG. )',
    author: 'A. Westerberg',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1983',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '1505',
    num_cols: '1505',
    nonzeros: '5414',
    num_explicit_zeros: '31',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '405',
    structural_full_rank: 'true',
    structural_rank: '1505',
    pattern_symmetry: '0.001',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '3.191277e+05',
    min_singular_value: '2.003300e-07',
    condition_number: '1.593010e+12',
    svd_rank: '1505',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
