{
    matrix_id: '267',
    name: 'west0479',
    group: 'HB',
    description: 'U 8 STAGE COLUMN SECTION, ALL SECTIONS RIGOROUS ( CHEM. ENG. )',
    author: 'A. Westerberg',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1983',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '479',
    num_cols: '479',
    nonzeros: '1888',
    num_explicit_zeros: '22',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '166',
    structural_full_rank: 'true',
    structural_rank: '479',
    pattern_symmetry: '0.014',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '3.189518e+05',
    min_singular_value: '9.806680e-07',
    condition_number: '3.252393e+11',
    svd_rank: '479',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
