{
    matrix_id: '265',
    name: 'west0167',
    group: 'HB',
    description: 'U RIGOROUS MODEL OF A CHEMICAL STAGE (CHEM.ENG. FROM A. WESTERBERG)',
    author: 'A. Westerberg',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1983',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '167',
    num_cols: '167',
    nonzeros: '506',
    num_explicit_zeros: '1',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '91',
    structural_full_rank: 'true',
    structural_rank: '167',
    pattern_symmetry: '0.016',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '3.201155e+05',
    min_singular_value: '6.689677e-06',
    condition_number: '4.785217e+10',
    svd_rank: '167',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
