{
    matrix_id: '268',
    name: 'west0497',
    group: 'HB',
    description: 'U RIGOROUS FLASH UNIT WITH RECYCLING  ( CHEM. ENG. FROM WESTERBERG )',
    author: 'A. Westerberg',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1983',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '497',
    num_cols: '497',
    nonzeros: '1721',
    num_explicit_zeros: '6',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '294',
    structural_full_rank: 'true',
    structural_rank: '497',
    pattern_symmetry: '0.007',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '6.898487e+05',
    min_singular_value: '1.492995e-06',
    condition_number: '4.620569e+11',
    svd_rank: '497',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
