{
    matrix_id: '264',
    name: 'west0156',
    group: 'HB',
    description: 'U SIMPLE CHEMICAL PLANT MODEL  ( CHEM. ENG. FROM A. WESTERBERG )',
    author: 'A. Westerberg',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1983',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '156',
    num_cols: '156',
    nonzeros: '362',
    num_explicit_zeros: '9',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '134',
    structural_full_rank: 'true',
    structural_rank: '156',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.867366e+07',
    min_singular_value: '8.100763e-12',
    condition_number: '2305172839010676224',
    svd_rank: '154',
    sprank_minus_rank: '2',
    null_space_dimension: '2',
    full_numerical_rank: 'no',
    svd_gap: '131188.574203',
}
