{
    matrix_id: '269',
    name: 'west0655',
    group: 'HB',
    description: 'U 16 STAGE COLUMN SECTION, SOME STAGES SIMPLIFIED  ( CHEM. ENG. )',
    author: 'A. Westerberg',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1983',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '655',
    num_cols: '655',
    nonzeros: '2808',
    num_explicit_zeros: '46',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '198',
    structural_full_rank: 'true',
    structural_rank: '655',
    pattern_symmetry: '0.006',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '3.189518e+05',
    min_singular_value: '9.772410e-07',
    condition_number: '3.263798e+11',
    svd_rank: '655',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
