{
    matrix_id: '407',
    name: 'ex10',
    group: 'FIDAP',
    description: ' TEST MATRIX FROM FIDAP: EX10.MAT',
    author: 'A. Baggag, Y. Saad',
    editor: 'A. Baggag, Y. Saad',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '2410',
    num_cols: '2410',
    nonzeros: '54840',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '2410',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '6.961986e+07',
    min_singular_value: '7.651177e-05',
    condition_number: '9.099235e+11',
    svd_rank: '2410',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'ex10.png,ex10_dmperm.png,ex10_svd.png,ex10hs.png,ex10hs_dmperm.png,ex10hs_svd.png,ex10_graph.gif,ex10hs_graph.gif,',
}
