{
    matrix_id: '408',
    name: 'ex10hs',
    group: 'FIDAP',
    description: 'TEST MATRIX FROM FIDAP: EX10hs.MAT',
    author: 'A. Baggag, Y. Saad',
    editor: 'A. Baggag, Y. Saad',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '2548',
    num_cols: '2548',
    nonzeros: '57308',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '2548',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '5.267915e+07',
    min_singular_value: '9.605452e-05',
    condition_number: '5.484297e+11',
    svd_rank: '2548',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'ex10hs.png,ex10hs_dmperm.png,ex10hs_svd.png,ex10hs_graph.gif,',
}
