{
    matrix_id: '409',
    name: 'ex11',
    group: 'FIDAP',
    description: ' TEST MATRIX FROM FIDAP: EX11.MAT',
    author: 'A. Baggag, Y. Saad',
    editor: 'A. Baggag, Y. Saad',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '16614',
    num_cols: '16614',
    nonzeros: '1096948',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '16614',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '5.586275e+08',
    min_singular_value: '1.942094e-04',
    condition_number: '2.876419e+12',
    svd_rank: '16527',
    sprank_minus_rank: '87',
    null_space_dimension: '87',
    full_numerical_rank: 'no',
    svd_gap: '1.006081',
    image_files: 'ex11.png,ex11_svd.png,ex11_graph.gif,',
}
