{
    matrix_id: '413',
    name: 'ex15',
    group: 'FIDAP',
    description: ' TEST MATRIX FROM FIDAP: EX15.MAT',
    author: 'A. Baggag, Y. Saad',
    editor: 'A. Baggag, Y. Saad',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '6867',
    num_cols: '6867',
    nonzeros: '98671',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '6867',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '1.113004e+10',
    min_singular_value: '1.292337e-03',
    condition_number: '8.612330e+12',
    svd_rank: '6667',
    sprank_minus_rank: '200',
    null_space_dimension: '200',
    full_numerical_rank: 'no',
    svd_gap: '1.000758',
    image_files: 'ex15.png,ex15_dmperm.png,ex15_svd.png,ex15_graph.gif,',
}
