{
    matrix_id: '414',
    name: 'ex18',
    group: 'FIDAP',
    description: ' TEST MATRIX FROM FIDAP: EX18.MAT',
    author: 'A. Baggag, Y. Saad',
    editor: 'A. Baggag, Y. Saad',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '5773',
    num_cols: '5773',
    nonzeros: '71701',
    num_explicit_zeros: '104',
    num_strongly_connected_components: '212',
    num_dmperm_blocks: '212',
    structural_full_rank: 'true',
    structural_rank: '5773',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.497',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.292117e+08',
    min_singular_value: '6.197510e-05',
    condition_number: '2.084898e+12',
    svd_rank: '5772',
    sprank_minus_rank: '1',
    null_space_dimension: '1',
    full_numerical_rank: 'no',
    svd_gap: '1.897253',
    image_files: 'ex18.png,ex18_dmperm.png,ex18_svd.png,ex18_graph.gif,',
}
