{
    matrix_id: '417',
    name: 'ex20',
    group: 'FIDAP',
    description: ' TEST MATRIX FROM FIDAP: EX20.MAT',
    author: 'A. Baggag, Y. Saad',
    editor: 'A. Baggag, Y. Saad',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '2203',
    num_cols: '2203',
    nonzeros: '67830',
    num_explicit_zeros: '2151',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '2203',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.971',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.521730e+00',
    min_singular_value: '5.425072e-09',
    condition_number: '2.804994e+08',
    svd_rank: '2203',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'ex20.png,ex20_svd.png,ex20_graph.gif,',
}
