{
    matrix_id: '418',
    name: 'ex21',
    group: 'FIDAP',
    description: ' TEST MATRIX FROM FIDAP: EX21.MAT',
    author: 'A. Baggag, Y. Saad',
    editor: 'A. Baggag, Y. Saad',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '656',
    num_cols: '656',
    nonzeros: '18964',
    num_explicit_zeros: '180',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '656',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.942',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '5.145271e-01',
    min_singular_value: '8.927355e-10',
    condition_number: '5.763488e+08',
    svd_rank: '656',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'ex21.png,ex21_svd.png,ex21_graph.gif,',
}
