{
    matrix_id: '422',
    name: 'ex25',
    group: 'FIDAP',
    description: ' TEST MATRIX FROM FIDAP: EX25.MAT',
    author: 'A. Baggag, Y. Saad',
    editor: 'A. Baggag, Y. Saad',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '848',
    num_cols: '848',
    nonzeros: '24369',
    num_explicit_zeros: '243',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '848',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.976',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '6.459115e-01',
    min_singular_value: '1.265031e-08',
    condition_number: '5.105894e+07',
    svd_rank: '848',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'ex25.png,ex25_svd.png,ex25_graph.gif,',
}
