{
    matrix_id: '426',
    name: 'ex29',
    group: 'FIDAP',
    description: ' TEST MATRIX FROM FIDAP: EX29.MAT',
    author: 'A. Baggag, Y. Saad',
    editor: 'A. Baggag, Y. Saad',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '2870',
    num_cols: '2870',
    nonzeros: '23754',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '180',
    num_dmperm_blocks: '180',
    structural_full_rank: 'true',
    structural_rank: '2870',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.996',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.000000e+00',
    min_singular_value: '1.330645e-03',
    condition_number: '7.515152e+02',
    svd_rank: '2870',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'ex29.png,ex29_dmperm.png,ex29_svd.png,ex29_graph.gif,',
}
