{
    matrix_id: '427',
    name: 'ex3',
    group: 'FIDAP',
    description: ' TEST MATRIX FROM FIDAP: EX3.MAT',
    author: 'A. Baggag, Y. Saad',
    editor: 'A. Baggag, Y. Saad',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '1821',
    num_cols: '1821',
    nonzeros: '52685',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '1821',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '2.261840e+07',
    min_singular_value: '1.343312e-03',
    condition_number: '1.683779e+10',
    svd_rank: '1821',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'ex3.png,ex31.png,ex31_dmperm.png,ex31_scc.png,ex31_svd.png,ex32.png,ex32_dmperm.png,ex32_scc.png,ex32_svd.png,ex33.png,ex33_dmperm.png,ex33_svd.png,ex35.png,ex35_dmperm.png,ex35_svd.png,ex36.png,ex36_dmperm.png,ex36_scc.png,ex36_svd.png,ex37.png,ex37_dmperm.png,ex37_svd.png,ex3_svd.png,ex31_graph.gif,ex32_graph.gif,ex33_graph.gif,ex35_graph.gif,ex36_graph.gif,ex37_graph.gif,ex3_graph.gif,',
}
