{
    matrix_id: '428',
    name: 'ex31',
    group: 'FIDAP',
    description: ' TEST MATRIX FROM FIDAP: EX31.MAT',
    author: 'A. Baggag, Y. Saad',
    editor: 'A. Baggag, Y. Saad',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '3909',
    num_cols: '3909',
    nonzeros: '91223',
    num_explicit_zeros: '24134',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '3909',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.727',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.276728e+01',
    min_singular_value: '7.936783e-05',
    condition_number: '2.868577e+05',
    svd_rank: '3909',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'ex31.png,ex31_dmperm.png,ex31_scc.png,ex31_svd.png,ex31_graph.gif,',
}
