{
    matrix_id: '430',
    name: 'ex33',
    group: 'FIDAP',
    description: ' TEST MATRIX FROM FIDAP: EX33.MAT',
    author: 'A. Baggag, Y. Saad',
    editor: 'A. Baggag, Y. Saad',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '1733',
    num_cols: '1733',
    nonzeros: '22189',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '1733',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '1.175987e+11',
    min_singular_value: '1.676120e-02',
    condition_number: '7.016124e+12',
    svd_rank: '1732',
    sprank_minus_rank: '1',
    null_space_dimension: '1',
    full_numerical_rank: 'no',
    svd_gap: '1.796788',
    image_files: 'ex33.png,ex33_dmperm.png,ex33_svd.png,ex33_graph.gif,',
}
