{
    matrix_id: '432',
    name: 'ex36',
    group: 'FIDAP',
    description: ' TEST MATRIX FROM FIDAP: EX36.MAT',
    author: 'A. Baggag, Y. Saad',
    editor: 'A. Baggag, Y. Saad',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '3079',
    num_cols: '3079',
    nonzeros: '53099',
    num_explicit_zeros: '744',
    num_strongly_connected_components: '3',
    num_dmperm_blocks: '3',
    structural_full_rank: 'true',
    structural_rank: '3079',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.995',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.624106e+02',
    min_singular_value: '2.145621e-04',
    condition_number: '1.223005e+06',
    svd_rank: '3079',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'ex36.png,ex36_dmperm.png,ex36_scc.png,ex36_svd.png,ex36_graph.gif,',
}
