{
    matrix_id: '434',
    name: 'ex4',
    group: 'FIDAP',
    description: ' TEST MATRIX FROM FIDAP: EX4.MAT',
    author: 'A. Baggag, Y. Saad',
    editor: 'A. Baggag, Y. Saad',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '1601',
    num_cols: '1601',
    nonzeros: '31849',
    num_explicit_zeros: '450',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '1601',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.568548e+00',
    min_singular_value: '6.572360e-04',
    condition_number: '2.386583e+03',
    svd_rank: '1601',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'ex4.png,ex40.png,ex40_svd.png,ex4_svd.png,ex40_graph.gif,ex4_graph.gif,',
}
