{
    matrix_id: '435',
    name: 'ex40',
    group: 'FIDAP',
    description: ' TEST MATRIX FROM FIDAP: EX40.MAT',
    author: 'A. Baggag, Y. Saad',
    editor: 'A. Baggag, Y. Saad',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '7740',
    num_cols: '7740',
    nonzeros: '456188',
    num_explicit_zeros: '1824',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '7740',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.771',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '7.249828e+00',
    min_singular_value: '2.633097e-06',
    condition_number: '2.753346e+06',
    svd_rank: '7740',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'ex40.png,ex40_svd.png,ex40_graph.gif,',
}
