{
    matrix_id: '437',
    name: 'ex6',
    group: 'FIDAP',
    description: ' TEST MATRIX FROM FIDAP: EX6.MAT',
    author: 'A. Baggag, Y. Saad',
    editor: 'A. Baggag, Y. Saad',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '1651',
    num_cols: '1651',
    nonzeros: '49062',
    num_explicit_zeros: '471',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '13',
    structural_full_rank: 'true',
    structural_rank: '1651',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.979',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '4.493428e+02',
    min_singular_value: '1.164253e-17',
    condition_number: '3.859494e+19',
    svd_rank: '1650',
    sprank_minus_rank: '1',
    null_space_dimension: '1',
    full_numerical_rank: 'no',
    svd_gap: '59312108473607.023438',
    image_files: 'ex6.png,ex6_dmperm.png,ex6_svd.png,ex6_graph.gif,',
}
