{
    matrix_id: '438',
    name: 'ex7',
    group: 'FIDAP',
    description: ' TEST MATRIX FROM FIDAP: EX7.MAT',
    author: 'A. Baggag, Y. Saad',
    editor: 'A. Baggag, Y. Saad',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '1633',
    num_cols: '1633',
    nonzeros: '46626',
    num_explicit_zeros: '7917',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '1633',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.824',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.853688e+09',
    min_singular_value: '2.243774e-02',
    condition_number: '8.261473e+10',
    svd_rank: '1633',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'ex7.png,ex7_dmperm.png,ex7_svd.png,ex7_graph.gif,',
}
