{
    matrix_id: '440',
    name: 'ex9',
    group: 'FIDAP',
    description: ' TEST MATRIX FROM FIDAP: EX9.MAT',
    author: 'A. Baggag, Y. Saad',
    editor: 'A. Baggag, Y. Saad',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '3363',
    num_cols: '3363',
    nonzeros: '99471',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '3363',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '3.787030e+09',
    min_singular_value: '3.243986e-04',
    condition_number: '1.167400e+13',
    svd_rank: '3344',
    sprank_minus_rank: '19',
    null_space_dimension: '19',
    full_numerical_rank: 'no',
    svd_gap: '1.358088',
    image_files: 'ex9.png,ex9_svd.png,ex9_graph.gif,',
}
