{
    matrix_id: '1405',
    name: 'ted_A',
    group: 'Bindel',
    description: 'FEM, coupled linear thermoeslasticity eqns on a bar. D Bindel, UC Berkeley',
    author: 'D. Bindel',
    editor: 'T. Davis',
    date: '2006',
    kind: 'thermal problem',
    problem_2D_or_3D: '1',
    num_rows: '10605',
    num_cols: '10605',
    nonzeros: '424587',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '4244',
    structural_full_rank: 'true',
    structural_rank: '10605',
    pattern_symmetry: '0.566',
    numeric_symmetry: '0.106',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.348574e+01',
    min_singular_value: '5.461308e-12',
    condition_number: '2.469324e+12',
    svd_rank: '10604',
    sprank_minus_rank: '1',
    null_space_dimension: '1',
    full_numerical_rank: 'no',
    svd_gap: '8.999793',
    image_files: 'ted_A.png,ted_A_dmperm.png,ted_A_svd.png,ted_A_unscaled.png,ted_A_unscaled_dmperm.png,ted_A_unscaled_svd.png,ted_A_APlusAT_graph.gif,ted_A_graph.gif,ted_A_unscaled_APlusAT_graph.gif,ted_A_unscaled_graph.gif,',
}
