{
    matrix_id: '1409',
    name: 'ted_B_unscaled',
    group: 'Bindel',
    description: 'FEM, coupled linear thermoeslasticity eqns on a bar. D Bindel, UC Berkeley',
    author: 'D. Bindel',
    editor: 'T. Davis',
    date: '2006',
    kind: 'thermal problem',
    problem_2D_or_3D: '1',
    num_rows: '10605',
    num_cols: '10605',
    nonzeros: '144579',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '4245',
    num_dmperm_blocks: '4245',
    structural_full_rank: 'true',
    structural_rank: '10605',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '1',
    min_singular_value: '7.818886e-12',
    condition_number: '1.278955e+11',
    svd_rank: '10605',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
