{
    matrix_id: '1644',
    name: 'msdoor',
    group: 'INPRO',
    description: 'medium size door',
    author: 'J. Weiher',
    editor: 'J. Koster',
    date: '2005',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '415863',
    num_cols: '415863',
    nonzeros: '19173163',
    num_explicit_zeros: '1067772',
    num_strongly_connected_components: '11079',
    num_dmperm_blocks: '11079',
    structural_full_rank: 'true',
    structural_rank: '415863',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    notes: 'from Parasol, http://www.parallab.uib.no/projects/parasol/data
',
}
