{
    matrix_id: '1509',
    name: 'NotreDame_actors',
    group: 'Barabasi',
    description: 'CCNR network: Barabasi\'s actor network (of www.imdb.com)',
    author: 'A Barabasi, R. Albert',
    editor: 'H. Jeong',
    date: '1999',
    kind: 'bipartite graph',
    problem_2D_or_3D: '0',
    num_rows: '392400',
    num_cols: '127823',
    nonzeros: '1470404',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '11902',
    num_dmperm_blocks: '19604',
    structural_full_rank: 'false',
    structural_rank: '114762',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'binary',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'http://www.nd.edu/~networks (14 duplicate entries removed)
',
    image_files: 'NotreDame_actors.png,NotreDame_actors_scc.png,NotreDame_actors_graph.gif,',
}
