{
    matrix_id: '441',
    name: 'big',
    group: 'Gaertner',
    description: 'Structuresymmetric Matrix big K. Gaertner ETH Zurich Oct 1996.',
    author: 'K. Gaertner',
    editor: 'F. Grund',
    date: '2001',
    kind: 'directed weighted graph',
    problem_2D_or_3D: '0',
    num_rows: '13209',
    num_cols: '13209',
    nonzeros: '91465',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'integer',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '3.912801e+04',
    min_singular_value: '8.819377e-04',
    condition_number: '4.436596e+07',
    svd_rank: '13209',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
