{
    matrix_id: '1411',
    name: 'F1',
    group: 'Koutsovasilis',
    description: 'Matrix from Panagiotis Koutsovasilis, Technische Universita(")t Dresden',
    author: 'P. Koutsovasilis',
    editor: 'T. Davis',
    date: '2006',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '343791',
    num_cols: '343791',
    nonzeros: '26837113',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '343791',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    notes: 'Stiffness matrix from an AUDI engine crankshaft
',
    b_field: 'full 343791-by-33
',
}
