{
    matrix_id: '1317',
    name: 'mri1',
    group: 'Bydder',
    description: 'MRI reconstruction (1), from Mark Bydder, UCSD',
    author: 'M. Bydder',
    editor: 'T. Davis',
    date: '2005',
    kind: 'computer graphics/vision problem',
    problem_2D_or_3D: '1',
    num_rows: '65536',
    num_cols: '147456',
    nonzeros: '589824',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '32820',
    num_dmperm_blocks: '258',
    structural_full_rank: 'false',
    structural_rank: '64517',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'x = lsqr (A,b) ; imagesc (abs (fftshift (fft2 (reshape (x, 384, 384))))) ;
',
    b_field: 'full 65536-by-1
',
    image_files: 'mri1.png,mri1_dmperm.png,mri1_scc.png,mri1_graph.gif,',
}
