{
    matrix_id: '1318',
    name: 'mri2',
    group: 'Bydder',
    description: 'MRI reconstruction (2), from Mark Bydder, UCSD',
    author: 'M. Bydder',
    editor: 'T. Davis',
    date: '2005',
    kind: 'computer graphics/vision problem',
    problem_2D_or_3D: '1',
    num_rows: '63240',
    num_cols: '147456',
    nonzeros: '569160',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '42860',
    num_dmperm_blocks: '438',
    structural_full_rank: 'false',
    structural_rank: '48321',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'x = lsqr (A,b) ; imagesc (abs (fftshift (fft2 (reshape (x, 384, 384))))) ;
',
    b_field: 'full 63240-by-1
',
    image_files: 'mri2.png,mri2_dmperm.png,mri2_scc.png,mri2_graph.gif,',
}
