{
    matrix_id: '925',
    name: 'ns3Da',
    group: 'FEMLAB',
    description: 'Comsol, Inc.  www.femlab.com : 3D Navier Stokes',
    author: 'COMSOL',
    editor: 'T. Davis',
    date: '2003',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '20414',
    num_cols: '20414',
    nonzeros: '1679599',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '20414',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 20414-by-1
',
    norm: '6.337590e-01',
    min_singular_value: '8.962024e-04',
    condition_number: '7.071606e+02',
    svd_rank: '20414',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'ns3Da.png,ns3Da_svd.png,ns3Da_APlusAT_graph.gif,ns3Da_graph.gif,',
}
