{
    matrix_id: '928',
    name: 'poisson3Db',
    group: 'FEMLAB',
    description: 'Comsol, Inc.  www.femlab.com : 3D Poisson problem',
    author: 'COMSOL',
    editor: 'T. Davis',
    date: '2003',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '85623',
    num_cols: '85623',
    nonzeros: '2374949',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '85623',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 85623-by-1
',
    image_files: 'poisson3Db.png,poisson3Db_graph.gif,',
}
