{
    matrix_id: '931',
    name: 'sme3Db',
    group: 'FEMLAB',
    description: 'Comsol, Inc.  www.femlab.com : 3D structural mechanics problem',
    author: 'COMSOL',
    editor: 'T. Davis',
    date: '2003',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '29067',
    num_cols: '29067',
    nonzeros: '2081063',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '29067',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.441',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 29067-by-1
',
    norm: '7.993463e+04',
    min_singular_value: '2.201064e-03',
    condition_number: '3.631636e+07',
    svd_rank: '29067',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'sme3Db.png,sme3Db_svd.png,sme3Db_APlusAT_graph.gif,sme3Db_graph.gif,',
}
