{
    matrix_id: '933',
    name: 'waveguide3D',
    group: 'FEMLAB',
    description: 'Comsol, Inc.  www.femlab.com : 3D waveguide problem',
    author: 'COMSOL',
    editor: 'T. Davis',
    date: '2003',
    kind: 'electromagnetics problem',
    problem_2D_or_3D: '1',
    num_rows: '21036',
    num_cols: '21036',
    nonzeros: '303468',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '21036',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.000',
    rb_type: 'complex',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 21036-by-1
',
    norm: '8.828849e-01',
    min_singular_value: '8.645242e-05',
    condition_number: '1.021238e+04',
    svd_rank: '21036',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'waveguide3D.png,waveguide3D_svd.png,waveguide3D_graph.gif,',
}
