{
    matrix_id: '979',
    name: 'Stanford',
    group: 'Kamvar',
    description: 'Sep Kamvar. Stanford web. aij=1 is link from page j to page i',
    author: 'S. Kamvar',
    editor: 'T. Davis',
    date: '2003',
    kind: 'directed graph',
    problem_2D_or_3D: '0',
    num_rows: '281903',
    num_cols: '281903',
    nonzeros: '2312497',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '29914',
    pattern_symmetry: '0.277',
    numeric_symmetry: '0.277',
    rb_type: 'binary',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
}
