{
    matrix_id: '927',
    name: 'poisson3Da',
    group: 'FEMLAB',
    description: 'Comsol, Inc.  www.femlab.com : 3D Poisson problem',
    author: 'COMSOL',
    editor: 'T. Davis',
    date: '2003',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '13514',
    num_cols: '13514',
    nonzeros: '352762',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '13514',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 13514-by-1
',
    norm: '8.797694e-01',
    min_singular_value: '7.842040e-04',
    condition_number: '1.121863e+03',
    svd_rank: '13514',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
