{
    matrix_id: '926',
    name: 'poisson2D',
    group: 'FEMLAB',
    description: 'Comsol, Inc.  www.femlab.com : 2D Poisson problem',
    author: 'COMSOL',
    editor: 'T. Davis',
    date: '2003',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '367',
    num_cols: '367',
    nonzeros: '2417',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '367',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 367-by-1
',
    norm: '8.880481e-01',
    min_singular_value: '6.689219e-03',
    condition_number: '1.327581e+02',
    svd_rank: '367',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
