{
    matrix_id: '930',
    name: 'sme3Da',
    group: 'FEMLAB',
    description: 'Comsol, Inc.  www.femlab.com : 3D structural mechanics problem',
    author: 'COMSOL',
    editor: 'T. Davis',
    date: '2003',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '12504',
    num_cols: '12504',
    nonzeros: '874887',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '12504',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.437',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 12504-by-1
',
    norm: '3.087879e+05',
    min_singular_value: '5.916130e-03',
    condition_number: '5.219424e+07',
    svd_rank: '12504',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
