{
    matrix_id: '932',
    name: 'sme3Dc',
    group: 'FEMLAB',
    description: 'Comsol, Inc.  www.femlab.com : 3D structural mechanics problem',
    author: 'COMSOL',
    editor: 'T. Davis',
    date: '2003',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '42930',
    num_cols: '42930',
    nonzeros: '3148656',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '42930',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.439',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 42930-by-1
',
}
