{
    matrix_id: '370',
    name: 'circuit_1',
    group: 'Bomhof',
    description: 'Circuit DAE with BDF method & Newton. W. Bomhof, Univ. Utrecht',
    author: 'W. Bomhof',
    editor: 'T. Davis',
    date: '2000',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '2624',
    num_cols: '2624',
    nonzeros: '35823',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '6',
    num_dmperm_blocks: '60',
    structural_full_rank: 'true',
    structural_rank: '2624',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.206',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 2624-by-1
',
    x_field: 'full 2624-by-1
',
    norm: '3.158959e+00',
    min_singular_value: '1.618509e-05',
    condition_number: '1.951772e+05',
    svd_rank: '2624',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
