{
    matrix_id: '2330',
    name: 'flickr',
    group: 'Gleich',
    description: '2005 crawl of flickr.com, by David Gleich',
    author: 'D. Gleich',
    editor: 'T. Davis',
    date: '2010',
    kind: 'directed graph',
    problem_2D_or_3D: '0',
    num_rows: '820878',
    num_cols: '820878',
    nonzeros: '9837214',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '277277',
    pattern_symmetry: '0.653',
    numeric_symmetry: '0.653',
    rb_type: 'binary',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'node names available upon request from David F. Gleich
',
    image_files: 'flickr.png,flickr_scc.png,flickr_APlusAT_graph.gif,flickr_graph.gif,',
}
