{
    matrix_id: '1841',
    name: 'wb-cs-stanford',
    group: 'Gleich',
    description: 'Stanford CS web, A(i,j)=1 if page i links to page j (2001)',
    author: 'D. Gleich',
    editor: 'T. Davis',
    date: '2001',
    kind: 'directed graph',
    problem_2D_or_3D: '0',
    num_rows: '9914',
    num_cols: '9914',
    nonzeros: '36854',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '4391',
    pattern_symmetry: '0.457',
    numeric_symmetry: '0.457',
    rb_type: 'binary',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'For nodenames, see http://www.cise.ufl.edu/research/sparse/aux/Gleich
This graph is a subset of Gleich/wb-edu, with *.cs.stanford.edu only.
',
    norm: '3.837660e+01',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '5475',
    null_space_dimension: '4439',
    full_numerical_rank: 'no',
    svd_gap: '9612037283.912130',
    image_files: 'wb-cs-stanford.png,wb-cs-stanford_scc.png,wb-cs-stanford_svd.png,wb-cs-stanford_APlusAT_graph.gif,wb-cs-stanford_graph.gif,',
}
