{
    matrix_id: '1918',
    name: 'photogrammetry2',
    group: 'Luong',
    description: 'Photogrammetry problem, B. Luong, FOGALE nanotech, France',
    author: 'B. Luong',
    editor: 'T. Davis',
    date: '2008',
    kind: 'computer graphics/vision problem',
    problem_2D_or_3D: '1',
    num_rows: '4472',
    num_cols: '936',
    nonzeros: '37056',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '936',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Photogrammetry problem from Bruno Luong, FOGALE nanotech, France.
This problem is nearly rank-deficient.                           
',
    b_field: 'full 4472-by-1
',
    norm: '2.833894e-04',
    min_singular_value: '2.116259e-12',
    condition_number: '1.339106e+08',
    svd_rank: '936',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'photogrammetry2.png,photogrammetry2_svd.png,photogrammetry2_graph.gif,',
}
