{
    matrix_id: '801',
    name: 'xenon1',
    group: 'Ronis',
    description: 'Complex zeolite,sodalite crystals. D Ronis ronis@onsager.chem.mcgill.ca',
    author: 'D. Ronis',
    editor: 'T. Davis',
    date: '2001',
    kind: 'materials problem',
    problem_2D_or_3D: '1',
    num_rows: '48600',
    num_cols: '48600',
    nonzeros: '1181120',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '31',
    num_dmperm_blocks: '31',
    structural_full_rank: 'true',
    structural_rank: '48600',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.776',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    image_files: 'xenon1.png,xenon1_dmperm.png,xenon1_graph.gif,',
}
