{
    matrix_id: '802',
    name: 'xenon2',
    group: 'Ronis',
    description: 'Complex zeolite,sodalite crystals. D Ronis ronis@onsager.chem.mcgill.ca',
    author: 'D. Ronis',
    editor: 'T. Davis',
    date: '2001',
    kind: 'materials problem',
    problem_2D_or_3D: '1',
    num_rows: '157464',
    num_cols: '157464',
    nonzeros: '3866688',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '55',
    num_dmperm_blocks: '55',
    structural_full_rank: 'true',
    structural_rank: '157464',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.776',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    image_files: 'xenon2.png,xenon2_dmperm.png,xenon2_graph.gif,',
}
