{
    matrix_id: '1329',
    name: 'Kemelmacher',
    group: 'Kemelmacher',
    description: 'Computer vision problem.  Ira Kemelmacher, Weizmann Inst., Israel',
    author: 'I. Kemelmacher',
    editor: 'T. Davis',
    date: '2005',
    kind: 'computer graphics/vision problem',
    problem_2D_or_3D: '1',
    num_rows: '28452',
    num_cols: '9693',
    nonzeros: '100875',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '9693',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.405784e+02',
    min_singular_value: '1.009821e-02',
    condition_number: '2.382386e+04',
    svd_rank: '9693',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
