{
    matrix_id: '374',
    name: 'rma10',
    group: 'Bova',
    description: '3D CFD model, Charleston harbor. Steve Bova, US Army Eng., WES',
    author: 'S. Bova',
    editor: 'T. Davis',
    date: '1997',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '46835',
    num_cols: '46835',
    nonzeros: '2329092',
    num_explicit_zeros: '44909',
    num_strongly_connected_components: '8',
    num_dmperm_blocks: '8',
    structural_full_rank: 'true',
    structural_rank: '46835',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.236',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 46835-by-1
',
}
