{
    matrix_id: '1187',
    name: 'rajat03',
    group: 'Rajat',
    description: 'Rajat/rajat03 circuit simulation matrix',
    author: 'Rajat',
    editor: 'T. Davis',
    date: '2004',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '7602',
    num_cols: '7602',
    nonzeros: '32653',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '103',
    structural_full_rank: 'true',
    structural_rank: '7602',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.402',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '5.102060e+02',
    min_singular_value: '4.033267e-05',
    condition_number: '1.264994e+07',
    svd_rank: '7602',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'rajat03.png,rajat03_dmperm.png,rajat03_svd.png,rajat03_graph.gif,',
}
