{
    matrix_id: '1316',
    name: 'rajat15',
    group: 'Rajat',
    description: 'Rajat/rajat15 circuit simulation matrix',
    author: 'Rajat',
    editor: 'T. Davis',
    date: '2006',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '37261',
    num_cols: '37261',
    nonzeros: '443573',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '19',
    structural_full_rank: 'true',
    structural_rank: '37261',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.943',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '3.268466e+05',
    min_singular_value: '7.103593e-04',
    condition_number: '4.601145e+08',
    svd_rank: '37261',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'rajat15.png,rajat15_dmperm.png,rajat15_svd.png,rajat15_graph.gif,',
}
