{
    matrix_id: '1345',
    name: 'rajat18',
    group: 'Rajat',
    description: 'Rajat/rajat18 circuit simulation matrix',
    author: 'Rajat',
    editor: 'T. Davis',
    date: '2006',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '94294',
    num_cols: '94294',
    nonzeros: '479151',
    num_explicit_zeros: '5992',
    num_strongly_connected_components: '5232',
    num_dmperm_blocks: '8549',
    structural_full_rank: 'true',
    structural_rank: '94294',
    pattern_symmetry: '0.626',
    numeric_symmetry: '0.285',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    image_files: 'rajat18.png,rajat18_dmperm.png,rajat18_scc.png,rajat18_APlusAT_graph.gif,rajat18_graph.gif,',
}
