{
    matrix_id: '1370',
    name: 'rajat21',
    group: 'Rajat',
    description: 'Rajat/rajat21 circuit simulation matrix',
    author: 'Rajat',
    editor: 'T. Davis',
    date: '2006',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '411676',
    num_cols: '411676',
    nonzeros: '1876011',
    num_explicit_zeros: '17359',
    num_strongly_connected_components: '5956',
    num_dmperm_blocks: '10195',
    structural_full_rank: 'true',
    structural_rank: '411676',
    pattern_symmetry: '0.765',
    numeric_symmetry: '0.615',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    image_files: 'rajat21.png,rajat21_dmperm.png,rajat21_scc.png,rajat21_APlusAT_graph.gif,rajat21_graph.gif,',
}
