{
    matrix_id: '1398',
    name: 'rajat31',
    group: 'Rajat',
    description: 'Rajat/rajat31 circuit simulation matrix',
    author: 'Rajat',
    editor: 'T. Davis',
    date: '2006',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '4690002',
    num_cols: '4690002',
    nonzeros: '20316253',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '2503',
    structural_full_rank: 'true',
    structural_rank: '4690002',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.400',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    image_files: 'rajat31.png,rajat31_dmperm.png,rajat31_graph.gif,',
}
