{
    matrix_id: '1369',
    name: 'rajat20',
    group: 'Rajat',
    description: 'Rajat/rajat20 circuit simulation matrix',
    author: 'Rajat',
    editor: 'T. Davis',
    date: '2006',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '86916',
    num_cols: '86916',
    nonzeros: '604299',
    num_explicit_zeros: '746',
    num_strongly_connected_components: '1355',
    num_dmperm_blocks: '3672',
    structural_full_rank: 'true',
    structural_rank: '86916',
    pattern_symmetry: '0.991',
    numeric_symmetry: '0.112',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    image_files: 'rajat20.png,rajat20_dmperm.png,rajat20_scc.png,rajat20_APlusAT_graph.gif,rajat20_graph.gif,',
}
