{
    matrix_id: '1195',
    name: 'rajat11',
    group: 'Rajat',
    description: 'Rajat/rajat11 circuit simulation matrix',
    author: 'Rajat',
    editor: 'T. Davis',
    date: '2004',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '135',
    num_cols: '135',
    nonzeros: '665',
    num_explicit_zeros: '147',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '7',
    structural_full_rank: 'true',
    structural_rank: '135',
    pattern_symmetry: '0.891',
    numeric_symmetry: '0.630',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.500053e+01',
    min_singular_value: '1.625352e-05',
    condition_number: '9.229098e+05',
    svd_rank: '135',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'rajat11.png,rajat11_dmperm.png,rajat11_svd.png,rajat11_APlusAT_graph.gif,rajat11_graph.gif,',
}
