{
    matrix_id: '1372',
    name: 'rajat23',
    group: 'Rajat',
    description: 'Rajat/rajat23 circuit simulation matrix',
    author: 'Rajat',
    editor: 'T. Davis',
    date: '2006',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '110355',
    num_cols: '110355',
    nonzeros: '555441',
    num_explicit_zeros: '1497',
    num_strongly_connected_components: '1410',
    num_dmperm_blocks: '6052',
    structural_full_rank: 'true',
    structural_rank: '110355',
    pattern_symmetry: '0.989',
    numeric_symmetry: '0.332',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    image_files: 'rajat23.png,rajat23_dmperm.png,rajat23_scc.png,rajat23_APlusAT_graph.gif,rajat23_graph.gif,',
}
