{
    matrix_id: '1346',
    name: 'rajat19',
    group: 'Rajat',
    description: 'Rajat/rajat19 circuit simulation matrix',
    author: 'Rajat',
    editor: 'T. Davis',
    date: '2006',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '1157',
    num_cols: '1157',
    nonzeros: '3699',
    num_explicit_zeros: '1700',
    num_strongly_connected_components: '166',
    num_dmperm_blocks: '734',
    structural_full_rank: 'true',
    structural_rank: '1157',
    pattern_symmetry: '0.904',
    numeric_symmetry: '0.919',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.091059e+01',
    min_singular_value: '9.999999e-10',
    condition_number: '1.091059e+10',
    svd_rank: '1157',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'rajat19.png,rajat19_dmperm.png,rajat19_scc.png,rajat19_svd.png,rajat19_APlusAT_graph.gif,rajat19_graph.gif,',
}
