{
    matrix_id: '1194',
    name: 'rajat10',
    group: 'Rajat',
    description: 'Rajat/rajat10 circuit simulation matrix',
    author: 'Rajat',
    editor: 'T. Davis',
    date: '2004',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '30202',
    num_cols: '30202',
    nonzeros: '130303',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '203',
    structural_full_rank: 'true',
    structural_rank: '30202',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.121903e+01',
    min_singular_value: '8.562500e-03',
    condition_number: '1.310251e+03',
    svd_rank: '30202',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'rajat10.png,rajat10_dmperm.png,rajat10_svd.png,rajat10_graph.gif,',
}
