{
    matrix_id: '1192',
    name: 'rajat08',
    group: 'Rajat',
    description: 'Rajat/rajat08 circuit simulation matrix',
    author: 'Rajat',
    editor: 'T. Davis',
    date: '2004',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '19362',
    num_cols: '19362',
    nonzeros: '83443',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '163',
    structural_full_rank: 'true',
    structural_rank: '19362',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.019232e+01',
    min_singular_value: '1.068990e-02',
    condition_number: '9.534528e+02',
    svd_rank: '19362',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'rajat08.png,rajat08_dmperm.png,rajat08_svd.png,rajat08_graph.gif,',
}
