{
    matrix_id: '1196',
    name: 'rajat12',
    group: 'Rajat',
    description: 'Rajat/rajat12 circuit simulation matrix',
    author: 'Rajat',
    editor: 'T. Davis',
    date: '2004',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '1879',
    num_cols: '1879',
    nonzeros: '12818',
    num_explicit_zeros: '108',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '24',
    structural_full_rank: 'true',
    structural_rank: '1879',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.455',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.047299e+03',
    min_singular_value: '1.514843e-03',
    condition_number: '6.913577e+05',
    svd_rank: '1879',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'rajat12.png,rajat12_dmperm.png,rajat12_svd.png,rajat12_graph.gif,',
}
