{
    matrix_id: '1880',
    name: 'water_tank',
    group: 'Rudnyi',
    description: '3D fluid flow: water in a tank.  Evgenii Rudnyi, IMTEK',
    author: 'E. Rudnyi',
    editor: 'T. Davis',
    date: '2007',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '60740',
    num_cols: '60740',
    nonzeros: '2035281',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '60740',
    pattern_symmetry: '0.969',
    numeric_symmetry: '0.918',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    image_files: 'water_tank.png,water_tank_dmperm.png,water_tank_APlusAT_graph.gif,water_tank_graph.gif,',
}
