{
    matrix_id: '1852',
    name: 'FEM_3D_thermal2',
    group: 'Botonakis',
    description: 'FEM 3D nonlinear thermal problem, 8-node bricks as volume elements',
    author: 'I. Botonakis',
    editor: 'T. Davis',
    date: '2007',
    kind: 'thermal problem',
    problem_2D_or_3D: '1',
    num_rows: '147900',
    num_cols: '147900',
    nonzeros: '3489300',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '147900',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.950',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'This is the smallest problem whose results are useful.
',
    image_files: 'FEM_3D_thermal2.png,FEM_3D_thermal2_graph.gif,',
}
