{
    matrix_id: '2257',
    name: 'thermomech_TC',
    group: 'Botonakis',
    description: 'FEM problem, temperature and deformation of a steel cylinder',
    author: 'I. Botonakis',
    editor: 'T. Davis',
    date: '2009',
    kind: 'thermal problem',
    problem_2D_or_3D: '1',
    num_rows: '102158',
    num_cols: '102158',
    nonzeros: '711558',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '102158',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    notes: 'TC and TK are for temperature, dM and dK for deformation
',
    image_files: 'thermomech_TC.png,thermomech_TC_graph.gif,',
}
