{
    matrix_id: '1893',
    name: 'largebasis',
    group: 'QLi',
    description: 'Large basis matrix from Q. Li, Univ. Wisconsin',
    author: 'Q. Li',
    editor: 'T. Davis',
    date: '2008',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '440020',
    num_cols: '440020',
    nonzeros: '5240084',
    num_explicit_zeros: '320016',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '440020',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    image_files: 'largebasis.png,largebasis_graph.gif,',
}
