{
    matrix_id: '914',
    name: 'cage13',
    group: 'vanHeukelum',
    description: 'DNA electrophoresis, 13 monomers in polymer. A. van Heukelum, Utrecht U',
    author: 'A. van Heukelum',
    editor: 'T. Davis',
    date: '2003',
    kind: 'directed weighted graph',
    problem_2D_or_3D: '0',
    num_rows: '445315',
    num_cols: '445315',
    nonzeros: '7479343',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.200',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    image_files: 'cage13.png,cage13_graph.gif,',
}
