{
    matrix_id: '909',
    name: 'cage8',
    group: 'vanHeukelum',
    description: 'DNA electrophoresis, 8 monomers in polymer. A. van Heukelum, Utrecht U.',
    author: 'A. van Heukelum',
    editor: 'T. Davis',
    date: '2003',
    kind: 'directed weighted graph',
    problem_2D_or_3D: '0',
    num_rows: '1015',
    num_cols: '1015',
    nonzeros: '11003',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.145',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.022023e+00',
    min_singular_value: '8.954487e-02',
    condition_number: '1.141353e+01',
    svd_rank: '1015',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'cage8.png,cage8_svd.png,cage8_graph.gif,',
}
