{
    matrix_id: '916',
    name: 'cage15',
    group: 'vanHeukelum',
    description: 'DNA electrophoresis, 15 monomers in polymer. A. van Heukelum, Utrecht U',
    author: 'A. van Heukelum',
    editor: 'T. Davis',
    date: '2003',
    kind: 'directed weighted graph',
    problem_2D_or_3D: '0',
    num_rows: '5154859',
    num_cols: '5154859',
    nonzeros: '99199551',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '5154859',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.213',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    image_files: 'cage15.png,cage15_graph.gif,',
}
