{
    matrix_id: '906',
    name: 'cage5',
    group: 'vanHeukelum',
    description: 'DNA electrophoresis, 5 monomers in polymer. A. van Heukelum, Utrecht U.',
    author: 'A. van Heukelum',
    editor: 'T. Davis',
    date: '2003',
    kind: 'directed weighted graph',
    problem_2D_or_3D: '0',
    num_rows: '37',
    num_cols: '37',
    nonzeros: '233',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.041',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.048130e+00',
    min_singular_value: '6.798732e-02',
    condition_number: '1.541655e+01',
    svd_rank: '37',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'cage5.png,cage5_svd.png,cage5_graph.gif,',
}
