{
    matrix_id: '908',
    name: 'cage7',
    group: 'vanHeukelum',
    description: 'DNA electrophoresis, 7 monomers in polymer. A. van Heukelum, Utrecht U.',
    author: 'A. van Heukelum',
    editor: 'T. Davis',
    date: '2003',
    kind: 'directed weighted graph',
    problem_2D_or_3D: '0',
    num_rows: '340',
    num_cols: '340',
    nonzeros: '3084',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.102',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.030537e+00',
    min_singular_value: '7.883973e-02',
    condition_number: '1.307130e+01',
    svd_rank: '340',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'cage7.png,cage7_svd.png,cage7_graph.gif,',
}
