{
    matrix_id: '904',
    name: 'cage3',
    group: 'vanHeukelum',
    description: 'DNA electrophoresis, 3 monomers in polymer. A. van Heukelum, Utrecht U.',
    author: 'A. van Heukelum',
    editor: 'T. Davis',
    date: '2003',
    kind: 'directed weighted graph',
    problem_2D_or_3D: '0',
    num_rows: '5',
    num_cols: '5',
    nonzeros: '19',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.136696e+00',
    min_singular_value: '6.031669e-02',
    condition_number: '1.884547e+01',
    svd_rank: '5',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'cage3.png,cage3_svd.png,cage3_graph.gif,',
}
