{
    matrix_id: '912',
    name: 'cage11',
    group: 'vanHeukelum',
    description: 'DNA electrophoresis, 11 monomers in polymer. A. van Heukelum, Utrecht U',
    author: 'A. van Heukelum',
    editor: 'T. Davis',
    date: '2003',
    kind: 'directed weighted graph',
    problem_2D_or_3D: '0',
    num_rows: '39082',
    num_cols: '39082',
    nonzeros: '559722',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.182',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.020789e+00',
    min_singular_value: '8.319109e-02',
    condition_number: '1.227041e+01',
    svd_rank: '39082',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'cage11.png,cage11_svd.png,cage11_graph.gif,',
}
