{
    matrix_id: '812',
    name: 'bbmat',
    group: 'Simon',
    description: 'BEAM + BAILEY 2D AIRFOIL EXACT JACOBIAN:  MACH = 0.08, ANGLE = 2.0, TURB',
    author: 'H. Simon',
    editor: 'H. Simon',
    date: '1993',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '38744',
    num_cols: '38744',
    nonzeros: '1771722',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '38744',
    pattern_symmetry: '0.530',
    numeric_symmetry: '0.001',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 38744-by-1
',
    x_field: 'full 38744-by-1
',
    norm: '3.992383e+03',
    min_singular_value: '7.350886e-06',
    condition_number: '5.431159e+08',
    svd_rank: '38744',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
