{
    matrix_id: '813',
    name: 'olafu',
    group: 'Simon',
    description: 'STRUCTURE FROM NASA LANGLEY, ACCURACY PROBLEM ON Y-MP',
    author: 'H. Simon',
    editor: 'H. Simon',
    date: '1993',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '16146',
    num_cols: '16146',
    nonzeros: '1015156',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '16146',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    b_field: 'full 16146-by-1
',
    norm: '9.478703e+11',
    min_singular_value: '1.245420e+00',
    condition_number: '7.610850e+11',
    svd_rank: '16145',
    sprank_minus_rank: '1',
    null_space_dimension: '1',
    full_numerical_rank: 'no',
    svd_gap: '2.189870',
}
