{
    matrix_id: '817',
    name: 'raefsky4',
    group: 'Simon',
    description: 'BUCKLING PROBLEM FOR CONTAINER MODEL, ARTHUR RAEFSKY, CENTRIC ENG.',
    author: 'A. Raefsky',
    editor: 'H. Simon',
    date: '1993',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '19779',
    num_cols: '19779',
    nonzeros: '1316789',
    num_explicit_zeros: '11822',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '19779',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    b_field: 'full 19779-by-1
',
    norm: '2.666937e+11',
    min_singular_value: '8.520300e-03',
    condition_number: '3.130097e+13',
    svd_rank: '19771',
    sprank_minus_rank: '8',
    null_space_dimension: '8',
    full_numerical_rank: 'no',
    svd_gap: '1.103816',
}
