{
    matrix_id: '1851',
    name: 'FEM_3D_thermal1',
    group: 'Botonakis',
    description: 'FEM 3D nonlinear thermal problem, 8-node bricks as volume elements',
    author: 'I. Botonakis',
    editor: 'T. Davis',
    date: '2007',
    kind: 'thermal problem',
    problem_2D_or_3D: '1',
    num_rows: '17880',
    num_cols: '17880',
    nonzeros: '430740',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '17880',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.951',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'This is a very small test problem.
',
    norm: '5.349521e+00',
    min_singular_value: '6.997742e-03',
    condition_number: '7.644639e+02',
    svd_rank: '17880',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
