{
    matrix_id: '2260',
    name: 'thermomech_dK',
    group: 'Botonakis',
    description: 'FEM problem, temperature and deformation of a steel cylinder',
    author: 'I. Botonakis',
    editor: 'T. Davis',
    date: '2009',
    kind: 'thermal problem',
    problem_2D_or_3D: '1',
    num_rows: '204316',
    num_cols: '204316',
    nonzeros: '2846228',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '204316',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.665',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'TC and TK are for temperature, dM and dK for deformation
',
}
