{
    matrix_id: '2259',
    name: 'thermomech_dM',
    group: 'Botonakis',
    description: 'FEM problem, temperature and deformation of a steel cylinder',
    author: 'I. Botonakis',
    editor: 'T. Davis',
    date: '2009',
    kind: 'thermal problem',
    problem_2D_or_3D: '1',
    num_rows: '204316',
    num_cols: '204316',
    nonzeros: '1423116',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '204316',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    notes: 'TC and TK are for temperature, dM and dK for deformation
',
}
