{
    matrix_id: '540',
    name: 'add32',
    group: 'Hamm',
    description: '32-bit adder, from Steve Hamm (Motorola) hamm@austoto.sps.mot.com',
    author: 'S. Hamm',
    editor: 'T. Davis',
    date: '1991',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '4960',
    num_cols: '4960',
    nonzeros: '19848',
    num_explicit_zeros: '4036',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '4960',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.305',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 4960-by-1
',
    norm: '5.749318e-02',
    min_singular_value: '4.206502e-04',
    condition_number: '1.366769e+02',
    svd_rank: '4960',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'add32.png,add32_svd.png,add32_graph.gif,',
}
