{
    matrix_id: '542',
    name: 'hcircuit',
    group: 'Hamm',
    description: 'Steve Hamm, Motorola. Circuit w/no parasitics (Steve.Hamm@motorola.com)',
    author: 'S. Hamm',
    editor: 'T. Davis',
    date: '2001',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '105676',
    num_cols: '105676',
    nonzeros: '513072',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1359',
    num_dmperm_blocks: '1420',
    structural_full_rank: 'true',
    structural_rank: '105676',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.195',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 105676-by-1
',
    image_files: 'hcircuit.png,hcircuit_dmperm.png,hcircuit_scc.png,hcircuit_APlusAT_graph.gif,hcircuit_graph.gif,',
}
