{
    matrix_id: '544',
    name: 'scircuit',
    group: 'Hamm',
    description: 'Steve Hamm, Motorola. Circuit,many parasitics (Steve.Hamm@motorola.com)',
    author: 'S. Hamm',
    editor: 'T. Davis',
    date: '2001',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '170998',
    num_cols: '170998',
    nonzeros: '958936',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '48',
    num_dmperm_blocks: '153',
    structural_full_rank: 'true',
    structural_rank: '170998',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.801',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 170998-by-1
',
    image_files: 'scircuit.png,scircuit_dmperm.png,scircuit_scc.png,scircuit_APlusAT_graph.gif,scircuit_graph.gif,',
}
