{
    matrix_id: '1926',
    name: 'bibd_14_7',
    group: 'JGD_BIBD',
    description: 'Balanced Incomplete Block Design from Mark Giesbrecht, Univ. of Waterloo',
    author: 'M. Giesbrecht',
    editor: 'J.-G. Dumas',
    date: '2008',
    kind: 'combinatorial problem',
    problem_2D_or_3D: '0',
    num_rows: '91',
    num_cols: '3432',
    nonzeros: '72072',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '91',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'binary',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Balanced Incomplete Block Design from Mark Giesbrecht, Univ. of Waterloo
From Jean-Guillaume Dumas\' Sparse Integer Matrix Collection,            
http://ljk.imag.fr/membres/Jean-Guillaume.Dumas/simc.html               
                                                                        
Filename in JGD collection: BIBD/bibd_14_7_91x3432.sms                  
',
    norm: '1.289651e+02',
    min_singular_value: '1.587451e+01',
    condition_number: '8.124038e+00',
    svd_rank: '91',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
