{
    matrix_id: '1929',
    name: 'bibd_16_8',
    group: 'JGD_BIBD',
    description: 'Balanced Incomplete Block Design from Mark Giesbrecht, Univ. of Waterloo',
    author: 'M. Giesbrecht',
    editor: 'J.-G. Dumas',
    date: '2008',
    kind: 'combinatorial problem',
    problem_2D_or_3D: '0',
    num_rows: '120',
    num_cols: '12870',
    nonzeros: '360360',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '120',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'binary',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Balanced Incomplete Block Design from Mark Giesbrecht, Univ. of Waterloo
From Jean-Guillaume Dumas\' Sparse Integer Matrix Collection,            
http://ljk.imag.fr/membres/Jean-Guillaume.Dumas/simc.html               
                                                                        
Filename in JGD collection: BIBD/bibd_16_8_120x12870.sms                
',
    norm: '2.899724e+02',
    min_singular_value: '3.039737e+01',
    condition_number: '9.539392e+00',
    svd_rank: '120',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
