{
    matrix_id: '1931',
    name: 'bibd_17_4b',
    group: 'JGD_BIBD',
    description: 'Balanced Incomplete Block Design from Mark Giesbrecht, Univ. of Waterloo',
    author: 'M. Giesbrecht',
    editor: 'J.-G. Dumas',
    date: '2008',
    kind: 'combinatorial problem',
    problem_2D_or_3D: '0',
    num_rows: '136',
    num_cols: '2380',
    nonzeros: '14280',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '136',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'binary',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Balanced Incomplete Block Design from Mark Giesbrecht, Univ. of Waterloo
From Jean-Guillaume Dumas\' Sparse Integer Matrix Collection,            
http://ljk.imag.fr/membres/Jean-Guillaume.Dumas/simc.html               
                                                                        
Filename in JGD collection: BIBD/bibd_17_4_136x2380.sms                 
',
    norm: '2.509980e+01',
    min_singular_value: '8.831761e+00',
    condition_number: '2.841993e+00',
    svd_rank: '136',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
