{
    matrix_id: '1395',
    name: 'fp',
    group: 'MKS',
    description: '2-D Fokker Planck eqn, electron dyn. in external field. Dan Smith, MKS Inst.',
    author: 'D. Smith',
    editor: 'T. Davis',
    date: '2006',
    kind: 'electromagnetics problem',
    problem_2D_or_3D: '1',
    num_rows: '7548',
    num_cols: '7548',
    nonzeros: '834222',
    num_explicit_zeros: '14331',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '7548',
    pattern_symmetry: '0.758',
    numeric_symmetry: '0.003',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.832902e+09',
    min_singular_value: '5.905184e-04',
    condition_number: '4.797314e+12',
    svd_rank: '7547',
    sprank_minus_rank: '1',
    null_space_dimension: '1',
    full_numerical_rank: 'no',
    svd_gap: '6.664847',
    image_files: 'fp.png,fp_svd.png,fp_APlusAT_graph.gif,fp_graph.gif,',
}
