{
    matrix_id: '862',
    name: 'kim1',
    group: 'Kim',
    description: '2D 197-by-195 complex mesh. Wonsik Kim, Korea',
    author: 'W. Kim',
    editor: 'T. Davis',
    date: '2002',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '38415',
    num_cols: '38415',
    nonzeros: '933195',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '38415',
    pattern_symmetry: '0.990',
    numeric_symmetry: '0.000',
    rb_type: 'complex',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.967171e+05',
    min_singular_value: '3.008306e+01',
    condition_number: '9.863260e+03',
    svd_rank: '38415',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
