{
    matrix_id: '1184',
    name: 'Pres_Poisson',
    group: 'ACUSIM',
    description: 'ACUSIM, Inc: computational fluid dynamics problem',
    author: 'F. Shakib',
    editor: 'T. Davis',
    date: '2004',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '14822',
    num_cols: '14822',
    nonzeros: '715804',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '14822',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    b_field: 'full 14822-by-1
',
    norm: '2.602892e+01',
    min_singular_value: '1.278025e-05',
    condition_number: '2.036653e+06',
    svd_rank: '14822',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
