{
    matrix_id: '1382',
    name: 'ins2',
    group: 'Andrianov',
    description: 'ins2 matrix from Alexander Andrianov, SAS Institute Inc.',
    author: 'A. Andrianov',
    editor: 'T. Davis',
    date: '2006',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '309412',
    num_cols: '309412',
    nonzeros: '2751484',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '309412',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    image_files: 'ins2.png,ins2_graph.gif,',
}
