{
    matrix_id: '1383',
    name: 'lp1',
    group: 'Andrianov',
    description: 'lp1 matrix from Alexander Andrianov, SAS Institute Inc.',
    author: 'A. Andrianov',
    editor: 'T. Davis',
    date: '2006',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '534388',
    num_cols: '534388',
    nonzeros: '1643420',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '534388',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    image_files: 'lp1.png,lp1_graph.gif,',
}
