{
    matrix_id: '1388',
    name: 'net150',
    group: 'Andrianov',
    description: 'net150 matrix from Alexander Andrianov, SAS Institute Inc.',
    author: 'A. Andrianov',
    editor: 'T. Davis',
    date: '2006',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '43520',
    num_cols: '43520',
    nonzeros: '3121200',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '43520',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    image_files: 'net150.png,net150_dmperm.png,net150_graph.gif,',
}
