{
    matrix_id: '1390',
    name: 'net4-1',
    group: 'Andrianov',
    description: 'net4-1 matrix from Alexander Andrianov, SAS Institute Inc.',
    author: 'A. Andrianov',
    editor: 'T. Davis',
    date: '2006',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '88343',
    num_cols: '88343',
    nonzeros: '2441727',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '97',
    num_dmperm_blocks: '97',
    structural_full_rank: 'true',
    structural_rank: '88343',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    image_files: 'net4-1.png,net4-1_dmperm.png,net4-1_graph.gif,',
}
