{
    matrix_id: '2274',
    name: 'memchip',
    group: 'Freescale',
    description: 'Memory chip from K. Gullapalli, Freescale Semiconductor',
    author: 'K. Gullapalli',
    editor: 'T. Davis',
    date: '2010',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '2707524',
    num_cols: '2707524',
    nonzeros: '13343948',
    num_explicit_zeros: '1466254',
    num_strongly_connected_components: '53',
    num_dmperm_blocks: '63',
    structural_full_rank: 'true',
    structural_rank: '2707524',
    pattern_symmetry: '0.906',
    numeric_symmetry: '0.402',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    image_files: 'memchip.png,memchip_dmperm.png,memchip_scc.png,memchip_APlusAT_graph.gif,memchip_graph.gif,',
}
