{
    matrix_id: '292',
    name: 'bfwa398',
    group: 'Bai',
    description: 'BOUNDED FINLINE WAVEGUIDE EIGENMODES B SHULTZ AND S GEDNEY',
    author: 'B. Schultz, S. Gedney',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1994',
    kind: 'electromagnetics problem',
    problem_2D_or_3D: '1',
    num_rows: '398',
    num_cols: '398',
    nonzeros: '3678',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '398',
    pattern_symmetry: '0.989',
    numeric_symmetry: '0.943',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.041190e+01',
    min_singular_value: '3.478622e-03',
    condition_number: '2.993111e+03',
    svd_rank: '398',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'bfwa398.png,bfwa398_dmperm.png,bfwa398_svd.png,bfwa398_APlusAT_graph.gif,bfwa398_graph.gif,',
}
