{
    matrix_id: '296',
    name: 'bfwb62',
    group: 'Bai',
    description: 'BOUNDED FINLINE WAVEGUIDE EIGENMODES B SHULTZ AND S GEDNEY',
    author: 'B. Schultz, S. Gedney',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1994',
    kind: 'electromagnetics problem',
    problem_2D_or_3D: '1',
    num_rows: '62',
    num_cols: '62',
    nonzeros: '342',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '62',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.757722e-04',
    min_singular_value: '1.021953e-05',
    condition_number: '1.719963e+01',
    svd_rank: '62',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'bfwb62.png,bfwb62_dmperm.png,bfwb62_svd.png,bfwb62_graph.gif,',
}
