{
    matrix_id: '300',
    name: 'cdde1',
    group: 'Bai',
    description: 'MODEL CONVECTION-DIFFUSION DIFFERENTIAL EQUATIONS',
    author: 'author unknown',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1992',
    kind: 'computational fluid dynamics problem sequence',
    problem_2D_or_3D: '1',
    num_rows: '961',
    num_cols: '961',
    nonzeros: '4681',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '961',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: Bai/cdde2 first: Bai/cdde1
',
    norm: '7.951453e+00',
    min_singular_value: '3.304263e-03',
    condition_number: '2.406422e+03',
    svd_rank: '961',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'cdde1.png,cdde1_svd.png,cdde1_graph.gif,',
}
