{
    matrix_id: '304',
    name: 'cdde5',
    group: 'Bai',
    description: 'MODEL CONVECTION-DIFFUSION DIFFERENTIAL EQUATIONS',
    author: 'author unknown',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1992',
    kind: 'subsequent computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '961',
    num_cols: '961',
    nonzeros: '4681',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '961',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: Bai/cdde6 first: Bai/cdde1
',
    norm: '7.736610e+00',
    min_singular_value: '4.690254e-04',
    condition_number: '1.649508e+04',
    svd_rank: '961',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'cdde5.png,cdde5_svd.png,cdde5_graph.gif,',
}
