{
    matrix_id: '306',
    name: 'ck104',
    group: 'Bai',
    description: 'CHUCK MATRIX (MULTIPLE EIGENVALUES)  J. CULLUM',
    author: 'J. Cullum',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1986',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '104',
    num_cols: '104',
    nonzeros: '992',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '104',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '5.732038e+00',
    min_singular_value: '1.048818e-03',
    condition_number: '5.465239e+03',
    svd_rank: '104',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'ck104.png,ck104_dmperm.png,ck104_svd.png,ck104_graph.gif,',
}
