{
    matrix_id: '309',
    name: 'dw1024',
    group: 'Bai',
    description: 'SQUARE DIELECTRIC WAVEGUIDE, H. DONG',
    author: 'H. Dong',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1993',
    kind: 'electromagnetics problem',
    problem_2D_or_3D: '1',
    num_rows: '2048',
    num_cols: '2048',
    nonzeros: '10114',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '2048',
    pattern_symmetry: '0.985',
    numeric_symmetry: '0.948',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '9.788048e-01',
    min_singular_value: '4.676095e-04',
    condition_number: '2.093210e+03',
    svd_rank: '2048',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'dw1024.png,dw1024_svd.png,dw1024_APlusAT_graph.gif,dw1024_graph.gif,',
}
