{
    matrix_id: '1615',
    name: 'dw8192',
    group: 'Bai',
    description: 'SQUARE DIELECTRIC WAVEGUIDE, H. DONG',
    author: 'H. Dong',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1993',
    kind: 'electromagnetics problem',
    problem_2D_or_3D: '1',
    num_rows: '8192',
    num_cols: '8192',
    nonzeros: '41746',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '8192',
    pattern_symmetry: '0.963',
    numeric_symmetry: '0.915',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.098278e+02',
    min_singular_value: '2.879140e-05',
    condition_number: '3.814605e+06',
    svd_rank: '8192',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'dw8192.png,dw8192_svd.png,dw8192_APlusAT_graph.gif,dw8192_graph.gif,',
}
