{
    matrix_id: '1619',
    name: 'dwg961b',
    group: 'Bai',
    description: 'DISPERSIVE WAVEGUIDE STRUCTURES',
    author: 'S. Gedney and U. Navasariwala',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1996',
    kind: 'electromagnetics problem',
    problem_2D_or_3D: '1',
    num_rows: '961',
    num_cols: '961',
    nonzeros: '10591',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '961',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.348',
    rb_type: 'complex',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '6.350904e+02',
    min_singular_value: '5.665684e-05',
    condition_number: '1.120942e+07',
    svd_rank: '961',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'dwg961b.png,dwg961b_svd.png,dwg961b_graph.gif,',
}
