{
    matrix_id: '313',
    name: 'lop163',
    group: 'Bai',
    description: 'SPARSE STOCHASTIC TEST MATRIX IN LOPSI',
    author: 'W. Stewart',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1978',
    kind: 'statistical/mathematical problem',
    problem_2D_or_3D: '0',
    num_rows: '163',
    num_cols: '163',
    nonzeros: '935',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '163',
    pattern_symmetry: '0.451',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.131655e+00',
    min_singular_value: '4.092970e-08',
    condition_number: '2.764876e+07',
    svd_rank: '163',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'lop163.png,lop163_svd.png,lop163_APlusAT_graph.gif,lop163_graph.gif,',
}
