{
    matrix_id: '1625',
    name: 'mhd4800b',
    group: 'Bai',
    description: 'ALFVEN SPECTRA IN MAGNETOHYDRODYNAMICS',
    author: 'A. Booten, M. Kooper, H. van der Vorst, S. Poedts, J. Goedbloed',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1994',
    kind: 'electromagnetics problem',
    problem_2D_or_3D: '1',
    num_rows: '4800',
    num_cols: '4800',
    nonzeros: '27520',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '14',
    num_dmperm_blocks: '14',
    structural_full_rank: 'true',
    structural_rank: '4800',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '2.196269e+00',
    min_singular_value: '2.689883e-14',
    condition_number: '8.164921e+13',
    svd_rank: '4798',
    sprank_minus_rank: '2',
    null_space_dimension: '2',
    full_numerical_rank: 'no',
    svd_gap: '2.269298',
    image_files: 'mhd4800b.png,mhd4800b_dmperm.png,mhd4800b_svd.png,mhd4800b_graph.gif,',
}
