{
    matrix_id: '315',
    name: 'mhdb416',
    group: 'Bai',
    description: 'MAGNETO-HYDRO-DYNAMICS ALFVEN SPECTRAL PROBLEM',
    author: 'A. Booten, M. Kooper, H. van der Vorst, S. Poedts, J. Goedbloed',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1994',
    kind: 'electromagnetics problem',
    problem_2D_or_3D: '1',
    num_rows: '416',
    num_cols: '416',
    nonzeros: '2312',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '14',
    num_dmperm_blocks: '14',
    structural_full_rank: 'true',
    structural_rank: '416',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '2.196279e+00',
    min_singular_value: '5.498640e-10',
    condition_number: '3.994223e+09',
    svd_rank: '416',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'mhdb416.png,mhdb416_dmperm.png,mhdb416_svd.png,mhdb416_graph.gif,',
}
