{
    matrix_id: '319',
    name: 'olm1000',
    group: 'Bai',
    description: 'OLMSTEAD FLOW MODEL',
    author: 'K. Meerbergen',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '1000',
    num_cols: '1000',
    nonzeros: '3996',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '1000',
    pattern_symmetry: '0.667',
    numeric_symmetry: '0.333',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '9.211618e+04',
    min_singular_value: '6.193842e-02',
    condition_number: '1.487222e+06',
    svd_rank: '1000',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'olm1000.png,olm1000_svd.png,olm1000_APlusAT_graph.gif,olm1000_graph.gif,',
}
