{
    matrix_id: '324',
    name: 'pde2961',
    group: 'Bai',
    description: 'MODEL PDE PROBLEM, H. ELMAN        NX=47, NY=63',
    author: 'H. Elman',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1982',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '2961',
    num_cols: '2961',
    nonzeros: '14585',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '2961',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.501',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.037829e+01',
    min_singular_value: '1.615315e-02',
    condition_number: '6.424933e+02',
    svd_rank: '2961',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'pde2961.png,pde2961_svd.png,pde2961_graph.gif,',
}
