{
    matrix_id: '326',
    name: 'qc2534',
    group: 'Bai',
    description: 'MODEL H2+ IN AN ELECTROMAGNETIC FIELD, S.I. CHU',
    author: 'S. Chu',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1991',
    kind: 'electromagnetics problem',
    problem_2D_or_3D: '1',
    num_rows: '2534',
    num_cols: '2534',
    nonzeros: '463360',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '2534',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.000',
    rb_type: 'complex',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '3.319456e+00',
    min_singular_value: '1.824673e-05',
    condition_number: '1.819206e+05',
    svd_rank: '2534',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'qc2534.png,qc2534_svd.png,qc2534_graph.gif,',
}
