{
    matrix_id: '327',
    name: 'qc324',
    group: 'Bai',
    description: 'MODEL H2+ IN AN ELECTROMAGNETIC FIELD, S.I. CHU',
    author: 'S. Chu',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1991',
    kind: 'electromagnetics problem',
    problem_2D_or_3D: '1',
    num_rows: '324',
    num_cols: '324',
    nonzeros: '26730',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '324',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.000',
    rb_type: 'complex',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.523109e+00',
    min_singular_value: '3.287700e-05',
    condition_number: '4.632751e+04',
    svd_rank: '324',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'qc324.png,qc324_svd.png,qc324_graph.gif,',
}
