{
    matrix_id: '329',
    name: 'rbsa480',
    group: 'Bai',
    description: 'FORWARD KINEMATICS FOR THE STEWART PLATFORM OF ROBOTICS',
    author: 'H. Ren',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1993',
    kind: 'robotics problem',
    problem_2D_or_3D: '1',
    num_rows: '480',
    num_cols: '480',
    nonzeros: '17088',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '480',
    pattern_symmetry: '0.075',
    numeric_symmetry: '0.001',
    rb_type: 'integer',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '8.574829e+02',
    min_singular_value: '8.243350e-02',
    condition_number: '1.040212e+04',
    svd_rank: '480',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'rbsa480.png,rbsa480_svd.png,rbsa480_APlusAT_graph.gif,rbsa480_graph.gif,',
}
