{
    matrix_id: '1635',
    name: 'rdb450l',
    group: 'Bai',
    description: 'REACTION-DIFFUSION BRUSSELATOR MODEL',
    author: 'K. Meerbergen',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '450',
    num_cols: '450',
    nonzeros: '2580',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '450',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.789',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.115884e+01',
    min_singular_value: '1.009272e-01',
    condition_number: '2.096445e+02',
    svd_rank: '450',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'rdb450l.png,rdb450l_svd.png,rdb450l_graph.gif,',
}
