{
    matrix_id: '334',
    name: 'rw136',
    group: 'Bai',
    description: 'MARKOV CHAIN MODELING, RANDOM WALK  (M = 15)  G. W. STEWART',
    author: 'G. Stewart',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1978',
    kind: 'statistical/mathematical problem',
    problem_2D_or_3D: '0',
    num_rows: '136',
    num_cols: '136',
    nonzeros: '479',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '6',
    structural_full_rank: 'true',
    structural_rank: '136',
    pattern_symmetry: '0.443',
    numeric_symmetry: '0.029',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.140850e+00',
    min_singular_value: '4.523380e-06',
    condition_number: '2.522119e+05',
    svd_rank: '136',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'rw136.png,rw136_dmperm.png,rw136_svd.png,rw136_APlusAT_graph.gif,rw136_graph.gif,',
}
