{
    matrix_id: '335',
    name: 'rw496',
    group: 'Bai',
    description: 'MARKOV CHAIN MODELING, RANDOM WALK  (M = 30)  G. W. STEWART',
    author: 'G. Stewart',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1978',
    kind: 'statistical/mathematical problem',
    problem_2D_or_3D: '0',
    num_rows: '496',
    num_cols: '496',
    nonzeros: '1859',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '6',
    structural_full_rank: 'true',
    structural_rank: '496',
    pattern_symmetry: '0.469',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.146816e+00',
    min_singular_value: '5.749721e-11',
    condition_number: '1.994559e+10',
    svd_rank: '496',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'rw496.png,rw496_dmperm.png,rw496_svd.png,rw496_APlusAT_graph.gif,rw496_graph.gif,',
}
