{
    matrix_id: '337',
    name: 'tub100',
    group: 'Bai',
    description: 'TUBULAR REACTOR MODEL',
    author: 'K. Meerbergen, D. Roose',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '100',
    num_cols: '100',
    nonzeros: '396',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '100',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.965195e+03',
    min_singular_value: '1.472823e-01',
    condition_number: '1.334306e+04',
    svd_rank: '100',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'tub100.png,tub1000.png,tub1000_svd.png,tub100_svd.png,tub1000_graph.gif,tub100_graph.gif,',
}
