{
    matrix_id: '2538',
    name: 'OPF_6000',
    group: 'IPSO',
    description: 'Power simulation matrix, Li Peijie, Inst. of Power Systems, Guangxi Univ.',
    author: 'L. Peijie',
    editor: 'J. Hogg',
    date: '2011',
    kind: 'power network problem',
    problem_2D_or_3D: '0',
    num_rows: '29902',
    num_cols: '29902',
    nonzeros: '274697',
    num_explicit_zeros: '27721',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '29902',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Three different kinds of optimization methods (OPF, TSCOPF, HTC)
applied to power system simulation.  All matrices are symmetric 
indefinite.  From Li Peijie, Institute of Power Systems,        
Guangxi University (beyondpeijie at gxu.edu.cn).  Collected by  
Jonathan Hogg, Rutherford Appleton Laboratory, Oxfordshire, UK. 
',
    b_field: 'full 29902-by-1
',
    norm: '6.666670e+07',
    min_singular_value: '6.959930e-04',
    condition_number: '9.578646e+10',
    svd_rank: '29902',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
