{
    matrix_id: '1912',
    name: 'cbuckle',
    group: 'TKK',
    description: 'Compressed cylindrical shell buckling; stiffness mtx K and initial stress G',
    author: 'R. Kouhia',
    editor: 'T. Davis',
    date: '2008',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '13681',
    num_cols: '13681',
    nonzeros: '676515',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '13681',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    notes: 'Matrix problems from Reijo Kouhia, Structural Mechanics, Helsinki  
University of Technology.   http://users.tkk.fi/~kouhia/sparse.html
',
    aux_fields: 'G: sparse 13681-by-13681
',    norm: '7.223612e+04',
    min_singular_value: '2.189548e-03',
    condition_number: '3.299134e+07',
    svd_rank: '13681',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'cbuckle.png,cbuckle_svd.png,cbuckle_graph.gif,',
}
