{
    matrix_id: '1917',
    name: 't2d_q9',
    group: 'TKK',
    description: 'Nonlinear diffusion problem, 50x50 biquadratic mesh, temp field. R Kouhia',
    author: 'R. Kouhia',
    editor: 'T. Davis',
    date: '2008',
    kind: 'structural problem sequence',
    problem_2D_or_3D: '1',
    num_rows: '9801',
    num_cols: '9801',
    nonzeros: '87025',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '9801',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.694',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Matrix sequence from Reijo Kouhia, Structural Mechanics, Helsinki  
University of Technology.   http://users.tkk.fi/~kouhia/sparse.html
',
    b_field: 'full 9801-by-1
',
    aux_fields: 'A: cell 45-by-1
b: cell 45-by-1
',    norm: '4.358065e+00',
    min_singular_value: '1.973288e-03',
    condition_number: '2.208529e+03',
    svd_rank: '9801',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 't2d_q9.png,t2d_q9_svd.png,t2d_q9_graph.gif,',
}
