{
    matrix_id: '1914',
    name: 'tube1',
    group: 'TKK',
    description: 'Tube problem from R. Kouhia',
    author: 'R. Kouhia',
    editor: 'T. Davis',
    date: '2008',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '21498',
    num_cols: '21498',
    nonzeros: '897056',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '21498',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    notes: 'Matrix problems from Reijo Kouhia, Structural Mechanics, Helsinki  
University of Technology.   http://users.tkk.fi/~kouhia/sparse.html
',
    norm: '4.325723e+01',
    min_singular_value: '3.189500e-204',
    condition_number: '1.356239e+205',
    svd_rank: '3583',
    sprank_minus_rank: '17915',
    null_space_dimension: '17915',
    full_numerical_rank: 'no',
    svd_gap: '10012298608.073833',
    image_files: 'tube1.png,tube1_svd.png,tube1_graph.gif,',
}
