{
    matrix_id: '868',
    name: 'bodyy4',
    group: 'Pothen',
    description: 'bodyy4, with coordinates.  From NASA, collected by Alex Pothen',
    author: 'NASA',
    editor: 'G. Kumfert, A. Pothen',
    date: '2003',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '17546',
    num_cols: '17546',
    nonzeros: '121550',
    num_explicit_zeros: '388',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '17546',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    aux_fields: 'coord: full 17546-by-2
',    norm: '8.322216e+02',
    min_singular_value: '1.032680e+00',
    condition_number: '8.058855e+02',
    svd_rank: '17546',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
