{
    matrix_id: '870',
    name: 'bodyy6',
    group: 'Pothen',
    description: 'bodyy6, with coordinates.  From NASA, collected by Alex Pothen',
    author: 'NASA',
    editor: 'G. Kumfert, A. Pothen',
    date: '2003',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '19366',
    num_cols: '19366',
    nonzeros: '134208',
    num_explicit_zeros: '540',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '19366',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    aux_fields: 'coord: full 19366-by-2
',    norm: '7.814275e+04',
    min_singular_value: '1.015576e+00',
    condition_number: '7.694428e+04',
    svd_rank: '19366',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
