{
    matrix_id: '874',
    name: 'mesh1em6',
    group: 'Pothen',
    description: 'mesh1em6, with coordinates.  From NASA, collected by Alex Pothen',
    author: 'NASA',
    editor: 'G. Kumfert, A. Pothen',
    date: '2003',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '48',
    num_cols: '48',
    nonzeros: '306',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '48',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    aux_fields: 'coord: full 48-by-2
',    norm: '7.205989e+00',
    min_singular_value: '1.179650e+00',
    condition_number: '6.108583e+00',
    svd_rank: '48',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
