{
    matrix_id: '877',
    name: 'mesh3e1',
    group: 'Pothen',
    description: 'mesh3e1, with coordinates.  From NASA, collected by Alex Pothen',
    author: 'NASA',
    editor: 'G. Kumfert, A. Pothen',
    date: '2003',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '289',
    num_cols: '289',
    nonzeros: '1377',
    num_explicit_zeros: '512',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '289',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    aux_fields: 'coord: full 289-by-2
',    norm: '8.927724e+00',
    min_singular_value: '1.000000e+00',
    condition_number: '8.927724e+00',
    svd_rank: '289',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
