{
    matrix_id: '883',
    name: 'sphere2',
    group: 'Pothen',
    description: 'sphere2, with coordinates.  From NASA, collected by Alex Pothen',
    author: 'NASA',
    editor: 'G. Kumfert, A. Pothen',
    date: '2003',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '66',
    num_cols: '66',
    nonzeros: '450',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '66',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    aux_fields: 'coord: full 66-by-3
',    norm: '6.877074e+00',
    min_singular_value: '2.273516e-16',
    condition_number: '30248629492495668',
    svd_rank: '64',
    sprank_minus_rank: '2',
    null_space_dimension: '2',
    full_numerical_rank: 'no',
    svd_gap: '140871119575388.531250',
}
