{
    matrix_id: '981',
    name: 'graphics',
    group: 'Sumner',
    description: 'Bob Sumner, MIT.  a computer graphics problem',
    author: 'R. Sumner',
    editor: 'T. Davis',
    date: '2003',
    kind: 'computer graphics/vision problem',
    problem_2D_or_3D: '1',
    num_rows: '29493',
    num_cols: '11822',
    nonzeros: '117954',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '11822',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '3.918540e+08',
    min_singular_value: '2.460721e+00',
    condition_number: '1.592436e+08',
    svd_rank: '11822',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'graphics.png,graphics_svd.png,graphics_graph.gif,',
}
