{
    matrix_id: '376',
    name: 'coater2',
    group: 'Brethour',
    description: 'Tail end of a converging slot coater. J. Brethour, CEMS, U. Minn',
    author: 'J. Brethour',
    editor: 'T. Davis',
    date: '1997',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '9540',
    num_cols: '9540',
    nonzeros: '207308',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '382',
    num_dmperm_blocks: '207',
    structural_full_rank: 'false',
    structural_rank: '9434',
    pattern_symmetry: '0.594',
    numeric_symmetry: '0.128',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.216522e+03',
    min_singular_value: '7.815851e-34',
    condition_number: '1.556480e+36',
    svd_rank: '9426',
    sprank_minus_rank: '8',
    null_space_dimension: '114',
    full_numerical_rank: 'no',
    svd_gap: '2.311083',
}
