{
    matrix_id: '375',
    name: 'coater1',
    group: 'Brethour',
    description: 'Lid-driven cavity, coating flow       J. Brethour, CEMS, U. Minn',
    author: 'J. Brethour',
    editor: 'T. Davis',
    date: '1997',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '1348',
    num_cols: '1348',
    nonzeros: '19457',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '262',
    num_dmperm_blocks: '85',
    structural_full_rank: 'false',
    structural_rank: '1331',
    pattern_symmetry: '0.592',
    numeric_symmetry: '0.395',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '6.653165e+01',
    min_singular_value: '1.445975e-18',
    condition_number: '4.601162e+19',
    svd_rank: '1330',
    sprank_minus_rank: '1',
    null_space_dimension: '18',
    full_numerical_rank: 'no',
    svd_gap: '65.171150',
}
