{
    matrix_id: '371',
    name: 'circuit_2',
    group: 'Bomhof',
    description: 'Circuit DAE with BDF method & Newton. W. Bomhof, Univ. Utrecht',
    author: 'W. Bomhof',
    editor: 'T. Davis',
    date: '2000',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '4510',
    num_cols: '4510',
    nonzeros: '21199',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '3231',
    num_dmperm_blocks: '3249',
    structural_full_rank: 'true',
    structural_rank: '4510',
    pattern_symmetry: '0.807',
    numeric_symmetry: '0.415',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 4510-by-1
',
    x_field: 'full 4510-by-1
',
    norm: '2.638701e+01',
    min_singular_value: '2.000148e-04',
    condition_number: '1.319253e+05',
    svd_rank: '4510',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'circuit_2.png,circuit_2_dmperm.png,circuit_2_scc.png,circuit_2_svd.png,circuit_2_APlusAT_graph.gif,circuit_2_graph.gif,',
}
