{
    matrix_id: '372',
    name: 'circuit_3',
    group: 'Bomhof',
    description: 'Circuit DAE with BDF method & Newton. W. Bomhof, Univ. Utrecht',
    author: 'W. Bomhof',
    editor: 'T. Davis',
    date: '2000',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '12127',
    num_cols: '12127',
    nonzeros: '48137',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '4399',
    num_dmperm_blocks: '4521',
    structural_full_rank: 'true',
    structural_rank: '12127',
    pattern_symmetry: '0.770',
    numeric_symmetry: '0.300',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 12127-by-1
',
    x_field: 'full 12127-by-1
',
    norm: '5.844330e+01',
    min_singular_value: '5.393853e-07',
    condition_number: '1.083517e+08',
    svd_rank: '12127',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'circuit_3.png,circuit_3_dmperm.png,circuit_3_scc.png,circuit_3_svd.png,circuit_3_APlusAT_graph.gif,circuit_3_graph.gif,',
}
