{
    matrix_id: '373',
    name: 'circuit_4',
    group: 'Bomhof',
    description: 'Circuit DAE with BDF method & Newton. W. Bomhof, Univ. Utrecht',
    author: 'W. Bomhof',
    editor: 'T. Davis',
    date: '2000',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '80209',
    num_cols: '80209',
    nonzeros: '307604',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '27923',
    num_dmperm_blocks: '28005',
    structural_full_rank: 'true',
    structural_rank: '80209',
    pattern_symmetry: '0.829',
    numeric_symmetry: '0.364',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 80209-by-1
',
    x_field: 'full 80209-by-1
',
    image_files: 'circuit_4.png,circuit_4_dmperm.png,circuit_4_scc.png,circuit_4_APlusAT_graph.gif,circuit_4_graph.gif,',
}
