{
    matrix_id: '539',
    name: 'add20',
    group: 'Hamm',
    description: '20-bit adder, from Steve Hamm (Motorola) hamm@austoto.sps.mot.com',
    author: 'S. Hamm',
    editor: 'T. Davis',
    date: '1991',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '2395',
    num_cols: '2395',
    nonzeros: '13151',
    num_explicit_zeros: '4168',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '2395',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.527',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 2395-by-1
',
    norm: '7.221442e-01',
    min_singular_value: '5.994340e-05',
    condition_number: '1.204710e+04',
    svd_rank: '2395',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
