{
    matrix_id: '541',
    name: 'bcircuit',
    group: 'Hamm',
    description: 'Steve Hamm, Motorola.  Circuit w/parasitics (Steve.Hamm@motorola.com)',
    author: 'S. Hamm',
    editor: 'T. Davis',
    date: '2001',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '68902',
    num_cols: '68902',
    nonzeros: '375558',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '68902',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.908',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 68902-by-1
',
}
