{
    matrix_id: '543',
    name: 'memplus',
    group: 'Hamm',
    description: 'Memory circuit, from Steve Hamm (Motorola), hamm@austoto.sps.mot.com',
    author: 'S. Hamm',
    editor: 'T. Davis',
    date: '1991',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '17758',
    num_cols: '17758',
    nonzeros: '99147',
    num_explicit_zeros: '27003',
    num_strongly_connected_components: '23',
    num_dmperm_blocks: '23',
    structural_full_rank: 'true',
    structural_rank: '17758',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.496',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 17758-by-1
',
    norm: '1.494846e+00',
    min_singular_value: '1.154896e-05',
    condition_number: '1.294355e+05',
    svd_rank: '17758',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
