{
    matrix_id: '983',
    name: 'ecl32',
    group: 'Sanghavi',
    description: 'semiconductor device simulation matrix. Jagesh Sanghavi, UC Berkeley',
    author: 'J. Sanghavi',
    editor: 'C. Voemel',
    date: '2003',
    kind: 'semiconductor device problem',
    problem_2D_or_3D: '1',
    num_rows: '51993',
    num_cols: '51993',
    nonzeros: '380415',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '9653',
    num_dmperm_blocks: '9653',
    structural_full_rank: 'true',
    structural_rank: '51993',
    pattern_symmetry: '0.922',
    numeric_symmetry: '0.603',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
}
