{
    matrix_id: '1413',
    name: 'ckt11752_dc_1',
    group: 'IBM_EDA',
    description: 'Circuit simulation problem from R. Kimmel, IBM EDA',
    author: 'T. Lehner',
    editor: 'T. Davis',
    date: '2006',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '49702',
    num_cols: '49702',
    nonzeros: '333029',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '172',
    num_dmperm_blocks: '172',
    structural_full_rank: 'true',
    structural_rank: '49702',
    pattern_symmetry: '0.984',
    numeric_symmetry: '0.736',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 49702-by-1
',
    image_files: 'ckt11752_dc_1.png,ckt11752_dc_1_dmperm.png,ckt11752_dc_1_APlusAT_graph.gif,ckt11752_dc_1_graph.gif,',
}
