{
    matrix_id: '1321',
    name: 'dc2',
    group: 'IBM_EDA',
    description: 'IBM EDA circuit simulation matrix, Timothy Lehner (DC)',
    author: 'T. Lehner',
    editor: 'T. Davis',
    date: '2005',
    kind: 'subsequent circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '116835',
    num_cols: '116835',
    nonzeros: '766396',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '19',
    num_dmperm_blocks: '19',
    structural_full_rank: 'true',
    structural_rank: '116835',
    pattern_symmetry: '0.854',
    numeric_symmetry: '0.243',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: IBM_EDA/dc3 first: IBM_EDA/dc1
',
    b_field: 'full 116835-by-1
',
    image_files: 'dc2.png,dc2_dmperm.png,dc2_APlusAT_graph.gif,dc2_graph.gif,',
}
