{
    matrix_id: '1323',
    name: 'trans4',
    group: 'IBM_EDA',
    description: 'IBM EDA circuit simulation matrix, Timothy Lehner (transient)',
    author: 'T. Lehner',
    editor: 'T. Davis',
    date: '2005',
    kind: 'circuit simulation problem sequence',
    problem_2D_or_3D: '0',
    num_rows: '116835',
    num_cols: '116835',
    nonzeros: '749800',
    num_explicit_zeros: '16596',
    num_strongly_connected_components: '19',
    num_dmperm_blocks: '19',
    structural_full_rank: 'true',
    structural_rank: '116835',
    pattern_symmetry: '0.854',
    numeric_symmetry: '0.302',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: IBM_EDA/trans5 first: IBM_EDA/trans4
',
    b_field: 'full 116835-by-1
',
    image_files: 'trans4.png,trans4_dmperm.png,trans4_APlusAT_graph.gif,trans4_graph.gif,',
}
