{
    matrix_id: '2556',
    name: 'Chevron2',
    group: 'Chevron',
    description: 'Temporal freq domain seismic modeling; J. Washbourne, Chevron',
    author: 'J. Washbourne',
    editor: 'T. Davis',
    date: '2012',
    kind: '2D/3D problem',
    problem_2D_or_3D: '0',
    num_rows: '90249',
    num_cols: '90249',
    nonzeros: '803173',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '90249',
    pattern_symmetry: '0.996',
    numeric_symmetry: '0.640',
    rb_type: 'complex',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Complex unsymmetric matrix arising from a 2D Helmholtz formulation
for temporal frequency domain seismic modeling.                   
From John Washbourne, Chevron                                     
',
    image_files: 'Chevron2.png,Chevron2_APlusAT_graph.gif,Chevron2_graph.gif,',
}
