{
    matrix_id: '1214',
    name: 'sts4098',
    group: 'Cannizzo',
    description: 'Structural engineering matrix (finite-element), Fabio Cannizzo',
    author: 'F. Cannizzo',
    editor: 'T. Davis',
    date: '2004',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '4098',
    num_cols: '4098',
    nonzeros: '72356',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '4098',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    b_field: 'sparse 4098-by-1
',
    norm: '3.071025e+08',
    min_singular_value: '1.414654e+00',
    condition_number: '2.170866e+08',
    svd_rank: '4098',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
