{
    matrix_id: '1538',
    name: 'c-19',
    group: 'Schenk_IBMNA',
    description: 'IBM TJ Watson, non-linear optimization',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2006',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '2327',
    num_cols: '2327',
    nonzeros: '21817',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '2327',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 2327-by-1
',
    norm: '1.843574e+04',
    min_singular_value: '2.716761e-02',
    condition_number: '6.785926e+05',
    svd_rank: '2327',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'c-19.png,c-19_svd.png,c-19_graph.gif,',
}
