{
    matrix_id: '1539',
    name: 'c-20',
    group: 'Schenk_IBMNA',
    description: 'IBM TJ Watson, non-linear optimization',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2006',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '2921',
    num_cols: '2921',
    nonzeros: '20445',
    num_explicit_zeros: '2240',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '2921',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 2921-by-1
',
    norm: '1.639673e+07',
    min_singular_value: '1.561836e-05',
    condition_number: '1.049837e+12',
    svd_rank: '2921',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'c-20.png,c-20_svd.png,c-20_graph.gif,',
}
