{
    matrix_id: '1540',
    name: 'c-21',
    group: 'Schenk_IBMNA',
    description: 'IBM TJ Watson, non-linear optimization',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2006',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '3509',
    num_cols: '3509',
    nonzeros: '32145',
    num_explicit_zeros: '12',
    num_strongly_connected_components: '7',
    num_dmperm_blocks: '7',
    structural_full_rank: 'true',
    structural_rank: '3509',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 3509-by-1
',
    norm: '5.972283e+03',
    min_singular_value: '1.819508e-03',
    condition_number: '3.282361e+06',
    svd_rank: '3509',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'c-21.png,c-21_dmperm.png,c-21_svd.png,c-21_graph.gif,',
}
