{
    matrix_id: '1541',
    name: 'c-22',
    group: 'Schenk_IBMNA',
    description: 'IBM TJ Watson, non-linear optimization',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2006',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '3792',
    num_cols: '3792',
    nonzeros: '28870',
    num_explicit_zeros: '2',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '3792',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 3792-by-1
',
    norm: '6.418634e+04',
    min_singular_value: '1.174605e-03',
    condition_number: '5.464504e+07',
    svd_rank: '3792',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'c-22.png,c-22_dmperm.png,c-22_svd.png,c-22_graph.gif,',
}
