{
    matrix_id: '1542',
    name: 'c-23',
    group: 'Schenk_IBMNA',
    description: 'IBM TJ Watson, non-linear optimization',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2006',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '3969',
    num_cols: '3969',
    nonzeros: '31079',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '3969',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 3969-by-1
',
    norm: '1.089708e+03',
    min_singular_value: '4.780286e-02',
    condition_number: '2.279588e+04',
    svd_rank: '3969',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'c-23.png,c-23_svd.png,c-23_graph.gif,',
}
