{
    matrix_id: '1543',
    name: 'c-24',
    group: 'Schenk_IBMNA',
    description: 'IBM TJ Watson, non-linear optimization',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2006',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '4119',
    num_cols: '4119',
    nonzeros: '35699',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '4119',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 4119-by-1
',
    norm: '5.111218e+04',
    min_singular_value: '2.287497e-04',
    condition_number: '2.234415e+08',
    svd_rank: '4119',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'c-24.png,c-24_svd.png,c-24_graph.gif,',
}
