{
    matrix_id: '1544',
    name: 'c-25',
    group: 'Schenk_IBMNA',
    description: 'IBM TJ Watson, non-linear optimization',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2006',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '3797',
    num_cols: '3797',
    nonzeros: '49635',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '3797',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 3797-by-1
',
    norm: '2.110702e+03',
    min_singular_value: '2.350734e-02',
    condition_number: '8.978907e+04',
    svd_rank: '3797',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'c-25.png,c-25_svd.png,c-25_graph.gif,',
}
