{
    matrix_id: '1550',
    name: 'c-31',
    group: 'Schenk_IBMNA',
    description: 'IBM TJ Watson, non-linear optimization',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2006',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '5339',
    num_cols: '5339',
    nonzeros: '78571',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '5339',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 5339-by-1
',
    norm: '5.494000e+04',
    min_singular_value: '4.845332e-05',
    condition_number: '1.133875e+09',
    svd_rank: '5339',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'c-31.png,c-31_svd.png,c-31_graph.gif,',
}
