{
    matrix_id: '1552',
    name: 'c-33',
    group: 'Schenk_IBMNA',
    description: 'IBM TJ Watson, non-linear optimization',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2006',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '6317',
    num_cols: '6317',
    nonzeros: '56123',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '6317',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 6317-by-1
',
    norm: '2.045408e+05',
    min_singular_value: '1.827313e-03',
    condition_number: '1.119353e+08',
    svd_rank: '6317',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'c-33.png,c-33_svd.png,c-33_graph.gif,',
}
