{
    matrix_id: '1553',
    name: 'c-34',
    group: 'Schenk_IBMNA',
    description: 'IBM TJ Watson, non-linear optimization',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2006',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '6611',
    num_cols: '6611',
    nonzeros: '64333',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '6611',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 6611-by-1
',
    norm: '1.730872e+03',
    min_singular_value: '1.831194e-02',
    condition_number: '9.452146e+04',
    svd_rank: '6611',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'c-34.png,c-34_svd.png,c-34_graph.gif,',
}
