{
    matrix_id: '1554',
    name: 'c-35',
    group: 'Schenk_IBMNA',
    description: 'IBM TJ Watson, non-linear optimization',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2006',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '6537',
    num_cols: '6537',
    nonzeros: '62891',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '6537',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 6537-by-1
',
    norm: '1.864351e+04',
    min_singular_value: '5.589956e-03',
    condition_number: '3.335180e+06',
    svd_rank: '6537',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'c-35.png,c-35_svd.png,c-35_graph.gif,',
}
