{
    matrix_id: '1556',
    name: 'c-37',
    group: 'Schenk_IBMNA',
    description: 'IBM TJ Watson, non-linear optimization',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2006',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '8204',
    num_cols: '8204',
    nonzeros: '74676',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '8204',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 8204-by-1
',
    norm: '4.408957e+04',
    min_singular_value: '6.973787e-04',
    condition_number: '6.322185e+07',
    svd_rank: '8204',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'c-37.png,c-37_svd.png,c-37_graph.gif,',
}
