{
    matrix_id: '1557',
    name: 'c-38',
    group: 'Schenk_IBMNA',
    description: 'IBM TJ Watson, non-linear optimization',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2006',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '8127',
    num_cols: '8127',
    nonzeros: '77689',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '8127',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 8127-by-1
',
    norm: '6.083484e+02',
    min_singular_value: '3.974359e-02',
    condition_number: '1.530683e+04',
    svd_rank: '8127',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'c-38.png,c-38_svd.png,c-38_graph.gif,',
}
