{
    matrix_id: '1559',
    name: 'c-40',
    group: 'Schenk_IBMNA',
    description: 'IBM TJ Watson, non-linear optimization',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2006',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '9941',
    num_cols: '9941',
    nonzeros: '81501',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '9941',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 9941-by-1
',
    norm: '1.470326e+03',
    min_singular_value: '1.326762e-03',
    condition_number: '1.108206e+06',
    svd_rank: '9941',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'c-40.png,c-40_svd.png,c-40_graph.gif,',
}
