{
    matrix_id: '1560',
    name: 'c-41',
    group: 'Schenk_IBMNA',
    description: 'IBM TJ Watson, non-linear optimization',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2006',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '9769',
    num_cols: '9769',
    nonzeros: '101635',
    num_explicit_zeros: '110',
    num_strongly_connected_components: '8',
    num_dmperm_blocks: '8',
    structural_full_rank: 'true',
    structural_rank: '9769',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 9769-by-1
',
    norm: '4.778187e+04',
    min_singular_value: '1.000007e-08',
    condition_number: '4.778155e+12',
    svd_rank: '9705',
    sprank_minus_rank: '64',
    null_space_dimension: '64',
    full_numerical_rank: 'no',
    svd_gap: '2.553443',
    image_files: 'c-41.png,c-41_dmperm.png,c-41_svd.png,c-41_graph.gif,',
}
