{
    matrix_id: '1561',
    name: 'c-42',
    group: 'Schenk_IBMNA',
    description: 'IBM TJ Watson, non-linear optimization',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2006',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '10471',
    num_cols: '10471',
    nonzeros: '110285',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '10471',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 10471-by-1
',
    norm: '4.048522e+04',
    min_singular_value: '2.313975e-03',
    condition_number: '1.749596e+07',
    svd_rank: '10471',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'c-42.png,c-42_svd.png,c-42_graph.gif,',
}
