{
    matrix_id: '1563',
    name: 'c-44',
    group: 'Schenk_IBMNA',
    description: 'IBM TJ Watson, non-linear optimization',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2006',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '10728',
    num_cols: '10728',
    nonzeros: '85000',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '10728',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 10728-by-1
',
    norm: '3.732874e+04',
    min_singular_value: '6.134316e-04',
    condition_number: '6.085232e+07',
    svd_rank: '10728',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'c-44.png,c-44_svd.png,c-44_graph.gif,',
}
