{
    matrix_id: '1564',
    name: 'c-45',
    group: 'Schenk_IBMNA',
    description: 'IBM TJ Watson, non-linear optimization',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2006',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '13206',
    num_cols: '13206',
    nonzeros: '174452',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '13206',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 13206-by-1
',
    norm: '3.657727e+05',
    min_singular_value: '6.715344e-06',
    condition_number: '5.446820e+10',
    svd_rank: '13206',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'c-45.png,c-45_svd.png,c-45_graph.gif,',
}
