{
    matrix_id: '1567',
    name: 'c-48',
    group: 'Schenk_IBMNA',
    description: 'IBM TJ Watson, non-linear optimization',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2006',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '18354',
    num_cols: '18354',
    nonzeros: '166080',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '18354',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 18354-by-1
',
    norm: '4.733325e+05',
    min_singular_value: '3.969987e-04',
    condition_number: '1.192277e+09',
    svd_rank: '18354',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'c-48.png,c-48_svd.png,c-48_graph.gif,',
}
