{
    matrix_id: '1568',
    name: 'c-49',
    group: 'Schenk_IBMNA',
    description: 'IBM TJ Watson, non-linear optimization',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2006',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '21132',
    num_cols: '21132',
    nonzeros: '157040',
    num_explicit_zeros: '2',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '21132',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 21132-by-1
',
    norm: '1.531521e+05',
    min_singular_value: '2.541993e-04',
    condition_number: '6.024885e+08',
    svd_rank: '21132',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'c-49.png,c-49_dmperm.png,c-49_svd.png,c-49_graph.gif,',
}
