{
    matrix_id: '1569',
    name: 'c-50',
    group: 'Schenk_IBMNA',
    description: 'IBM TJ Watson, non-linear optimization',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2006',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '22401',
    num_cols: '22401',
    nonzeros: '180245',
    num_explicit_zeros: '13380',
    num_strongly_connected_components: '3',
    num_dmperm_blocks: '3',
    structural_full_rank: 'true',
    structural_rank: '22401',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 22401-by-1
',
    norm: '2.658597e+05',
    min_singular_value: '1.676394e-05',
    condition_number: '1.585902e+10',
    svd_rank: '22401',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'c-50.png,c-50_dmperm.png,c-50_svd.png,c-50_graph.gif,',
}
