{
    matrix_id: '1570',
    name: 'c-51',
    group: 'Schenk_IBMNA',
    description: 'IBM TJ Watson, non-linear optimization',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2006',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '23196',
    num_cols: '23196',
    nonzeros: '203048',
    num_explicit_zeros: '2',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '23196',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 23196-by-1
',
    norm: '5.303473e+03',
    min_singular_value: '1.373912e-03',
    condition_number: '3.860125e+06',
    svd_rank: '23196',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'c-51.png,c-51_dmperm.png,c-51_svd.png,c-51_graph.gif,',
}
