{
    matrix_id: '1575',
    name: 'c-57',
    group: 'Schenk_IBMNA',
    description: 'IBM TJ Watson, non-linear optimization',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2006',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '37833',
    num_cols: '37833',
    nonzeros: '403373',
    num_explicit_zeros: '1824',
    num_strongly_connected_components: '49',
    num_dmperm_blocks: '49',
    structural_full_rank: 'true',
    structural_rank: '37833',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 37833-by-1
',
    norm: '7.270099e+04',
    min_singular_value: '4.097991e-04',
    condition_number: '1.774064e+08',
    svd_rank: '37833',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'c-57.png,c-57_dmperm.png,c-57_svd.png,c-57_graph.gif,',
}
