{
    matrix_id: '1578',
    name: 'c-65',
    group: 'Schenk_IBMNA',
    description: 'IBM TJ Watson, non-linear optimization',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2006',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '48066',
    num_cols: '48066',
    nonzeros: '360428',
    num_explicit_zeros: '100',
    num_strongly_connected_components: '51',
    num_dmperm_blocks: '51',
    structural_full_rank: 'true',
    structural_rank: '48066',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 48066-by-1
',
    image_files: 'c-65.png,c-65_dmperm.png,c-65_graph.gif,',
}
