{
    matrix_id: '951',
    name: 'c-66',
    group: 'Schenk_IBMNA',
    description: 'Olaf Schenk, Univ. Basel: IBM TJ Watson, Yorktown, nonlinear optimization',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2003',
    kind: 'optimization problem sequence',
    problem_2D_or_3D: '0',
    num_rows: '49989',
    num_cols: '49989',
    nonzeros: '444853',
    num_explicit_zeros: '54154',
    num_strongly_connected_components: '6',
    num_dmperm_blocks: '6',
    structural_full_rank: 'true',
    structural_rank: '49989',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: Schenk_IBMNA/c-66b first: Schenk_IBMNA/c-66
',
    b_field: 'full 49989-by-1
',
    image_files: 'c-66.png,c-66_dmperm.png,c-66b.png,c-66b_dmperm.png,c-66_graph.gif,c-66b_graph.gif,',
}
