{
    matrix_id: '952',
    name: 'c-67',
    group: 'Schenk_IBMNA',
    description: 'Olaf Schenk, Univ. Basel: IBM TJ Watson, Yorktown, nonlinear optimization',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2003',
    kind: 'optimization problem sequence',
    problem_2D_or_3D: '0',
    num_rows: '57975',
    num_cols: '57975',
    nonzeros: '530229',
    num_explicit_zeros: '1706',
    num_strongly_connected_components: '342',
    num_dmperm_blocks: '342',
    structural_full_rank: 'true',
    structural_rank: '57975',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: Schenk_IBMNA/c-67b first: Schenk_IBMNA/c-67
',
    b_field: 'full 57975-by-1
',
    image_files: 'c-67.png,c-67_dmperm.png,c-67b.png,c-67b_dmperm.png,c-67_graph.gif,c-67b_graph.gif,',
}
