{
    matrix_id: '1579',
    name: 'c-big',
    group: 'Schenk_IBMNA',
    description: 'IBM TJ Watson, non-linear optimization',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2006',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '345241',
    num_cols: '345241',
    nonzeros: '2340859',
    num_explicit_zeros: '152',
    num_strongly_connected_components: '77',
    num_dmperm_blocks: '77',
    structural_full_rank: 'true',
    structural_rank: '345241',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 345241-by-1
',
    image_files: 'c-big.png,c-big_dmperm.png,c-big_graph.gif,',
}
