{
    matrix_id: '2246',
    name: 'fem_hifreq_circuit',
    group: 'Lee',
    description: 'FEM, Maxwell\'s eqns for hi-freq. circuit, C. for Electromag., UIUC',
    author: 'S.-H. Lee',
    editor: 'T. Davis',
    date: '2009',
    kind: 'electromagnetics problem',
    problem_2D_or_3D: '1',
    num_rows: '491100',
    num_cols: '491100',
    nonzeros: '20239237',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '491100',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.499',
    rb_type: 'complex',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    image_files: 'fem_hifreq_circuit.png,fem_hifreq_circuit_APlusAT_graph.gif,fem_hifreq_circuit_graph.gif,',
}
