{
    matrix_id: '1535',
    name: 'extr1b',
    group: 'Zitney',
    description: 'Chemical process separation sequence, S. Zitney, Cray Research',
    author: 'S. Zitney',
    editor: 'S. Hadfield, T. Davis',
    date: '1994',
    kind: 'chemical process simulation problem sequence',
    problem_2D_or_3D: '0',
    num_rows: '2836',
    num_cols: '2836',
    nonzeros: '10965',
    num_explicit_zeros: '439',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '869',
    structural_full_rank: 'true',
    structural_rank: '2836',
    pattern_symmetry: '0.004',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'aux.A{i}: ith matrix in sequence. aux.Zeros{i}: binary pattern of explicit
zero entries provided in original data.  aux.S = union of all patterns.   
',
    aux_fields: 'S: sparse 2836-by-2836
A: cell 44-by-1
Zeros: cell 44-by-1
',    norm: '7.412999e+05',
    min_singular_value: '2.197004e-07',
    condition_number: '3.374139e+12',
    svd_rank: '2835',
    sprank_minus_rank: '1',
    null_space_dimension: '1',
    full_numerical_rank: 'no',
    svd_gap: '2.726744',
    image_files: 'extr1b.png,extr1b_dmperm.png,extr1b_svd.png,extr1b_APlusAT_graph.gif,extr1b_graph.gif,',
}
