{
    matrix_id: '837',
    name: 'hydr1',
    group: 'Zitney',
    description: 'Chemical process separation, Steve Zitney, Cray Research',
    author: 'S. Zitney',
    editor: 'T. Davis',
    date: '1997',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '5308',
    num_cols: '5308',
    nonzeros: '22680',
    num_explicit_zeros: '1072',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1076',
    structural_full_rank: 'true',
    structural_rank: '5308',
    pattern_symmetry: '0.004',
    numeric_symmetry: '0.001',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.992168e+06',
    min_singular_value: '1.271726e-08',
    condition_number: '2.352841e+14',
    svd_rank: '5191',
    sprank_minus_rank: '117',
    null_space_dimension: '117',
    full_numerical_rank: 'no',
    svd_gap: '1.035763',
    image_files: 'hydr1.png,hydr1_dmperm.png,hydr1_svd.png,hydr1c.png,hydr1c_dmperm.png,hydr1c_svd.png,hydr1_APlusAT_graph.gif,hydr1_graph.gif,hydr1c_APlusAT_graph.gif,hydr1c_graph.gif,',
}
