{
    matrix_id: '841',
    name: 'rdist3a',
    group: 'Zitney',
    description: 'Chemical process separation, Steve Zitney, Cray Research',
    author: 'S. Zitney',
    editor: 'T. Davis',
    date: '1992',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '2398',
    num_cols: '2398',
    nonzeros: '61896',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '99',
    structural_full_rank: 'true',
    structural_rank: '2398',
    pattern_symmetry: '0.140',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.144227e+03',
    min_singular_value: '7.099231e-05',
    condition_number: '1.611762e+07',
    svd_rank: '2398',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'rdist3a.png,rdist3a_dmperm.png,rdist3a_scc.png,rdist3a_svd.png,rdist3a_APlusAT_graph.gif,rdist3a_graph.gif,',
}
