{
    matrix_id: '839',
    name: 'rdist1',
    group: 'Zitney',
    description: 'Chemical process separation, Steve Zitney, Cray Research',
    author: 'S. Zitney',
    editor: 'T. Davis',
    date: '1992',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '4134',
    num_cols: '4134',
    nonzeros: '94408',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '199',
    structural_full_rank: 'true',
    structural_rank: '4134',
    pattern_symmetry: '0.059',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.535265e+03',
    min_singular_value: '8.845432e-05',
    condition_number: '1.735659e+07',
    svd_rank: '4134',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'rdist1.png,rdist1_dmperm.png,rdist1_scc.png,rdist1_svd.png,rdist1_APlusAT_graph.gif,rdist1_graph.gif,',
}
