{
    matrix_id: '1890',
    name: 'Maragal_7',
    group: 'NYPA',
    description: 'Rank deficient least squares problem, D. Maragal, NY Power Authority',
    author: 'D. Maragal',
    editor: 'T. Davis',
    date: '2008',
    kind: 'least squares problem',
    problem_2D_or_3D: '0',
    num_rows: '46845',
    num_cols: '26564',
    nonzeros: '1200537',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '41',
    num_dmperm_blocks: '1294',
    structural_full_rank: 'false',
    structural_rank: '25866',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'rank deficient (rank(A) < sprank(A) < size(A,2))
sprank: 25866 columns: 26564                    
',
    b_field: 'full 46845-by-1
',
    norm: '1.332835e+01',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '20843',
    sprank_minus_rank: '5023',
    null_space_dimension: '5721',
    full_numerical_rank: 'no',
    svd_gap: '112840544.190394',
    image_files: 'Maragal_7.png,Maragal_7_dmperm.png,Maragal_7_scc.png,Maragal_7_svd.png,Maragal_7_graph.gif,',
}
