{
    matrix_id: '1884',
    name: 'Maragal_1',
    group: 'NYPA',
    description: 'Rank deficient least squares problem, D. Maragal, NY Power Authority',
    author: 'D. Maragal',
    editor: 'T. Davis',
    date: '2008',
    kind: 'least squares problem',
    problem_2D_or_3D: '0',
    num_rows: '32',
    num_cols: '14',
    nonzeros: '234',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '14',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'rank deficient (rank(A) < sprank(A) == size(A,2))
rank: 10 sprank: 14 columns: 14                  
',
    b_field: 'full 32-by-1
',
    norm: '5.932732e+00',
    min_singular_value: '1.279533e-16',
    condition_number: '46366380528885720',
    svd_rank: '10',
    sprank_minus_rank: '4',
    null_space_dimension: '4',
    full_numerical_rank: 'no',
    svd_gap: '1460882612086555.500000',
    image_files: 'Maragal_1.png,Maragal_1_svd.png,Maragal_1_graph.gif,',
}
