{
    matrix_id: '2217',
    name: 'Maragal_8',
    group: 'NYPA',
    description: 'Rank deficient problem, D. Maragal, NY Power Authority',
    author: 'D. Maragal',
    editor: 'T. Davis',
    date: '2008',
    kind: 'least squares problem',
    problem_2D_or_3D: '0',
    num_rows: '33212',
    num_cols: '75077',
    nonzeros: '1308415',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '14353',
    num_dmperm_blocks: '1799',
    structural_full_rank: 'false',
    structural_rank: '18456',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 33212-by-1
',
    norm: '1.259312e+01',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '15343',
    sprank_minus_rank: '3113',
    null_space_dimension: '17869',
    full_numerical_rank: 'no',
    svd_gap: '695700.873404',
    image_files: 'Maragal_8.png,Maragal_8_dmperm.png,Maragal_8_scc.png,Maragal_8_svd.png,Maragal_8_graph.gif,',
}
