{
    matrix_id: '2826',
    name: 'Goodwin_127',
    group: 'Goodwin',
    description: 'Finite element, Navier-Stokes & other transport eqns',
    author: 'R. Goodwin',
    editor: 'T. Davis',
    date: '2018',
    kind: 'computational fluid dynamics',
    problem_2D_or_3D: '1',
    num_rows: '178437',
    num_cols: '178437',
    nonzeros: '5778545',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2034',
    num_dmperm_blocks: '2034',
    structural_full_rank: 'true',
    structural_rank: '178437',
    pattern_symmetry: '0.990',
    numeric_symmetry: '0.066',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Finite element discretization of the Navier-Stokes and similar
transport equations on various geometries from Ralph Goodwin. 
',
    image_files: 'Goodwin_127.png,Goodwin_127_dmperm.png,Goodwin_127_scc.png,',
}
