{
    matrix_id: '2818',
    name: 'Goodwin_013',
    group: 'Goodwin',
    description: 'Finite element, Navier-Stokes & other transport eqns',
    author: 'R. Goodwin',
    editor: 'T. Davis',
    date: '2018',
    kind: 'computational fluid dynamics',
    problem_2D_or_3D: '1',
    num_rows: '1965',
    num_cols: '1965',
    nonzeros: '56069',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '210',
    num_dmperm_blocks: '210',
    structural_full_rank: 'true',
    structural_rank: '1965',
    pattern_symmetry: '0.925',
    numeric_symmetry: '0.058',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Finite element discretization of the Navier-Stokes and similar
transport equations on various geometries from Ralph Goodwin. 
',
    image_files: 'Goodwin_013.png,Goodwin_013_dmperm.png,Goodwin_013_scc.png,',
}
