{
    matrix_id: '2820',
    name: 'Goodwin_023',
    group: 'Goodwin',
    description: 'Finite element, Navier-Stokes & other transport eqns',
    author: 'R. Goodwin',
    editor: 'T. Davis',
    date: '2018',
    kind: 'computational fluid dynamics',
    problem_2D_or_3D: '1',
    num_rows: '6005',
    num_cols: '6005',
    nonzeros: '182168',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '370',
    num_dmperm_blocks: '370',
    structural_full_rank: 'true',
    structural_rank: '6005',
    pattern_symmetry: '0.957',
    numeric_symmetry: '0.062',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Finite element discretization of the Navier-Stokes and similar
transport equations on various geometries from Ralph Goodwin. 
',
    image_files: 'Goodwin_023.png,Goodwin_023_dmperm.png,Goodwin_023_scc.png,',
}
