{
    matrix_id: '2821',
    name: 'Goodwin_030',
    group: 'Goodwin',
    description: 'Finite element, Navier-Stokes & other transport eqns',
    author: 'R. Goodwin',
    editor: 'T. Davis',
    date: '2018',
    kind: 'computational fluid dynamics',
    problem_2D_or_3D: '1',
    num_rows: '10142',
    num_cols: '10142',
    nonzeros: '312814',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '482',
    num_dmperm_blocks: '482',
    structural_full_rank: 'true',
    structural_rank: '10142',
    pattern_symmetry: '0.966',
    numeric_symmetry: '0.063',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Finite element discretization of the Navier-Stokes and similar
transport equations on various geometries from Ralph Goodwin. 
',
    image_files: 'Goodwin_030.png,Goodwin_030_dmperm.png,Goodwin_030_scc.png,',
}
