{
    matrix_id: '2819',
    name: 'Goodwin_017',
    group: 'Goodwin',
    description: 'Finite element, Navier-Stokes & other transport eqns',
    author: 'R. Goodwin',
    editor: 'T. Davis',
    date: '2018',
    kind: 'computational fluid dynamics',
    problem_2D_or_3D: '1',
    num_rows: '3317',
    num_cols: '3317',
    nonzeros: '97773',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '274',
    num_dmperm_blocks: '274',
    structural_full_rank: 'true',
    structural_rank: '3317',
    pattern_symmetry: '0.942',
    numeric_symmetry: '0.060',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Finite element discretization of the Navier-Stokes and similar
transport equations on various geometries from Ralph Goodwin. 
',
    image_files: 'Goodwin_017.png,Goodwin_017_dmperm.png,Goodwin_017_scc.png,',
}
