{
    matrix_id: '447',
    name: 'rim',
    group: 'Goodwin',
    description: 'FEM, fluid mechanics problem.  From Ralph Goodwin, Univ. Illinois',
    author: 'R. Goodwin',
    editor: 'T. Davis',
    date: '1995',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '22560',
    num_cols: '22560',
    nonzeros: '1014951',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '22560',
    pattern_symmetry: '0.639',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '8.234632e+04',
    min_singular_value: '9.291773e-18',
    condition_number: '8.862282e+21',
    svd_rank: '22479',
    sprank_minus_rank: '81',
    null_space_dimension: '81',
    full_numerical_rank: 'no',
    svd_gap: '1.006677',
    image_files: 'rim.png,rim_dmperm.png,rim_scc.png,rim_svd.png,rim_APlusAT_graph.gif,rim_graph.gif,',
}
