{
    matrix_id: '982',
    name: 'language',
    group: 'Tromble',
    description: 'Roy Tromble. finite-state machine for natural language processing',
    author: 'R. Tromble',
    editor: 'T. Davis',
    date: '2003',
    kind: 'directed weighted graph',
    problem_2D_or_3D: '0',
    num_rows: '399130',
    num_cols: '399130',
    nonzeros: '1216334',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2456',
    pattern_symmetry: '0.058',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    image_files: 'language.png,language_dmperm.png,language_APlusAT_graph.gif,language_graph.gif,',
}
