{
    matrix_id: '917',
    name: 'fd12',
    group: 'Hohn',
    description: 'M. Hohn, Univ Utah. Single-material crack problem, finite diff log grid',
    author: 'M. Hohn',
    editor: 'T. Davis',
    date: '2003',
    kind: 'materials problem',
    problem_2D_or_3D: '1',
    num_rows: '7500',
    num_cols: '7500',
    nonzeros: '28462',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '713',
    structural_full_rank: 'true',
    structural_rank: '7500',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 7500-by-1
',
    norm: '1.028106e+08',
    min_singular_value: '6.514364e-03',
    condition_number: '1.578214e+10',
    svd_rank: '7500',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
