{
    matrix_id: '918',
    name: 'fd15',
    group: 'Hohn',
    description: 'M. Hohn, Univ Utah. Single-material crack problem, finite diff log grid',
    author: 'M. Hohn',
    editor: 'T. Davis',
    date: '2003',
    kind: 'materials problem',
    problem_2D_or_3D: '1',
    num_rows: '11532',
    num_cols: '11532',
    nonzeros: '44206',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '887',
    structural_full_rank: 'true',
    structural_rank: '11532',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 11532-by-1
',
    norm: '1.937926e+08',
    min_singular_value: '3.951963e-03',
    condition_number: '4.903705e+10',
    svd_rank: '11532',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
