{
    matrix_id: '922',
    name: 'sinc18',
    group: 'Hohn',
    description: 'M. Hohn, Univ Utah. Single-material crack problem, sinc basis  log grid',
    author: 'M. Hohn',
    editor: 'T. Davis',
    date: '2003',
    kind: 'materials problem',
    problem_2D_or_3D: '1',
    num_rows: '16428',
    num_cols: '16428',
    nonzeros: '948696',
    num_explicit_zeros: '25130',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '779',
    structural_full_rank: 'true',
    structural_rank: '16428',
    pattern_symmetry: '0.012',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 16428-by-1
',
    norm: '4.207672e+08',
    min_singular_value: '3.199549e-03',
    condition_number: '1.315083e+11',
    svd_rank: '16428',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
