{
    matrix_id: '1319',
    name: 'airfoil_2d',
    group: 'Engwirda',
    description: 'Unstructured 2D mesh (airfoil), from Darren Engwirda',
    author: 'D. Engwirda',
    editor: 'T. Davis',
    date: '2006',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '14214',
    num_cols: '14214',
    nonzeros: '259688',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '638',
    num_dmperm_blocks: '638',
    structural_full_rank: 'true',
    structural_rank: '14214',
    pattern_symmetry: '0.982',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'trimesh(t,coord(:,1),coord(:,2),A\ones(n,1))
',
    aux_fields: 'coord: full 14214-by-2
t: full 27748-by-3
',    norm: '2.526725e+05',
    min_singular_value: '1.414135e-01',
    condition_number: '1.786763e+06',
    svd_rank: '14214',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'airfoil_2d.png,airfoil_2d_dmperm.png,airfoil_2d_gplot.png,airfoil_2d_svd.png,airfoil_2d_APlusAT_graph.gif,airfoil_2d_graph.gif,',
}
