{
    matrix_id: '1510',
    name: 'NotreDame_www',
    group: 'Barabasi',
    description: 'CCNR network: Barabasi\'s web page network of nd.edu',
    author: 'R. Albert, H. Jeong, A. Barabasi',
    editor: 'H. Jeong',
    date: '1999',
    kind: 'directed graph',
    problem_2D_or_3D: '0',
    num_rows: '325729',
    num_cols: '325729',
    nonzeros: '929849',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '231666',
    pattern_symmetry: '0.332',
    numeric_symmetry: '0.332',
    rb_type: 'binary',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'http://www.nd.edu/~networks
',
}
