{
    matrix_id: '1511',
    name: 'NotreDame_yeast',
    group: 'Barabasi',
    description: 'CCNR network: Barabasi\'s yeast protein interaction',
    author: 'H. Jeong, S. Mason, A. Barabasi, Z. Oltvai',
    editor: 'H. Jeong',
    date: '2001',
    kind: 'undirected graph',
    problem_2D_or_3D: '0',
    num_rows: '2114',
    num_cols: '2114',
    nonzeros: '4480',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '417',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'http://www.nd.edu/~networks
',
    norm: '7.541239e+00',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '1263',
    null_space_dimension: '851',
    full_numerical_rank: 'no',
    svd_gap: '8458668389663.914062',
}
