{
    matrix_id: '919',
    name: 'fd18',
    group: 'Hohn',
    description: 'M. Hohn, Univ Utah. Single-material crack problem, finite diff log grid',
    author: 'M. Hohn',
    editor: 'T. Davis',
    date: '2003',
    kind: 'materials problem',
    problem_2D_or_3D: '1',
    num_rows: '16428',
    num_cols: '16428',
    nonzeros: '63406',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1061',
    structural_full_rank: 'true',
    structural_rank: '16428',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 16428-by-1
',
    norm: '5.441578e+08',
    min_singular_value: '8.368918e-03',
    condition_number: '6.502129e+10',
    svd_rank: '16428',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'fd18.png,fd18_dmperm.png,fd18_svd.png,fd18_APlusAT_graph.gif,fd18_graph.gif,',
}
