{
    matrix_id: '921',
    name: 'sinc15',
    group: 'Hohn',
    description: 'M. Hohn, Univ Utah. Single-material crack problem, sinc basis  log grid',
    author: 'M. Hohn',
    editor: 'T. Davis',
    date: '2003',
    kind: 'materials problem',
    problem_2D_or_3D: '1',
    num_rows: '11532',
    num_cols: '11532',
    nonzeros: '551184',
    num_explicit_zeros: '17342',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '653',
    structural_full_rank: 'true',
    structural_rank: '11532',
    pattern_symmetry: '0.014',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 11532-by-1
',
    norm: '1.534728e+08',
    min_singular_value: '2.019702e-03',
    condition_number: '7.598786e+10',
    svd_rank: '11532',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'sinc15.png,sinc15_dmperm.png,sinc15_svd.png,sinc15_APlusAT_graph.gif,sinc15_graph.gif,',
}
