{
    matrix_id: '903',
    name: 'landmark',
    group: 'Pereyra',
    description: 'Matrix from Victor Pereyra, Stanford University',
    author: 'V. Pereyra',
    editor: 'T. Davis',
    date: '2003',
    kind: 'least squares problem',
    problem_2D_or_3D: '0',
    num_rows: '71952',
    num_cols: '2704',
    nonzeros: '1146848',
    num_explicit_zeros: '4384',
    num_strongly_connected_components: '32',
    num_dmperm_blocks: '5',
    structural_full_rank: 'false',
    structural_rank: '2673',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '5.686476e+00',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '2671',
    sprank_minus_rank: '2',
    null_space_dimension: '33',
    full_numerical_rank: 'no',
    svd_gap: '1634.091252',
    image_files: 'landmark.png,landmark_dmperm.png,landmark_scc.png,landmark_svd.png,landmark_graph.gif,',
}
