{
    matrix_id: '1423',
    name: 'apache2',
    group: 'GHS_psdef',
    description: 'SPD matrix (finite difference 3D) from APACHE small',
    author: '',
    editor: 'N. Gould, Y. Hu, J. Scott',
    date: '2006',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '715176',
    num_cols: '715176',
    nonzeros: '4817870',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '715176',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
}
