{
    matrix_id: '1253',
    name: 'bmw7st_1',
    group: 'GHS_psdef',
    description: 'stiffness matrix',
    author: 'S. Mayer',
    editor: 'J. Koster',
    date: '2004',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '141347',
    num_cols: '141347',
    nonzeros: '7318399',
    num_explicit_zeros: '21268',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '141347',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
}
