{
    matrix_id: '1254',
    name: 'bmwcra_1',
    group: 'GHS_psdef',
    description: 'stiffness matrix',
    author: 'S. Mayer',
    editor: 'J. Koster',
    date: '2004',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '148770',
    num_cols: '148770',
    nonzeros: '10641602',
    num_explicit_zeros: '2400',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '148770',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
}
