{
    matrix_id: '1255',
    name: 'copter1',
    group: 'GHS_psdef',
    description: 'Gould, Hu, & Scott: Helicoptor rotor blade, from Pothen & Kumfert',
    author: 'G. Kumfert, A. Pothen',
    editor: 'N. Gould, Y. Hu, J. Scott',
    date: '2004',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '17222',
    num_cols: '17222',
    nonzeros: '211064',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '17222',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '1.525993e+01',
    min_singular_value: '1.583946e-03',
    condition_number: '9.634119e+03',
    svd_rank: '17222',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
