{
    matrix_id: '1258',
    name: 'crankseg_2',
    group: 'GHS_psdef',
    description: 'OUTPUT4-Matrix',
    author: 'S. Mayer',
    editor: 'J. Koster',
    date: '2004',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '63838',
    num_cols: '63838',
    nonzeros: '14148858',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '63838',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
}
