{
    matrix_id: '1263',
    name: 'ford2',
    group: 'GHS_psdef',
    description: 'Gould, Hu, & Scott: car surface mesh, from Pothen & Kumfert',
    author: 'G. Kumfert, A. Pothen',
    editor: 'N. Gould, Y. Hu, J. Scott',
    date: '2004',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '100196',
    num_cols: '100196',
    nonzeros: '544688',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '100196',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
}
