{
    matrix_id: '1266',
    name: 'hood',
    group: 'GHS_psdef',
    description: ' INDEED Test Matrix (DC-mh)',
    author: 'J. Weiher',
    editor: 'J. Koster',
    date: '2004',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '220542',
    num_cols: '220542',
    nonzeros: '9895422',
    num_explicit_zeros: '873014',
    num_strongly_connected_components: '9908',
    num_dmperm_blocks: '9908',
    structural_full_rank: 'true',
    structural_rank: '220542',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
}
