{
    matrix_id: '1312',
    name: 'jnlbrng1',
    group: 'GHS_psdef',
    description: 'Gould, Hu, & Scott: quadratic journal bearing problem (CUTEr)',
    author: 'J. More\', G. Toraldo',
    editor: 'N. Gould, Y. Hu, J. Scott',
    date: '1991',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '40000',
    num_cols: '40000',
    nonzeros: '199200',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '40000',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '1.842729e+01',
    min_singular_value: '1.005710e-01',
    condition_number: '1.832266e+02',
    svd_rank: '40000',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
