{
    matrix_id: '1268',
    name: 'ldoor',
    group: 'GHS_psdef',
    description: ' INDEED Test Matrix',
    author: 'J. Weiher',
    editor: 'J. Koster',
    date: '2004',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '952203',
    num_cols: '952203',
    nonzeros: '42493817',
    num_explicit_zeros: '4028658',
    num_strongly_connected_components: '42667',
    num_dmperm_blocks: '42667',
    structural_full_rank: 'true',
    structural_rank: '952203',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
}
