{
    matrix_id: '1270',
    name: 'oilpan',
    group: 'GHS_psdef',
    description: ' 1. TEST MATRIX FROM INPRO FOR PARASOL (OIL-PAN)',
    author: 'J. Weiher',
    editor: 'J. Koster',
    date: '2004',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '73752',
    num_cols: '73752',
    nonzeros: '2148558',
    num_explicit_zeros: '1448630',
    num_strongly_connected_components: '17459',
    num_dmperm_blocks: '17459',
    structural_full_rank: 'true',
    structural_rank: '73752',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
}
