{
    matrix_id: '732',
    name: 'li',
    group: 'Li',
    description: '3D Finite element matrix, magnetohydrodynamic problem with 5 variables',
    author: 'B. Li',
    editor: 'T. Davis',
    date: '1999',
    kind: 'electromagnetics problem',
    problem_2D_or_3D: '1',
    num_rows: '22695',
    num_cols: '22695',
    nonzeros: '1215181',
    num_explicit_zeros: '135128',
    num_strongly_connected_components: '4',
    num_dmperm_blocks: '4',
    structural_full_rank: 'true',
    structural_rank: '22695',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.869',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '4.359842e+08',
    min_singular_value: '3.570947e-06',
    condition_number: '1.220920e+14',
    svd_rank: '22640',
    sprank_minus_rank: '55',
    null_space_dimension: '55',
    full_numerical_rank: 'no',
    svd_gap: '1.026094',
}
