{
    matrix_id: '733',
    name: 'pli',
    group: 'Li',
    description: '3D Finite element matrix, magnetohydrodynamic problem with 5 variables',
    author: 'B. Li',
    editor: 'T. Davis',
    date: '1999',
    kind: 'duplicate electromagnetics problem',
    problem_2D_or_3D: '1',
    num_rows: '22695',
    num_cols: '22695',
    nonzeros: '1350309',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '22695',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    notes: 'nonzero pattern of Li/li
',
    norm: '8.373889e+01',
    min_singular_value: '1.868052e-21',
    condition_number: '4.482685e+22',
    svd_rank: '22131',
    sprank_minus_rank: '564',
    null_space_dimension: '564',
    full_numerical_rank: 'no',
    svd_gap: '195.457158',
}
