{
    matrix_id: '824',
    name: 'utm300',
    group: 'TOKAMAK',
    description: ' Uedge Test Matrix',
    author: 'Y. Saad',
    editor: 'Y. Saad',
    date: '1996',
    kind: 'electromagnetics problem',
    problem_2D_or_3D: '1',
    num_rows: '300',
    num_cols: '300',
    nonzeros: '3155',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '31',
    num_dmperm_blocks: '31',
    structural_full_rank: 'true',
    structural_rank: '300',
    pattern_symmetry: '0.465',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 300-by-1
',
    norm: '2.349383e+00',
    min_singular_value: '2.774938e-06',
    condition_number: '8.466435e+05',
    svd_rank: '300',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'utm300.png,utm300_dmperm.png,utm300_svd.png,utm300_APlusAT_graph.gif,utm300_graph.gif,',
}
