{
    matrix_id: '2657',
    name: 'LeGresley_87936',
    group: 'LeGresley',
    description: 'Power flow analysis of an electrical grid',
    author: 'P. LeGresley',
    editor: 'T. Davis',
    date: '2013',
    kind: 'power network problem',
    problem_2D_or_3D: '0',
    num_rows: '87936',
    num_cols: '87936',
    nonzeros: '593276',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2114',
    num_dmperm_blocks: '3024',
    structural_full_rank: 'true',
    structural_rank: '87936',
    pattern_symmetry: '0.979',
    numeric_symmetry: '0.034',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Power flow analyses of electrical grids.           
Submitted by Patrick LeGresley, Stanford, July 2013
',
    b_field: 'full 87936-by-1
',
    image_files: 'LeGresley_87936.png,LeGresley_87936_dmperm.png,LeGresley_87936_scc.png,LeGresley_87936_APlusAT_graph.gif,LeGresley_87936_graph.gif,',
}
