{
    matrix_id: '847',
    name: 'pkustk01',
    group: 'Chen',
    description: 'PKU SYMMETRIC STIFFNESS, BEIJING BOTANIC EXHIBITION HALL',
    author: 'P. Chen',
    editor: 'T. Davis',
    date: '2002',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '22044',
    num_cols: '22044',
    nonzeros: '979380',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '22044',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '6.427871e+01',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '3732',
    sprank_minus_rank: '18312',
    null_space_dimension: '18312',
    full_numerical_rank: 'no',
    svd_gap: '4948070258.067274',
    image_files: 'pkustk01.png,pkustk01_svd.png,pkustk01_graph.gif,',
}
