{
    matrix_id: '849',
    name: 'pkustk03',
    group: 'Chen',
    description: 'PKU SYMMETRIC STIFFNESS, SILOS IN WAREHOUSE',
    author: 'P. Chen',
    editor: 'T. Davis',
    date: '2002',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '63336',
    num_cols: '63336',
    nonzeros: '3130416',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '63336',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    image_files: 'pkustk03.png,pkustk03_graph.gif,',
}
