{
    matrix_id: '850',
    name: 'pkustk04',
    group: 'Chen',
    description: 'PKU SYMMETRIC STIFFNESS, YUNSHAN PLAZA, DALIAN, CHINA',
    author: 'P. Chen',
    editor: 'T. Davis',
    date: '2002',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '55590',
    num_cols: '55590',
    nonzeros: '4218660',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '55590',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    image_files: 'pkustk04.png,pkustk04_graph.gif,',
}
