{
    matrix_id: '858',
    name: 'pkustk12',
    group: 'Chen',
    description: 'PKU SYMMETRIC STIFFNESS, JIJIAN PLAZA, CHINA',
    author: 'P. Chen',
    editor: 'T. Davis',
    date: '2002',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '94653',
    num_cols: '94653',
    nonzeros: '7512317',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '94653',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    image_files: 'pkustk12.png,pkustk12_graph.gif,',
}
