{
    matrix_id: '859',
    name: 'pkustk13',
    group: 'Chen',
    description: 'PKY SYMMETRIC STIFFNESS, MACHINE ELEMENT',
    author: 'P. Chen',
    editor: 'T. Davis',
    date: '2002',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '94893',
    num_cols: '94893',
    nonzeros: '6616827',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '94893',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    image_files: 'pkustk13.png,pkustk13_graph.gif,',
}
