{
    matrix_id: '848',
    name: 'pkustk02',
    group: 'Chen',
    description: 'PKU SYMMETRIC STIFFNESS, FEIYUE BUILDING',
    author: 'P. Chen',
    editor: 'T. Davis',
    date: '2002',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '10800',
    num_cols: '10800',
    nonzeros: '810000',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '10800',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '1.052388e+02',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '1224',
    sprank_minus_rank: '9576',
    null_space_dimension: '9576',
    full_numerical_rank: 'no',
    svd_gap: '1264248752.679350',
    image_files: 'pkustk02.png,pkustk02_svd.png,pkustk02_graph.gif,',
}
