{
    matrix_id: '889',
    name: 'fv3',
    group: 'Norris',
    description: 'S.Norris, Univ. Auckland. FEM, Laplace eqn 2D 101x101 mesh',
    author: 'S. Norris',
    editor: 'T. Davis',
    date: '2003',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '9801',
    num_cols: '9801',
    nonzeros: '87025',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '9801',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '4.000000e+00',
    min_singular_value: '1.973515e-03',
    condition_number: '2.026840e+03',
    svd_rank: '9801',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'fv3.png,fv3_svd.png,fv3_graph.gif,',
}
