{
    matrix_id: '891',
    name: 'heart2',
    group: 'Norris',
    description: 'S.Norris, Univ. Auckland. Quasi-static FEM of a heart',
    author: 'S. Norris',
    editor: 'T. Davis',
    date: '2003',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '2339',
    num_cols: '2339',
    nonzeros: '680341',
    num_explicit_zeros: '2456',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '2339',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '4.759540e+05',
    min_singular_value: '2.274836e-01',
    condition_number: '2.092257e+06',
    svd_rank: '2339',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'heart2.png,heart2_svd.png,heart2_graph.gif,',
}
