{
    matrix_id: '895',
    name: 'stomach',
    group: 'Norris',
    description: 'S.Norris, Univ. Auckland. 3D electro-physical model of a duodenum',
    author: 'S. Norris',
    editor: 'T. Davis',
    date: '2003',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '213360',
    num_cols: '213360',
    nonzeros: '3021648',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '213360',
    pattern_symmetry: '0.847',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    image_files: 'stomach.png,stomach_APlusAT_graph.gif,stomach_graph.gif,',
}
