{
    matrix_id: '1597',
    name: 'conf6_0-4x4-30',
    group: 'QCD',
    description: 'Quantum chromodynamics conf6.0-00l4x4-3000',
    author: 'B. Medeke',
    editor: 'R. Boisvert, R. Pozo, K. Remington, B. Miller, R. Lipman, R. Barrett, J. Dongarra',
    date: '1999',
    kind: 'theoretical/quantum chemistry problem',
    problem_2D_or_3D: '0',
    num_rows: '3072',
    num_cols: '3072',
    nonzeros: '119808',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '3072',
    pattern_symmetry: '0.923',
    numeric_symmetry: '0.462',
    rb_type: 'complex',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '7.114280e+00',
    min_singular_value: '4.150425e-01',
    condition_number: '1.714109e+01',
    svd_rank: '3072',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
