{
    matrix_id: '2215',
    name: 'mono_500Hz',
    group: 'FreeFieldTechnologies',
    description: '3D vibro-acoustic problem, aircraft engine nacelle. M. Gontier',
    author: 'M. Gontier',
    editor: 'T. Davis',
    date: '2008',
    kind: 'acoustics problem',
    problem_2D_or_3D: '1',
    num_rows: '169410',
    num_cols: '169410',
    nonzeros: '5033796',
    num_explicit_zeros: '2492',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '169410',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.821',
    rb_type: 'complex',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Free Field Technologies, Mont-Saint Guibert, Belguim (http://www.fft.be)
',
}
