{
    matrix_id: '2823',
    name: 'Goodwin_054',
    group: 'Goodwin',
    description: 'Finite element, Navier-Stokes & other transport eqns',
    author: 'R. Goodwin',
    editor: 'T. Davis',
    date: '2018',
    kind: 'computational fluid dynamics',
    problem_2D_or_3D: '1',
    num_rows: '32510',
    num_cols: '32510',
    nonzeros: '1030878',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '866',
    num_dmperm_blocks: '866',
    structural_full_rank: 'true',
    structural_rank: '32510',
    pattern_symmetry: '0.980',
    numeric_symmetry: '0.065',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Finite element discretization of the Navier-Stokes and similar
transport equations on various geometries from Ralph Goodwin. 
',
    image_files: 'Goodwin_054.png,Goodwin_054_dmperm.png,Goodwin_054_scc.png,',
}
