{
    matrix_id: '2824',
    name: 'Goodwin_071',
    group: 'Goodwin',
    description: 'Finite element, Navier-Stokes & other transport eqns',
    author: 'R. Goodwin',
    editor: 'T. Davis',
    date: '2018',
    kind: 'computational fluid dynamics',
    problem_2D_or_3D: '1',
    num_rows: '56021',
    num_cols: '56021',
    nonzeros: '1797934',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1138',
    num_dmperm_blocks: '1138',
    structural_full_rank: 'true',
    structural_rank: '56021',
    pattern_symmetry: '0.985',
    numeric_symmetry: '0.066',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Finite element discretization of the Navier-Stokes and similar
transport equations on various geometries from Ralph Goodwin. 
',
    image_files: 'Goodwin_071.png,Goodwin_071_dmperm.png,Goodwin_071_scc.png,',
}
