{
    matrix_id: '446',
    name: 'goodwin',
    group: 'Goodwin',
    description: 'FEM, fluid mechanics problem.  From Ralph Goodwin, Univ. Illinois',
    author: 'R. Goodwin',
    editor: 'T. Davis',
    date: '1995',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '7320',
    num_cols: '7320',
    nonzeros: '324772',
    num_explicit_zeros: '12',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '7320',
    pattern_symmetry: '0.635',
    numeric_symmetry: '0.001',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.337086e+04',
    min_singular_value: '1.194281e-06',
    condition_number: '1.956898e+10',
    svd_rank: '7320',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
