{
    matrix_id: '2825',
    name: 'Goodwin_095',
    group: 'Goodwin',
    description: 'Finite element, Navier-Stokes & other transport eqns',
    author: 'R. Goodwin',
    editor: 'T. Davis',
    date: '2018',
    kind: 'computational fluid dynamics',
    problem_2D_or_3D: '1',
    num_rows: '100037',
    num_cols: '100037',
    nonzeros: '3226066',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1522',
    num_dmperm_blocks: '1522',
    structural_full_rank: 'true',
    structural_rank: '100037',
    pattern_symmetry: '0.988',
    numeric_symmetry: '0.064',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Finite element discretization of the Navier-Stokes and similar
transport equations on various geometries from Ralph Goodwin. 
',
    image_files: 'Goodwin_095.png,Goodwin_095_dmperm.png,Goodwin_095_scc.png,',
}
