{
    matrix_id: '2822',
    name: 'Goodwin_040',
    group: 'Goodwin',
    description: 'Finite element, Navier-Stokes & other transport eqns',
    author: 'R. Goodwin',
    editor: 'T. Davis',
    date: '2018',
    kind: 'computational fluid dynamics',
    problem_2D_or_3D: '1',
    num_rows: '17922',
    num_cols: '17922',
    nonzeros: '561677',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '642',
    num_dmperm_blocks: '642',
    structural_full_rank: 'true',
    structural_rank: '17922',
    pattern_symmetry: '0.975',
    numeric_symmetry: '0.064',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Finite element discretization of the Navier-Stokes and similar
transport equations on various geometries from Ralph Goodwin. 
',
    image_files: 'Goodwin_040.png,Goodwin_040_dmperm.png,Goodwin_040_scc.png,',
}
