{
    matrix_id: '2',
    name: '494_bus',
    group: 'HB',
    description: 'S ADMITTANCE MATRIX  494 BUS POWER SYSTEM, D.J.TYLAVSKY, JULY 1985.',
    author: 'D. Tylavsky',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1985',
    kind: 'power network problem',
    problem_2D_or_3D: '0',
    num_rows: '494',
    num_cols: '494',
    nonzeros: '1666',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '494',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '3.000514e+04',
    min_singular_value: '1.242238e-02',
    condition_number: '2.415411e+06',
    svd_rank: '494',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: '494_bus.png,494_bus_svd.png,494_bus_graph.gif,',
}
