{
    matrix_id: '4',
    name: '685_bus',
    group: 'HB',
    description: 'S ADMITTANCE MATRIX  685 BUS POWER SYSTEM, D.J.TYLAVSKY, JULY 1985.',
    author: 'D. Tylavsky',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1985',
    kind: 'power network problem',
    problem_2D_or_3D: '0',
    num_rows: '685',
    num_cols: '685',
    nonzeros: '3249',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '685',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '2.618649e+04',
    min_singular_value: '6.188821e-02',
    condition_number: '4.231256e+05',
    svd_rank: '685',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: '685_bus.png,685_bus_svd.png,685_bus_graph.gif,',
}
