{
    matrix_id: '6',
    name: 'arc130',
    group: 'HB',
    description: 'UNSYMMETRIC MATRIX FROM LASER PROBLEM. A.R.CURTIS, OCT 1974',
    author: 'A. Curtis',
    editor: 'A. Curtis, I. Duff, J. Reid',
    date: '1974',
    kind: 'materials problem',
    problem_2D_or_3D: '1',
    num_rows: '130',
    num_cols: '130',
    nonzeros: '1037',
    num_explicit_zeros: '245',
    num_strongly_connected_components: '55',
    num_dmperm_blocks: '55',
    structural_full_rank: 'true',
    structural_rank: '130',
    pattern_symmetry: '0.759',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.397348e+05',
    min_singular_value: '3.959802e-06',
    condition_number: '6.054212e+10',
    svd_rank: '130',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'arc130.png,arc130_dmperm.png,arc130_svd.png,arc130_APlusAT_graph.gif,arc130_graph.gif,',
}
