{
    matrix_id: '9',
    name: 'ash331',
    group: 'HB',
    description: 'UNSYMMETRIC OVERDETERMINED PATTERN OF SCOTLAND SURVEY. ASHKENAZI,1974',
    author: 'V. Askenazi',
    editor: 'A. Curtis, I. Duff, J. Reid',
    date: '1974',
    kind: 'least squares problem',
    problem_2D_or_3D: '0',
    num_rows: '331',
    num_cols: '104',
    nonzeros: '662',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '104',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'binary',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '4.150687e+00',
    min_singular_value: '1.340441e+00',
    condition_number: '3.096508e+00',
    svd_rank: '104',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'ash331.png,ash331_svd.png,ash331_graph.gif,',
}
