{
    matrix_id: '10',
    name: 'ash608',
    group: 'HB',
    description: 'UNSYMMETRIC OVERDETERMINED PATTERN OF ENGLAND SURVEY. ASHKENAZI,1974',
    author: 'V. Askenazi',
    editor: 'A. Curtis, I. Duff, J. Reid',
    date: '1974',
    kind: 'least squares problem',
    problem_2D_or_3D: '0',
    num_rows: '608',
    num_cols: '188',
    nonzeros: '1216',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '188',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'binary',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '3.975924e+00',
    min_singular_value: '1.178763e+00',
    condition_number: '3.372962e+00',
    svd_rank: '188',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'ash608.png,ash608_svd.png,ash608_graph.gif,',
}
