{
    matrix_id: '11',
    name: 'ash85',
    group: 'HB',
    description: 'SYMMETRIC PATTERN OF NORMAL MATRIX OF HOLLAND SURVEY. ASHKENAZI, 1974',
    author: 'V. Askenazi',
    editor: 'A. Curtis, I. Duff, J. Reid',
    date: '1974',
    kind: 'least squares problem',
    problem_2D_or_3D: '0',
    num_rows: '85',
    num_cols: '85',
    nonzeros: '523',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '85',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '6.721547e+00',
    min_singular_value: '1.449402e-02',
    condition_number: '4.637463e+02',
    svd_rank: '85',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'ash85.png,ash85_svd.png,ash85_graph.gif,',
}
