{
    matrix_id: '12',
    name: 'ash958',
    group: 'HB',
    description: 'UNSYMMETRIC OVERDETERMINED PATTERN OF U.K. SURVEY. ASHKENAZI,1974',
    author: 'V. Askenazi',
    editor: 'A. Curtis, I. Duff, J. Reid',
    date: '1974',
    kind: 'least squares problem',
    problem_2D_or_3D: '0',
    num_rows: '958',
    num_cols: '292',
    nonzeros: '1916',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '292',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'binary',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '4.238275e+00',
    min_singular_value: '1.323899e+00',
    condition_number: '3.201358e+00',
    svd_rank: '292',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'ash958.png,ash958_svd.png,ash958_graph.gif,',
}
