{
    matrix_id: '14',
    name: 'bcspwr02',
    group: 'HB',
    description: 'SYMMETRIC STRUCTURE OF A SMALL TEST POWER SYSTEM',
    author: 'B. Dembart, J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1981',
    kind: 'power network problem',
    problem_2D_or_3D: '0',
    num_rows: '49',
    num_cols: '49',
    nonzeros: '167',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '49',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '4.308565e+00',
    min_singular_value: '1.320750e-16',
    condition_number: '32622115621105240',
    svd_rank: '48',
    sprank_minus_rank: '1',
    null_space_dimension: '1',
    full_numerical_rank: 'no',
    svd_gap: '575128761395423.750000',
    image_files: 'bcspwr02.png,bcspwr02_svd.png,bcspwr02_graph.gif,',
}
