{
    matrix_id: '17',
    name: 'bcspwr05',
    group: 'HB',
    description: 'SYMMETRIC STRUCTURE EQUIVALENCED REPRESENTATION OF WESTERN US NETWORK',
    author: 'B. Dembart, J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1981',
    kind: 'power network problem',
    problem_2D_or_3D: '0',
    num_rows: '443',
    num_cols: '443',
    nonzeros: '1623',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '443',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '5.178281e+00',
    min_singular_value: '4.724103e-17',
    condition_number: '109614047844109440',
    svd_rank: '437',
    sprank_minus_rank: '6',
    null_space_dimension: '6',
    full_numerical_rank: 'no',
    svd_gap: '21926567507228.238281',
    image_files: 'bcspwr05.png,bcspwr05_svd.png,bcspwr05_graph.gif,',
}
