{
    matrix_id: '16',
    name: 'bcspwr04',
    group: 'HB',
    description: 'SYMMETRIC STRUCTURE EQUIVALENCED REPRESENTATION OF U.S. POWER NETWORK',
    author: 'B. Dembart, J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1981',
    kind: 'power network problem',
    problem_2D_or_3D: '0',
    num_rows: '274',
    num_cols: '274',
    nonzeros: '1612',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '274',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '1.011456e+01',
    min_singular_value: '9.119241e-18',
    condition_number: '1109145449652521984',
    svd_rank: '262',
    sprank_minus_rank: '12',
    null_space_dimension: '12',
    full_numerical_rank: 'no',
    svd_gap: '753350498274.629517',
    image_files: 'bcspwr04.png,bcspwr04_svd.png,bcspwr04_graph.gif,',
}
