{
    matrix_id: '40',
    name: 'bcsstk18',
    group: 'HB',
    description: 'S  STIFFNESS MATRIX - R.E.GINNA NUCLEAR POWER STATION',
    author: 'M. Will',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1985',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '11948',
    num_cols: '11948',
    nonzeros: '149090',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '792',
    num_dmperm_blocks: '792',
    structural_full_rank: 'true',
    structural_rank: '11948',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '4.295198e+10',
    min_singular_value: '1.241388e-01',
    condition_number: '3.459995e+11',
    svd_rank: '11948',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'bcsstk18.png,bcsstk18_dmperm.png,bcsstk18_svd.png,bcsstk18_graph.gif,',
}
