{
    matrix_id: '57',
    name: 'bcsstm02',
    group: 'HB',
    description: 'SYMMETRIC MASS MATRIX, SMALL OIL RIG, STATICALLY CONDENSED',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '66',
    num_cols: '66',
    nonzeros: '66',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '66',
    num_dmperm_blocks: '66',
    structural_full_rank: 'true',
    structural_rank: '66',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '1.728286e-01',
    min_singular_value: '1.974694e-02',
    condition_number: '8.752170e+00',
    svd_rank: '66',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'bcsstm02.png,bcsstm02_dmperm.png,bcsstm02_svd.png,bcsstm02_graph.gif,',
}
