{
    matrix_id: '55',
    name: 'bcsstk33',
    group: 'HB',
    description: 'STIFFNESS MATRIX FOR PIN BOSS (AUTO STEERING COMPONENT), SOLID ELEMENTS',
    author: 'R. Cigel, R. Grimes, J. Lewis, E. Meyer',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1986',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '8738',
    num_cols: '8738',
    nonzeros: '591904',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '8738',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '7.582727e+01',
    min_singular_value: '5.127207e-64',
    condition_number: '1.478920e+65',
    svd_rank: '3979',
    sprank_minus_rank: '4759',
    null_space_dimension: '4759',
    full_numerical_rank: 'no',
    svd_gap: '67765026782.398140',
    image_files: 'bcsstk33.png,bcsstk33_svd.png,bcsstk33_graph.gif,',
}
