{
    matrix_id: '76',
    name: 'bcsstm26',
    group: 'HB',
    description: 'SYMMETRIC MASS      MATRIX - REACTOR CONTAINMENT FLOOR -- SECTION',
    author: 'A. Mera, R. Cigel, J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1984',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '1922',
    num_cols: '1922',
    nonzeros: '1922',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1922',
    num_dmperm_blocks: '1922',
    structural_full_rank: 'true',
    structural_rank: '1922',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '1.512404e+00',
    min_singular_value: '5.782098e-06',
    condition_number: '2.615666e+05',
    svd_rank: '1922',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'bcsstm26.png,bcsstm26_dmperm.png,bcsstm26_svd.png,bcsstm26_graph.gif,',
}
