{
    matrix_id: '44',
    name: 'bcsstk22',
    group: 'HB',
    description: 'SYMMETRIC STIFFNESS MATRIX - TEXTILE LOOM FRAME',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1984',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '138',
    num_cols: '138',
    nonzeros: '696',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '4',
    num_dmperm_blocks: '4',
    structural_full_rank: 'true',
    structural_rank: '138',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '5.850119e+06',
    min_singular_value: '5.283871e+01',
    condition_number: '1.107165e+05',
    svd_rank: '138',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'bcsstk22.png,bcsstk22_dmperm.png,bcsstk22_svd.png,bcsstk22_graph.gif,',
}
