{
    matrix_id: '74',
    name: 'bcsstm24',
    group: 'HB',
    description: 'SYMMETRIC MASS      MATRIX - WINTER SPORTS ARENA',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1984',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '3562',
    num_cols: '3562',
    nonzeros: '3562',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '3562',
    num_dmperm_blocks: '3562',
    structural_full_rank: 'true',
    structural_rank: '3562',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '1.015347e+06',
    min_singular_value: '5.616972e-08',
    condition_number: '1.807642e+13',
    svd_rank: '3496',
    sprank_minus_rank: '66',
    null_space_dimension: '66',
    full_numerical_rank: 'no',
    svd_gap: '5482.080844',
    image_files: 'bcsstm24.png,bcsstm24_dmperm.png,bcsstm24_svd.png,bcsstm24_graph.gif,',
}
