{
    matrix_id: '50',
    name: 'bcsstk28',
    group: 'HB',
    description: 'SOLID ELEMENT MODEL (MSC NASTRAN)',
    author: 'A. Mera, R. Cigel, J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1984',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '4410',
    num_cols: '4410',
    nonzeros: '219024',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '4410',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '7.696214e+08',
    min_singular_value: '8.141737e-01',
    condition_number: '9.452791e+08',
    svd_rank: '4410',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'bcsstk28.png,bcsstk28_svd.png,bcsstk28_graph.gif,',
}
