{
    matrix_id: '23',
    name: 'bcsstk01',
    group: 'HB',
    description: 'SYMMETRIC STIFFNESS MATRIX SMALL GENERALIZED EIGENVALUE PROBLEM',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '48',
    num_cols: '48',
    nonzeros: '400',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '48',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '3.015179e+09',
    min_singular_value: '3.417268e+03',
    condition_number: '8.823363e+05',
    svd_rank: '48',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'bcsstk01.png,bcsstk01_svd.png,bcsstk01_graph.gif,',
}
