{
    matrix_id: '37',
    name: 'bcsstk15',
    group: 'HB',
    description: 'S  STIFFNESS MATRIX - MODULE OF AN OFFSHORE PLATFORM',
    author: 'M. Will',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1985',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '3948',
    num_cols: '3948',
    nonzeros: '117816',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '7',
    num_dmperm_blocks: '7',
    structural_full_rank: 'true',
    structural_rank: '3948',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '6.538182e+09',
    min_singular_value: '9.999995e-01',
    condition_number: '6.538185e+09',
    svd_rank: '3948',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'bcsstk15.png,bcsstk15_dmperm.png,bcsstk15_svd.png,bcsstk15_graph.gif,',
}
