{
    matrix_id: '73',
    name: 'bcsstm23',
    group: 'HB',
    description: 'SYMMETRIC MASS      MATRIX - PORTION OF A 3D GLOBALLY TRIANGLULAR BLDG',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1984',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '3134',
    num_cols: '3134',
    nonzeros: '3134',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '3134',
    num_dmperm_blocks: '3134',
    structural_full_rank: 'true',
    structural_rank: '3134',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '8.270348e+06',
    min_singular_value: '8.741942e-03',
    condition_number: '9.460538e+08',
    svd_rank: '3134',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'bcsstm23.png,bcsstm23_dmperm.png,bcsstm23_svd.png,bcsstm23_graph.gif,',
}
