{
    matrix_id: '63',
    name: 'bcsstm08',
    group: 'HB',
    description: 'SYMMETRIC MASS MATRIX, FRAME BUILDING (TV STUDIO)',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '1074',
    num_cols: '1074',
    nonzeros: '1074',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1074',
    num_dmperm_blocks: '1074',
    structural_full_rank: 'true',
    structural_rank: '1074',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '1.444061e+06',
    min_singular_value: '1.746943e-01',
    condition_number: '8.266217e+06',
    svd_rank: '1074',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'bcsstm08.png,bcsstm08_dmperm.png,bcsstm08_svd.png,bcsstm08_graph.gif,',
}
