{
    matrix_id: '26',
    name: 'bcsstk04',
    group: 'HB',
    description: 'SYMMETRIC STIFFNESS MATRIX, OIL RIG, NOT CONDENSED (SAME MODEL AS X02)',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '132',
    num_cols: '132',
    nonzeros: '3648',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '132',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '9.660618e+06',
    min_singular_value: '4.214073e+00',
    condition_number: '2.292466e+06',
    svd_rank: '132',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'bcsstk04.png,bcsstk04_svd.png,bcsstk04_graph.gif,',
}
