{
    matrix_id: '25',
    name: 'bcsstk03',
    group: 'HB',
    description: 'SYMMETRIC STIFFNESS MATRIX, SMALL TEST STRUCTURE',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '112',
    num_cols: '112',
    nonzeros: '640',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '112',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '1.997345e+11',
    min_singular_value: '2.941020e+04',
    condition_number: '6.791333e+06',
    svd_rank: '112',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'bcsstk03.png,bcsstk03_dmperm.png,bcsstk03_svd.png,bcsstk03_graph.gif,',
}
