{
    matrix_id: '67',
    name: 'bcsstm12',
    group: 'HB',
    description: 'SYMMETRIC MASS MATRIX, ORE CAR (CONSISTENT MASSES)',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '1473',
    num_cols: '1473',
    nonzeros: '19659',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '10',
    num_dmperm_blocks: '10',
    structural_full_rank: 'true',
    structural_rank: '1473',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '1.341559e+01',
    min_singular_value: '2.118712e-05',
    condition_number: '6.331955e+05',
    svd_rank: '1473',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'bcsstm12.png,bcsstm12_dmperm.png,bcsstm12_svd.png,bcsstm12_graph.gif,',
}
