{
    matrix_id: '64',
    name: 'bcsstm09',
    group: 'HB',
    description: 'SYMMETRIC MASS MATRIX, SQUARE PLATE CLAMPED',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '1083',
    num_cols: '1083',
    nonzeros: '1083',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1083',
    num_dmperm_blocks: '1083',
    structural_full_rank: 'true',
    structural_rank: '1083',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '2.590204e-04',
    min_singular_value: '2.590204e-08',
    condition_number: '10000',
    svd_rank: '1083',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'bcsstm09.png,bcsstm09_dmperm.png,bcsstm09_svd.png,bcsstm09_graph.gif,',
}
