{
    matrix_id: '35',
    name: 'bcsstk13',
    group: 'HB',
    description: 'SYMMETRIC STIFFNESS MATRIX, FLUID FLOW GENERALIZED EIGENVALUES',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '2003',
    num_cols: '2003',
    nonzeros: '83883',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '2003',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '3.114812e+12',
    min_singular_value: '2.843328e+02',
    condition_number: '1.095481e+10',
    svd_rank: '2003',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'bcsstk13.png,bcsstk13_svd.png,bcsstk13_graph.gif,',
}
