{
    matrix_id: '48',
    name: 'bcsstk26',
    group: 'HB',
    description: 'SYMMETRIC STIFFNESS MATRIX - REACTOR CONTAINMENT FLOOR -- SECTION',
    author: 'A. Mera, R. Cigel, J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1984',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '1922',
    num_cols: '1922',
    nonzeros: '30336',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '1922',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '1.582731e+11',
    min_singular_value: '9.538334e+02',
    condition_number: '1.659338e+08',
    svd_rank: '1922',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'bcsstk26.png,bcsstk26_svd.png,bcsstk26_graph.gif,',
}
