{
    matrix_id: '42',
    name: 'bcsstk20',
    group: 'HB',
    description: 'SYMMETRIC STIFFNESS MATRIX - FRAME WITHIN A SUSPENSION BRIDGE',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1984',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '485',
    num_cols: '485',
    nonzeros: '3135',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '4',
    num_dmperm_blocks: '4',
    structural_full_rank: 'true',
    structural_rank: '485',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '12615207924650080',
    min_singular_value: '3.240766e+03',
    condition_number: '3.892662e+12',
    svd_rank: '485',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'bcsstk20.png,bcsstk20_dmperm.png,bcsstk20_svd.png,bcsstk20_graph.gif,',
}
