{
    matrix_id: '69',
    name: 'bcsstm19',
    group: 'HB',
    description: 'SYMMETRIC MASS      MATRIX - PART OF A SUSPENSION BRIDGE',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1984',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '817',
    num_cols: '817',
    nonzeros: '817',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '817',
    num_dmperm_blocks: '817',
    structural_full_rank: 'true',
    structural_rank: '817',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '3.954518e+07',
    min_singular_value: '1.691885e+02',
    condition_number: '2.337344e+05',
    svd_rank: '817',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'bcsstm19.png,bcsstm19_dmperm.png,bcsstm19_svd.png,bcsstm19_graph.gif,',
}
