{
    matrix_id: '72',
    name: 'bcsstm22',
    group: 'HB',
    description: 'SYMMETRIC MASS      MATRIX - TEXTILE LOOM FRAME',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1984',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '138',
    num_cols: '138',
    nonzeros: '138',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '138',
    num_dmperm_blocks: '138',
    structural_full_rank: 'true',
    structural_rank: '138',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '9.737666e-03',
    min_singular_value: '1.034497e-05',
    condition_number: '9.412946e+02',
    svd_rank: '138',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'bcsstm22.png,bcsstm22_dmperm.png,bcsstm22_svd.png,bcsstm22_graph.gif,',
}
