{
    matrix_id: '28',
    name: 'bcsstk06',
    group: 'HB',
    description: 'SYMMETRIC STIFFNESS MATRIX, MEDIUM TEST PROBLEM, LUMPED MASSES',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '420',
    num_cols: '420',
    nonzeros: '7860',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '420',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '3.486950e+09',
    min_singular_value: '4.606246e+02',
    condition_number: '7.570047e+06',
    svd_rank: '420',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'bcsstk06.png,bcsstk06_svd.png,bcsstk06_graph.gif,',
}
