{
    matrix_id: '68',
    name: 'bcsstm13',
    group: 'HB',
    description: 'SYMMETRIC MASS MATRIX, FLUID FLOW GENERALIZED EIGENVALUES',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '2003',
    num_cols: '2003',
    nonzeros: '21181',
    num_explicit_zeros: '762',
    num_strongly_connected_components: '1334',
    num_dmperm_blocks: '574',
    structural_full_rank: 'false',
    structural_rank: '1241',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.579266e+02',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '1241',
    sprank_minus_rank: '0',
    null_space_dimension: '762',
    full_numerical_rank: 'no',
    svd_gap: '662075714845.188599',
    image_files: 'bcsstm13.png,bcsstm13_dmperm.png,bcsstm13_scc.png,bcsstm13_svd.png,bcsstm13_graph.gif,',
}
