{
    matrix_id: '78',
    name: 'beacxc',
    group: 'HB',
    description: 'U NONSYMMETRIC MATRIX U.S. ECONOMY 1972  -SZYLD-I.E.A.-NYU-',
    author: 'D. Szyld',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'economic problem',
    problem_2D_or_3D: '0',
    num_rows: '497',
    num_cols: '506',
    nonzeros: '50409',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '66',
    num_dmperm_blocks: '10',
    structural_full_rank: 'false',
    structural_rank: '449',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.061518e+01',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '449',
    sprank_minus_rank: '0',
    null_space_dimension: '48',
    full_numerical_rank: 'no',
    svd_gap: '1089453281.540612',
    image_files: 'beacxc.png,beacxc_dmperm.png,beacxc_scc.png,beacxc_svd.png,beacxc_graph.gif,',
}
