{
    matrix_id: '81',
    name: 'blckhole',
    group: 'HB',
    description: 'S  CONNECTIVITY STRUCTURE OF A GEODESIC DOME ON A COARSE BASE',
    author: 'E. Meyer',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1983',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '2132',
    num_cols: '2132',
    nonzeros: '14872',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '12',
    num_dmperm_blocks: '12',
    structural_full_rank: 'true',
    structural_rank: '2132',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '8.231003e+00',
    min_singular_value: '1.975370e-03',
    condition_number: '4.166815e+03',
    svd_rank: '2132',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'blckhole.png,blckhole_dmperm.png,blckhole_svd.png,blckhole_graph.gif,',
}
