{
    matrix_id: '86',
    name: 'bp_1600',
    group: 'HB',
    description: 'UNSYMMETRIC BASIS FROM LP PROBLEM BP',
    author: 'M. Saunders',
    editor: 'A. Curtis, I. Duff, J. Reid',
    date: '1978',
    kind: 'subsequent optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '822',
    num_cols: '822',
    nonzeros: '4841',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '450',
    structural_full_rank: 'true',
    structural_rank: '822',
    pattern_symmetry: '0.011',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: - first: HB/bp_0
',
    norm: '4.036798e+02',
    min_singular_value: '1.193257e-04',
    condition_number: '3.383008e+06',
    svd_rank: '822',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'bp_1600.png,bp_1600_dmperm.png,bp_1600_scc.png,bp_1600_svd.png,bp_1600_APlusAT_graph.gif,bp_1600_graph.gif,',
}
