{
    matrix_id: '83',
    name: 'bp_1000',
    group: 'HB',
    description: 'UNSYMMETRIC BASIS FROM LP PROBLEM BP',
    author: 'M. Saunders',
    editor: 'A. Curtis, I. Duff, J. Reid',
    date: '1978',
    kind: 'subsequent optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '822',
    num_cols: '822',
    nonzeros: '4661',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '463',
    structural_full_rank: 'true',
    structural_rank: '822',
    pattern_symmetry: '0.009',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: HB/bp_1200 first: HB/bp_0
',
    norm: '4.034222e+02',
    min_singular_value: '1.661821e-05',
    condition_number: '2.427591e+07',
    svd_rank: '822',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'bp_1000.png,bp_1000_dmperm.png,bp_1000_scc.png,bp_1000_svd.png,bp_1000_APlusAT_graph.gif,bp_1000_graph.gif,',
}
