{
    matrix_id: '85',
    name: 'bp_1400',
    group: 'HB',
    description: 'UNSYMMETRIC BASIS FROM LP PROBLEM BP',
    author: 'M. Saunders',
    editor: 'A. Curtis, I. Duff, J. Reid',
    date: '1978',
    kind: 'subsequent optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '822',
    num_cols: '822',
    nonzeros: '4790',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '403',
    structural_full_rank: 'true',
    structural_rank: '822',
    pattern_symmetry: '0.010',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: HB/bp_1600 first: HB/bp_0
',
    norm: '4.035911e+02',
    min_singular_value: '4.446537e-05',
    condition_number: '9.076525e+06',
    svd_rank: '822',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'bp_1400.png,bp_1400_dmperm.png,bp_1400_scc.png,bp_1400_svd.png,bp_1400_APlusAT_graph.gif,bp_1400_graph.gif,',
}
