{
    matrix_id: '94',
    name: 'can_161',
    group: 'HB',
    description: 'SYMMETRIC PATTERN FROM CANNES,LUCIEN MARRO,JUNE 1981.',
    author: 'L. Marro',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1981',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '161',
    num_cols: '161',
    nonzeros: '1377',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '161',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '8.821749e+00',
    min_singular_value: '3.969288e-02',
    condition_number: '2.222502e+02',
    svd_rank: '161',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'can_161.png,can_161_svd.png,can_161_graph.gif,',
}
