{
    matrix_id: '102',
    name: 'can_61',
    group: 'HB',
    description: 'SYMMETRIC PATTERN FROM CANNES,LUCIEN MARRO,JUNE 1981.',
    author: 'L. Marro',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1981',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '61',
    num_cols: '61',
    nonzeros: '557',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '61',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '1.094671e+01',
    min_singular_value: '1.094024e-32',
    condition_number: '1.000592e+33',
    svd_rank: '49',
    sprank_minus_rank: '12',
    null_space_dimension: '12',
    full_numerical_rank: 'no',
    svd_gap: '49978634104451.101562',
    image_files: 'can_61.png,can_61_svd.png,can_61_graph.gif,',
}
