{
    matrix_id: '1176',
    name: 'cegb3306',
    group: 'HB',
    description: 'FINITE ELEMENT FRAMEWORK PROBLEM, ESSENTIALLY IN TWO DIMENSIONS',
    author: 'A. Donovan',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1980',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '3306',
    num_cols: '3306',
    nonzeros: '74916',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '85',
    num_dmperm_blocks: '3',
    structural_full_rank: 'false',
    structural_rank: '3222',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '3.604032e+01',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '537',
    sprank_minus_rank: '2685',
    null_space_dimension: '2769',
    full_numerical_rank: 'no',
    svd_gap: '354334640835.680786',
    image_files: 'cegb3306.png,cegb3306_dmperm.png,cegb3306_scc.png,cegb3306_svd.png,cegb3306_graph.gif,',
}
