{
    matrix_id: '129',
    name: 'dwt_59',
    group: 'HB',
    description: 'SYMMETRIC CONNECTION TABLE FROM DTNSRDC, WASHINGTON',
    author: 'G. Everstine, D. Taylor',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1980',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '59',
    num_cols: '59',
    nonzeros: '267',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '59',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '4.966416e+00',
    min_singular_value: '4.205181e-02',
    condition_number: '1.181023e+02',
    svd_rank: '59',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'dwt_59.png,dwt_592.png,dwt_592_svd.png,dwt_59_svd.png,dwt_592_graph.gif,dwt_59_graph.gif,',
}
