{
    matrix_id: '136',
    name: 'dwt_87',
    group: 'HB',
    description: 'SYMMETRIC CONNECTION TABLE FROM DTNSRDC, WASHINGTON',
    author: 'G. Everstine, D. Taylor',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1980',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '87',
    num_cols: '87',
    nonzeros: '541',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '87',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '7.713552e+00',
    min_singular_value: '7.621502e-02',
    condition_number: '1.012078e+02',
    svd_rank: '87',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'dwt_87.png,dwt_878.png,dwt_878_svd.png,dwt_87_svd.png,dwt_878_graph.gif,dwt_87_graph.gif,',
}
