{
    matrix_id: '128',
    name: 'dwt_512',
    group: 'HB',
    description: 'SYMMETRIC CONNECTION TABLE FROM DTNSRDC, WASHINGTON',
    author: 'G. Everstine, D. Taylor',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1980',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '512',
    num_cols: '512',
    nonzeros: '3502',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '32',
    num_dmperm_blocks: '32',
    structural_full_rank: 'true',
    structural_rank: '512',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '1.138403e+01',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '477',
    sprank_minus_rank: '35',
    null_space_dimension: '35',
    full_numerical_rank: 'no',
    svd_gap: '4313302984153.762695',
    image_files: 'dwt_512.png,dwt_512_dmperm.png,dwt_512_svd.png,dwt_512_graph.gif,',
}
