{
    matrix_id: '144',
    name: 'fs_183_6',
    group: 'HB',
    description: 'UNSYMMETRIC FACSIMILE CONVERGENCE MATRIX',
    author: 'A. Curtis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1983',
    kind: 'subsequent 2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '183',
    num_cols: '183',
    nonzeros: '1000',
    num_explicit_zeros: '69',
    num_strongly_connected_components: '37',
    num_dmperm_blocks: '37',
    structural_full_rank: 'true',
    structural_rank: '183',
    pattern_symmetry: '0.418',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: - first: HB/fs_183_1
',
    norm: '1.180839e+09',
    min_singular_value: '6.799008e-03',
    condition_number: '1.736781e+11',
    svd_rank: '183',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'fs_183_6.png,fs_183_6_dmperm.png,fs_183_6_svd.png,fs_183_6_APlusAT_graph.gif,fs_183_6_graph.gif,',
}
