{
    matrix_id: '141',
    name: 'fs_183_1',
    group: 'HB',
    description: 'UNSYMMETRIC FACSIMILE CONVERGENCE MATRIX',
    author: 'A. Curtis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1983',
    kind: '2D/3D problem sequence',
    problem_2D_or_3D: '1',
    num_rows: '183',
    num_cols: '183',
    nonzeros: '998',
    num_explicit_zeros: '71',
    num_strongly_connected_components: '37',
    num_dmperm_blocks: '37',
    structural_full_rank: 'true',
    structural_rank: '183',
    pattern_symmetry: '0.418',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: HB/fs_183_3 first: HB/fs_183_1
',
    norm: '1.129349e+09',
    min_singular_value: '5.148887e-05',
    condition_number: '2.193385e+13',
    svd_rank: '183',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'fs_183_1.png,fs_183_1_dmperm.png,fs_183_1_svd.png,fs_183_1_APlusAT_graph.gif,fs_183_1_graph.gif,',
}
