{
    matrix_id: '143',
    name: 'fs_183_4',
    group: 'HB',
    description: 'UNSYMMETRIC FACSIMILE CONVERGENCE MATRIX',
    author: 'A. Curtis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1983',
    kind: 'subsequent 2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '183',
    num_cols: '183',
    nonzeros: '1069',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '30',
    num_dmperm_blocks: '30',
    structural_full_rank: 'true',
    structural_rank: '183',
    pattern_symmetry: '0.418',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: HB/fs_183_6 first: HB/fs_183_1
',
    norm: '1.122892e+09',
    min_singular_value: '5.160508e-03',
    condition_number: '2.175933e+11',
    svd_rank: '183',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'fs_183_4.png,fs_183_4_dmperm.png,fs_183_4_svd.png,fs_183_4_APlusAT_graph.gif,fs_183_4_graph.gif,',
}
