{
    matrix_id: '146',
    name: 'fs_541_2',
    group: 'HB',
    description: 'UNSYMMETRIC FACSIMILE CONVERGENCE MATRIX',
    author: 'A. Curtis',
    editor: 'A. Curtis, I. Duff, J. Reid',
    date: '1978',
    kind: 'subsequent 2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '541',
    num_cols: '541',
    nonzeros: '4282',
    num_explicit_zeros: '3',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '541',
    pattern_symmetry: '0.683',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: HB/fs_541_3 first: HB/fs_541_1
',
    norm: '1.698175e+06',
    min_singular_value: '3.850000e-05',
    condition_number: '4.410843e+10',
    svd_rank: '541',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'fs_541_2.png,fs_541_2_dmperm.png,fs_541_2_svd.png,fs_541_2_APlusAT_graph.gif,fs_541_2_graph.gif,',
}
