{
    matrix_id: '149',
    name: 'fs_680_1',
    group: 'HB',
    description: 'UNSYMMETRIC FACSIMILE CONVERGENCE MATRIX',
    author: 'A. Curtis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1983',
    kind: '2D/3D problem sequence',
    problem_2D_or_3D: '1',
    num_rows: '680',
    num_cols: '680',
    nonzeros: '2184',
    num_explicit_zeros: '462',
    num_strongly_connected_components: '446',
    num_dmperm_blocks: '446',
    structural_full_rank: 'true',
    structural_rank: '680',
    pattern_symmetry: '0.511',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: HB/fs_680_2 first: HB/fs_680_1
',
    norm: '7.191491e+13',
    min_singular_value: '4.668218e+09',
    condition_number: '1.540522e+04',
    svd_rank: '680',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'fs_680_1.png,fs_680_1_dmperm.png,fs_680_1_svd.png,fs_680_1_APlusAT_graph.gif,fs_680_1_graph.gif,',
}
