{
    matrix_id: '157',
    name: 'gemat12',
    group: 'HB',
    description: 'UNSUMMETRIC MATRIX FROM G.E. OPF PROGRAM. WESTERN UTILITY SYSTEMBASIS 1',
    author: 'R. Burchett',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1984',
    kind: 'subsequent power network problem',
    problem_2D_or_3D: '0',
    num_rows: '4929',
    num_cols: '4929',
    nonzeros: '33044',
    num_explicit_zeros: '67',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '378',
    structural_full_rank: 'true',
    structural_rank: '4929',
    pattern_symmetry: '0.001',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: - first: HB/gemat11
',
    norm: '6.927498e+02',
    min_singular_value: '6.637586e-06',
    condition_number: '1.043677e+08',
    svd_rank: '4929',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'gemat12.png,gemat12_dmperm.png,gemat12_scc.png,gemat12_svd.png,gemat12_APlusAT_graph.gif,gemat12_graph.gif,',
}
