{
    matrix_id: '156',
    name: 'gemat11',
    group: 'HB',
    description: 'UNSUMMETRIC MATRIX FROM G.E. OPF PROGRAM. WESTERN UTILITY SYSTEMBASIS 0',
    author: 'R. Burchett',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1984',
    kind: 'power network problem sequence',
    problem_2D_or_3D: '0',
    num_rows: '4929',
    num_cols: '4929',
    nonzeros: '33108',
    num_explicit_zeros: '77',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '352',
    structural_full_rank: 'true',
    structural_rank: '4929',
    pattern_symmetry: '0.001',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: HB/gemat12 first: HB/gemat11
',
    norm: '6.927498e+02',
    min_singular_value: '1.163187e-05',
    condition_number: '5.955619e+07',
    svd_rank: '4929',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'gemat11.png,gemat11_dmperm.png,gemat11_scc.png,gemat11_svd.png,gemat11_APlusAT_graph.gif,gemat11_graph.gif,',
}
