{
    matrix_id: '159',
    name: 'gr_30_30',
    group: 'HB',
    description: 'SYMMETRIC MATRIX FROM NINE POINT START ON A  30 X  30 GRID.',
    author: 'R. Grimes',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1983',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '900',
    num_cols: '900',
    nonzeros: '7744',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '900',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'integer',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '1.195906e+01',
    min_singular_value: '6.146282e-02',
    condition_number: '1.945739e+02',
    svd_rank: '900',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'gr_30_30.png,gr_30_30_svd.png,gr_30_30_graph.gif,',
}
