{
    matrix_id: '165',
    name: 'gre_343',
    group: 'HB',
    description: 'UNSYMMETRIC MATRIX FROM GRENOBLE,FRANCOIS CACHARD,MARCH 1981.',
    author: 'F. Cachard',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1981',
    kind: 'directed weighted graph',
    problem_2D_or_3D: '0',
    num_rows: '343',
    num_cols: '343',
    nonzeros: '1310',
    num_explicit_zeros: '125',
    num_strongly_connected_components: '1',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.009539e+00',
    min_singular_value: '9.015650e-03',
    condition_number: '1.119763e+02',
    svd_rank: '343',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'gre_343.png,gre_343_svd.png,gre_343_APlusAT_graph.gif,gre_343_graph.gif,',
}
