{
    matrix_id: '162',
    name: 'gre_185',
    group: 'HB',
    description: 'UNSYMMETRIC MATRIX FROM GRENOBLE,FRANCOIS CACHARD,MARCH 1981.',
    author: 'F. Cachard',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1981',
    kind: 'directed weighted graph',
    problem_2D_or_3D: '0',
    num_rows: '185',
    num_cols: '185',
    nonzeros: '975',
    num_explicit_zeros: '30',
    num_strongly_connected_components: '1',
    pattern_symmetry: '0.415',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.109007e+00',
    min_singular_value: '6.119428e-06',
    condition_number: '1.812273e+05',
    svd_rank: '185',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'gre_185.png,gre_185_svd.png,gre_185_APlusAT_graph.gif,gre_185_graph.gif,',
}
