{
    matrix_id: '163',
    name: 'gre_216a',
    group: 'HB',
    description: 'UNSYMMETRIC MATRIX FROM GRENOBLE,FRANCOIS CACHARD,MARCH 1981.',
    author: 'F. Cachard',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1981',
    kind: 'directed weighted graph',
    problem_2D_or_3D: '0',
    num_rows: '216',
    num_cols: '216',
    nonzeros: '812',
    num_explicit_zeros: '64',
    num_strongly_connected_components: '1',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.011166e+00',
    min_singular_value: '9.815685e-03',
    condition_number: '1.030153e+02',
    svd_rank: '216',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'gre_216a.png,gre_216a_svd.png,gre_216a_APlusAT_graph.gif,gre_216a_graph.gif,',
}
