{
    matrix_id: '160',
    name: 'gre_1107',
    group: 'HB',
    description: 'UNSYMMETRIC MATRIX FROM GRENOBLE,FRANCOIS CACHARD,MARCH 1981.',
    author: 'F. Cachard',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1981',
    kind: 'directed weighted graph',
    problem_2D_or_3D: '0',
    num_rows: '1107',
    num_cols: '1107',
    nonzeros: '5664',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.110239e+00',
    min_singular_value: '3.482569e-08',
    condition_number: '3.187989e+07',
    svd_rank: '1107',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'gre_1107.png,gre_1107_svd.png,gre_1107_APlusAT_graph.gif,gre_1107_graph.gif,',
}
