{
    matrix_id: '166',
    name: 'gre_512',
    group: 'HB',
    description: 'UNSYMMETRIC MATRIX FROM GRENOBLE,FRANCOIS CACHARD,MARCH 1981.',
    author: 'F. Cachard',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1981',
    kind: 'directed weighted graph',
    problem_2D_or_3D: '0',
    num_rows: '512',
    num_cols: '512',
    nonzeros: '1976',
    num_explicit_zeros: '216',
    num_strongly_connected_components: '1',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.008349e+00',
    min_singular_value: '6.369125e-03',
    condition_number: '1.583183e+02',
    svd_rank: '512',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'gre_512.png,gre_512_svd.png,gre_512_APlusAT_graph.gif,gre_512_graph.gif,',
}
