{
    matrix_id: '167',
    name: 'hor_131',
    group: 'HB',
    description: 'UNSYMMETRIC MATRIX NNC  R.P.HORNBY JANUARY,1983.',
    author: 'R. Hornby',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1983',
    kind: 'directed weighted graph',
    problem_2D_or_3D: '0',
    num_rows: '434',
    num_cols: '434',
    nonzeros: '4182',
    num_explicit_zeros: '528',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.374',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '6.607441e-01',
    min_singular_value: '1.533813e-05',
    condition_number: '4.307853e+04',
    svd_rank: '434',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'hor_131.png,hor_131_svd.png,hor_131_graph.gif,',
}
