{
    matrix_id: '175',
    name: 'impcol_e',
    group: 'HB',
    description: 'UNSYMMETRIC MATRIX - HYDROCARBON SEPARATION PROBLEM(CHEM ENG),1982',
    author: 'D. Bogle',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '225',
    num_cols: '225',
    nonzeros: '1303',
    num_explicit_zeros: '5',
    num_strongly_connected_components: '17',
    num_dmperm_blocks: '151',
    structural_full_rank: 'true',
    structural_rank: '225',
    pattern_symmetry: '0.104',
    numeric_symmetry: '0.002',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '5.000000e+03',
    min_singular_value: '7.041288e-04',
    condition_number: '7.100974e+06',
    svd_rank: '225',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'impcol_e.png,impcol_e_dmperm.png,impcol_e_scc.png,impcol_e_svd.png,impcol_e_APlusAT_graph.gif,impcol_e_graph.gif,',
}
