{
    matrix_id: '173',
    name: 'impcol_c',
    group: 'HB',
    description: 'UNSYMMETRIC MATRIX - ETHYLENE PLANT MODEL (CHEM ENG)   ,1982',
    author: 'D. Bogle',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '137',
    num_cols: '137',
    nonzeros: '400',
    num_explicit_zeros: '11',
    num_strongly_connected_components: '18',
    num_dmperm_blocks: '115',
    structural_full_rank: 'true',
    structural_rank: '137',
    pattern_symmetry: '0.044',
    numeric_symmetry: '0.011',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.200000e+02',
    min_singular_value: '6.786789e-03',
    condition_number: '1.768141e+04',
    svd_rank: '137',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'impcol_c.png,impcol_c_dmperm.png,impcol_c_scc.png,impcol_c_svd.png,impcol_c_APlusAT_graph.gif,impcol_c_graph.gif,',
}
