{
    matrix_id: '184',
    name: 'jagmesh9',
    group: 'HB',
    description: 'SYMMETRIC PATTERN FROM ALAN GEORGE - PINCHED HOLE PROBLEM',
    author: 'A. George',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1978',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '1349',
    num_cols: '1349',
    nonzeros: '9101',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '1349',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '6.954292e+00',
    min_singular_value: '1.152033e-03',
    condition_number: '6.036539e+03',
    svd_rank: '1349',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'jagmesh9.png,jagmesh9_svd.png,jagmesh9_graph.gif,',
}
