{
    matrix_id: '178',
    name: 'jagmesh3',
    group: 'HB',
    description: 'SYMMETRIC PATTERN FROM ALAN GEORGE - PLAIN SQUARE',
    author: 'A. George',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1978',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '1089',
    num_cols: '1089',
    nonzeros: '7361',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '1089',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '6.967736e+00',
    min_singular_value: '5.963447e-03',
    condition_number: '1.168407e+03',
    svd_rank: '1089',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'jagmesh3.png,jagmesh3_svd.png,jagmesh3_graph.gif,',
}
