{
    matrix_id: '177',
    name: 'jagmesh2',
    group: 'HB',
    description: 'SYMMETRIC PATTERN FROM ALAN GEORGE - GRADED L',
    author: 'A. George',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1978',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '1009',
    num_cols: '1009',
    nonzeros: '6865',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '1009',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '6.969544e+00',
    min_singular_value: '2.945094e-03',
    condition_number: '2.366493e+03',
    svd_rank: '1009',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'jagmesh2.png,jagmesh2_svd.png,jagmesh2_graph.gif,',
}
