{
    matrix_id: '185',
    name: 'jgl009',
    group: 'HB',
    description: 'U JOHN G. LEWIS P4 COUNTEREXAMPLE WHICH REQUIRES FILL IN SPIKES',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1983',
    kind: 'counter-example problem',
    problem_2D_or_3D: '0',
    num_rows: '9',
    num_cols: '9',
    nonzeros: '50',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '9',
    pattern_symmetry: '0.476',
    numeric_symmetry: '0.476',
    rb_type: 'binary',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '6.101288e+00',
    min_singular_value: '4.861731e-63',
    condition_number: '1.254962e+63',
    svd_rank: '5',
    sprank_minus_rank: '4',
    null_space_dimension: '4',
    full_numerical_rank: 'no',
    svd_gap: '6027489080018935.000000',
    image_files: 'jgl009.png,jgl009_svd.png,jgl009_APlusAT_graph.gif,jgl009_graph.gif,',
}
