{
    matrix_id: '186',
    name: 'jgl011',
    group: 'HB',
    description: 'U JOHN G. LEWIS P4 COUNTEREXAMPLE WHICH REQUIRES FILL IN SPIKES',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1983',
    kind: 'counter-example problem',
    problem_2D_or_3D: '0',
    num_rows: '11',
    num_cols: '11',
    nonzeros: '76',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '11',
    pattern_symmetry: '0.515',
    numeric_symmetry: '0.515',
    rb_type: 'binary',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '7.694946e+00',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '5',
    sprank_minus_rank: '6',
    null_space_dimension: '6',
    full_numerical_rank: 'no',
    svd_gap: '3926024851182060.500000',
    image_files: 'jgl011.png,jgl011_svd.png,jgl011_APlusAT_graph.gif,jgl011_graph.gif,',
}
