{
    matrix_id: '1181',
    name: 'lock_700',
    group: 'HB',
    description: 'FINITE ELEMENT PROBLEM. LOCKHEED PORCH PROBLEM',
    author: 'W. Loden',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1980',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '700',
    num_cols: '700',
    nonzeros: '22175',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '10',
    num_dmperm_blocks: '3',
    structural_full_rank: 'false',
    structural_rank: '691',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '4.297855e+01',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '165',
    sprank_minus_rank: '526',
    null_space_dimension: '535',
    full_numerical_rank: 'no',
    svd_gap: '355123793473.713379',
    image_files: 'lock_700.png,lock_700_dmperm.png,lock_700_scc.png,lock_700_svd.png,lock_700_graph.gif,',
}
