{
    matrix_id: '199',
    name: 'lshp2614',
    group: 'HB',
    description: 'SYMMETRIC MATRIX FROM ALAN GEORGE\'S L-SHAPE PROBLEMS, 1978.',
    author: 'A. George',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1978',
    kind: 'thermal problem',
    problem_2D_or_3D: '1',
    num_rows: '2614',
    num_cols: '2614',
    nonzeros: '17980',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '2614',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '6.987978e+00',
    min_singular_value: '1.344526e-03',
    condition_number: '5.197354e+03',
    svd_rank: '2614',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'lshp2614.png,lshp2614_svd.png,lshp2614_graph.gif,',
}
