{
    matrix_id: '202',
    name: 'lshp_265',
    group: 'HB',
    description: 'SYMMETRIC MATRIX FROM ALAN GEORGE\'S L-SHAPE PROBLEMS, 1978.',
    author: 'A. George',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1978',
    kind: 'thermal problem',
    problem_2D_or_3D: '1',
    num_rows: '265',
    num_cols: '265',
    nonzeros: '1753',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '265',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '6.890650e+00',
    min_singular_value: '4.964477e-03',
    condition_number: '1.387991e+03',
    svd_rank: '265',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'lshp_265.png,lshp_265_svd.png,lshp_265_graph.gif,',
}
