{
    matrix_id: '207',
    name: 'lund_b',
    group: 'HB',
    description: 'SYMMETRIC MATRIX B OF LUND EIGENVALUE PROBLEM, MAY 1974',
    author: 'T. Johansson',
    editor: 'A. Curtis, I. Duff, J. Reid',
    date: '1974',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '147',
    num_cols: '147',
    nonzeros: '2441',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '147',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '7.432299e+03',
    min_singular_value: '2.474424e-01',
    condition_number: '3.003648e+04',
    svd_rank: '147',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'lund_b.png,lund_b_svd.png,lund_b_graph.gif,',
}
