{
    matrix_id: '211',
    name: 'mbeause',
    group: 'HB',
    description: 'U NONSYMMETRIC MATRIX U.S. ECONOMY 1972  -SZYLD-I.E.A.-NYU-',
    author: 'D. Szyld',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'economic problem',
    problem_2D_or_3D: '0',
    num_rows: '496',
    num_cols: '496',
    nonzeros: '41063',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '66',
    num_dmperm_blocks: '28',
    structural_full_rank: 'false',
    structural_rank: '447',
    pattern_symmetry: '0.219',
    numeric_symmetry: '0.008',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.175505e+04',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '447',
    sprank_minus_rank: '0',
    null_space_dimension: '49',
    full_numerical_rank: 'no',
    svd_gap: '2981899762.504123',
    image_files: 'mbeause.png,mbeause_dmperm.png,mbeause_scc.png,mbeause_svd.png,mbeause_APlusAT_graph.gif,mbeause_graph.gif,',
}
