{
    matrix_id: '210',
    name: 'mbeaflw',
    group: 'HB',
    description: 'U NONSYMMETRIC MATRIX U.S. ECONOMY 1972  -SZYLD-I.E.A.-NYU-',
    author: 'D. Szyld',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'economic problem',
    problem_2D_or_3D: '0',
    num_rows: '496',
    num_cols: '496',
    nonzeros: '49920',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '54',
    num_dmperm_blocks: '10',
    structural_full_rank: 'false',
    structural_rank: '448',
    pattern_symmetry: '0.316',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.976238e+04',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '448',
    sprank_minus_rank: '0',
    null_space_dimension: '48',
    full_numerical_rank: 'no',
    svd_gap: '386590201.471280',
    image_files: 'mbeaflw.png,mbeaflw_dmperm.png,mbeaflw_scc.png,mbeaflw_svd.png,mbeaflw_APlusAT_graph.gif,mbeaflw_graph.gif,',
}
