{
    matrix_id: '212',
    name: 'mcca',
    group: 'HB',
    description: 'U NON-LTE PROBLEM ASTROPHYSICS.CODE:M.CARLSSON, ATOM=CA 2 ATMOS=VAL3C .',
    author: 'M. Carlsson',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1985',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '180',
    num_cols: '180',
    nonzeros: '2659',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '6',
    num_dmperm_blocks: '6',
    structural_full_rank: 'true',
    structural_rank: '180',
    pattern_symmetry: '0.645',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.044230e+19',
    min_singular_value: '1.046316e+02',
    condition_number: '195374181169902880',
    svd_rank: '143',
    sprank_minus_rank: '37',
    null_space_dimension: '37',
    full_numerical_rank: 'no',
    svd_gap: '1.096218',
    image_files: 'mcca.png,mcca_dmperm.png,mcca_svd.png,mcca_APlusAT_graph.gif,mcca_graph.gif,',
}
