{
    matrix_id: '215',
    name: 'nnc261',
    group: 'HB',
    description: 'U NATIONAL NUCLEAR CORP. FISSION REACTOR SIESMIC STUDIES',
    author: 'National Nuclear Corp.',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '261',
    num_cols: '261',
    nonzeros: '1500',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '29',
    structural_full_rank: 'true',
    structural_rank: '261',
    pattern_symmetry: '0.824',
    numeric_symmetry: '0.613',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.040628e+03',
    min_singular_value: '3.573898e-12',
    condition_number: '2.911744e+14',
    svd_rank: '260',
    sprank_minus_rank: '1',
    null_space_dimension: '1',
    full_numerical_rank: 'no',
    svd_gap: '169.180150',
    image_files: 'nnc261.png,nnc261_dmperm.png,nnc261_svd.png,nnc261_APlusAT_graph.gif,nnc261_graph.gif,',
}
