{
    matrix_id: '218',
    name: 'nos2',
    group: 'HB',
    description: 'SYMMETRIC MATRIX, FE APPROXIMATION TO BIHARMONIC OPERATOR ON BEAM.',
    author: 'H. Simon',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '957',
    num_cols: '957',
    nonzeros: '4137',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '957',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '1.572826e+11',
    min_singular_value: '3.084227e+01',
    condition_number: '5.099580e+09',
    svd_rank: '957',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'nos2.png,nos2_dmperm.png,nos2_svd.png,nos2_graph.gif,',
}
