{
    matrix_id: '221',
    name: 'nos5',
    group: 'HB',
    description: 'SYMMETRIC MATRIX, FE APPROXIMATION OF BUILDING.',
    author: 'H. Simon',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '468',
    num_cols: '468',
    nonzeros: '5172',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '468',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '5.820291e+05',
    min_singular_value: '5.289948e+01',
    condition_number: '1.100255e+04',
    svd_rank: '468',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'nos5.png,nos5_svd.png,nos5_graph.gif,',
}
