{
    matrix_id: '222',
    name: 'nos6',
    group: 'HB',
    description: 'SYMMETRIC MATRIX, POISSON\'S EQUATION IN L SHAPE, MIXED BC.',
    author: 'H. Simon',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '675',
    num_cols: '675',
    nonzeros: '3255',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '675',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '7.650603e+06',
    min_singular_value: '1.000015e+00',
    condition_number: '7.650487e+06',
    svd_rank: '675',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'nos6.png,nos6_svd.png,nos6_graph.gif,',
}
