{
    matrix_id: '223',
    name: 'nos7',
    group: 'HB',
    description: 'SYMMETRIC MATRIX, POISSON\'S EQUATION IN UNIT CUBE.',
    author: 'H. Simon',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '729',
    num_cols: '729',
    nonzeros: '4617',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '729',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '9.864030e+06',
    min_singular_value: '4.154132e-03',
    condition_number: '2.374510e+09',
    svd_rank: '729',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'nos7.png,nos7_svd.png,nos7_graph.gif,',
}
