{
    matrix_id: '224',
    name: 'orani678',
    group: 'HB',
    description: 'UNSYMMETRIC MATRIX            ORANI678 ST ERTAR             24OCT84',
    author: 'K. Pearson',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1984',
    kind: 'economic problem',
    problem_2D_or_3D: '0',
    num_rows: '2529',
    num_cols: '2529',
    nonzeros: '90158',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '700',
    structural_full_rank: 'true',
    structural_rank: '2529',
    pattern_symmetry: '0.071',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'sparse 2529-by-86
',
    norm: '3.198555e+01',
    min_singular_value: '3.338801e-03',
    condition_number: '9.579953e+03',
    svd_rank: '2529',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'orani678.png,orani678_dmperm.png,orani678_svd.png,orani678_APlusAT_graph.gif,orani678_graph.gif,',
}
