{
    matrix_id: '232',
    name: 'pores_1',
    group: 'HB',
    description: 'UNSYMMETRIC MATRIX FROM  PORES',
    author: 'J. Appleyard',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1980',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '30',
    num_cols: '30',
    nonzeros: '180',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '30',
    pattern_symmetry: '0.627',
    numeric_symmetry: '0.293',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '3.123907e+07',
    min_singular_value: '1.723424e+01',
    condition_number: '1.812616e+06',
    svd_rank: '30',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'pores_1.png,pores_1_svd.png,pores_1_APlusAT_graph.gif,pores_1_graph.gif,',
}
