{
    matrix_id: '233',
    name: 'pores_2',
    group: 'HB',
    description: 'UNSYMMETRIC MATRIX FROM PORES',
    author: 'J. Appleyard',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1980',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '1224',
    num_cols: '1224',
    nonzeros: '9613',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '1224',
    pattern_symmetry: '0.612',
    numeric_symmetry: '0.391',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '6.088947e+07',
    min_singular_value: '5.564281e-01',
    condition_number: '1.094292e+08',
    svd_rank: '1224',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'pores_2.png,pores_2_svd.png,pores_2_APlusAT_graph.gif,pores_2_graph.gif,',
}
