{
    matrix_id: '237',
    name: 'psmigr_3',
    group: 'HB',
    description: 'UNSYMMETRIC MATRIX . INTERCOUNTY MIGRATION . PAUL SLATER CA, NOV 1983',
    author: 'P. Slater',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1983',
    kind: 'economic problem',
    problem_2D_or_3D: '0',
    num_rows: '3140',
    num_cols: '3140',
    nonzeros: '543160',
    num_explicit_zeros: '2',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '3140',
    pattern_symmetry: '0.479',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.000003e+00',
    min_singular_value: '7.524751e-03',
    condition_number: '1.328952e+02',
    svd_rank: '3140',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'psmigr_3.png,psmigr_3_svd.png,psmigr_3_APlusAT_graph.gif,psmigr_3_graph.gif,',
}
