{
    matrix_id: '236',
    name: 'psmigr_2',
    group: 'HB',
    description: 'UNSYMMETRIC MATRIX . INTERCOUNTY MIGRATION . PAUL SLATER CA, NOV 1983',
    author: 'P. Slater',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1983',
    kind: 'economic problem',
    problem_2D_or_3D: '0',
    num_rows: '3140',
    num_cols: '3140',
    nonzeros: '540022',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '3140',
    pattern_symmetry: '0.479',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '9.999998e-01',
    min_singular_value: '5.813007e-05',
    condition_number: '1.720280e+04',
    svd_rank: '3140',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'psmigr_2.png,psmigr_2_svd.png,psmigr_2_APlusAT_graph.gif,psmigr_2_graph.gif,',
}
