{
    matrix_id: '238',
    name: 'rgg010',
    group: 'HB',
    description: 'S EXAMPLE TO DEMONSTRATE THE CHIMNEY EFFECT IN P4 - BY R.G. GRIMES',
    author: 'J. Lewis',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1983',
    kind: 'counter-example problem',
    problem_2D_or_3D: '0',
    num_rows: '10',
    num_cols: '10',
    nonzeros: '76',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '10',
    pattern_symmetry: '0.636',
    numeric_symmetry: '0.636',
    rb_type: 'binary',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '8.197068e+00',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '4',
    sprank_minus_rank: '6',
    null_space_dimension: '6',
    full_numerical_rank: 'no',
    svd_gap: '3347022221632210.500000',
    image_files: 'rgg010.png,rgg010_svd.png,rgg010_APlusAT_graph.gif,rgg010_graph.gif,',
}
