{
    matrix_id: '240',
    name: 'saylr3',
    group: 'HB',
    description: 'UNSYMMETRIC MATRIX OF PAUL SAYLOR - 10 BY 10 BY 10 3D GRID   MAY, 1983',
    author: 'R. Kendall, D. Peaceman, H. Stone, W. Watts',
    editor: 'P. Saylor',
    date: '1984',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '1000',
    num_cols: '1000',
    nonzeros: '3750',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '318',
    num_dmperm_blocks: '318',
    structural_full_rank: 'true',
    structural_rank: '1000',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '5.044869e+00',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '998',
    sprank_minus_rank: '2',
    null_space_dimension: '2',
    full_numerical_rank: 'no',
    svd_gap: '3474100328685.446289',
    image_files: 'saylr3.png,saylr3_dmperm.png,saylr3_svd.png,saylr3_graph.gif,',
}
