{
    matrix_id: '243',
    name: 'sherman2',
    group: 'HB',
    description: 'U THERMAL SIMULATION, STEAM INJECTION,  6 BY  6 BY  5 GRID, FIVE UNK',
    author: 'A. Sherman',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1984',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '1080',
    num_cols: '1080',
    nonzeros: '23094',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '211',
    num_dmperm_blocks: '211',
    structural_full_rank: 'true',
    structural_rank: '1080',
    pattern_symmetry: '0.671',
    numeric_symmetry: '0.005',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 1080-by-1
',
    norm: '2.438417e+09',
    min_singular_value: '2.528606e-03',
    condition_number: '9.643326e+11',
    svd_rank: '1080',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'sherman2.png,sherman2_dmperm.png,sherman2_svd.png,sherman2_APlusAT_graph.gif,sherman2_graph.gif,',
}
