{
    matrix_id: '246',
    name: 'sherman5',
    group: 'HB',
    description: 'U FULLY IMPLICIT BLACK OIL SIMULATOR   16 BY 23 BY  3 GRID, THREE UNK',
    author: 'A. Sherman',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1984',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '3312',
    num_cols: '3312',
    nonzeros: '20793',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1675',
    num_dmperm_blocks: '1675',
    structural_full_rank: 'true',
    structural_rank: '3312',
    pattern_symmetry: '0.739',
    numeric_symmetry: '0.153',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 3312-by-1
',
    norm: '4.547505e+03',
    min_singular_value: '2.419647e-02',
    condition_number: '1.879408e+05',
    svd_rank: '3312',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'sherman5.png,sherman5_dmperm.png,sherman5_svd.png,sherman5_APlusAT_graph.gif,sherman5_graph.gif,',
}
