{
    matrix_id: '245',
    name: 'sherman4',
    group: 'HB',
    description: 'U BLACK OIL, IMPES SIMULATION,         16 BY 23 BY  3 GRID, ONE  UNK',
    author: 'A. Sherman',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1984',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '1104',
    num_cols: '1104',
    nonzeros: '3786',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '559',
    num_dmperm_blocks: '559',
    structural_full_rank: 'true',
    structural_rank: '1104',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 1104-by-1
',
    norm: '6.650889e+01',
    min_singular_value: '3.052784e-02',
    condition_number: '2.178631e+03',
    svd_rank: '1104',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'sherman4.png,sherman4_dmperm.png,sherman4_svd.png,sherman4_graph.gif,',
}
