{
    matrix_id: '249',
    name: 'shl_400',
    group: 'HB',
    description: 'UNSYMMETRIC BASIS FROM LP PROBLEM SHELL',
    author: 'M. Saunders',
    editor: 'A. Curtis, I. Duff, J. Reid',
    date: '1978',
    kind: 'subsequent optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '663',
    num_cols: '663',
    nonzeros: '1712',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '663',
    structural_full_rank: 'true',
    structural_rank: '663',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'integer',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: - first: HB/shl_0
',
    norm: '9.251252e+03',
    min_singular_value: '1.076035e-05',
    condition_number: '8.597537e+08',
    svd_rank: '663',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'shl_400.png,shl_400_dmperm.png,shl_400_scc.png,shl_400_svd.png,shl_400_APlusAT_graph.gif,shl_400_graph.gif,',
}
