{
    matrix_id: '253',
    name: 'steam3',
    group: 'HB',
    description: 'UNSYMMETRIC - 1D STEAM MODEL OF OIL RES. - 20 POINTS - 4 DOF  MAY 1983',
    author: 'R. Grimes',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1983',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '80',
    num_cols: '80',
    nonzeros: '314',
    num_explicit_zeros: '614',
    num_strongly_connected_components: '21',
    num_dmperm_blocks: '21',
    structural_full_rank: 'true',
    structural_rank: '80',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.325',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.738567e+10',
    min_singular_value: '3.481531e-01',
    condition_number: '4.993686e+10',
    svd_rank: '80',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'steam3.png,steam3_dmperm.png,steam3_svd.png,steam3_graph.gif,',
}
