{
    matrix_id: '255',
    name: 'str_200',
    group: 'HB',
    description: 'UNSYMMETRIC BASIS FROM LP PROBLEM STAIR',
    author: 'M. Saunders',
    editor: 'A. Curtis, I. Duff, J. Reid',
    date: '1978',
    kind: 'subsequent optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '363',
    num_cols: '363',
    nonzeros: '3068',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '234',
    structural_full_rank: 'true',
    structural_rank: '363',
    pattern_symmetry: '0.011',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: HB/str_400 first: HB/str_0
',
    norm: '1.207668e+01',
    min_singular_value: '7.994581e-04',
    condition_number: '1.510608e+04',
    svd_rank: '363',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'str_200.png,str_200_dmperm.png,str_200_scc.png,str_200_svd.png,str_200_APlusAT_graph.gif,str_200_graph.gif,',
}
