{
    matrix_id: '257',
    name: 'str_600',
    group: 'HB',
    description: 'UNSYMMETRIC BASIS FROM LP PROBLEM STAIR',
    author: 'M. Saunders',
    editor: 'A. Curtis, I. Duff, J. Reid',
    date: '1978',
    kind: 'subsequent optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '363',
    num_cols: '363',
    nonzeros: '3279',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '142',
    structural_full_rank: 'true',
    structural_rank: '363',
    pattern_symmetry: '0.019',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: - first: HB/str_0
',
    norm: '1.460100e+01',
    min_singular_value: '7.676841e-05',
    condition_number: '1.901954e+05',
    svd_rank: '363',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'str_600.png,str_600_dmperm.png,str_600_scc.png,str_600_svd.png,str_600_APlusAT_graph.gif,str_600_graph.gif,',
}
