{
    matrix_id: '272',
    name: 'west2021',
    group: 'HB',
    description: 'U 15 STAGE COLUMN SECTIONS, ALL SECTIONS RIGOROUS ( CHEM. ENG. )',
    author: 'A. Westerberg',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1983',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '2021',
    num_cols: '2021',
    nonzeros: '7310',
    num_explicit_zeros: '43',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '522',
    structural_full_rank: 'true',
    structural_rank: '2021',
    pattern_symmetry: '0.003',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '3.190857e+05',
    min_singular_value: '2.447674e-07',
    condition_number: '1.303628e+12',
    svd_rank: '2021',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'west2021.png,west2021_dmperm.png,west2021_svd.png,west2021_APlusAT_graph.gif,west2021_graph.gif,',
}
