{
    matrix_id: '262',
    name: 'west0067',
    group: 'HB',
    description: 'U CAVETT PROBLEM WITH 5 COMPONENTS ( CHEM. ENG. FROM WESTERBERG )',
    author: 'A. Westerberg',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1983',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '67',
    num_cols: '67',
    nonzeros: '294',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '67',
    pattern_symmetry: '0.034',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '4.060711e+00',
    min_singular_value: '3.118410e-02',
    condition_number: '1.302174e+02',
    svd_rank: '67',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'west0067.png,west0067_dmperm.png,west0067_svd.png,west0067_APlusAT_graph.gif,west0067_graph.gif,',
}
