{
    matrix_id: '266',
    name: 'west0381',
    group: 'HB',
    description: 'U MULTIPLY FED COLUMN, 24 COMPONENTS ( CHEM. ENG. FROM WESTERBERG )',
    author: 'A. Westerberg',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1983',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '381',
    num_cols: '381',
    nonzeros: '2134',
    num_explicit_zeros: '23',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '6',
    structural_full_rank: 'true',
    structural_rank: '381',
    pattern_symmetry: '0.006',
    numeric_symmetry: '0.001',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.715325e+03',
    min_singular_value: '1.366364e-03',
    condition_number: '1.255394e+06',
    svd_rank: '381',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'west0381.png,west0381_dmperm.png,west0381_svd.png,west0381_APlusAT_graph.gif,west0381_graph.gif,',
}
