{
    matrix_id: '263',
    name: 'west0132',
    group: 'HB',
    description: 'U RIGOROUS FLASH UNIT ( CHEM. ENG. FROM A. WESTERBERG )',
    author: 'A. Westerberg',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1983',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '132',
    num_cols: '132',
    nonzeros: '413',
    num_explicit_zeros: '1',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '56',
    structural_full_rank: 'true',
    structural_rank: '132',
    pattern_symmetry: '0.020',
    numeric_symmetry: '0.005',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '3.201155e+05',
    min_singular_value: '7.610737e-07',
    condition_number: '4.206104e+11',
    svd_rank: '132',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'west0132.png,west0132_dmperm.png,west0132_scc.png,west0132_svd.png,west0132_APlusAT_graph.gif,west0132_graph.gif,',
}
