{
    matrix_id: '276',
    name: 'wm2',
    group: 'HB',
    description: 'U NONSYMMETRIC MATRIX COEFFICIENT MATRIX OF THE WORLD MODEL -SZYLD-IEA-',
    author: 'D. Szyld',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1982',
    kind: 'economic problem',
    problem_2D_or_3D: '0',
    num_rows: '207',
    num_cols: '260',
    nonzeros: '2942',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '4',
    num_dmperm_blocks: '36',
    structural_full_rank: 'true',
    structural_rank: '207',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.865287e+01',
    min_singular_value: '6.703445e-02',
    condition_number: '4.274350e+02',
    svd_rank: '207',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'wm2.png,wm2_dmperm.png,wm2_scc.png,wm2_svd.png,wm2_graph.gif,',
}
