{
    matrix_id: '279',
    name: 'young2c',
    group: 'HB',
    description: 'complex matrix from aero research, David Young, corrected CUA version',
    author: 'D. Young',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1984',
    kind: 'duplicate acoustics problem',
    problem_2D_or_3D: '1',
    num_rows: '841',
    num_cols: '841',
    nonzeros: '4089',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '841',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.848',
    rb_type: 'complex',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'duplicate of HB/young1c
',
    norm: '4.701961e+02',
    min_singular_value: '1.132963e+00',
    condition_number: '4.150145e+02',
    svd_rank: '841',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'young2c.png,young2c_svd.png,young2c_graph.gif,',
}
