{
    matrix_id: '282',
    name: 'zenios',
    group: 'HB',
    description: 'S AIR-TRAFFIC CONTROL MODEL BY STAVROS A. ZENIOS',
    author: 'S. Zenios',
    editor: 'I. Duff, R. Grimes, J. Lewis',
    date: '1985',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '2873',
    num_cols: '2873',
    nonzeros: '1314',
    num_explicit_zeros: '25877',
    num_strongly_connected_components: '2650',
    num_dmperm_blocks: '84',
    structural_full_rank: 'false',
    structural_rank: '266',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '3.337948e+00',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '265',
    sprank_minus_rank: '1',
    null_space_dimension: '2608',
    full_numerical_rank: 'no',
    svd_gap: '5827.885973',
    image_files: 'zenios.png,zenios_dmperm.png,zenios_scc.png,zenios_svd.png,zenios_graph.gif,',
}
