{
    matrix_id: '737',
    name: 'lhr04c',
    group: 'Mallya',
    description: 'Light hydrocarbon recovery, corrected version of LHR04',
    author: 'J. Mallya',
    editor: 'T. Davis',
    date: '1997',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '4101',
    num_cols: '4101',
    nonzeros: '82682',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '31',
    num_dmperm_blocks: '439',
    structural_full_rank: 'true',
    structural_rank: '4101',
    pattern_symmetry: '0.015',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.341478e+01',
    min_singular_value: '3.526477e-12',
    condition_number: '3.804017e+12',
    svd_rank: '4100',
    sprank_minus_rank: '1',
    null_space_dimension: '1',
    full_numerical_rank: 'no',
    svd_gap: '211.300558',
}
