{
    matrix_id: '738',
    name: 'lhr07',
    group: 'Mallya',
    description: 'Light hydrocarbon recovery. OK if illconditioned,from a nonlinear solvr',
    author: 'J. Mallya',
    editor: 'T. Davis',
    date: '1994',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '7337',
    num_cols: '7337',
    nonzeros: '154660',
    num_explicit_zeros: '1848',
    num_strongly_connected_components: '31',
    num_dmperm_blocks: '676',
    structural_full_rank: 'true',
    structural_rank: '7337',
    pattern_symmetry: '0.017',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 7337-by-1
',
    norm: '1.831458e+01',
    min_singular_value: '4.159202e-21',
    condition_number: '4.403387e+21',
    svd_rank: '7315',
    sprank_minus_rank: '22',
    null_space_dimension: '22',
    full_numerical_rank: 'no',
    svd_gap: '6905.455054',
}
