{
    matrix_id: '735',
    name: 'lhr02',
    group: 'Mallya',
    description: 'Light hydrocarbon recovery. OK if illconditioned,from a nonlinear solvr',
    author: 'J. Mallya',
    editor: 'T. Davis',
    date: '1994',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '2954',
    num_cols: '2954',
    nonzeros: '36875',
    num_explicit_zeros: '331',
    num_strongly_connected_components: '42',
    num_dmperm_blocks: '596',
    structural_full_rank: 'true',
    structural_rank: '2954',
    pattern_symmetry: '0.007',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 2954-by-1
',
    norm: '5.970664e+00',
    min_singular_value: '6.125713e-06',
    condition_number: '9.746888e+05',
    svd_rank: '2954',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
