{
    matrix_id: '741',
    name: 'lhr10c',
    group: 'Mallya',
    description: 'Light hydrocarbon recovery, corrected version of LHR10',
    author: 'J. Mallya',
    editor: 'T. Davis',
    date: '1997',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '10672',
    num_cols: '10672',
    nonzeros: '232633',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '31',
    num_dmperm_blocks: '908',
    structural_full_rank: 'true',
    structural_rank: '10672',
    pattern_symmetry: '0.009',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.890660e+01',
    min_singular_value: '2.558172e-13',
    condition_number: '7.390669e+13',
    svd_rank: '10670',
    sprank_minus_rank: '2',
    null_space_dimension: '2',
    full_numerical_rank: 'no',
    svd_gap: '55.004416',
}
