{
    matrix_id: '750',
    name: 'lhr71',
    group: 'Mallya',
    description: 'Light hydrocarbon recovery. OK if illconditioned,from a nonlinear solvr',
    author: 'J. Mallya',
    editor: 'T. Davis',
    date: '1994',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '70304',
    num_cols: '70304',
    nonzeros: '1494006',
    num_explicit_zeros: '34086',
    num_strongly_connected_components: '121',
    num_dmperm_blocks: '15970',
    structural_full_rank: 'true',
    structural_rank: '70304',
    pattern_symmetry: '0.002',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 70304-by-1
',
    image_files: 'lhr71.png,lhr71_dmperm.png,lhr71_scc.png,lhr71_APlusAT_graph.gif,lhr71_graph.gif,',
}
