{
    matrix_id: '1297',
    name: 'boyd2',
    group: 'GHS_indef',
    description: 'Gould, Hu, & Scott: KKT matrix - convex QP (CUTEr)',
    author: 'N. Gould',
    editor: 'N. Gould',
    date: '2004',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '466316',
    num_cols: '466316',
    nonzeros: '1500397',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '466316',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 466316-by-1
',
}
