{
    matrix_id: '1298',
    name: 'brainpc2',
    group: 'GHS_indef',
    description: 'Gould, Hu, & Scott: biological model (CUTEr)',
    author: 'N. Duatrebande',
    editor: 'P. Toint',
    date: '1994',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '27607',
    num_cols: '27607',
    nonzeros: '179395',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '27607',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '4.464852e+03',
    min_singular_value: '1.000000e-01',
    condition_number: '4.464852e+04',
    svd_rank: '27607',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
