{
    matrix_id: '1300',
    name: 'cont-201',
    group: 'GHS_indef',
    description: 'Gould, Hu, & Scott: KKT matrix - convex QP (from Maros & Meszaros)',
    author: 'I. Maros, C. Meszaros',
    editor: 'N. Gould',
    date: '2004',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '80595',
    num_cols: '80595',
    nonzeros: '438795',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '80595',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 80595-by-1
',
}
