{
    matrix_id: '1230',
    name: 'copter2',
    group: 'GHS_indef',
    description: 'ADAPTED CFD GRID FOR HELICOPTER ROTOR BLADE, R. STRAWN NASA AMES',
    author: 'G. Kumfert, A. Pothen',
    editor: 'N. Gould, Y. Hu, J. Scott',
    date: '2004',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '55476',
    num_cols: '55476',
    nonzeros: '759952',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '55476',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
}
