{
    matrix_id: '1237',
    name: 'helm3d01',
    group: 'GHS_indef',
    description: 'Helmholtz eq. on a unit cube:   -div grad u -10000 u = 1, B.C. u = 0',
    author: '',
    editor: 'N. Gould, Y. Hu, J. Scott',
    date: '2004',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '32226',
    num_cols: '32226',
    nonzeros: '428444',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '32226',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '5.052177e-01',
    min_singular_value: '2.060517e-06',
    condition_number: '2.451897e+05',
    svd_rank: '32226',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
