{
    matrix_id: '1238',
    name: 'k1_san',
    group: 'GHS_indef',
    description: 'Aug. system modelling the underground of Straz pod Ralskem mine by MFE',
    author: '',
    editor: 'N. Gould, Y. Hu, J. Scott',
    date: '2004',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '67759',
    num_cols: '67759',
    nonzeros: '559774',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '3',
    structural_full_rank: 'false',
    structural_rank: '67758',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
}
