{
    matrix_id: '1242',
    name: 'ncvxqp1',
    group: 'GHS_indef',
    description: 'Gould, Hu, & Scott: KKT matrix - nonconvex QP (CUTEr)',
    author: 'N. Gould',
    editor: 'N. Gould',
    date: '1994',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '12111',
    num_cols: '12111',
    nonzeros: '73963',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '12111',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '7.580208e+12',
    min_singular_value: '5.229257e-17',
    condition_number: '1.449576e+29',
    svd_rank: '7087',
    sprank_minus_rank: '5024',
    null_space_dimension: '5024',
    full_numerical_rank: 'no',
    svd_gap: '1.744561',
}
