{
    matrix_id: '1244',
    name: 'olesnik0',
    group: 'GHS_indef',
    description: 'Aug. system modelling the underground of Straz pod Ralskem mine by MFE',
    author: '',
    editor: 'N. Gould, Y. Hu, J. Scott',
    date: '2004',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '88263',
    num_cols: '88263',
    nonzeros: '744216',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '3',
    structural_full_rank: 'true',
    structural_rank: '88263',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
}
