{
    matrix_id: '1427',
    name: 'qpband',
    group: 'GHS_indef',
    description: 'QPBAND     augmented system -    20000 rows',
    author: 'N. Gould',
    editor: 'N. Gould',
    date: '1999',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '20000',
    num_cols: '20000',
    nonzeros: '45000',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '5000',
    num_dmperm_blocks: '5000',
    structural_full_rank: 'true',
    structural_rank: '20000',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.769106e+00',
    min_singular_value: '4.302140e-01',
    condition_number: '6.436577e+00',
    svd_rank: '20000',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
