{
    matrix_id: '1249',
    name: 'tuma1',
    group: 'GHS_indef',
    description: 'Gould, Hu, & Scott: mine model from Miroslav Tuma',
    author: 'M. Tuma',
    editor: 'N. Gould, Y. Hu, J. Scott',
    date: '2004',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '22967',
    num_cols: '22967',
    nonzeros: '87760',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1437',
    structural_full_rank: 'true',
    structural_rank: '22967',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '4.891341e+00',
    min_singular_value: '1.595498e-03',
    condition_number: '3.065714e+03',
    svd_rank: '22967',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
