{
    matrix_id: '1892',
    name: 'denormal',
    group: 'Castrillon',
    description: 'denormals in A+alpha*I as alpha > 0 varies, J. Castrillon, Teledyne',
    author: 'J. Castrillon',
    editor: 'T. Davis',
    date: '2008',
    kind: 'counter-example problem',
    problem_2D_or_3D: '0',
    num_rows: '89400',
    num_cols: '89400',
    nonzeros: '1156224',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '89400',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    notes: 'The problem is x=(A+alpha*I)\b as alpha varies from 0 to 100.  However,
as this occurs, performance suffers because of the many denormals that 
appear below the diagonal in L.                                        
',
}
