{
    matrix_id: '287',
    name: 'epb0',
    group: 'Averous',
    description: 'Plate-fin heat exchanger w/ simple model (DAE) David.Averous@ensigct.fr',
    author: 'D. Averous',
    editor: 'T. Davis',
    date: '1998',
    kind: 'thermal problem',
    problem_2D_or_3D: '1',
    num_rows: '1794',
    num_cols: '1794',
    nonzeros: '7764',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '1794',
    pattern_symmetry: '0.501',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '5.741849e-01',
    min_singular_value: '8.948555e-06',
    condition_number: '6.416510e+04',
    svd_rank: '1794',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
