{
    matrix_id: '288',
    name: 'epb1',
    group: 'Averous',
    description: 'Plate-fin heat exchanger (simple case)   (DAE) David.Averous@ensigct.fr',
    author: 'D. Averous',
    editor: 'T. Davis',
    date: '1998',
    kind: 'thermal problem',
    problem_2D_or_3D: '1',
    num_rows: '14734',
    num_cols: '14734',
    nonzeros: '95053',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '14734',
    pattern_symmetry: '0.729',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.082716e-01',
    min_singular_value: '3.505868e-05',
    condition_number: '5.940657e+03',
    svd_rank: '14734',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
