{
    matrix_id: '1643',
    name: 'mixtank_new',
    group: 'POLYFLOW',
    description: 'POLYFLOW mixing tank (new version to avoid underflow)',
    author: 'J. Marchal',
    editor: 'J. Koster',
    date: '2005',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '29957',
    num_cols: '29957',
    nonzeros: '1990919',
    num_explicit_zeros: '4122',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '29957',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.989',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'from Parasol, http://www.parallab.uib.no/projects/parasol/data
',
    b_field: 'full 29957-by-1
',
    norm: '1.822137e+01',
    min_singular_value: '8.350975e-11',
    condition_number: '2.181946e+11',
    svd_rank: '29956',
    sprank_minus_rank: '1',
    null_space_dimension: '1',
    full_numerical_rank: 'no',
    svd_gap: '1.360792',
}
