{
    matrix_id: '1183',
    name: 'coupled',
    group: 'IBM_Austin',
    description: 'IBM Austin, transient simulation, timing path. high coupling',
    author: 'E. Acar',
    editor: 'T. Davis',
    date: '2004',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '11341',
    num_cols: '11341',
    nonzeros: '97193',
    num_explicit_zeros: '1330',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '49',
    structural_full_rank: 'true',
    structural_rank: '11341',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.782',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.015190e+02',
    min_singular_value: '5.452526e-03',
    condition_number: '3.695883e+04',
    svd_rank: '11341',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'coupled.png,coupled_dmperm.png,coupled_svd.png,coupled_graph.gif,',
}
