{
    matrix_id: '1598',
    name: 'conf5_4-8x8-05',
    group: 'QCD',
    description: 'Quantum chromodynamics conf5.4-00l8x8-0500',
    author: 'B. Medeke',
    editor: 'R. Boisvert, R. Pozo, K. Remington, B. Miller, R. Lipman, R. Barrett, J. Dongarra',
    date: '1999',
    kind: 'theoretical/quantum chemistry problem',
    problem_2D_or_3D: '0',
    num_rows: '49152',
    num_cols: '49152',
    nonzeros: '1916928',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '49152',
    pattern_symmetry: '0.923',
    numeric_symmetry: '0.462',
    rb_type: 'complex',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    image_files: 'conf5_4-8x8-05.png,conf5_4-8x8-05_dmperm.png,conf5_4-8x8-05_APlusAT_graph.gif,conf5_4-8x8-05_graph.gif,',
}
