{
    matrix_id: '1408',
    name: 'ted_A_unscaled',
    group: 'Bindel',
    description: 'FEM, coupled linear thermoeslasticity eqns on a bar. D Bindel, UC Berkeley',
    author: 'D. Bindel',
    editor: 'T. Davis',
    date: '2006',
    kind: 'thermal problem',
    problem_2D_or_3D: '1',
    num_rows: '10605',
    num_cols: '10605',
    nonzeros: '424587',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '4244',
    structural_full_rank: 'true',
    structural_rank: '10605',
    pattern_symmetry: '0.566',
    numeric_symmetry: '0.106',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.225147e+12',
    min_singular_value: '2.144320e-05',
    condition_number: '103769334752744272',
    svd_rank: '6363',
    sprank_minus_rank: '4242',
    null_space_dimension: '4242',
    full_numerical_rank: 'no',
    svd_gap: '27.355103',
    image_files: 'ted_A_unscaled.png,ted_A_unscaled_dmperm.png,ted_A_unscaled_svd.png,ted_A_unscaled_APlusAT_graph.gif,ted_A_unscaled_graph.gif,',
}
