{
    matrix_id: '1407',
    name: 'ted_AB',
    group: 'Bindel',
    description: 'FEM, coupled linear thermoeslasticity eqns on a bar. D Bindel, UC Berkeley',
    author: 'D. Bindel',
    editor: 'T. Davis',
    date: '2006',
    kind: 'thermal problem',
    problem_2D_or_3D: '1',
    num_rows: '10605',
    num_cols: '10605',
    nonzeros: '522387',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '10605',
    pattern_symmetry: '0.642',
    numeric_symmetry: '0.000',
    rb_type: 'complex',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    aux_fields: 'w0: full 1-by-1
',    norm: '1.348574e+01',
    min_singular_value: '2.820180e-14',
    condition_number: '4.781872e+14',
    svd_rank: '10604',
    sprank_minus_rank: '1',
    null_space_dimension: '1',
    full_numerical_rank: 'no',
    svd_gap: '72918.545198',
    image_files: 'ted_AB.png,ted_AB_svd.png,ted_AB_unscaled.png,ted_AB_unscaled_svd.png,ted_AB_APlusAT_graph.gif,ted_AB_graph.gif,ted_AB_unscaled_APlusAT_graph.gif,ted_AB_unscaled_graph.gif,',
}
