{
    matrix_id: '1410',
    name: 'ted_AB_unscaled',
    group: 'Bindel',
    description: 'FEM, coupled linear thermoeslasticity eqns on a bar. D Bindel, UC Berkeley',
    author: 'D. Bindel',
    editor: 'T. Davis',
    date: '2006',
    kind: 'thermal problem',
    problem_2D_or_3D: '1',
    num_rows: '10605',
    num_cols: '10605',
    nonzeros: '522387',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '10605',
    pattern_symmetry: '0.642',
    numeric_symmetry: '0.000',
    rb_type: 'complex',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    aux_fields: 'w0: full 1-by-1
',    norm: '2.225147e+12',
    min_singular_value: '2.702800e-09',
    condition_number: '8.232747e+20',
    svd_rank: '6363',
    sprank_minus_rank: '4242',
    null_space_dimension: '4242',
    full_numerical_rank: 'no',
    svd_gap: '27.356765',
    image_files: 'ted_AB_unscaled.png,ted_AB_unscaled_svd.png,ted_AB_unscaled_APlusAT_graph.gif,ted_AB_unscaled_graph.gif,',
}
