{
    matrix_id: '1412',
    name: 'G2_circuit',
    group: 'AMD',
    description: 'circuit simulation problem, Ufuk Okuyucu, AMD, Inc.',
    author: 'U. Okuyucu',
    editor: 'T. Davis',
    date: '2006',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '150102',
    num_cols: '150102',
    nonzeros: '726674',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '150102',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
}
