{
    matrix_id: '537',
    name: 'gupta2',
    group: 'Gupta',
    description: 'Linear programming matrix (A*A\'), Anshul Gupta, anshul@watson.ibm.com',
    author: 'A. Gupta',
    editor: 'T. Davis',
    date: '1996',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '62064',
    num_cols: '62064',
    nonzeros: '4248286',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '62064',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
}
