{
    matrix_id: '536',
    name: 'gupta1',
    group: 'Gupta',
    description: 'Linear programming matrix (A*A\'), Anshul Gupta, anshul@watson.ibm.com',
    author: 'A. Gupta',
    editor: 'T. Davis',
    date: '1996',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '31802',
    num_cols: '31802',
    nonzeros: '2164210',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '31802',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '4.203185e+02',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '30782',
    sprank_minus_rank: '1020',
    null_space_dimension: '1020',
    full_numerical_rank: 'no',
    svd_gap: '3148645.534336',
}
