{
    matrix_id: '2004',
    name: 'HFE18_96_in',
    group: 'JGD_Groebner',
    description: 'Groebner basis from Jean-Charles Fauge`res',
    author: 'J.-C. Faugeres',
    editor: 'J.-G. Dumas',
    date: '2008',
    kind: 'combinatorial problem',
    problem_2D_or_3D: '0',
    num_rows: '2372',
    num_cols: '4096',
    nonzeros: '933343',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1726',
    num_dmperm_blocks: '2',
    structural_full_rank: 'false',
    structural_rank: '2371',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'binary',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Gro"bner basis from Jean-Charles Fauge`res,                 
From Jean-Guillaume Dumas\' Sparse Integer Matrix Collection,
http://ljk.imag.fr/membres/Jean-Guillaume.Dumas/simc.html   
                                                            
http://www-calfor.lip6.fr/~jcf/                             
                                                            
Filename in JGD collection: Grobner/HFE18_96.in.sms         
',
    norm: '5.553063e+02',
    min_singular_value: '9.671243e-15',
    condition_number: '57418297338960616',
    svd_rank: '2371',
    sprank_minus_rank: '0',
    null_space_dimension: '1',
    full_numerical_rank: 'no',
    svd_gap: '43844654883.028305',
}
