{
    matrix_id: '2005',
    name: 'rkat7_mat5',
    group: 'JGD_Groebner',
    description: 'Groebner basis from Jean-Charles Fauge`res',
    author: 'J.-C. Faugeres',
    editor: 'J.-G. Dumas',
    date: '2008',
    kind: 'combinatorial problem',
    problem_2D_or_3D: '0',
    num_rows: '694',
    num_cols: '738',
    nonzeros: '38114',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '694',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'integer',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Gro"bner basis from Jean-Charles Fauge`res,                 
From Jean-Guillaume Dumas\' Sparse Integer Matrix Collection,
http://ljk.imag.fr/membres/Jean-Guillaume.Dumas/simc.html   
                                                            
http://www-calfor.lip6.fr/~jcf/                             
                                                            
Filename in JGD collection: Grobner/rkat7_mat5              
',
    norm: '3.762787e+06',
    min_singular_value: '3.524278e-06',
    condition_number: '1.067676e+12',
    svd_rank: '694',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
