{
    matrix_id: '1400',
    name: 'Chem97Zt',
    group: 'Bates',
    description: 'Mixed-effects model from D. Bates, Univ. Wisc.',
    author: 'D. Bates',
    editor: 'T. Davis',
    date: '2006',
    kind: 'statistical/mathematical problem',
    problem_2D_or_3D: '0',
    num_rows: '2541',
    num_cols: '31022',
    nonzeros: '62044',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '131',
    num_dmperm_blocks: '163',
    structural_full_rank: 'true',
    structural_rank: '2541',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'binary',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '3.142132e+01',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '2410',
    sprank_minus_rank: '131',
    null_space_dimension: '131',
    full_numerical_rank: 'no',
    svd_gap: '55101733731501.734375',
    image_files: 'Chem97Zt.png,Chem97ZtZ.png,Chem97ZtZ_dmperm.png,Chem97ZtZ_svd.png,Chem97Zt_dmperm.png,Chem97Zt_scc.png,Chem97Zt_svd.png,Chem97ZtZ_graph.gif,Chem97Zt_graph.gif,',
}
