{
    matrix_id: '1385',
    name: 'mip1',
    group: 'Andrianov',
    description: 'mip1 matrix from Alexander Andrianov, SAS Institute Inc.',
    author: 'A. Andrianov',
    editor: 'T. Davis',
    date: '2006',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '66463',
    num_cols: '66463',
    nonzeros: '10352819',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '66463',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
}
