{
    matrix_id: '561',
    name: 'g7jac140sc',
    group: 'Hollinger',
    description: 'Jacobian from CEPII\'s \'G7marmotte\' OLG model, oldstack 140 (scaled)',
    author: 'P. Hollinger',
    editor: 'T. Davis',
    date: '2001',
    kind: 'economic problem',
    problem_2D_or_3D: '0',
    num_rows: '41490',
    num_cols: '41490',
    nonzeros: '488633',
    num_explicit_zeros: '77323',
    num_strongly_connected_components: '1017',
    num_dmperm_blocks: '1997',
    structural_full_rank: 'true',
    structural_rank: '41490',
    pattern_symmetry: '0.034',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
}
