{
    matrix_id: '562',
    name: 'g7jac160',
    group: 'Hollinger',
    description: 'Jacobian from CEPII\'s \'G7marmotte\' OLG model, oldstack 160',
    author: 'P. Hollinger',
    editor: 'T. Davis',
    date: '2001',
    kind: 'economic problem',
    problem_2D_or_3D: '0',
    num_rows: '47430',
    num_cols: '47430',
    nonzeros: '564952',
    num_explicit_zeros: '91664',
    num_strongly_connected_components: '1157',
    num_dmperm_blocks: '2277',
    structural_full_rank: 'true',
    structural_rank: '47430',
    pattern_symmetry: '0.033',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
}
