{
    matrix_id: '567',
    name: 'g7jac200sc',
    group: 'Hollinger',
    description: 'Jacobian from CEPII\'s \'G7marmotte\' OLG model, oldstack 200 (scaled)',
    author: 'P. Hollinger',
    editor: 'T. Davis',
    date: '2001',
    kind: 'economic problem',
    problem_2D_or_3D: '0',
    num_rows: '59310',
    num_cols: '59310',
    nonzeros: '717620',
    num_explicit_zeros: '120316',
    num_strongly_connected_components: '1437',
    num_dmperm_blocks: '2837',
    structural_full_rank: 'true',
    structural_rank: '59310',
    pattern_symmetry: '0.032',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
}
