{
    matrix_id: '548',
    name: 'g7jac020sc',
    group: 'Hollinger',
    description: 'Jacobian from CEPII\'s \'G7marmotte\' OLG model, oldstack 020 (scaled)',
    author: 'P. Hollinger',
    editor: 'T. Davis',
    date: '2001',
    kind: 'economic problem',
    problem_2D_or_3D: '0',
    num_rows: '5850',
    num_cols: '5850',
    nonzeros: '42568',
    num_explicit_zeros: '2897',
    num_strongly_connected_components: '177',
    num_dmperm_blocks: '317',
    structural_full_rank: 'true',
    structural_rank: '5850',
    pattern_symmetry: '0.062',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.712691e+04',
    min_singular_value: '6.095966e-09',
    condition_number: '4.449977e+12',
    svd_rank: '5848',
    sprank_minus_rank: '2',
    null_space_dimension: '2',
    full_numerical_rank: 'no',
    svd_gap: '3.071758',
}
