{
    matrix_id: '565',
    name: 'g7jac180sc',
    group: 'Hollinger',
    description: 'Jacobian from CEPII\'s \'G7marmotte\' OLG model, oldstack 180 (scaled)',
    author: 'P. Hollinger',
    editor: 'T. Davis',
    date: '2001',
    kind: 'economic problem',
    problem_2D_or_3D: '0',
    num_rows: '53370',
    num_cols: '53370',
    nonzeros: '641290',
    num_explicit_zeros: '105986',
    num_strongly_connected_components: '1297',
    num_dmperm_blocks: '2557',
    structural_full_rank: 'true',
    structural_rank: '53370',
    pattern_symmetry: '0.033',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
}
