{
    matrix_id: '588',
    name: 'mark3jac100',
    group: 'Hollinger',
    description: 'Jacobian from MULTIMOD Mark3, oldstack 100',
    author: 'P. Hollinger',
    editor: 'T. Davis',
    date: '2001',
    kind: 'economic problem',
    problem_2D_or_3D: '0',
    num_rows: '45769',
    num_cols: '45769',
    nonzeros: '268563',
    num_explicit_zeros: '16652',
    num_strongly_connected_components: '1601',
    num_dmperm_blocks: '1601',
    structural_full_rank: 'true',
    structural_rank: '45769',
    pattern_symmetry: '0.074',
    numeric_symmetry: '0.014',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    image_files: 'mark3jac100.png,mark3jac100_dmperm.png,mark3jac100_scc.png,mark3jac100_APlusAT_graph.gif,mark3jac100_graph.gif,',
}
