{
    matrix_id: '592',
    name: 'mark3jac140',
    group: 'Hollinger',
    description: 'Jacobian from MULTIMOD Mark3, oldstack 140',
    author: 'P. Hollinger',
    editor: 'T. Davis',
    date: '2001',
    kind: 'economic problem',
    problem_2D_or_3D: '0',
    num_rows: '64089',
    num_cols: '64089',
    nonzeros: '376395',
    num_explicit_zeros: '23340',
    num_strongly_connected_components: '2241',
    num_dmperm_blocks: '2241',
    structural_full_rank: 'true',
    structural_rank: '64089',
    pattern_symmetry: '0.074',
    numeric_symmetry: '0.014',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    image_files: 'mark3jac140.png,mark3jac140_dmperm.png,mark3jac140_scc.png,mark3jac140_APlusAT_graph.gif,mark3jac140_graph.gif,',
}
