{
    matrix_id: '591',
    name: 'mark3jac120sc',
    group: 'Hollinger',
    description: 'Jacobian from MULTIMOD Mark3, oldstack 120 (scaled)',
    author: 'P. Hollinger',
    editor: 'T. Davis',
    date: '2001',
    kind: 'economic problem',
    problem_2D_or_3D: '0',
    num_rows: '54929',
    num_cols: '54929',
    nonzeros: '322483',
    num_explicit_zeros: '19992',
    num_strongly_connected_components: '1921',
    num_dmperm_blocks: '1921',
    structural_full_rank: 'true',
    structural_rank: '54929',
    pattern_symmetry: '0.074',
    numeric_symmetry: '0.013',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
}
