{
    matrix_id: '864',
    name: 'comsol',
    group: 'Langemyr',
    description: 'FEM, structural mechanics.  Lars Langemyr, COMSOL. May need pivtol>0.1',
    author: 'L. Langemyr',
    editor: 'T. Davis',
    date: '2002',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '1500',
    num_cols: '1500',
    nonzeros: '97645',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '1500',
    pattern_symmetry: '0.999',
    numeric_symmetry: '0.001',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 1500-by-1
',
    norm: '6.328481e-01',
    min_singular_value: '4.471738e-07',
    condition_number: '1.415217e+06',
    svd_rank: '1500',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
