{
    matrix_id: '1897',
    name: 't2em',
    group: 'CEMW',
    description: 'Electromagnetics problem, David Isaak, Computational_EM_Works',
    author: 'D. Isaak',
    editor: 'T. Davis',
    date: '2008',
    kind: 'electromagnetics problem',
    problem_2D_or_3D: '1',
    num_rows: '921632',
    num_cols: '921632',
    nonzeros: '4590832',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '4333',
    num_dmperm_blocks: '4333',
    structural_full_rank: 'true',
    structural_rank: '921632',
    pattern_symmetry: '0.999',
    numeric_symmetry: '0.999',
    rb_type: 'integer',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    image_files: 't2em.png,t2em_dmperm.png,t2em_APlusAT_graph.gif,t2em_graph.gif,',
}
