{
    matrix_id: '1899',
    name: 'tmt_sym',
    group: 'CEMW',
    description: 'symmetric electromagnetics problem, David Isaak, Computational_EM_Works',
    author: 'D. Isaak',
    editor: 'T. Davis',
    date: '2008',
    kind: 'electromagnetics problem',
    problem_2D_or_3D: '1',
    num_rows: '726713',
    num_cols: '726713',
    nonzeros: '5080961',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '726713',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    image_files: 'tmt_sym.png,tmt_sym_graph.gif,',
}
