{
    matrix_id: '1898',
    name: 'tmt_unsym',
    group: 'CEMW',
    description: 'unsymmetric electromagnetics problem, David Isaak, Computational_EM_Works',
    author: 'D. Isaak',
    editor: 'T. Davis',
    date: '2008',
    kind: 'electromagnetics problem',
    problem_2D_or_3D: '1',
    num_rows: '917825',
    num_cols: '917825',
    nonzeros: '4584801',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '917825',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    image_files: 'tmt_unsym.png,tmt_unsym_graph.gif,',
}
