{
    matrix_id: '1900',
    name: 'vfem',
    group: 'CEMW',
    description: 'Electromagnetics, David Isaak, Computational_EM_Works; vector finite element',
    author: 'D. Isaak',
    editor: 'T. Davis',
    date: '2008',
    kind: 'electromagnetics problem',
    problem_2D_or_3D: '1',
    num_rows: '93476',
    num_cols: '93476',
    nonzeros: '1434636',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '93476',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.821',
    rb_type: 'complex',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    image_files: 'vfem.png,vfem_graph.gif,',
}
