{
    matrix_id: '1360',
    name: 'Si2',
    group: 'PARSEC',
    description: 'Real-space pseudopotential method. Zhou, Saad, Tiago, Chelikowsky, Univ MN',
    author: 'Y. Zhou, Y. Saad, M. Tiago, J. Chelikowsky',
    editor: 'T. Davis',
    date: '2005',
    kind: 'theoretical/quantum chemistry problem',
    problem_2D_or_3D: '0',
    num_rows: '769',
    num_cols: '769',
    nonzeros: '17801',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '769',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '4.138131e+01',
    min_singular_value: '2.422115e-01',
    condition_number: '1.708478e+02',
    svd_rank: '769',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'Si2.png,Si2_svd.png,Si2_graph.gif,',
}
