{
    matrix_id: '1366',
    name: 'SiNa',
    group: 'PARSEC',
    description: 'Real-space pseudopotential method. Zhou, Saad, Tiago, Chelikowsky, Univ MN',
    author: 'Y. Zhou, Y. Saad, M. Tiago, J. Chelikowsky',
    editor: 'T. Davis',
    date: '2005',
    kind: 'theoretical/quantum chemistry problem',
    problem_2D_or_3D: '0',
    num_rows: '5743',
    num_cols: '5743',
    nonzeros: '198787',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '5743',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '2.561590e+01',
    min_singular_value: '5.051282e-02',
    condition_number: '5.071168e+02',
    svd_rank: '5743',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'SiNa.png,SiNa_svd.png,SiNa_graph.gif,',
}
