{
    matrix_id: '1896',
    name: 'circuit204',
    group: 'YZhou',
    description: 'Circuit simulation problem, Y. Zhou, Carleton Univ, Canada',
    author: 'Y. Zhou',
    editor: 'T. Davis',
    date: '2008',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '1020',
    num_cols: '1020',
    nonzeros: '5883',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '114',
    num_dmperm_blocks: '157',
    structural_full_rank: 'true',
    structural_rank: '1020',
    pattern_symmetry: '0.438',
    numeric_symmetry: '0.373',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'block size 204*204
',
    norm: '6.510995e+00',
    min_singular_value: '2.335946e-09',
    condition_number: '2.787305e+09',
    svd_rank: '1020',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'circuit204.png,circuit204_dmperm.png,circuit204_scc.png,circuit204_svd.png,circuit204_APlusAT_graph.gif,circuit204_graph.gif,',
}
