{
    matrix_id: '924',
    name: 'Andrews',
    group: 'Andrews',
    description: 'Eigenvalue problem, Stuart Andrews, Brown Univ. stu@cs.brown.edu',
    author: 'S. Andrews',
    editor: 'T. Davis',
    date: '2003',
    kind: 'computer graphics/vision problem',
    problem_2D_or_3D: '1',
    num_rows: '60000',
    num_cols: '60000',
    nonzeros: '760154',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '60000',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'integer',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    image_files: 'Andrews.png,Andrews_graph.gif,',
}
