{
    matrix_id: '1850',
    name: 'BenElechi1',
    group: 'BenElechi',
    description: 'problem with many sparse right-hand sides, S. Ben Elechi',
    author: 'S. Ben Elechi',
    editor: 'T. Davis',
    date: '2007',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '245874',
    num_cols: '245874',
    nonzeros: '13150496',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '7',
    num_dmperm_blocks: '7',
    structural_full_rank: 'true',
    structural_rank: '245874',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    b_field: 'sparse 245874-by-40543
',
    image_files: 'BenElechi1.png,BenElechi1_dmperm.png,BenElechi1_graph.gif,',
}
