{
    matrix_id: '834',
    name: 'Zhao1',
    group: 'Zhao',
    description: 'Electromagnetic matrix from A. C. Cangellaris and Li Zhao',
    author: 'L. Zhao',
    editor: 'T. Davis',
    date: '2001',
    kind: 'electromagnetics problem',
    problem_2D_or_3D: '1',
    num_rows: '33861',
    num_cols: '33861',
    nonzeros: '166453',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '33861',
    pattern_symmetry: '0.922',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.782773e+00',
    min_singular_value: '9.725694e-03',
    condition_number: '2.861259e+02',
    svd_rank: '33861',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'Zhao1.png,Zhao1_svd.png,Zhao1_APlusAT_graph.gif,Zhao1_graph.gif,',
}
