{
    matrix_id: '803',
    name: '3dtube',
    group: 'Rothberg',
    description: '3-D pressure tube',
    author: 'E. Rothberg',
    editor: 'T. Davis',
    date: '1997',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '45330',
    num_cols: '45330',
    nonzeros: '3213618',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '45330',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
}
