{
    matrix_id: '805',
    name: 'cfd2',
    group: 'Rothberg',
    description: 'CFD, symmetric pressure matrix, from Ed Rothberg, Silicon Graphics, Inc.',
    author: 'E. Rothberg',
    editor: 'T. Davis',
    date: '1997',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '123440',
    num_cols: '123440',
    nonzeros: '3085406',
    num_explicit_zeros: '2492',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '123440',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
}
