{
    matrix_id: '806',
    name: 'gearbox',
    group: 'Rothberg',
    description: 'ZF aircraft flap actuator',
    author: 'E. Rothberg',
    editor: 'T. Davis',
    date: '1997',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '153746',
    num_cols: '153746',
    nonzeros: '9080404',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '6',
    num_dmperm_blocks: '6',
    structural_full_rank: 'true',
    structural_rank: '153746',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
}
