{
    matrix_id: '808',
    name: 'struct4',
    group: 'Rothberg',
    description: 'Finite element matrix, from Ed Rothberg, Silicon Graphics, Inc.',
    author: 'E. Rothberg',
    editor: 'T. Davis',
    date: '1997',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '4350',
    num_cols: '4350',
    nonzeros: '237798',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '4350',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '7.194731e+01',
    min_singular_value: '9.939085e-04',
    condition_number: '7.238826e+04',
    svd_rank: '4350',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
