{
    matrix_id: '807',
    name: 'struct3',
    group: 'Rothberg',
    description: 'Finite element matrix, from Ed Rothberg, Silicon Graphics, Inc.',
    author: 'E. Rothberg',
    editor: 'T. Davis',
    date: '1997',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '53570',
    num_cols: '53570',
    nonzeros: '1173694',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '53570',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
}
