{
    matrix_id: '1202',
    name: 'gyro_k',
    group: 'Oberwolfach',
    description: 'Oberwolfach: butterfly gyro, K matrix',
    author: 'D. Billger',
    editor: 'E. Rudnyi',
    date: '2004',
    kind: 'duplicate model reduction problem',
    problem_2D_or_3D: '1',
    num_rows: '17361',
    num_cols: '17361',
    nonzeros: '1021159',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '17361',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '3.656952e+09',
    min_singular_value: '3.337148e+00',
    condition_number: '1.095832e+09',
    svd_rank: '17361',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'gyro_k.png,gyro_k_svd.png,gyro_k_graph.gif,',
}
