{
    matrix_id: '1442',
    name: 'rail_1357',
    group: 'Oberwolfach',
    description: 'Oberwolfach: heat transfer, steel profile cooling',
    author: 'P. Benner, J. Saak',
    editor: 'E. Rudnyi',
    date: '2002',
    kind: 'model reduction problem',
    problem_2D_or_3D: '1',
    num_rows: '1357',
    num_cols: '1357',
    nonzeros: '8985',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '1357',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Primary matrix in this model reduction problem is the Oberwolfach A matrix
',
    aux_fields: 'E: sparse 1357-by-1357
B: sparse 1357-by-7
C: sparse 6-by-1357
',    norm: '4.800765e-05',
    min_singular_value: '3.610997e-09',
    condition_number: '1.329485e+04',
    svd_rank: '1357',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'rail_1357.png,rail_1357_svd.png,rail_1357_graph.gif,',
}
