{
    matrix_id: '1446',
    name: 'spiral',
    group: 'Oberwolfach',
    description: 'Oberwolfach: spiral inductor PEEC',
    author: 'J. Li, M. Kamon',
    editor: 'E. Rudnyi',
    date: '2006',
    kind: 'model reduction problem',
    problem_2D_or_3D: '1',
    num_rows: '1434',
    num_cols: '1434',
    nonzeros: '18228',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '30',
    num_dmperm_blocks: '30',
    structural_full_rank: 'true',
    structural_rank: '1434',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Primary matrix in this model reduction problem is the Oberwolfach A matrix
',
    aux_fields: 'E: sparse 1434-by-1434
B: sparse 1434-by-1
',    norm: '9.136055e+02',
    min_singular_value: '2.337539e-03',
    condition_number: '3.908407e+05',
    svd_rank: '1434',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'spiral.png,spiral_dmperm.png,spiral_svd.png,spiral_graph.gif,',
}
