{
    matrix_id: '1207',
    name: 't2dal_e',
    group: 'Oberwolfach',
    description: 'Oberwolfach: micropyros thruster, E matrix',
    author: 'E. Rudnyi',
    editor: 'E. Rudnyi',
    date: '2004',
    kind: 'duplicate model reduction problem',
    problem_2D_or_3D: '1',
    num_rows: '4257',
    num_cols: '4257',
    nonzeros: '4257',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '4257',
    num_dmperm_blocks: '4257',
    structural_full_rank: 'true',
    structural_rank: '4257',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '2.072385e-05',
    min_singular_value: '5.502635e-13',
    condition_number: '3.766168e+07',
    svd_rank: '4257',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 't2dal_e.png,t2dal_e_dmperm.png,t2dal_e_svd.png,t2dal_e_graph.gif,',
}
