{
    matrix_id: '1206',
    name: 't2dal_a',
    group: 'Oberwolfach',
    description: 'Oberwolfach: micropyros thruster, A matrix',
    author: 'E. Rudnyi',
    editor: 'E. Rudnyi',
    date: '2004',
    kind: 'duplicate model reduction problem',
    problem_2D_or_3D: '1',
    num_rows: '4257',
    num_cols: '4257',
    nonzeros: '37465',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '4257',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.456427e+02',
    min_singular_value: '7.468304e-15',
    condition_number: '19501447571576876',
    svd_rank: '4256',
    sprank_minus_rank: '1',
    null_space_dimension: '1',
    full_numerical_rank: 'no',
    svd_gap: '49369818.026148',
    image_files: 't2dal_a.png,t2dal_a_svd.png,t2dal_a_graph.gif,',
}
