{
    matrix_id: '1208',
    name: 't3dh_a',
    group: 'Oberwolfach',
    description: 'Oberwolfach: micropyros thruster, A matrix',
    author: 'E. Rudnyi',
    editor: 'E. Rudnyi',
    date: '2004',
    kind: 'duplicate model reduction problem',
    problem_2D_or_3D: '1',
    num_rows: '79171',
    num_cols: '79171',
    nonzeros: '4352105',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '79171',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    image_files: 't3dh_a.png,t3dh_a_graph.gif,',
}
