{
    matrix_id: '1210',
    name: 't3dl_a',
    group: 'Oberwolfach',
    description: 'Oberwolfach: micropyros thruster, A matrix',
    author: 'E. Rudnyi',
    editor: 'E. Rudnyi',
    date: '2004',
    kind: 'duplicate model reduction problem',
    problem_2D_or_3D: '1',
    num_rows: '20360',
    num_cols: '20360',
    nonzeros: '509866',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '20360',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.197710e+00',
    min_singular_value: '1.963587e-15',
    condition_number: '6.099599e+14',
    svd_rank: '20359',
    sprank_minus_rank: '1',
    null_space_dimension: '1',
    full_numerical_rank: 'no',
    svd_gap: '179810846.764243',
    image_files: 't3dl_a.png,t3dl_a_svd.png,t3dl_a_graph.gif,',
}
