{
    matrix_id: '1879',
    name: 'viscorocks',
    group: 'Mancktelow',
    description: 'FEM viscoelastic behavior of rocks, Neil Mancktelow, ETH-Zentrum',
    author: 'N. Mancktelow',
    editor: 'T. Davis',
    date: '2007',
    kind: 'materials problem',
    problem_2D_or_3D: '1',
    num_rows: '37762',
    num_cols: '37762',
    nonzeros: '1133641',
    num_explicit_zeros: '28603',
    num_strongly_connected_components: '773',
    num_dmperm_blocks: '773',
    structural_full_rank: 'true',
    structural_rank: '37762',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.280',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '7.416273e+07',
    min_singular_value: '7.590744e-05',
    condition_number: '9.770153e+11',
    svd_rank: '37752',
    sprank_minus_rank: '10',
    null_space_dimension: '10',
    full_numerical_rank: 'no',
    svd_gap: '1.235428',
}
