{
    matrix_id: '836',
    name: 'extr1',
    group: 'Zitney',
    description: 'Chemical process separation, Steve Zitney, Cray Research',
    author: 'S. Zitney',
    editor: 'T. Davis',
    date: '1997',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '2837',
    num_cols: '2837',
    nonzeros: '10967',
    num_explicit_zeros: '440',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '880',
    structural_full_rank: 'true',
    structural_rank: '2837',
    pattern_symmetry: '0.004',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '7.412999e+05',
    min_singular_value: '2.197020e-07',
    condition_number: '3.374115e+12',
    svd_rank: '2836',
    sprank_minus_rank: '1',
    null_space_dimension: '1',
    full_numerical_rank: 'no',
    svd_gap: '2.726710',
}
