{
    matrix_id: '838',
    name: 'radfr1',
    group: 'Zitney',
    description: 'Chemical process separation, Steve Zitney, Cray Research',
    author: 'S. Zitney',
    editor: 'T. Davis',
    date: '1997',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '1048',
    num_cols: '1048',
    nonzeros: '13299',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '98',
    structural_full_rank: 'true',
    structural_rank: '1048',
    pattern_symmetry: '0.054',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '5.827715e+02',
    min_singular_value: '9.828595e-09',
    condition_number: '5.929347e+10',
    svd_rank: '1048',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
