{
    matrix_id: '840',
    name: 'rdist2',
    group: 'Zitney',
    description: 'Chemical process separation, Steve Zitney, Cray Research',
    author: 'S. Zitney',
    editor: 'T. Davis',
    date: '1992',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '3198',
    num_cols: '3198',
    nonzeros: '56834',
    num_explicit_zeros: '100',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '199',
    structural_full_rank: 'true',
    structural_rank: '3198',
    pattern_symmetry: '0.046',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.195150e+03',
    min_singular_value: '8.737605e-05',
    condition_number: '1.367824e+07',
    svd_rank: '3198',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
