{
    matrix_id: '444',
    name: 'garon1',
    group: 'Garon',
    description: '2D FEM, Navier-Stokes, CFD. Square w/ inlet and outlet on opp. sides',
    author: 'A. Garon',
    editor: 'T. Davis',
    date: '1996',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '3175',
    num_cols: '3175',
    nonzeros: '84723',
    num_explicit_zeros: '4204',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '3175',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.672',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '3.609398e+01',
    min_singular_value: '3.843434e-06',
    condition_number: '9.391076e+06',
    svd_rank: '3175',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
