{
    matrix_id: '1399',
    name: 'laminar_duct3D',
    group: 'Raju',
    description: '3D laminar flow in a duct, mesh 50x30x10. M. Raju, Case W. Univ.',
    author: 'M. Raju',
    editor: 'T. Davis',
    date: '2006',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '67173',
    num_cols: '67173',
    nonzeros: '3788857',
    num_explicit_zeros: '44220',
    num_strongly_connected_components: '13025',
    num_dmperm_blocks: '13025',
    structural_full_rank: 'true',
    structural_rank: '67173',
    pattern_symmetry: '0.902',
    numeric_symmetry: '0.552',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 67173-by-1
',
}
