{
    matrix_id: '1402',
    name: 'thermal1',
    group: 'Schmid',
    description: 'unstructured FEM, steady state thermal problem. Dani Schmid, Univ. Oslo',
    author: 'D. Schmid',
    editor: 'T. Davis',
    date: '2006',
    kind: 'thermal problem',
    problem_2D_or_3D: '1',
    num_rows: '82654',
    num_cols: '82654',
    nonzeros: '574458',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '249',
    num_dmperm_blocks: '249',
    structural_full_rank: 'true',
    structural_rank: '82654',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    b_field: 'full 82654-by-1
',
    image_files: 'thermal1.png,thermal1_dmperm.png,thermal1_graph.gif,',
}
