{
    matrix_id: '756',
    name: 'barth5',
    group: 'Nasa',
    description: 'BARTH5: Nasa matrix, but with a diagonal added to the original matrix',
    author: 'NASA',
    editor: 'G. Kumfert, A. Pothen',
    date: '1995',
    kind: 'duplicate structural problem',
    problem_2D_or_3D: '1',
    num_rows: '15606',
    num_cols: '15606',
    nonzeros: '61484',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1155',
    num_dmperm_blocks: '1155',
    structural_full_rank: 'true',
    structural_rank: '15606',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'binary',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Let A=Nasa/barth5, then Pothen/barth5 = spones(A+A\') with xyz coord.
',
    norm: '4.227673e+00',
    min_singular_value: '7.224696e-11',
    condition_number: '5.851696e+10',
    svd_rank: '15606',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
