{
    matrix_id: '754',
    name: 'barth',
    group: 'Nasa',
    description: 'BARTH: Nasa matrix, but with a diagonal added to the original',
    author: 'NASA',
    editor: 'G. Kumfert, A. Pothen',
    date: '1995',
    kind: 'duplicate structural problem',
    problem_2D_or_3D: '1',
    num_rows: '6691',
    num_cols: '6691',
    nonzeros: '26439',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '981',
    num_dmperm_blocks: '981',
    structural_full_rank: 'true',
    structural_rank: '6691',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'binary',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Let A=Nasa/barth, then Pothen/barth = spones(A+A\') with xyz coord.
',
    norm: '4.892839e+00',
    min_singular_value: '6.715379e-17',
    condition_number: '72860211591892704',
    svd_rank: '6690',
    sprank_minus_rank: '1',
    null_space_dimension: '1',
    full_numerical_rank: 'no',
    svd_gap: '88041979283.592499',
    image_files: 'barth.png,barth_dmperm.png,barth_svd.png,barth_APlusAT_graph.gif,barth_graph.gif,',
}
