{
    matrix_id: '758',
    name: 'nasa2146',
    group: 'Nasa',
    description: 'STRUCTURE FROM NASA LANGLEY, 2146 DEGREES OF FREEDOM',
    author: 'NASA',
    editor: 'G. Kumfert, A. Pothen',
    date: '1995',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '2146',
    num_cols: '2146',
    nonzeros: '72250',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '2146',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    b_field: 'full 2146-by-1
',
    norm: '3.272816e+07',
    min_singular_value: '1.898015e+04',
    condition_number: '1.724336e+03',
    svd_rank: '2146',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
