{
    matrix_id: '757',
    name: 'nasa1824',
    group: 'Nasa',
    description: 'STRUCTURE FROM NASA LANGLEY, 1824 DEGREES OF FREEDOM',
    author: 'NASA',
    editor: 'G. Kumfert, A. Pothen',
    date: '1995',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '1824',
    num_cols: '1824',
    nonzeros: '39208',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '1824',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    b_field: 'full 1824-by-1
',
    norm: '2.121717e+07',
    min_singular_value: '1.119058e+01',
    condition_number: '1.895985e+06',
    svd_rank: '1824',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
