{
    matrix_id: '761',
    name: 'nasasrb',
    group: 'Nasa',
    description: 'STRUCTURE FROM NASA LANGLEY, SHUTTLE ROCKET BOOSTER',
    author: 'NASA',
    editor: 'G. Kumfert, A. Pothen',
    date: '1995',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '54870',
    num_cols: '54870',
    nonzeros: '2677324',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '54870',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    b_field: 'full 54870-by-1
',
}
