{
    matrix_id: '760',
    name: 'nasa4704',
    group: 'Nasa',
    description: 'STRUCTURE FROM NASA LANGLEY, 4704 DEGREES OF FREEDOM',
    author: 'NASA',
    editor: 'G. Kumfert, A. Pothen',
    date: '1995',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '4704',
    num_cols: '4704',
    nonzeros: '104756',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '4704',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    b_field: 'full 4704-by-1
',
    norm: '2.066909e+08',
    min_singular_value: '4.961295e+00',
    condition_number: '4.166067e+07',
    svd_rank: '4704',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
