{
    matrix_id: '764',
    name: 'skirt',
    group: 'Nasa',
    description: 'SKIRT: Nasa matrix, but with a diagonal added to the original matrix',
    author: 'NASA',
    editor: 'G. Kumfert, A. Pothen',
    date: '1995',
    kind: 'duplicate structural problem',
    problem_2D_or_3D: '1',
    num_rows: '12598',
    num_cols: '12598',
    nonzeros: '196520',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '7',
    num_dmperm_blocks: '7',
    structural_full_rank: 'true',
    structural_rank: '12598',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    notes: 'Identical to Pothen/skirt; the latter has xyz coordinates.
',
    norm: '2.331372e+01',
    min_singular_value: '1.884828e-33',
    condition_number: '1.236915e+34',
    svd_rank: '9831',
    sprank_minus_rank: '2767',
    null_space_dimension: '2767',
    full_numerical_rank: 'no',
    svd_gap: '1454523016.246378',
}
