{
    matrix_id: '1885',
    name: 'Maragal_2',
    group: 'NYPA',
    description: 'Rank deficient least squares problem, D. Maragal, NY Power Authority',
    author: 'D. Maragal',
    editor: 'T. Davis',
    date: '2008',
    kind: 'least squares problem',
    problem_2D_or_3D: '0',
    num_rows: '555',
    num_cols: '350',
    nonzeros: '4357',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '110',
    num_dmperm_blocks: '13',
    structural_full_rank: 'false',
    structural_rank: '220',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'rank deficient (rank(A) < sprank(A) < size(A,2))
rank: 171 sprank: 220 columns: 350              
',
    b_field: 'full 555-by-1
',
    norm: '1.029508e+01',
    min_singular_value: '3.599600e-47',
    condition_number: '2.860063e+47',
    svd_rank: '171',
    sprank_minus_rank: '49',
    null_space_dimension: '179',
    full_numerical_rank: 'no',
    svd_gap: '11870880364289.941406',
}
