{
    matrix_id: '1887',
    name: 'Maragal_4',
    group: 'NYPA',
    description: 'Rank deficient least squares problem, D. Maragal, NY Power Authority',
    author: 'D. Maragal',
    editor: 'T. Davis',
    date: '2008',
    kind: 'least squares problem',
    problem_2D_or_3D: '0',
    num_rows: '1964',
    num_cols: '1034',
    nonzeros: '26719',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '8',
    num_dmperm_blocks: '23',
    structural_full_rank: 'false',
    structural_rank: '995',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'rank deficient (rank(A) < sprank(A) < size(A,2))
rank: 801 sprank: 995 columns: 1034             
',
    b_field: 'full 1964-by-1
',
    norm: '9.488473e+00',
    min_singular_value: '1.549781e-33',
    condition_number: '6.122459e+33',
    svd_rank: '801',
    sprank_minus_rank: '194',
    null_space_dimension: '233',
    full_numerical_rank: 'no',
    svd_gap: '293026424.415151',
}
