{
    matrix_id: '1347',
    name: 'bundle1',
    group: 'Lourakis',
    description: 'Sparse bundle adjustment, 3D vision, M. Lourakis, Greece',
    author: 'M. Lourakis',
    editor: 'T. Davis',
    date: '2006',
    kind: 'computer graphics/vision problem',
    problem_2D_or_3D: '1',
    num_rows: '10581',
    num_cols: '10581',
    nonzeros: '770811',
    num_explicit_zeros: '90',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '10581',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '6.428996e+12',
    min_singular_value: '6.401863e+09',
    condition_number: '1.004238e+03',
    svd_rank: '10581',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
