{
    matrix_id: '811',
    name: 'appu',
    group: 'Simon',
    description: 'RANDOM SPARSE MATRIX USED IN THE APP BENCHMARK, NASA AMES RESEARCH CENTE',
    author: 'H. Simon',
    editor: 'H. Simon',
    date: '1993',
    kind: 'directed weighted random graph',
    problem_2D_or_3D: '0',
    num_rows: '14000',
    num_cols: '14000',
    nonzeros: '1853104',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.943',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.713065e+01',
    min_singular_value: '1.000002e-01',
    condition_number: '1.713062e+02',
    svd_rank: '14000',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'appu.png,appu_svd.png,appu_graph.gif,',
}
