{
    matrix_id: '818',
    name: 'raefsky5',
    group: 'Simon',
    description: 'LANDING HYDROFOIL AIRPLANE FSE MODEL, ARTHUR RAEFSKY, CENTRIC ENG.',
    author: 'A. Raefsky',
    editor: 'H. Simon',
    date: '1993',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '6316',
    num_cols: '6316',
    nonzeros: '167178',
    num_explicit_zeros: '1480',
    num_strongly_connected_components: '6316',
    num_dmperm_blocks: '6316',
    structural_full_rank: 'true',
    structural_rank: '6316',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 6316-by-1
',
    norm: '2.024942e+11',
    min_singular_value: '5.229809e-04',
    condition_number: '3.871924e+14',
    svd_rank: '1801',
    sprank_minus_rank: '4515',
    null_space_dimension: '4515',
    full_numerical_rank: 'no',
    svd_gap: '1.007809',
    image_files: 'raefsky5.png,raefsky5_dmperm.png,raefsky5_svd.png,raefsky5_APlusAT_graph.gif,raefsky5_graph.gif,',
}
