{
    matrix_id: '814',
    name: 'raefsky1',
    group: 'Simon',
    description: 'INCOMPRESSIBLE FLOW IN PRESSURE DRIVEN PIPE, T=05, A. RAEFSKY, CENTRIC',
    author: 'A. Raefsky',
    editor: 'H. Simon',
    date: '1993',
    kind: 'computational fluid dynamics problem sequence',
    problem_2D_or_3D: '1',
    num_rows: '3242',
    num_cols: '3242',
    nonzeros: '293409',
    num_explicit_zeros: '867',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '3242',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.090',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: Simon/raefsky2 first: Simon/raefsky1
',
    b_field: 'full 3242-by-1
',
    norm: '3.709513e+00',
    min_singular_value: '2.878919e-04',
    condition_number: '1.288509e+04',
    svd_rank: '3242',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'raefsky1.png,raefsky1_svd.png,raefsky1_graph.gif,',
}
