{
    matrix_id: '815',
    name: 'raefsky2',
    group: 'Simon',
    description: 'INCOMPRESSIBLE FLOW IN PRESSURE DRIVEN PIPE, T=25, A. RAEFSKY, CENTRIC',
    author: 'A. Raefsky',
    editor: 'H. Simon',
    date: '1993',
    kind: 'subsequent computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '3242',
    num_cols: '3242',
    nonzeros: '293551',
    num_explicit_zeros: '725',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '3242',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.098',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: - first: Simon/raefsky1
',
    b_field: 'full 3242-by-1
',
    norm: '3.724811e+00',
    min_singular_value: '8.760269e-04',
    condition_number: '4.251937e+03',
    svd_rank: '3242',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'raefsky2.png,raefsky2_svd.png,raefsky2_graph.gif,',
}
