{
    matrix_id: '816',
    name: 'raefsky3',
    group: 'Simon',
    description: 'FLUID STRUCTURE INTERACTION TURBULENCE PROBLEM BY  A. RAEFSKY, CENTRIC',
    author: 'A. Raefsky',
    editor: 'H. Simon',
    date: '1993',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '21200',
    num_cols: '21200',
    nonzeros: '1488768',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '21200',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.476',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 21200-by-1
',
    norm: '7.988064e+00',
    min_singular_value: '4.033028e-11',
    condition_number: '1.980662e+11',
    svd_rank: '21200',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'raefsky3.png,raefsky3_svd.png,raefsky3_graph.gif,',
}
