{
    matrix_id: '821',
    name: 'venkat25',
    group: 'Simon',
    description: 'UNSTRUCTURED 2D EULER SOLVER, V. VENKATAKRISHNAN NASA,   TIME STEP = 25',
    author: 'V. Venkatakrishnan',
    editor: 'H. Simon',
    date: '1993',
    kind: 'subsequent computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '62424',
    num_cols: '62424',
    nonzeros: '1717763',
    num_explicit_zeros: '29',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '62424',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.055',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: Simon/venkat50 first: Simon/venkat01
',
    b_field: 'full 62424-by-1
',
    image_files: 'venkat25.png,venkat25_graph.gif,',
}
