{
    matrix_id: '1581',
    name: 'af_1_k101',
    group: 'Schenk_AFE',
    description: 'AutoForm Eng, Zurich. pos. def. sheet metal forming',
    author: 'AutoForm Eng.',
    editor: 'O. Schenk',
    date: '2006',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '503625',
    num_cols: '503625',
    nonzeros: '17550675',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '503625',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    b_field: 'full 503625-by-1
',
}
