{
    matrix_id: '1586',
    name: 'af_shell10',
    group: 'Schenk_AFE',
    description: 'AutoForm Eng., Zurich. indefinite. sheet metal forming',
    author: 'AutoForm Eng.',
    editor: 'O. Schenk',
    date: '2006',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '1508065',
    num_cols: '1508065',
    nonzeros: '52259885',
    num_explicit_zeros: '412440',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '1508065',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
}
