{
    matrix_id: '948',
    name: 'af_shell9',
    group: 'Schenk_AFE',
    description: 'Olaf Schenk, Univ. Basel: AutoForm Eng. GmbH, Zurich. sheet metal forming. indefinite',
    author: 'AutoForm Eng.',
    editor: 'O. Schenk',
    date: '2003',
    kind: 'subsequent structural problem',
    problem_2D_or_3D: '1',
    num_rows: '504855',
    num_cols: '504855',
    nonzeros: '17588845',
    num_explicit_zeros: '30',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '504855',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    notes: 'next: - first: Schenk_AFE/af_shell1
',
    b_field: 'full 504855-by-1
',
}
