{
    matrix_id: '832',
    name: 'wang3',
    group: 'Wang',
    description: 'Discretized electron continuity, 3d diode, uniform 30-30-30 mesh',
    author: 'S. Wang',
    editor: 'T. Davis',
    date: '1994',
    kind: 'semiconductor device problem',
    problem_2D_or_3D: '1',
    num_rows: '26064',
    num_cols: '26064',
    nonzeros: '177168',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '26064',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.978',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 26064-by-1
',
    norm: '2.680075e-01',
    min_singular_value: '4.331000e-05',
    condition_number: '6.188121e+03',
    svd_rank: '26064',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
