{
    matrix_id: '1881',
    name: 'Rucci1',
    group: 'Rucci',
    description: 'ill-conditioned least-squares problem, A. Rucci',
    author: 'A. Rucci',
    editor: 'T. Davis',
    date: '2007',
    kind: 'least squares problem',
    problem_2D_or_3D: '0',
    num_rows: '1977885',
    num_cols: '109900',
    nonzeros: '7791168',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '109900',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
}
