{
    matrix_id: '963',
    name: 'barrier2-12',
    group: 'Schenk_ISEI',
    description: 'Olaf Schenk, Univ. Basel: Integrated Systems Eng., San Jose, semiconductor device',
    author: 'Integrated Sys. Eng.',
    editor: 'O. Schenk',
    date: '2003',
    kind: 'subsequent semiconductor device problem',
    problem_2D_or_3D: '1',
    num_rows: '115625',
    num_cols: '115625',
    nonzeros: '2158759',
    num_explicit_zeros: '1738798',
    num_strongly_connected_components: '436',
    num_dmperm_blocks: '436',
    structural_full_rank: 'true',
    structural_rank: '115625',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.198',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: - first: Schenk_ISEI/barrier2-9
',
    b_field: 'full 115625-by-1
',
}
