{
    matrix_id: '969',
    name: 'igbt3',
    group: 'Schenk_ISEI',
    description: 'Olaf Schenk, Univ. Basel: Integrated Systems Eng., San Jose, semiconductor device',
    author: 'Integrated Sys. Eng.',
    editor: 'O. Schenk',
    date: '2003',
    kind: 'semiconductor device problem',
    problem_2D_or_3D: '1',
    num_rows: '10938',
    num_cols: '10938',
    nonzeros: '130500',
    num_explicit_zeros: '103506',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '10938',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.172',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 10938-by-1
',
    norm: '1.203859e+12',
    min_singular_value: '2.893540e-08',
    condition_number: '4.160506e+19',
    svd_rank: '7592',
    sprank_minus_rank: '3346',
    null_space_dimension: '3346',
    full_numerical_rank: 'no',
    svd_gap: '1.003477',
}
