{
    matrix_id: '977',
    name: 'para-8',
    group: 'Schenk_ISEI',
    description: 'Olaf Schenk, Univ. Basel: Integrated Systems Eng., San Jose, semiconductor device',
    author: 'Integrated Sys. Eng.',
    editor: 'O. Schenk',
    date: '2003',
    kind: 'subsequent semiconductor device problem',
    problem_2D_or_3D: '1',
    num_rows: '155924',
    num_cols: '155924',
    nonzeros: '2094873',
    num_explicit_zeros: '3321485',
    num_strongly_connected_components: '565',
    num_dmperm_blocks: '565',
    structural_full_rank: 'true',
    structural_rank: '155924',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.178',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: Schenk_ISEI/para-9 first: Schenk_ISEI/para-5
',
    b_field: 'full 155924-by-1
',
}
