{
    matrix_id: '973',
    name: 'para-4',
    group: 'Schenk_ISEI',
    description: 'Olaf Schenk, Univ. Basel: Integrated Systems Eng., San Jose, semiconductor device',
    author: 'Integrated Sys. Eng.',
    editor: 'O. Schenk',
    date: '2003',
    kind: 'semiconductor device problem',
    problem_2D_or_3D: '1',
    num_rows: '153226',
    num_cols: '153226',
    nonzeros: '2930882',
    num_explicit_zeros: '2395346',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '153226',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.290',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 153226-by-1
',
}
