{
    matrix_id: '1265',
    name: 'halfb',
    group: 'DNVS',
    description: 'Gould, Hu, & Scott: half-breadth barge from Christian Damhaug',
    author: 'C. Damhaug',
    editor: 'N. Gould, Y. Hu, J. Scott',
    date: '2004',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '224617',
    num_cols: '224617',
    nonzeros: '12387821',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '224617',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    image_files: 'halfb.png,halfb_graph.gif,',
}
