{
    matrix_id: '1280',
    name: 'shipsec5',
    group: 'DNVS',
    description: 'DNV-PARASOL Ship section 5-1999-01-15',
    author: 'C. Damhaug',
    editor: 'J. Koster',
    date: '1999',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '179860',
    num_cols: '179860',
    nonzeros: '4598604',
    num_explicit_zeros: '5514492',
    num_strongly_connected_components: '36',
    num_dmperm_blocks: '36',
    structural_full_rank: 'true',
    structural_rank: '179860',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    image_files: 'shipsec5.png,shipsec5_dmperm.png,shipsec5_graph.gif,',
}
