{
    matrix_id: '1278',
    name: 'ship_003',
    group: 'DNVS',
    description: 'DNV-Ex 3 : Ship structure from production run-1999-01-17',
    author: 'C. Damhaug',
    editor: 'J. Koster',
    date: '1999',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '121728',
    num_cols: '121728',
    nonzeros: '3777036',
    num_explicit_zeros: '4308998',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '121728',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    image_files: 'ship_003.png,ship_003_graph.gif,',
}
