{
    matrix_id: '1279',
    name: 'shipsec1',
    group: 'DNVS',
    description: 'DNV-Ex 4 : Ship section/detail from production run-1999-01-17',
    author: 'C. Damhaug',
    editor: 'J. Koster',
    date: '1999',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '140874',
    num_cols: '140874',
    nonzeros: '3568176',
    num_explicit_zeros: '4245228',
    num_strongly_connected_components: '3',
    num_dmperm_blocks: '3',
    structural_full_rank: 'true',
    structural_rank: '140874',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    image_files: 'shipsec1.png,shipsec1_dmperm.png,shipsec1_graph.gif,',
}
