{
    matrix_id: '1284',
    name: 'trdheim',
    group: 'DNVS',
    description: 'Matrix Representation of TRDHEIM, Mesh of the Trondheim Fjord',
    author: 'C. Damhaug',
    editor: 'N. Gould, Y. Hu, J. Scott',
    date: '2004',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '22098',
    num_cols: '22098',
    nonzeros: '1935324',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '22098',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '1.046293e+02',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '2819',
    sprank_minus_rank: '19279',
    null_space_dimension: '19279',
    full_numerical_rank: 'no',
    svd_gap: '497409589756.771362',
    image_files: 'trdheim.png,trdheim_svd.png,trdheim_graph.gif,',
}
