{
    matrix_id: '1286',
    name: 'tsyl201',
    group: 'DNVS',
    description: 'Matrix Representation of TSYL201, part of condeep cylinder',
    author: 'C. Damhaug',
    editor: 'N. Gould, Y. Hu, J. Scott',
    date: '2004',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '20685',
    num_cols: '20685',
    nonzeros: '2454957',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '20685',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '1.262268e+02',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '2866',
    sprank_minus_rank: '17819',
    null_space_dimension: '17819',
    full_numerical_rank: 'no',
    svd_gap: '71287286738.227509',
    image_files: 'tsyl201.png,tsyl201_svd.png,tsyl201_graph.gif,',
}
