{
    matrix_id: '473',
    name: 'G13',
    group: 'Gset',
    description: '2D torus, 32-by-25, uniformly random +1/-1 entries',
    author: 'C. Helmberg',
    editor: 'Y. Ye',
    date: '1996',
    kind: 'undirected weighted random graph',
    problem_2D_or_3D: '0',
    num_rows: '800',
    num_cols: '800',
    nonzeros: '3200',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'integer',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '3.555232e+00',
    min_singular_value: '5.107353e-04',
    condition_number: '6.961008e+03',
    svd_rank: '800',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'G13.png,G13_svd.png,G13_graph.gif,',
}
