{
    matrix_id: '475',
    name: 'G15',
    group: 'Gset',
    description: 'Random matrix, nodes 1..n descreasing average degree.G15=pattern of G19',
    author: 'C. Helmberg',
    editor: 'Y. Ye',
    date: '1996',
    kind: 'duplicate undirected random graph',
    problem_2D_or_3D: '0',
    num_rows: '800',
    num_cols: '800',
    nonzeros: '9322',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'This matrix is the nonzero pattern of Gset/G19
',
    norm: '2.315137e+01',
    min_singular_value: '2.276305e-05',
    condition_number: '1.017059e+06',
    svd_rank: '800',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'G15.png,G15_svd.png,G15_graph.gif,',
}
