{
    matrix_id: '476',
    name: 'G16',
    group: 'Gset',
    description: 'Random matrix, nodes 1..n descreasing average degree.G16=pattern of G20',
    author: 'C. Helmberg',
    editor: 'Y. Ye',
    date: '1996',
    kind: 'duplicate undirected random graph',
    problem_2D_or_3D: '0',
    num_rows: '800',
    num_cols: '800',
    nonzeros: '9344',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'This matrix is the nonzero pattern of Gset/G20
',
    norm: '2.262275e+01',
    min_singular_value: '1.742504e-03',
    condition_number: '1.298290e+04',
    svd_rank: '800',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'G16.png,G16_svd.png,G16_graph.gif,',
}
