{
    matrix_id: '485',
    name: 'G24',
    group: 'Gset',
    description: 'Random matrix, 1% uniformly distributed. G24=pattern of G29',
    author: 'C. Helmberg',
    editor: 'Y. Ye',
    date: '1996',
    kind: 'undirected random graph',
    problem_2D_or_3D: '0',
    num_rows: '2000',
    num_cols: '2000',
    nonzeros: '39980',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.107455e+01',
    min_singular_value: '1.812114e-03',
    condition_number: '1.162982e+04',
    svd_rank: '2000',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'G24.png,G24_svd.png,G24_graph.gif,',
}
