{
    matrix_id: '487',
    name: 'G26',
    group: 'Gset',
    description: 'Random matrix, 1% uniformly distributed. G26=pattern of G31',
    author: 'C. Helmberg',
    editor: 'Y. Ye',
    date: '1996',
    kind: 'undirected random graph',
    problem_2D_or_3D: '0',
    num_rows: '2000',
    num_cols: '2000',
    nonzeros: '39980',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.109297e+01',
    min_singular_value: '1.561476e-03',
    condition_number: '1.350835e+04',
    svd_rank: '2000',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'G26.png,G26_svd.png,G26_graph.gif,',
}
