{
    matrix_id: '488',
    name: 'G27',
    group: 'Gset',
    description: 'Random matrix, 1% uniformly distributed. G22=pattern of G27',
    author: 'C. Helmberg',
    editor: 'Y. Ye',
    date: '1996',
    kind: 'undirected weighted random graph',
    problem_2D_or_3D: '0',
    num_rows: '2000',
    num_cols: '2000',
    nonzeros: '39980',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'integer',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '9.171899e+00',
    min_singular_value: '1.391804e-03',
    condition_number: '6.589938e+03',
    svd_rank: '2000',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'G27.png,G27_svd.png,G27_graph.gif,',
}
