{
    matrix_id: '492',
    name: 'G30',
    group: 'Gset',
    description: 'Random matrix, 1% uniformly distributed. G25=pattern of G30',
    author: 'C. Helmberg',
    editor: 'Y. Ye',
    date: '1996',
    kind: 'undirected weighted random graph',
    problem_2D_or_3D: '0',
    num_rows: '2000',
    num_cols: '2000',
    nonzeros: '39980',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'integer',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '9.239506e+00',
    min_singular_value: '3.177471e-03',
    condition_number: '2.907818e+03',
    svd_rank: '2000',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'G30.png,G30_svd.png,G30_graph.gif,',
}
