{
    matrix_id: '493',
    name: 'G31',
    group: 'Gset',
    description: 'Random matrix, 1% uniformly distributed. G26=pattern of G31',
    author: 'C. Helmberg',
    editor: 'Y. Ye',
    date: '1996',
    kind: 'undirected weighted random graph',
    problem_2D_or_3D: '0',
    num_rows: '2000',
    num_cols: '2000',
    nonzeros: '39980',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'integer',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '9.244205e+00',
    min_singular_value: '3.667579e-03',
    condition_number: '2.520520e+03',
    svd_rank: '2000',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'G31.png,G31_svd.png,G31_graph.gif,',
}
