{
    matrix_id: '494',
    name: 'G32',
    group: 'Gset',
    description: '2D torus, 20-by-100, uniformly random +1/-1 entries',
    author: 'C. Helmberg',
    editor: 'Y. Ye',
    date: '1996',
    kind: 'undirected weighted random graph',
    problem_2D_or_3D: '0',
    num_rows: '2000',
    num_cols: '2000',
    nonzeros: '8000',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'integer',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '3.480552e+00',
    min_singular_value: '1.985459e-03',
    condition_number: '1.753021e+03',
    svd_rank: '2000',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'G32.png,G32_svd.png,G32_graph.gif,',
}
