{
    matrix_id: '497',
    name: 'G35',
    group: 'Gset',
    description: 'Random matrix, nodes 1..n descreasing average degree.G35=pattern of G39',
    author: 'C. Helmberg',
    editor: 'Y. Ye',
    date: '1996',
    kind: 'duplicate undirected random graph',
    problem_2D_or_3D: '0',
    num_rows: '2000',
    num_cols: '2000',
    nonzeros: '23556',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'This matrix is the nonzero pattern of Gset/G39
',
    norm: '2.691121e+01',
    min_singular_value: '2.725243e-03',
    condition_number: '9.874795e+03',
    svd_rank: '2000',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'G35.png,G35_svd.png,G35_graph.gif,',
}
