{
    matrix_id: '499',
    name: 'G37',
    group: 'Gset',
    description: 'Random matrix, nodes 1..n descreasing average degree.G37=pattern of G41',
    author: 'C. Helmberg',
    editor: 'Y. Ye',
    date: '1996',
    kind: 'duplicate undirected random graph',
    problem_2D_or_3D: '0',
    num_rows: '2000',
    num_cols: '2000',
    nonzeros: '23570',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'This matrix is the nonzero pattern of Gset/G41
',
    norm: '2.714653e+01',
    min_singular_value: '1.598147e-04',
    condition_number: '1.698625e+05',
    svd_rank: '2000',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'G37.png,G37_svd.png,G37_graph.gif,',
}
