{
    matrix_id: '500',
    name: 'G38',
    group: 'Gset',
    description: 'Random matrix, nodes 1..n descreasing average degree.G38=pattern of G42',
    author: 'C. Helmberg',
    editor: 'Y. Ye',
    date: '1996',
    kind: 'duplicate undirected random graph',
    problem_2D_or_3D: '0',
    num_rows: '2000',
    num_cols: '2000',
    nonzeros: '23558',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'This matrix is the nonzero pattern of Gset/G42
',
    norm: '2.709818e+01',
    min_singular_value: '2.162600e-03',
    condition_number: '1.253037e+04',
    svd_rank: '2000',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'G38.png,G38_svd.png,G38_graph.gif,',
}
