{
    matrix_id: '501',
    name: 'G39',
    group: 'Gset',
    description: 'Random matrix, nodes 1..n descreasing average degree.G35=pattern of G39',
    author: 'C. Helmberg',
    editor: 'Y. Ye',
    date: '1996',
    kind: 'undirected weighted random graph',
    problem_2D_or_3D: '0',
    num_rows: '2000',
    num_cols: '2000',
    nonzeros: '23556',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'integer',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.615390e+01',
    min_singular_value: '6.091560e-04',
    condition_number: '2.651849e+04',
    svd_rank: '2000',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'G39.png,G39_svd.png,G39_graph.gif,',
}
