{
    matrix_id: '505',
    name: 'G42',
    group: 'Gset',
    description: 'Random matrix, nodes 1..n descreasing average degree.G38=pattern of G42',
    author: 'C. Helmberg',
    editor: 'Y. Ye',
    date: '1996',
    kind: 'undirected weighted random graph',
    problem_2D_or_3D: '0',
    num_rows: '2000',
    num_cols: '2000',
    nonzeros: '23558',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'integer',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.694079e+01',
    min_singular_value: '1.858551e-03',
    condition_number: '9.115050e+03',
    svd_rank: '2000',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'G42.png,G42_svd.png,G42_graph.gif,',
}
