{
    matrix_id: '527',
    name: 'G62',
    group: 'Gset',
    description: '2D torus, 70-by-100',
    author: 'C. Helmberg',
    editor: 'Y. Ye',
    date: '1996',
    kind: 'undirected weighted random graph',
    problem_2D_or_3D: '0',
    num_rows: '7000',
    num_cols: '7000',
    nonzeros: '28000',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'integer',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '3.581990e+00',
    min_singular_value: '7.524847e-04',
    condition_number: '4.760216e+03',
    svd_rank: '7000',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'G62.png,G62_svd.png,G62_graph.gif,',
}
