{
    matrix_id: '528',
    name: 'G63',
    group: 'Gset',
    description: 'Random matrix, nodes 1..n descreasing average degree.G63=pattern of G64',
    author: 'C. Helmberg',
    editor: 'Y. Ye',
    date: '1996',
    kind: 'duplicate undirected random graph',
    problem_2D_or_3D: '0',
    num_rows: '7000',
    num_cols: '7000',
    nonzeros: '82918',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'This matrix is the nonzero pattern of Gset/G64
',
    norm: '3.338201e+01',
    min_singular_value: '5.567220e-04',
    condition_number: '5.996171e+04',
    svd_rank: '7000',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'G63.png,G63_svd.png,G63_graph.gif,',
}
