{
    matrix_id: '530',
    name: 'G65',
    group: 'Gset',
    description: '2D torus, 80-by-100',
    author: 'C. Helmberg',
    editor: 'Y. Ye',
    date: '1996',
    kind: 'undirected weighted random graph',
    problem_2D_or_3D: '0',
    num_rows: '8000',
    num_cols: '8000',
    nonzeros: '32000',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'integer',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '3.542670e+00',
    min_singular_value: '2.946512e-04',
    condition_number: '1.202327e+04',
    svd_rank: '8000',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'G65.png,G65_svd.png,G65_graph.gif,',
}
