{
    matrix_id: '531',
    name: 'G66',
    group: 'Gset',
    description: '2D torus, 100-by-90',
    author: 'C. Helmberg',
    editor: 'Y. Ye',
    date: '1996',
    kind: 'undirected weighted random graph',
    problem_2D_or_3D: '0',
    num_rows: '9000',
    num_cols: '9000',
    nonzeros: '36000',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'integer',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '3.582068e+00',
    min_singular_value: '2.144111e-04',
    condition_number: '1.670655e+04',
    svd_rank: '9000',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'G66.png,G66_svd.png,G66_graph.gif,',
}
