{
    matrix_id: '533',
    name: 'G7',
    group: 'Gset',
    description: 'Random matrix, 3% uniformly distributed. No diagonal. G2=pattern of G7',
    author: 'C. Helmberg',
    editor: 'Y. Ye',
    date: '1996',
    kind: 'undirected weighted random graph',
    problem_2D_or_3D: '0',
    num_rows: '800',
    num_cols: '800',
    nonzeros: '38352',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'integer',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.388879e+01',
    min_singular_value: '1.192578e-03',
    condition_number: '1.164602e+04',
    svd_rank: '800',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'G7.png,G7_svd.png,G7_graph.gif,',
}
