{
    matrix_id: '791',
    name: 'aft01',
    group: 'Okunbor',
    description: 'Acoustic Radiation around aft duct fan. D. Okunbor, Univ Missouri-Rolla',
    author: 'W. Eversman, D. Okunbor',
    editor: 'T. Davis',
    date: '2001',
    kind: 'acoustics problem',
    problem_2D_or_3D: '1',
    num_rows: '8205',
    num_cols: '8205',
    nonzeros: '125567',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '8205',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '1.000000e+15',
    min_singular_value: '2.279417e-04',
    condition_number: '4387085799161085440',
    svd_rank: '1',
    sprank_minus_rank: '8204',
    null_space_dimension: '8204',
    full_numerical_rank: 'no',
    image_files: 'aft01.png,aft01_svd.png,aft01_graph.gif,',
}
