{
    matrix_id: '792',
    name: 'aft02',
    group: 'Okunbor',
    description: 'Acoustic Radiation around aft duct fan. D. Okunbor, Univ Missouri-Rolla',
    author: 'W. Eversman, D. Okunbor',
    editor: 'T. Davis',
    date: '2001',
    kind: 'acoustics problem',
    problem_2D_or_3D: '1',
    num_rows: '8184',
    num_cols: '8184',
    nonzeros: '127762',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '8184',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.996',
    rb_type: 'complex',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.000000e+13',
    min_singular_value: '5.914816e-03',
    condition_number: '3.381339e+15',
    svd_rank: '654',
    sprank_minus_rank: '7530',
    null_space_dimension: '7530',
    full_numerical_rank: 'no',
    svd_gap: '1.003033',
    image_files: 'aft02.png,aft02_svd.png,aft02_graph.gif,',
}
