{
    matrix_id: '1853',
    name: 'parabolic_fem',
    group: 'Wissgott',
    description: 'Parabolic FEM, diffusion-convection reaction, constant homogenous diffusion',
    author: 'P. Wissgott',
    editor: 'T. Davis',
    date: '2007',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '525825',
    num_cols: '525825',
    nonzeros: '3674625',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '525825',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    b_field: 'full 525825-by-1
',
    image_files: 'parabolic_fem.png,parabolic_fem_graph.gif,',
}
