{
    matrix_id: '291',
    name: 'af23560',
    group: 'Bai',
    description: ' NACA 0012 AIRFOIL  M=0.8, EIGENVALUE CALCULATION',
    author: 'A. Mahajan',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1991',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '23560',
    num_cols: '23560',
    nonzeros: '460598',
    num_explicit_zeros: '23658',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '23560',
    pattern_symmetry: '0.997',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '6.457400e+02',
    min_singular_value: '3.246537e-02',
    condition_number: '1.989012e+04',
    svd_rank: '23560',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
