{
    matrix_id: '294',
    name: 'bfwa782',
    group: 'Bai',
    description: 'BOUNDED FINLINE WAVEGUIDE EIGENMODES B SHULTZ AND S GEDNEY',
    author: 'B. Schultz, S. Gedney',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1994',
    kind: 'electromagnetics problem',
    problem_2D_or_3D: '1',
    num_rows: '782',
    num_cols: '782',
    nonzeros: '7514',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '782',
    pattern_symmetry: '0.992',
    numeric_symmetry: '0.960',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.257448e+01',
    min_singular_value: '7.224162e-03',
    condition_number: '1.740615e+03',
    svd_rank: '782',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
