{
    matrix_id: '293',
    name: 'bfwa62',
    group: 'Bai',
    description: 'BOUNDED FINLINE WAVEGUIDE EIGENMODES B SHULTZ AND S GEDNEY',
    author: 'B. Schultz, S. Gedney',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1994',
    kind: 'electromagnetics problem',
    problem_2D_or_3D: '1',
    num_rows: '62',
    num_cols: '62',
    nonzeros: '450',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '62',
    pattern_symmetry: '0.969',
    numeric_symmetry: '0.814',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '9.258453e+00',
    min_singular_value: '1.674037e-02',
    condition_number: '5.530615e+02',
    svd_rank: '62',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
