{
    matrix_id: '297',
    name: 'bfwb782',
    group: 'Bai',
    description: 'BOUNDED FINLINE WAVEGUIDE EIGENMODES B SHULTZ AND S GEDNEY',
    author: 'B. Schultz, S. Gedney',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1994',
    kind: 'electromagnetics problem',
    problem_2D_or_3D: '1',
    num_rows: '782',
    num_cols: '782',
    nonzeros: '5982',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '782',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.347399e-05',
    min_singular_value: '1.298885e-06',
    condition_number: '1.807242e+01',
    svd_rank: '782',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
