{
    matrix_id: '298',
    name: 'bwm200',
    group: 'Bai',
    description: 'BRUSSELATOR WAVE MODEL IN TRANSPORT INTERACTION OF CHEMICAL SOLUTIONS',
    author: 'Y. Saad',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1992',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '200',
    num_cols: '200',
    nonzeros: '796',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '200',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.664',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.235555e+03',
    min_singular_value: '5.121417e-01',
    condition_number: '2.412527e+03',
    svd_rank: '200',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
