{
    matrix_id: '307',
    name: 'ck400',
    group: 'Bai',
    description: 'CHUCK MATRIX (MULTIPLE EIGENVALUES)  J. CULLUM',
    author: 'J. Cullum',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1986',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '400',
    num_cols: '400',
    nonzeros: '2860',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '400',
    pattern_symmetry: '0.989',
    numeric_symmetry: '0.002',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '5.732038e+00',
    min_singular_value: '2.211310e-05',
    condition_number: '2.592146e+05',
    svd_rank: '400',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
