{
    matrix_id: '1616',
    name: 'dwa512',
    group: 'Bai',
    description: 'SQUARE DIELECTRIC WAVEGUIDE, H. DONG',
    author: 'H. Dong',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1993',
    kind: 'electromagnetics problem',
    problem_2D_or_3D: '1',
    num_rows: '512',
    num_cols: '512',
    nonzeros: '2480',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '512',
    pattern_symmetry: '0.980',
    numeric_symmetry: '0.915',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.422023e+00',
    min_singular_value: '2.107875e-04',
    condition_number: '1.149036e+04',
    svd_rank: '512',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
