{
    matrix_id: '1618',
    name: 'dwg961a',
    group: 'Bai',
    description: 'DISPERSIVE WAVEGUIDE STRUCTURES',
    author: 'S. Gedney and U. Navasariwala',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1996',
    kind: 'electromagnetics problem',
    problem_2D_or_3D: '1',
    num_rows: '961',
    num_cols: '961',
    nonzeros: '3405',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '257',
    num_dmperm_blocks: '3',
    structural_full_rank: 'false',
    structural_rank: '705',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.360',
    rb_type: 'complex',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '5.166744e+05',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '705',
    sprank_minus_rank: '0',
    null_space_dimension: '256',
    full_numerical_rank: 'no',
    svd_gap: 'Inf',
}
