{
    matrix_id: '1621',
    name: 'mhd1280b',
    group: 'Bai',
    description: 'ALFVEN SPECTRA IN MAGNETOHYDRODYNAMIC',
    author: 'A. Booten, M. Kooper, H. van der Vorst, S. Poedts, J. Goedbloed',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1994',
    kind: 'electromagnetics problem',
    problem_2D_or_3D: '1',
    num_rows: '1280',
    num_cols: '1280',
    nonzeros: '22778',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '20',
    num_dmperm_blocks: '20',
    structural_full_rank: 'true',
    structural_rank: '1280',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'complex',
    structure: 'Hermitian',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '7.032203e+01',
    min_singular_value: '1.480591e-11',
    condition_number: '4.749591e+12',
    svd_rank: '1278',
    sprank_minus_rank: '2',
    null_space_dimension: '2',
    full_numerical_rank: 'no',
    svd_gap: '41.145962',
}
