{
    matrix_id: '1622',
    name: 'mhd3200a',
    group: 'Bai',
    description: 'ALFVEN SPECTRA IN MAGNETOHYDRODYNAMICS',
    author: 'A. Booten, M. Kooper, H. van der Vorst, S. Poedts, J. Goedbloed',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1994',
    kind: 'electromagnetics problem',
    problem_2D_or_3D: '1',
    num_rows: '3200',
    num_cols: '3200',
    nonzeros: '68026',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '8',
    num_dmperm_blocks: '8',
    structural_full_rank: 'true',
    structural_rank: '3200',
    pattern_symmetry: '0.768',
    numeric_symmetry: '0.267',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.607399e+05',
    min_singular_value: '9.538626e-27',
    condition_number: '1.685148e+31',
    svd_rank: '2244',
    sprank_minus_rank: '956',
    null_space_dimension: '956',
    full_numerical_rank: 'no',
    svd_gap: '1.016165',
}
