{
    matrix_id: '1623',
    name: 'mhd3200b',
    group: 'Bai',
    description: 'ALFVEN SPECTRA IN MAGNETOHYDRODYNAMICS',
    author: 'A. Booten, M. Kooper, H. van der Vorst, S. Poedts, J. Goedbloed',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1994',
    kind: 'electromagnetics problem',
    problem_2D_or_3D: '1',
    num_rows: '3200',
    num_cols: '3200',
    nonzeros: '18316',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '14',
    num_dmperm_blocks: '14',
    structural_full_rank: 'true',
    structural_rank: '3200',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '2.196269e+00',
    min_singular_value: '1.369264e-13',
    condition_number: '1.603978e+13',
    svd_rank: '3199',
    sprank_minus_rank: '1',
    null_space_dimension: '1',
    full_numerical_rank: 'no',
    svd_gap: '41.146707',
}
