{
    matrix_id: '1624',
    name: 'mhd4800a',
    group: 'Bai',
    description: 'ALFVEN SPECTRA IN MAGNETOHYDRODYNAMICS',
    author: 'A. Booten, M. Kooper, H. van der Vorst, S. Poedts, J. Goedbloed',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1994',
    kind: 'electromagnetics problem',
    problem_2D_or_3D: '1',
    num_rows: '4800',
    num_cols: '4800',
    nonzeros: '102252',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '8',
    num_dmperm_blocks: '8',
    structural_full_rank: 'true',
    structural_rank: '4800',
    pattern_symmetry: '0.768',
    numeric_symmetry: '0.268',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '3.628701e+05',
    min_singular_value: '9.324603e-28',
    condition_number: '3.891534e+32',
    svd_rank: '3302',
    sprank_minus_rank: '1498',
    null_space_dimension: '1498',
    full_numerical_rank: 'no',
    svd_gap: '3.131673',
}
