{
    matrix_id: '314',
    name: 'mhda416',
    group: 'Bai',
    description: 'MAGNETO-HYDRO-DYNAMICS ALFVEN SPECTRAL PROBLEM',
    author: 'A. Booten, M. Kooper, H. van der Vorst, S. Poedts, J. Goedbloed',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1994',
    kind: 'electromagnetics problem',
    problem_2D_or_3D: '1',
    num_rows: '416',
    num_cols: '416',
    nonzeros: '8562',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '8',
    num_dmperm_blocks: '8',
    structural_full_rank: 'true',
    structural_rank: '416',
    pattern_symmetry: '0.768',
    numeric_symmetry: '0.268',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.542594e+03',
    min_singular_value: '1.506255e-21',
    condition_number: '1.688023e+24',
    svd_rank: '322',
    sprank_minus_rank: '94',
    null_space_dimension: '94',
    full_numerical_rank: 'no',
    svd_gap: '1.092394',
}
