{
    matrix_id: '316',
    name: 'odepa400',
    group: 'Bai',
    description: 'MODEL ORDINARY DIFFERENTIAL EIGENVALUE PROBLEM',
    author: 'G. Stewart',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1978',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '400',
    num_cols: '400',
    nonzeros: '1201',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '400',
    pattern_symmetry: '0.996',
    numeric_symmetry: '0.994',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '5.004889e+00',
    min_singular_value: '2.215250e-05',
    condition_number: '2.259288e+05',
    svd_rank: '400',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
