{
    matrix_id: '317',
    name: 'odepb400',
    group: 'Bai',
    description: 'MODEL ORDINARY DIFFERENTIAL EIGENVALUE PROBLEM',
    author: 'G. Stewart',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1978',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '400',
    num_cols: '400',
    nonzeros: '399',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '400',
    num_dmperm_blocks: '401',
    structural_full_rank: 'false',
    structural_rank: '399',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.660000e-14',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '399',
    sprank_minus_rank: '0',
    null_space_dimension: '1',
    full_numerical_rank: 'no',
    svd_gap: 'Inf',
}
