{
    matrix_id: '318',
    name: 'olm100',
    group: 'Bai',
    description: 'OLMSTEAD FLOW MODEL',
    author: 'K. Meerbergen',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '100',
    num_cols: '100',
    nonzeros: '396',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '100',
    pattern_symmetry: '0.669',
    numeric_symmetry: '0.331',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '9.531567e+02',
    min_singular_value: '6.239910e-02',
    condition_number: '1.527517e+04',
    svd_rank: '100',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
