{
    matrix_id: '322',
    name: 'olm5000',
    group: 'Bai',
    description: 'OLMSTEAD FLOW MODEL',
    author: 'K. Meerbergen',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '5000',
    num_cols: '5000',
    nonzeros: '19996',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '5000',
    pattern_symmetry: '0.667',
    numeric_symmetry: '0.333',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.295590e+06',
    min_singular_value: '6.192415e-02',
    condition_number: '3.707099e+07',
    svd_rank: '5000',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
