{
    matrix_id: '321',
    name: 'olm500',
    group: 'Bai',
    description: 'OLMSTEAD FLOW MODEL',
    author: 'K. Meerbergen',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '500',
    num_cols: '500',
    nonzeros: '1996',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '500',
    pattern_symmetry: '0.667',
    numeric_symmetry: '0.333',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.312000e+04',
    min_singular_value: '6.194341e-02',
    condition_number: '3.732439e+05',
    svd_rank: '500',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
