{
    matrix_id: '323',
    name: 'pde225',
    group: 'Bai',
    description: 'MODEL PDE PROBLEM, H. ELMAN     NX = NY = 15',
    author: 'H. Elman',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1982',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '225',
    num_cols: '225',
    nonzeros: '1065',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '225',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.500',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '9.788621e+00',
    min_singular_value: '2.505803e-01',
    condition_number: '3.906381e+01',
    svd_rank: '225',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
