{
    matrix_id: '325',
    name: 'pde900',
    group: 'Bai',
    description: 'MODEL PDE PROBLEM, H. ELMAN     NX = NY = 30',
    author: 'H. Elman',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1982',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '900',
    num_cols: '900',
    nonzeros: '4380',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '900',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.500',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.044507e+01',
    min_singular_value: '6.846448e-02',
    condition_number: '1.525619e+02',
    svd_rank: '900',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
