{
    matrix_id: '328',
    name: 'qh882',
    group: 'Bai',
    description: 'QUEBEC HYDRO POWER SYSTEM, DEO',
    author: 'D. Ndereyimana',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1994',
    kind: 'power network problem',
    problem_2D_or_3D: '0',
    num_rows: '882',
    num_cols: '882',
    nonzeros: '3354',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '43',
    structural_full_rank: 'true',
    structural_rank: '882',
    pattern_symmetry: '0.926',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '6.686351e+12',
    min_singular_value: '2.718254e-04',
    condition_number: '24597962756102996',
    svd_rank: '821',
    sprank_minus_rank: '61',
    null_space_dimension: '61',
    full_numerical_rank: 'no',
    svd_gap: '1.018542',
}
