{
    matrix_id: '1629',
    name: 'rdb1250l',
    group: 'Bai',
    description: 'REACTION-DIFFUSION BRUSSELATOR MODEL',
    author: 'K. Meerbergen',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '1250',
    num_cols: '1250',
    nonzeros: '7300',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '1250',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.793',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '4.746962e+01',
    min_singular_value: '1.009458e-01',
    condition_number: '4.702485e+02',
    svd_rank: '1250',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
