{
    matrix_id: '1633',
    name: 'rdb3200l',
    group: 'Bai',
    description: 'REACTION-DIFFUSION BRUSSELATOR MODEL',
    author: 'K. Meerbergen',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '3200',
    num_cols: '3200',
    nonzeros: '18880',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '3200',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.796',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.115734e+02',
    min_singular_value: '1.009239e-01',
    condition_number: '1.105521e+03',
    svd_rank: '3200',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
