{
    matrix_id: '1636',
    name: 'rdb800l',
    group: 'Bai',
    description: 'REACTION-DIFFUSION BRUSSELATOR MODEL',
    author: 'K. Meerbergen',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '800',
    num_cols: '800',
    nonzeros: '4640',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '800',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.792',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '3.261904e+01',
    min_singular_value: '1.010358e-01',
    condition_number: '3.228465e+02',
    svd_rank: '800',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
