{
    matrix_id: '1640',
    name: 'tols4000',
    group: 'Bai',
    description: 'TOLOSA MATRIX',
    author: 'S. Godet-Thobie',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1991',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '4000',
    num_cols: '4000',
    nonzeros: '8784',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '3129',
    num_dmperm_blocks: '3983',
    structural_full_rank: 'true',
    structural_rank: '4000',
    pattern_symmetry: '0.361',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.344496e+07',
    min_singular_value: '9.953124e-01',
    condition_number: '2.355538e+07',
    svd_rank: '4000',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
