{
    matrix_id: '1641',
    name: 'tols90',
    group: 'Bai',
    description: 'TOLOSA MATRIX',
    author: 'S. Godet-Thobie',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1991',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '90',
    num_cols: '90',
    nonzeros: '1746',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '73',
    structural_full_rank: 'true',
    structural_rank: '90',
    pattern_symmetry: '0.269',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.013719e+04',
    min_singular_value: '9.953124e-01',
    condition_number: '2.023203e+04',
    svd_rank: '90',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
