{
    matrix_id: '1639',
    name: 'tols340',
    group: 'Bai',
    description: 'TOLOSA MATRIX',
    author: 'S. Godet-Thobie',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1991',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '340',
    num_cols: '340',
    nonzeros: '2196',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '201',
    num_dmperm_blocks: '323',
    structural_full_rank: 'true',
    structural_rank: '340',
    pattern_symmetry: '0.286',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.025002e+05',
    min_singular_value: '9.953124e-01',
    condition_number: '2.034539e+05',
    svd_rank: '340',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
