{
    matrix_id: '1638',
    name: 'tols2000',
    group: 'Bai',
    description: 'TOLOSA MATRIX',
    author: 'S. Godet-Thobie',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1991',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '2000',
    num_cols: '2000',
    nonzeros: '5184',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1529',
    num_dmperm_blocks: '1983',
    structural_full_rank: 'true',
    structural_rank: '2000',
    pattern_symmetry: '0.339',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '5.963364e+06',
    min_singular_value: '9.953124e-01',
    condition_number: '5.991450e+06',
    svd_rank: '2000',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
