{
    matrix_id: '1637',
    name: 'tols1090',
    group: 'Bai',
    description: 'TOLOSA MATRIX',
    author: 'S. Godet-Thobie',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1991',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '1090',
    num_cols: '1090',
    nonzeros: '3546',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '801',
    num_dmperm_blocks: '1073',
    structural_full_rank: 'true',
    structural_rank: '1090',
    pattern_symmetry: '0.318',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.822500e+06',
    min_singular_value: '9.953124e-01',
    condition_number: '1.831084e+06',
    svd_rank: '1090',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
