{
    matrix_id: '338',
    name: 'tub1000',
    group: 'Bai',
    description: 'TUBULAR REACTOR MODEL',
    author: 'K. Meerbergen, D. Roose',
    editor: 'Z. Bai, D. Day, J. Demmel, J. Dongarra',
    date: '1994',
    kind: 'computational fluid dynamics problem',
    problem_2D_or_3D: '1',
    num_rows: '1000',
    num_cols: '1000',
    nonzeros: '3996',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '1000',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.009772e+05',
    min_singular_value: '1.513633e-01',
    condition_number: '1.327780e+06',
    svd_rank: '1000',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
