{
    matrix_id: '907',
    name: 'cage6',
    group: 'vanHeukelum',
    description: 'DNA electrophoresis, 6 monomers in polymer. A. van Heukelum, Utrecht U.',
    author: 'A. van Heukelum',
    editor: 'T. Davis',
    date: '2003',
    kind: 'directed weighted graph',
    problem_2D_or_3D: '0',
    num_rows: '93',
    num_cols: '93',
    nonzeros: '785',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.092',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.025123e+00',
    min_singular_value: '8.972958e-02',
    condition_number: '1.142458e+01',
    svd_rank: '93',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
