{
    matrix_id: '911',
    name: 'cage10',
    group: 'vanHeukelum',
    description: 'DNA electrophoresis, 10 monomers in polymer. A. van Heukelum, Utrecht U',
    author: 'A. van Heukelum',
    editor: 'T. Davis',
    date: '2003',
    kind: 'directed weighted graph',
    problem_2D_or_3D: '0',
    num_rows: '11397',
    num_cols: '11397',
    nonzeros: '150645',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.174',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.020390e+00',
    min_singular_value: '9.261556e-02',
    condition_number: '1.101748e+01',
    svd_rank: '11397',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
