{
    matrix_id: '910',
    name: 'cage9',
    group: 'vanHeukelum',
    description: 'DNA electrophoresis, 9 monomers in polymer. A. van Heukelum, Utrecht U.',
    author: 'A. van Heukelum',
    editor: 'T. Davis',
    date: '2003',
    kind: 'directed weighted graph',
    problem_2D_or_3D: '0',
    num_rows: '3534',
    num_cols: '3534',
    nonzeros: '41594',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.154',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.023936e+00',
    min_singular_value: '8.126291e-02',
    condition_number: '1.260028e+01',
    svd_rank: '3534',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
