{
    matrix_id: '905',
    name: 'cage4',
    group: 'vanHeukelum',
    description: 'DNA electrophoresis, 4 monomers in polymer. A. van Heukelum, Utrecht U.',
    author: 'A. van Heukelum',
    editor: 'T. Davis',
    date: '2003',
    kind: 'directed weighted graph',
    problem_2D_or_3D: '0',
    num_rows: '9',
    num_cols: '9',
    nonzeros: '49',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.031365e+00',
    min_singular_value: '5.326446e-02',
    condition_number: '1.936311e+01',
    svd_rank: '9',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
