{
    matrix_id: '915',
    name: 'cage14',
    group: 'vanHeukelum',
    description: 'DNA electrophoresis, 14 monomers in polymer. A. van Heukelum, Utrecht U',
    author: 'A. van Heukelum',
    editor: 'T. Davis',
    date: '2003',
    kind: 'directed weighted graph',
    problem_2D_or_3D: '0',
    num_rows: '1505785',
    num_cols: '1505785',
    nonzeros: '27130349',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.207',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
}
