{
    matrix_id: '913',
    name: 'cage12',
    group: 'vanHeukelum',
    description: 'DNA electrophoresis, 12 monomers in polymer. A. van Heukelum, Utrecht U',
    author: 'A. van Heukelum',
    editor: 'T. Davis',
    date: '2003',
    kind: 'directed weighted graph',
    problem_2D_or_3D: '0',
    num_rows: '130228',
    num_cols: '130228',
    nonzeros: '2032536',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.194',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
}
