{
    matrix_id: '828',
    name: 'swang1',
    group: 'Wang',
    description: 'Discret.vorticity eqn, square driven cavity, semiconductor device sim.',
    author: 'S. Wang',
    editor: 'T. Davis',
    date: '1994',
    kind: 'semiconductor device problem sequence',
    problem_2D_or_3D: '1',
    num_rows: '3169',
    num_cols: '3169',
    nonzeros: '20841',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '3169',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: Wang/swang2 first: Wang/swang1
',
    norm: '1.971898e-02',
    min_singular_value: '3.291735e-03',
    condition_number: '5.990451e+00',
    svd_rank: '3169',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'swang1.png,swang1_svd.png,swang1_graph.gif,',
}
