{
    matrix_id: '833',
    name: 'wang4',
    group: 'Wang',
    description: 'MOSFET, doping 1.0e19 n-region, 1.0e15 p-region, uniform 30-30-30 mesh',
    author: 'S. Wang',
    editor: 'T. Davis',
    date: '1994',
    kind: 'semiconductor device problem',
    problem_2D_or_3D: '1',
    num_rows: '26068',
    num_cols: '26068',
    nonzeros: '177196',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '26068',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.046',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.301494e-01',
    min_singular_value: '3.232634e-07',
    condition_number: '4.026111e+05',
    svd_rank: '26068',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'wang4.png,wang4_svd.png,wang4_graph.gif,',
}
