{
    matrix_id: '830',
    name: 'wang1',
    group: 'Wang',
    description: 'Discretized electron continuity, 3d diode, nonuniform 14-14-16 mesh',
    author: 'S. Wang',
    editor: 'T. Davis',
    date: '1994',
    kind: 'semiconductor device problem sequence',
    problem_2D_or_3D: '1',
    num_rows: '2903',
    num_cols: '2903',
    nonzeros: '19093',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '2903',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.808',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: Wang/wang2 first: Wang/wang1
',
    norm: '4.138078e+00',
    min_singular_value: '2.036154e-04',
    condition_number: '2.032301e+04',
    svd_rank: '2903',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'wang1.png,wang1_svd.png,wang1_graph.gif,',
}
