{
    matrix_id: '443',
    name: 'pesa',
    group: 'Gaertner',
    description: 'Structuresymmetric Matrix pesa K. Gaertner ETH Zurich Oct 1996.',
    author: 'K. Gaertner',
    editor: 'F. Grund',
    date: '2001',
    kind: 'directed weighted graph',
    problem_2D_or_3D: '0',
    num_rows: '11738',
    num_cols: '11738',
    nonzeros: '79566',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'integer',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '3.391401e+04',
    min_singular_value: '7.927935e-04',
    condition_number: '4.277786e+07',
    svd_rank: '11738',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'pesa.png,pesa_svd.png,pesa_graph.gif,',
}
