{
    matrix_id: '985',
    name: 'adder_dcop_02',
    group: 'Sandia',
    description: 'Sandia/adder_dcop_02 circuit simulation matrix. Sandia National Lab.',
    author: 'R. Hoekstra',
    editor: 'T. Davis',
    date: '2003',
    kind: 'subsequent circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '1813',
    num_cols: '1813',
    nonzeros: '11246',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '6',
    num_dmperm_blocks: '469',
    structural_full_rank: 'true',
    structural_rank: '1813',
    pattern_symmetry: '0.648',
    numeric_symmetry: '0.026',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: Sandia/adder_dcop_03 first: Sandia/init_adder1
',
    norm: '1.223415e+00',
    min_singular_value: '4.121149e-15',
    condition_number: '2.968626e+14',
    svd_rank: '1790',
    sprank_minus_rank: '23',
    null_space_dimension: '23',
    full_numerical_rank: 'no',
    svd_gap: '1.184568',
    image_files: 'adder_dcop_02.png,adder_dcop_02_dmperm.png,adder_dcop_02_scc.png,adder_dcop_02_svd.png,adder_dcop_02_APlusAT_graph.gif,adder_dcop_02_graph.gif,',
}
