{
    matrix_id: '990',
    name: 'adder_dcop_07',
    group: 'Sandia',
    description: 'Sandia/adder_dcop_07 circuit simulation matrix. Sandia National Lab.',
    author: 'R. Hoekstra',
    editor: 'T. Davis',
    date: '2003',
    kind: 'subsequent circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '1813',
    num_cols: '1813',
    nonzeros: '11226',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '6',
    num_dmperm_blocks: '469',
    structural_full_rank: 'true',
    structural_rank: '1813',
    pattern_symmetry: '0.648',
    numeric_symmetry: '0.006',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: Sandia/adder_dcop_08 first: Sandia/init_adder1
',
    norm: '5.544571e+00',
    min_singular_value: '2.107695e-12',
    condition_number: '2.630632e+12',
    svd_rank: '1813',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'adder_dcop_07.png,adder_dcop_07_dmperm.png,adder_dcop_07_scc.png,adder_dcop_07_svd.png,adder_dcop_07_APlusAT_graph.gif,adder_dcop_07_graph.gif,',
}
