{
    matrix_id: '1003',
    name: 'adder_dcop_20',
    group: 'Sandia',
    description: 'Sandia/adder_dcop_20 circuit simulation matrix. Sandia National Lab.',
    author: 'R. Hoekstra',
    editor: 'T. Davis',
    date: '2003',
    kind: 'subsequent circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '1813',
    num_cols: '1813',
    nonzeros: '11246',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '6',
    num_dmperm_blocks: '469',
    structural_full_rank: 'true',
    structural_rank: '1813',
    pattern_symmetry: '0.648',
    numeric_symmetry: '0.007',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: Sandia/adder_dcop_21 first: Sandia/init_adder1
',
    norm: '1.231560e+00',
    min_singular_value: '2.108369e-12',
    condition_number: '5.841293e+11',
    svd_rank: '1813',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'adder_dcop_20.png,adder_dcop_20_dmperm.png,adder_dcop_20_scc.png,adder_dcop_20_svd.png,adder_dcop_20_APlusAT_graph.gif,adder_dcop_20_graph.gif,',
}
