{
    matrix_id: '984',
    name: 'adder_dcop_01',
    group: 'Sandia',
    description: 'Sandia/adder_dcop_01 circuit simulation matrix. Sandia National Lab.',
    author: 'R. Hoekstra',
    editor: 'T. Davis',
    date: '2003',
    kind: 'subsequent circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '1813',
    num_cols: '1813',
    nonzeros: '11156',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '6',
    num_dmperm_blocks: '469',
    structural_full_rank: 'true',
    structural_rank: '1813',
    pattern_symmetry: '0.654',
    numeric_symmetry: '0.016',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: Sandia/adder_dcop_02 first: Sandia/init_adder1
',
    norm: '1.018064e+00',
    min_singular_value: '3.117735e-08',
    condition_number: '3.265396e+07',
    svd_rank: '1813',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'adder_dcop_01.png,adder_dcop_01_dmperm.png,adder_dcop_01_scc.png,adder_dcop_01_svd.png,adder_dcop_01_APlusAT_graph.gif,adder_dcop_01_graph.gif,',
}
