{
    matrix_id: '986',
    name: 'adder_dcop_03',
    group: 'Sandia',
    description: 'Sandia/adder_dcop_03 circuit simulation matrix. Sandia National Lab.',
    author: 'R. Hoekstra',
    editor: 'T. Davis',
    date: '2003',
    kind: 'subsequent circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '1813',
    num_cols: '1813',
    nonzeros: '11148',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '7',
    num_dmperm_blocks: '483',
    structural_full_rank: 'true',
    structural_rank: '1813',
    pattern_symmetry: '0.643',
    numeric_symmetry: '0.035',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: Sandia/adder_dcop_04 first: Sandia/init_adder1
',
    norm: '3.866532e+00',
    min_singular_value: '1.998775e-12',
    condition_number: '1934450391988',
    svd_rank: '1813',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'adder_dcop_03.png,adder_dcop_03_dmperm.png,adder_dcop_03_scc.png,adder_dcop_03_svd.png,adder_dcop_03_APlusAT_graph.gif,adder_dcop_03_graph.gif,',
}
