{
    matrix_id: '1053',
    name: 'adder_trans_01',
    group: 'Sandia',
    description: 'Sandia/adder_trans_01 circuit simulation matrix. Sandia National Lab.',
    author: 'R. Hoekstra',
    editor: 'T. Davis',
    date: '2003',
    kind: 'circuit simulation problem sequence',
    problem_2D_or_3D: '0',
    num_rows: '1814',
    num_cols: '1814',
    nonzeros: '14579',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '3',
    num_dmperm_blocks: '20',
    structural_full_rank: 'true',
    structural_rank: '1814',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.031',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: Sandia/adder_trans_02 first: Sandia/adder_trans_01
',
    norm: '7.192196e+00',
    min_singular_value: '1.459773e-03',
    condition_number: '4.926928e+03',
    svd_rank: '1814',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'adder_trans_01.png,adder_trans_01_dmperm.png,adder_trans_01_scc.png,adder_trans_01_svd.png,adder_trans_01_graph.gif,',
}
