{
    matrix_id: '989',
    name: 'adder_dcop_06',
    group: 'Sandia',
    description: 'Sandia/adder_dcop_06 circuit simulation matrix. Sandia National Lab.',
    author: 'R. Hoekstra',
    editor: 'T. Davis',
    date: '2003',
    kind: 'subsequent circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '1813',
    num_cols: '1813',
    nonzeros: '11224',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '6',
    num_dmperm_blocks: '470',
    structural_full_rank: 'true',
    structural_rank: '1813',
    pattern_symmetry: '0.649',
    numeric_symmetry: '0.015',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: Sandia/adder_dcop_07 first: Sandia/init_adder1
',
    norm: '2.105506e+00',
    min_singular_value: '1.999999e-12',
    condition_number: '1.052754e+12',
    svd_rank: '1813',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'adder_dcop_06.png,adder_dcop_06_dmperm.png,adder_dcop_06_scc.png,adder_dcop_06_svd.png,adder_dcop_06_APlusAT_graph.gif,adder_dcop_06_graph.gif,',
}
