{
    matrix_id: '992',
    name: 'adder_dcop_09',
    group: 'Sandia',
    description: 'Sandia/adder_dcop_09 circuit simulation matrix. Sandia National Lab.',
    author: 'R. Hoekstra',
    editor: 'T. Davis',
    date: '2003',
    kind: 'subsequent circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '1813',
    num_cols: '1813',
    nonzeros: '11239',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '6',
    num_dmperm_blocks: '470',
    structural_full_rank: 'true',
    structural_rank: '1813',
    pattern_symmetry: '0.648',
    numeric_symmetry: '0.006',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: Sandia/adder_dcop_10 first: Sandia/init_adder1
',
    norm: '2.037621e+01',
    min_singular_value: '1.991568e-12',
    condition_number: '1.023124e+13',
    svd_rank: '1754',
    sprank_minus_rank: '59',
    null_space_dimension: '59',
    full_numerical_rank: 'no',
    svd_gap: '2.601082',
    image_files: 'adder_dcop_09.png,adder_dcop_09_dmperm.png,adder_dcop_09_scc.png,adder_dcop_09_svd.png,adder_dcop_09_APlusAT_graph.gif,adder_dcop_09_graph.gif,',
}
