{
    matrix_id: '1416',
    name: 'ASIC_100ks',
    group: 'Sandia',
    description: 'Sandia, Xyce circuit simulation matrix (base)',
    author: 'R. Hoekstra',
    editor: 'T. Davis',
    date: '2006',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '99190',
    num_cols: '99190',
    nonzeros: '578890',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '249',
    num_dmperm_blocks: '249',
    structural_full_rank: 'true',
    structural_rank: '99190',
    pattern_symmetry: '1.000',
    numeric_symmetry: '0.001',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    image_files: 'ASIC_100ks.png,ASIC_100ks_dmperm.png,ASIC_100ks_graph.gif,',
}
