{
    matrix_id: '1098',
    name: 'fpga_dcop_44',
    group: 'Sandia',
    description: 'Sandia/fpga_dcop_44 circuit simulation matrix. Sandia National Lab.',
    author: 'R. Hoekstra',
    editor: 'T. Davis',
    date: '2003',
    kind: 'subsequent circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '1220',
    num_cols: '1220',
    nonzeros: '5892',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '34',
    num_dmperm_blocks: '188',
    structural_full_rank: 'true',
    structural_rank: '1220',
    pattern_symmetry: '0.818',
    numeric_symmetry: '0.332',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: Sandia/fpga_dcop_45 first: Sandia/fpga_dcop_01
',
    b_field: 'full 1220-by-1
',
    norm: '2.871652e+00',
    min_singular_value: '9.263877e-13',
    condition_number: '3.099838e+12',
    svd_rank: '1220',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'fpga_dcop_44.png,fpga_dcop_44_dmperm.png,fpga_dcop_44_scc.png,fpga_dcop_44_svd.png,fpga_dcop_44_APlusAT_graph.gif,fpga_dcop_44_graph.gif,',
}
