{
    matrix_id: '1056',
    name: 'fpga_dcop_02',
    group: 'Sandia',
    description: 'Sandia/fpga_dcop_02 circuit simulation matrix. Sandia National Lab.',
    author: 'R. Hoekstra',
    editor: 'T. Davis',
    date: '2003',
    kind: 'subsequent circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '1220',
    num_cols: '1220',
    nonzeros: '5892',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '34',
    num_dmperm_blocks: '188',
    structural_full_rank: 'true',
    structural_rank: '1220',
    pattern_symmetry: '0.818',
    numeric_symmetry: '0.327',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: Sandia/fpga_dcop_03 first: Sandia/fpga_dcop_01
',
    b_field: 'full 1220-by-1
',
    norm: '2.881223e+00',
    min_singular_value: '4.681740e-17',
    condition_number: '61541716792204368',
    svd_rank: '1219',
    sprank_minus_rank: '1',
    null_space_dimension: '1',
    full_numerical_rank: 'no',
    svd_gap: '14234.905989',
    image_files: 'fpga_dcop_02.png,fpga_dcop_02_dmperm.png,fpga_dcop_02_scc.png,fpga_dcop_02_svd.png,fpga_dcop_02_APlusAT_graph.gif,fpga_dcop_02_graph.gif,',
}
