{
    matrix_id: '1066',
    name: 'fpga_dcop_12',
    group: 'Sandia',
    description: 'Sandia/fpga_dcop_12 circuit simulation matrix. Sandia National Lab.',
    author: 'R. Hoekstra',
    editor: 'T. Davis',
    date: '2003',
    kind: 'subsequent circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '1220',
    num_cols: '1220',
    nonzeros: '5892',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '34',
    num_dmperm_blocks: '188',
    structural_full_rank: 'true',
    structural_rank: '1220',
    pattern_symmetry: '0.818',
    numeric_symmetry: '0.322',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: Sandia/fpga_dcop_13 first: Sandia/fpga_dcop_01
',
    b_field: 'full 1220-by-1
',
    norm: '8.374127e+00',
    min_singular_value: '6.668639e-13',
    condition_number: '1.255748e+13',
    svd_rank: '1219',
    sprank_minus_rank: '1',
    null_space_dimension: '1',
    full_numerical_rank: 'no',
    svd_gap: '14.305279',
    image_files: 'fpga_dcop_12.png,fpga_dcop_12_dmperm.png,fpga_dcop_12_scc.png,fpga_dcop_12_svd.png,fpga_dcop_12_APlusAT_graph.gif,fpga_dcop_12_graph.gif,',
}
