{
    matrix_id: '1063',
    name: 'fpga_dcop_09',
    group: 'Sandia',
    description: 'Sandia/fpga_dcop_09 circuit simulation matrix. Sandia National Lab.',
    author: 'R. Hoekstra',
    editor: 'T. Davis',
    date: '2003',
    kind: 'subsequent circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '1220',
    num_cols: '1220',
    nonzeros: '5888',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '34',
    num_dmperm_blocks: '189',
    structural_full_rank: 'true',
    structural_rank: '1220',
    pattern_symmetry: '0.819',
    numeric_symmetry: '0.334',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: Sandia/fpga_dcop_10 first: Sandia/fpga_dcop_01
',
    b_field: 'full 1220-by-1
',
    norm: '2.016320e+01',
    min_singular_value: '6.666604e-13',
    condition_number: '3.024508e+13',
    svd_rank: '1208',
    sprank_minus_rank: '12',
    null_space_dimension: '12',
    full_numerical_rank: 'no',
    svd_gap: '9.418834',
    image_files: 'fpga_dcop_09.png,fpga_dcop_09_dmperm.png,fpga_dcop_09_scc.png,fpga_dcop_09_svd.png,fpga_dcop_09_APlusAT_graph.gif,fpga_dcop_09_graph.gif,',
}
