{
    matrix_id: '1120',
    name: 'oscil_dcop_09',
    group: 'Sandia',
    description: 'Sandia/oscil_dcop_09 circuit simulation matrix. Sandia National Lab.',
    author: 'R. Hoekstra',
    editor: 'T. Davis',
    date: '2003',
    kind: 'subsequent circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '430',
    num_cols: '430',
    nonzeros: '1544',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '9',
    num_dmperm_blocks: '31',
    structural_full_rank: 'true',
    structural_rank: '430',
    pattern_symmetry: '0.976',
    numeric_symmetry: '0.698',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: Sandia/oscil_dcop_10 first: Sandia/oscil_dcop_01
',
    b_field: 'full 430-by-1
',
    norm: '2.001004e+06',
    min_singular_value: '6.906669e-07',
    condition_number: '2.897206e+12',
    svd_rank: '430',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'oscil_dcop_09.png,oscil_dcop_09_dmperm.png,oscil_dcop_09_scc.png,oscil_dcop_09_svd.png,oscil_dcop_09_APlusAT_graph.gif,oscil_dcop_09_graph.gif,',
}
