{
    matrix_id: '1148',
    name: 'oscil_dcop_37',
    group: 'Sandia',
    description: 'Sandia/oscil_dcop_37 circuit simulation matrix. Sandia National Lab.',
    author: 'R. Hoekstra',
    editor: 'T. Davis',
    date: '2003',
    kind: 'subsequent circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '430',
    num_cols: '430',
    nonzeros: '1544',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '9',
    num_dmperm_blocks: '31',
    structural_full_rank: 'true',
    structural_rank: '430',
    pattern_symmetry: '0.976',
    numeric_symmetry: '0.698',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'next: Sandia/oscil_dcop_38 first: Sandia/oscil_dcop_01
',
    b_field: 'full 430-by-1
',
    norm: '2.001004e+06',
    min_singular_value: '7.158374e-12',
    condition_number: '279533369953926240',
    svd_rank: '413',
    sprank_minus_rank: '17',
    null_space_dimension: '17',
    full_numerical_rank: 'no',
    svd_gap: '1.742413',
    image_files: 'oscil_dcop_37.png,oscil_dcop_37_dmperm.png,oscil_dcop_37_scc.png,oscil_dcop_37_svd.png,oscil_dcop_37_APlusAT_graph.gif,oscil_dcop_37_graph.gif,',
}
