{
    matrix_id: '2555',
    name: 'Chevron1',
    group: 'Chevron',
    description: 'Temporal freq domain seismic modeling; J. Washbourne, Chevron',
    author: 'J. Washbourne',
    editor: 'T. Davis',
    date: '2012',
    kind: '2D/3D problem',
    problem_2D_or_3D: '0',
    num_rows: '37365',
    num_cols: '37365',
    nonzeros: '330633',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '37365',
    pattern_symmetry: '0.995',
    numeric_symmetry: '0.710',
    rb_type: 'complex',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Complex unsymmetric matrix arising from a 2D Helmholtz formulation
for temporal frequency domain seismic modeling.                   
From John Washbourne, Chevron                                     
',
    norm: '5.192608e-02',
    min_singular_value: '5.209323e-07',
    condition_number: '9.967913e+04',
    svd_rank: '37365',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
