{
    matrix_id: '2006',
    name: 'robot24c1_mat5',
    group: 'JGD_Groebner',
    description: 'Groebner basis from Jean-Charles Fauge`res',
    author: 'J.-C. Faugeres',
    editor: 'J.-G. Dumas',
    date: '2008',
    kind: 'combinatorial problem',
    problem_2D_or_3D: '0',
    num_rows: '404',
    num_cols: '302',
    nonzeros: '15118',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '302',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'integer',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Gro"bner basis from Jean-Charles Fauge`res,                 
From Jean-Guillaume Dumas\' Sparse Integer Matrix Collection,
http://ljk.imag.fr/membres/Jean-Guillaume.Dumas/simc.html   
                                                            
http://www-calfor.lip6.fr/~jcf/                             
                                                            
Filename in JGD collection: Grobner/robot24c1_mat5          
',
    norm: '2.355792e+06',
    min_singular_value: '7.066943e-06',
    condition_number: '3.333537e+11',
    svd_rank: '302',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'robot24c1_mat5.png,robot24c1_mat5_J.png,robot24c1_mat5_J_svd.png,robot24c1_mat5_svd.png,robot24c1_mat5_J_graph.gif,robot24c1_mat5_graph.gif,',
}
