{
    matrix_id: '860',
    name: 'pkustk14',
    group: 'Chen',
    description: 'PKU SYMMETRIC STIFFNESS, TALL BUILDING',
    author: 'P. Chen',
    editor: 'T. Davis',
    date: '2002',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '151926',
    num_cols: '151926',
    nonzeros: '14836504',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '151926',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
}
