{
    matrix_id: '857',
    name: 'pkustk11',
    group: 'Chen',
    description: 'PKU SYMMETRIC STIFFNESS, COFFERDAM, FULL SIZE',
    author: 'P. Chen',
    editor: 'T. Davis',
    date: '2002',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '87804',
    num_cols: '87804',
    nonzeros: '5217912',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '2',
    num_dmperm_blocks: '2',
    structural_full_rank: 'true',
    structural_rank: '87804',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
}
