{
    matrix_id: '855',
    name: 'pkustk09',
    group: 'Chen',
    description: 'PKU SYMMETRIC STIFFNESS, GROUP SILOS IN DALIAN, CHINA',
    author: 'P. Chen',
    editor: 'T. Davis',
    date: '2002',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '33960',
    num_cols: '33960',
    nonzeros: '1583640',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '33960',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '5.531085e+01',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '5583',
    sprank_minus_rank: '28377',
    null_space_dimension: '28377',
    full_numerical_rank: 'no',
    svd_gap: '6.474968',
}
