{
    matrix_id: '851',
    name: 'pkustk05',
    group: 'Chen',
    description: 'PKU SYMMETRIC STIFFNESS, COFFERDAM 37164 DOFS',
    author: 'P. Chen',
    editor: 'T. Davis',
    date: '2002',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '37164',
    num_cols: '37164',
    nonzeros: '2205144',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '37164',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '7.762053e+01',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '6149',
    sprank_minus_rank: '31015',
    null_space_dimension: '31015',
    full_numerical_rank: 'no',
    svd_gap: '1.949488',
}
