{
    matrix_id: '470',
    name: 'G10',
    group: 'Gset',
    description: 'Random matrix, 3% uniformly distributed. No diagonal. G5=pattern of G10',
    author: 'C. Helmberg',
    editor: 'Y. Ye',
    date: '1996',
    kind: 'undirected weighted random graph',
    problem_2D_or_3D: '0',
    num_rows: '800',
    num_cols: '800',
    nonzeros: '38352',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'integer',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.387462e+01',
    min_singular_value: '3.976311e-03',
    condition_number: '3.489320e+03',
    svd_rank: '800',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
