{
    matrix_id: '474',
    name: 'G14',
    group: 'Gset',
    description: 'Random matrix, nodes 1..n descreasing average degree.G14=pattern of G18',
    author: 'C. Helmberg',
    editor: 'Y. Ye',
    date: '1996',
    kind: 'duplicate undirected random graph',
    problem_2D_or_3D: '0',
    num_rows: '800',
    num_cols: '800',
    nonzeros: '9388',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'This matrix is the nonzero pattern of Gset/G18
',
    norm: '2.242769e+01',
    min_singular_value: '1.124639e-02',
    condition_number: '1.994212e+03',
    svd_rank: '800',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
