{
    matrix_id: '479',
    name: 'G19',
    group: 'Gset',
    description: 'Random matrix, nodes 1..n descreasing average degree.G15=pattern of G19',
    author: 'C. Helmberg',
    editor: 'Y. Ye',
    date: '1996',
    kind: 'undirected weighted random graph',
    problem_2D_or_3D: '0',
    num_rows: '800',
    num_cols: '800',
    nonzeros: '9322',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'integer',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.364572e+01',
    min_singular_value: '5.862491e-03',
    condition_number: '2.327631e+03',
    svd_rank: '800',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
