{
    matrix_id: '483',
    name: 'G22',
    group: 'Gset',
    description: 'Random matrix, 1% uniformly distributed. G22=pattern of G27',
    author: 'C. Helmberg',
    editor: 'Y. Ye',
    date: '1996',
    kind: 'undirected random graph',
    problem_2D_or_3D: '0',
    num_rows: '2000',
    num_cols: '2000',
    nonzeros: '39980',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.107608e+01',
    min_singular_value: '7.388089e-04',
    condition_number: '2.852710e+04',
    svd_rank: '2000',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
