{
    matrix_id: '495',
    name: 'G33',
    group: 'Gset',
    description: '2D torus, 25-by-80, uniformly random +1/-1 entries',
    author: 'C. Helmberg',
    editor: 'Y. Ye',
    date: '1996',
    kind: 'undirected weighted random graph',
    problem_2D_or_3D: '0',
    num_rows: '2000',
    num_cols: '2000',
    nonzeros: '8000',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'integer',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '3.487011e+00',
    min_singular_value: '1.091949e-03',
    condition_number: '3.193384e+03',
    svd_rank: '2000',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
