{
    matrix_id: '502',
    name: 'G4',
    group: 'Gset',
    description: 'Random matrix, 3% uniformly distributed. No diagonal. G4=pattern of G9',
    author: 'C. Helmberg',
    editor: 'Y. Ye',
    date: '1996',
    kind: 'undirected random graph',
    problem_2D_or_3D: '0',
    num_rows: '800',
    num_cols: '800',
    nonzeros: '38352',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '4.889071e+01',
    min_singular_value: '2.018873e-02',
    condition_number: '2.421683e+03',
    svd_rank: '800',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'G4.png,G4_svd.png,G4_graph.gif,',
}
