{
    matrix_id: '506',
    name: 'G43',
    group: 'Gset',
    description: 'Random matrix, 1% uniformly distributed.',
    author: 'C. Helmberg',
    editor: 'Y. Ye',
    date: '1996',
    kind: 'undirected random graph',
    problem_2D_or_3D: '0',
    num_rows: '1000',
    num_cols: '1000',
    nonzeros: '19980',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.101603e+01',
    min_singular_value: '7.211457e-03',
    condition_number: '2.914255e+03',
    svd_rank: '1000',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
