{
    matrix_id: '513',
    name: 'G5',
    group: 'Gset',
    description: 'Random matrix, 3% uniformly distributed. No diagonal. G5=pattern of G10',
    author: 'C. Helmberg',
    editor: 'Y. Ye',
    date: '1996',
    kind: 'undirected random graph',
    problem_2D_or_3D: '0',
    num_rows: '800',
    num_cols: '800',
    nonzeros: '38352',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '4.886825e+01',
    min_singular_value: '6.648107e-04',
    condition_number: '7.350701e+04',
    svd_rank: '800',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'G5.png,G5_svd.png,G5_graph.gif,',
}
