{
    matrix_id: '516',
    name: 'G52',
    group: 'Gset',
    description: 'Random matrix, nodes 1..n descreasing average degree.',
    author: 'C. Helmberg',
    editor: 'Y. Ye',
    date: '1996',
    kind: 'undirected random graph',
    problem_2D_or_3D: '0',
    num_rows: '1000',
    num_cols: '1000',
    nonzeros: '11832',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.369635e+01',
    min_singular_value: '6.142958e-03',
    condition_number: '3.857482e+03',
    svd_rank: '1000',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
