{
    matrix_id: '521',
    name: 'G57',
    group: 'Gset',
    description: '2D torus, 50-by-100',
    author: 'C. Helmberg',
    editor: 'Y. Ye',
    date: '1996',
    kind: 'undirected weighted random graph',
    problem_2D_or_3D: '0',
    num_rows: '5000',
    num_cols: '5000',
    nonzeros: '20000',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'integer',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '3.556619e+00',
    min_singular_value: '7.053243e-04',
    condition_number: '5.042530e+03',
    svd_rank: '5000',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
