{
    matrix_id: '522',
    name: 'G58',
    group: 'Gset',
    description: 'Random matrix, nodes 1..n descreasing average degree.G58=pattern of G59',
    author: 'C. Helmberg',
    editor: 'Y. Ye',
    date: '1996',
    kind: 'duplicate undirected random graph',
    problem_2D_or_3D: '0',
    num_rows: '5000',
    num_cols: '5000',
    nonzeros: '59140',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'This matrix is the nonzero pattern of Gset/G59
',
    norm: '3.211928e+01',
    min_singular_value: '1.436345e-04',
    condition_number: '2.236181e+05',
    svd_rank: '5000',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
