{
    matrix_id: '523',
    name: 'G59',
    group: 'Gset',
    description: 'Random matrix, nodes 1..n descreasing average degree.G58=pattern of G59',
    author: 'C. Helmberg',
    editor: 'Y. Ye',
    date: '1996',
    kind: 'undirected weighted random graph',
    problem_2D_or_3D: '0',
    num_rows: '5000',
    num_cols: '5000',
    nonzeros: '59140',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'integer',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.436481e+01',
    min_singular_value: '1.034510e-03',
    condition_number: '2.355203e+04',
    svd_rank: '5000',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
