{
    matrix_id: '529',
    name: 'G64',
    group: 'Gset',
    description: 'Random matrix, nodes 1..n descreasing average degree.G63=pattern of G64',
    author: 'C. Helmberg',
    editor: 'Y. Ye',
    date: '1996',
    kind: 'undirected weighted random graph',
    problem_2D_or_3D: '0',
    num_rows: '7000',
    num_cols: '7000',
    nonzeros: '82918',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'integer',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.488104e+01',
    min_singular_value: '2.726490e-04',
    condition_number: '9.125665e+04',
    svd_rank: '7000',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
