{
    matrix_id: '450',
    name: 'b2_ss',
    group: 'Grund',
    description: 'Unsymmetric Matrix b2_ss, F. Grund, Dec 1994.',
    author: 'F. Grund',
    editor: 'F. Grund',
    date: '1997',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '1089',
    num_cols: '1089',
    nonzeros: '3895',
    num_explicit_zeros: '333',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '249',
    structural_full_rank: 'true',
    structural_rank: '1089',
    pattern_symmetry: '0.015',
    numeric_symmetry: '0.001',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 1089-by-1
',
    norm: '2.093497e+05',
    min_singular_value: '2.731586e-07',
    condition_number: '766403596998',
    svd_rank: '1089',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'b2_ss.png,b2_ss_dmperm.png,b2_ss_svd.png,b2_ss_APlusAT_graph.gif,b2_ss_graph.gif,',
}
