{
    matrix_id: '451',
    name: 'b_dyn',
    group: 'Grund',
    description: 'Unsymmetric Matrix b_dyn, F. Grund, Dec 1994.',
    author: 'F. Grund',
    editor: 'F. Grund',
    date: '1997',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '1089',
    num_cols: '1089',
    nonzeros: '4144',
    num_explicit_zeros: '120',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '164',
    structural_full_rank: 'true',
    structural_rank: '1089',
    pattern_symmetry: '0.015',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 1089-by-1
',
    norm: '2.913515e+04',
    min_singular_value: '1.149366e-10',
    condition_number: '2.534889e+14',
    svd_rank: '1028',
    sprank_minus_rank: '61',
    null_space_dimension: '61',
    full_numerical_rank: 'no',
    svd_gap: '14.099896',
    image_files: 'b_dyn.png,b_dyn_dmperm.png,b_dyn_svd.png,b_dyn_APlusAT_graph.gif,b_dyn_graph.gif,',
}
