{
    matrix_id: '452',
    name: 'bayer01',
    group: 'Grund',
    description: 'Unsymmetric Matrix bayer01, Bayer AG, F. Grund, Apr 1996.',
    author: 'Bayer',
    editor: 'F. Grund',
    date: '1997',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '57735',
    num_cols: '57735',
    nonzeros: '275094',
    num_explicit_zeros: '2680',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '9133',
    structural_full_rank: 'true',
    structural_rank: '57735',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    image_files: 'bayer01.png,bayer01_dmperm.png,bayer01_APlusAT_graph.gif,bayer01_graph.gif,',
}
