{
    matrix_id: '464',
    name: 'd_ss',
    group: 'Grund',
    description: 'Unsymmetric Matrix d_ss, F. Grund, Dec 1994.',
    author: 'F. Grund',
    editor: 'F. Grund',
    date: '1997',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '53',
    num_cols: '53',
    nonzeros: '144',
    num_explicit_zeros: '5',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '53',
    pattern_symmetry: '0.041',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 53-by-1
',
    norm: '3.569888e+04',
    min_singular_value: '5.809551e-05',
    condition_number: '6.144860e+08',
    svd_rank: '53',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'd_ss.png,d_ss_svd.png,d_ss_APlusAT_graph.gif,d_ss_graph.gif,',
}
