{
    matrix_id: '465',
    name: 'meg1',
    group: 'Grund',
    description: 'Unsymmetric Matrix meg1, 1MB RAM simulation, F. Grund, Oct 1990.',
    author: 'F. Grund',
    editor: 'F. Grund',
    date: '1997',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '2904',
    num_cols: '2904',
    nonzeros: '58142',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '929',
    structural_full_rank: 'true',
    structural_rank: '2904',
    pattern_symmetry: '0.002',
    numeric_symmetry: '0.002',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.099515e+06',
    min_singular_value: '1.518569e-06',
    condition_number: '1.382562e+12',
    svd_rank: '2904',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'meg1.png,meg1_dmperm.png,meg1_svd.png,meg1_APlusAT_graph.gif,meg1_graph.gif,',
}
