{
    matrix_id: '2279',
    name: 'poli4',
    group: 'Grund',
    description: 'Economic problem from Friedrich Grund, Berlin',
    author: 'F. Grund',
    editor: 'T. Davis',
    date: '2010',
    kind: 'economic problem',
    problem_2D_or_3D: '0',
    num_rows: '33833',
    num_cols: '33833',
    nonzeros: '73249',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '33628',
    num_dmperm_blocks: '33628',
    structural_full_rank: 'true',
    structural_rank: '33833',
    pattern_symmetry: '0.004',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.562510e+01',
    min_singular_value: '2.082857e-02',
    condition_number: '7.501762e+02',
    svd_rank: '33833',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'poli4.png,poli4_dmperm.png,poli4_svd.png,poli4_APlusAT_graph.gif,poli4_graph.gif,',
}
