{
    matrix_id: '468',
    name: 'poli_large',
    group: 'Grund',
    description: 'Unsymmetric Matrix poli_large, FU Berlin, Aug 1996.',
    author: 'F. Grund',
    editor: 'F. Grund',
    date: '1997',
    kind: 'economic problem',
    problem_2D_or_3D: '0',
    num_rows: '15575',
    num_cols: '15575',
    nonzeros: '33033',
    num_explicit_zeros: '41',
    num_strongly_connected_components: '15466',
    num_dmperm_blocks: '15466',
    structural_full_rank: 'true',
    structural_rank: '15575',
    pattern_symmetry: '0.004',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.363183e+01',
    min_singular_value: '4.569483e-01',
    condition_number: '2.983233e+01',
    svd_rank: '15575',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'poli_large.png,poli_large_dmperm.png,poli_large_svd.png,poli_large_APlusAT_graph.gif,poli_large_graph.gif,',
}
