{
    matrix_id: '2278',
    name: 'poli3',
    group: 'Grund',
    description: 'Economic problem from Friedrich Grund, Berlin',
    author: 'F. Grund',
    editor: 'T. Davis',
    date: '2010',
    kind: 'economic problem',
    problem_2D_or_3D: '0',
    num_rows: '16955',
    num_cols: '16955',
    nonzeros: '37849',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '16794',
    num_dmperm_blocks: '16794',
    structural_full_rank: 'true',
    structural_rank: '16955',
    pattern_symmetry: '0.005',
    numeric_symmetry: '0.001',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.599179e+01',
    min_singular_value: '3.044325e-02',
    condition_number: '5.252983e+02',
    svd_rank: '16955',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'poli3.png,poli3_dmperm.png,poli3_svd.png,poli3_APlusAT_graph.gif,poli3_graph.gif,',
}
