{
    matrix_id: '755',
    name: 'barth4',
    group: 'Nasa',
    description: 'BARTH4: Nasa matrix, but with a diagonal added to the original matrix',
    author: 'NASA',
    editor: 'G. Kumfert, A. Pothen',
    date: '1995',
    kind: 'duplicate structural problem',
    problem_2D_or_3D: '1',
    num_rows: '6019',
    num_cols: '6019',
    nonzeros: '23492',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '33',
    num_dmperm_blocks: '33',
    structural_full_rank: 'true',
    structural_rank: '6019',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'binary',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Let A=Nasa/barth4, then Pothen/barth4 = spones(A+A\') with xyz coord.
',
    norm: '4.389711e+00',
    min_singular_value: '5.974320e-18',
    condition_number: '734763392727743232',
    svd_rank: '6018',
    sprank_minus_rank: '1',
    null_space_dimension: '1',
    full_numerical_rank: 'no',
    svd_gap: '644820274356.105469',
    image_files: 'barth4.png,barth4_dmperm.png,barth4_svd.png,barth4_APlusAT_graph.gif,barth4_graph.gif,',
}
