{
    matrix_id: '763',
    name: 'shuttle_eddy',
    group: 'Nasa',
    description: 'SHUTTLE_EDDY: Nasa matrix, but with diagonal added to original matrix',
    author: 'NASA',
    editor: 'G. Kumfert, A. Pothen',
    date: '1995',
    kind: 'duplicate structural problem',
    problem_2D_or_3D: '1',
    num_rows: '10429',
    num_cols: '10429',
    nonzeros: '103599',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '10429',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    notes: 'Identical to Pothen/shuttle_eddy; the latter has xyz coordinates.
',
    norm: '1.614161e+01',
    min_singular_value: '1.155304e-18',
    condition_number: '1.397175e+19',
    svd_rank: '9757',
    sprank_minus_rank: '672',
    null_space_dimension: '672',
    full_numerical_rank: 'no',
    svd_gap: '707869886734.339478',
    image_files: 'shuttle_eddy.png,shuttle_eddy_svd.png,shuttle_eddy_graph.gif,',
}
