{
    matrix_id: '2900',
    name: 'uni_chimera_i1',
    group: 'FlowIPM22',
    description: 'max flow Chimera graph: FlowIPM22/uni_chimera_i1',
    author: 'Y. Gao, R. Kyng, D. Spielman',
    editor: 'T. Davis',
    date: '2023',
    kind: 'undirected weighted graph',
    problem_2D_or_3D: '0',
    num_rows: '100000',
    num_cols: '100000',
    nonzeros: '1100592',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    notes: 'FlowIPM22: Laplacians from Newton-Steps of Maxflow Short-step IPM on     
Chimera Graphs                                                           
                                                                         
A collection of matrices arising from solving maximum flow problems on a 
diverse collection of graphs (known as Chimeras) using a short-step      
interior point method. The Laplacian matrices arise when computing Newton
steps of the interior point method.                                      
                                                                         
The matrices are symmetric graph Laplacians, meaning they are symmetric  
diagonally dominant matrices with non-positive off-diagonals and row sums
equal to zero.                                                           
                                                                         
Generated by Yuan Gao, Rasmus Kyng, and Daniel Spielman. 2022.           
                                                                         
References:                                                              
                                                                         
data set: https://www.spe.org/web/csp/datasets/set02.htm                 
                                                                         
An Algebraic Sparsified Nested Dissection Algorithm Using Low-Rank       
Approximations Léopold Cambier, Chao Chen, Erik G. Boman, Sivasankaran   
Rajamanickam, Raymond S. Tuminaro, and Eric Darve                        
SIAM Journal on Matrix Analysis and Applications, vol 41, no 2,          
pp 715-746, 2020.  https://epubs.siam.org/doi/10.1137/19M123806X         
                                                                         
Problem set name:        uni_chimera_i1                                  
                                                                         
The primary matrix is the first matrix in the set.                       
Original matrix names in this sequence:                                  
                                                                         
    1: ipmMat/uni_chimera.n100000.i1.eps1.0e-5.1.mm                      
    2: ipmMat/uni_chimera.n100000.i1.eps1.0e-5.2.mm                      
    3: ipmMat/uni_chimera.n100000.i1.eps1.0e-5.3.mm                      
    4: ipmMat/uni_chimera.n100000.i1.eps1.0e-5.4.mm                      
    5: ipmMat/uni_chimera.n100000.i1.eps0.0001.1.mm                      
    6: ipmMat/uni_chimera.n100000.i1.eps0.0001.2.mm                      
    7: ipmMat/uni_chimera.n100000.i1.eps0.0001.3.mm                      
    8: ipmMat/uni_chimera.n100000.i1.eps0.0001.4.mm                      
    9: ipmMat/uni_chimera.n100000.i1.eps0.0001.5.mm                      
   10: ipmMat/uni_chimera.n100000.i1.eps0.0001.6.mm                      
   11: ipmMat/uni_chimera.n100000.i1.eps0.001.1.mm                       
   12: ipmMat/uni_chimera.n100000.i1.eps0.001.2.mm                       
   13: ipmMat/uni_chimera.n100000.i1.eps0.001.3.mm                       
   14: ipmMat/uni_chimera.n100000.i1.eps0.001.4.mm                       
   15: ipmMat/uni_chimera.n100000.i1.eps0.001.5.mm                       
   16: ipmMat/uni_chimera.n100000.i1.eps0.001.6.mm                       
   17: ipmMat/uni_chimera.n100000.i1.eps0.01.1.mm                        
   18: ipmMat/uni_chimera.n100000.i1.eps0.01.2.mm                        
   19: ipmMat/uni_chimera.n100000.i1.eps0.01.3.mm                        
   20: ipmMat/uni_chimera.n100000.i1.eps0.01.4.mm                        
   21: ipmMat/uni_chimera.n100000.i1.eps0.01.5.mm                        
   22: ipmMat/uni_chimera.n100000.i1.eps0.01.6.mm                        
   23: ipmMat/uni_chimera.n100000.i1.eps0.1.1.mm                         
   24: ipmMat/uni_chimera.n100000.i1.eps0.1.2.mm                         
   25: ipmMat/uni_chimera.n100000.i1.eps0.1.3.mm                         
   26: ipmMat/uni_chimera.n100000.i1.eps0.1.4.mm                         
   27: ipmMat/uni_chimera.n100000.i1.eps0.1.5.mm                         
   28: ipmMat/uni_chimera.n100000.i1.eps0.1.6.mm                         
',
    aux_fields: 'A: cell 28-by-1
',    image_files: '',
}
