{
    matrix_id: '345',
    name: 'bcsstm35',
    group: 'Boeing',
    description: 'MASS MATRIX, AUTOMOBILE SEAT FRAME AND BODY ATTACHMENT',
    author: 'R. Grimes',
    editor: 'T. Davis',
    date: '1995',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '30237',
    num_cols: '30237',
    nonzeros: '20619',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '29228',
    num_dmperm_blocks: '14796',
    structural_full_rank: 'false',
    structural_rank: '15803',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '2.950553e-02',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '15609',
    sprank_minus_rank: '194',
    null_space_dimension: '14628',
    full_numerical_rank: 'no',
    svd_gap: '3.171794',
    image_files: 'bcsstm35.png,bcsstm35_dmperm.png,bcsstm35_scc.png,bcsstm35_svd.png,bcsstm35_graph.gif,',
}
