{
    matrix_id: '349',
    name: 'bcsstm39',
    group: 'Boeing',
    description: 'SHUTTLE SOLID ROCKET BOOSTER, MASS MATRIX     , E. PRAMONO, NASA AMES',
    author: 'R. Grimes',
    editor: 'T. Davis',
    date: '1995',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '46772',
    num_cols: '46772',
    nonzeros: '46772',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '46772',
    num_dmperm_blocks: '46772',
    structural_full_rank: 'true',
    structural_rank: '46772',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    image_files: 'bcsstm39.png,bcsstm39_dmperm.png,bcsstm39_graph.gif,',
}
