{
    matrix_id: '340',
    name: 'bcsstk35',
    group: 'Boeing',
    description: 'STIFFNESS MATRIX, AUTOMOBILE SEAT FRAME AND BODY ATTACHMENT',
    author: 'R. Grimes',
    editor: 'T. Davis',
    date: '1995',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '30237',
    num_cols: '30237',
    nonzeros: '1450163',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '30237',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '4.949239e+09',
    min_singular_value: '1.110887e-05',
    condition_number: '4.455216e+14',
    svd_rank: '30231',
    sprank_minus_rank: '6',
    null_space_dimension: '6',
    full_numerical_rank: 'no',
    svd_gap: '686.231828',
    image_files: 'bcsstk35.png,bcsstk35_svd.png,bcsstk35_graph.gif,',
}
