{
    matrix_id: '342',
    name: 'bcsstk37',
    group: 'Boeing',
    description: 'STIFFNESS MATRIX, TRACK BALL',
    author: 'R. Grimes',
    editor: 'T. Davis',
    date: '1995',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '25503',
    num_cols: '25503',
    nonzeros: '1140977',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '25503',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '8.412869e+07',
    min_singular_value: '1.224263e-06',
    condition_number: '6.871781e+13',
    svd_rank: '25395',
    sprank_minus_rank: '108',
    null_space_dimension: '108',
    full_numerical_rank: 'no',
    svd_gap: '1.013346',
    image_files: 'bcsstk37.png,bcsstk37_svd.png,bcsstk37_graph.gif,',
}
