{
    matrix_id: '343',
    name: 'bcsstk38',
    group: 'Boeing',
    description: 'STIFFNESS MATRIX, AIRPLANE ENGINE COMPONENT',
    author: 'R. Grimes',
    editor: 'T. Davis',
    date: '1995',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '8032',
    num_cols: '8032',
    nonzeros: '355460',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '8032',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '4.042307e+11',
    min_singular_value: '7.327514e-06',
    condition_number: '55166149525887384',
    svd_rank: '8008',
    sprank_minus_rank: '24',
    null_space_dimension: '24',
    full_numerical_rank: 'no',
    svd_gap: '1.284864',
    image_files: 'bcsstk38.png,bcsstk38_svd.png,bcsstk38_graph.gif,',
}
