{
    matrix_id: '347',
    name: 'bcsstm37',
    group: 'Boeing',
    description: 'MASS MATRIX, TRACK BALL',
    author: 'R. Grimes',
    editor: 'T. Davis',
    date: '1995',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '25503',
    num_cols: '25503',
    nonzeros: '15525',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '25068',
    num_dmperm_blocks: '13572',
    structural_full_rank: 'false',
    structural_rank: '14005',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.170887e-04',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '13921',
    sprank_minus_rank: '84',
    null_space_dimension: '11582',
    full_numerical_rank: 'no',
    svd_gap: '1.144120',
    image_files: 'bcsstm37.png,bcsstm37_dmperm.png,bcsstm37_scc.png,bcsstm37_svd.png,bcsstm37_graph.gif,',
}
