{
    matrix_id: '846',
    name: 'bcsstk39',
    group: 'Boeing',
    description: 'SHUTTLE SOLID ROCKET BOOSTER, STIFFNESS MATRIX, E. PRAMONO, NASA AMES',
    author: 'R. Grimes',
    editor: 'T. Davis',
    date: '2002',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '46772',
    num_cols: '46772',
    nonzeros: '2060662',
    num_explicit_zeros: '28632',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '46772',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    image_files: 'bcsstk39.png,bcsstk39_graph.gif,',
}
