{
    matrix_id: '348',
    name: 'bcsstm38',
    group: 'Boeing',
    description: 'MASS MATRIX, AIRPLANE ENGINE COMPONENT',
    author: 'R. Grimes',
    editor: 'T. Davis',
    date: '1995',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '8032',
    num_cols: '8032',
    nonzeros: '10485',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '6656',
    num_dmperm_blocks: '3825',
    structural_full_rank: 'false',
    structural_rank: '5199',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '5.411040e+02',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '5112',
    sprank_minus_rank: '87',
    null_space_dimension: '2920',
    full_numerical_rank: 'no',
    svd_gap: '95331.277583',
    image_files: 'bcsstm38.png,bcsstm38_dmperm.png,bcsstm38_scc.png,bcsstm38_svd.png,bcsstm38_graph.gif,',
}
