{
    matrix_id: '353',
    name: 'crystm01',
    group: 'Boeing',
    description: 'FEM CRYSTAL FREE VIBRATION MASS MATRIX',
    author: 'R. Grimes',
    editor: 'T. Davis',
    date: '1995',
    kind: 'materials problem',
    problem_2D_or_3D: '1',
    num_rows: '4875',
    num_cols: '4875',
    nonzeros: '105339',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '3',
    num_dmperm_blocks: '3',
    structural_full_rank: 'true',
    structural_rank: '4875',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '5.305693e-12',
    min_singular_value: '2.323834e-14',
    condition_number: '2.283164e+02',
    svd_rank: '4875',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'crystm01.png,crystm01_dmperm.png,crystm01_svd.png,crystm01_graph.gif,',
}
