{
    matrix_id: '357',
    name: 'msc00726',
    group: 'Boeing',
    description: 'SYMMETRIC TEST MATRIX FROM MSC/NASTRAN BC4F8.OUT2',
    author: 'R. Grimes',
    editor: 'T. Davis',
    date: '1995',
    kind: 'structural problem',
    problem_2D_or_3D: '1',
    num_rows: '726',
    num_cols: '726',
    nonzeros: '34518',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '726',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '4.219587e+09',
    min_singular_value: '1.009913e+04',
    condition_number: '4.178170e+05',
    svd_rank: '726',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'msc00726.png,msc00726_svd.png,msc00726_graph.gif,',
}
