{
    matrix_id: '1875',
    name: 'hvdc2',
    group: 'HVDC',
    description: 'Power simulation matrix, Alex Wang, Manitoba HVDC, Canada',
    author: 'A. Wang',
    editor: 'T. Davis',
    date: '2007',
    kind: 'power network problem',
    problem_2D_or_3D: '0',
    num_rows: '189860',
    num_cols: '189860',
    nonzeros: '1339638',
    num_explicit_zeros: '7635',
    num_strongly_connected_components: '67',
    num_dmperm_blocks: '69',
    structural_full_rank: 'true',
    structural_rank: '189860',
    pattern_symmetry: '0.989',
    numeric_symmetry: '0.063',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 189860-by-1
',
}
