{
    matrix_id: '1954',
    name: 'Franz1',
    group: 'JGD_Franz',
    description: 'Cohomology of various rings, from Matthias Franz, Univ. Konstanz, Germany',
    author: 'M. Franz',
    editor: 'J.-G. Dumas',
    date: '2008',
    kind: 'combinatorial problem',
    problem_2D_or_3D: '0',
    num_rows: '2240',
    num_cols: '768',
    nonzeros: '5120',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '768',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'integer',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Cohomology of various rings, from Matthias Franz, Univ. Konstanz, Germany
From Jean-Guillaume Dumas\' Sparse Integer Matrix Collection,             
http://ljk.imag.fr/membres/Jean-Guillaume.Dumas/simc.html                
                                                                         
Filename in JGD collection: Franz/big1sparse                             
',
    norm: '4.179007e+00',
    min_singular_value: '1.523734e-15',
    condition_number: '2742608665340875',
    svd_rank: '755',
    sprank_minus_rank: '13',
    null_space_dimension: '13',
    full_numerical_rank: 'no',
    svd_gap: '310459996085291.687500',
    image_files: 'Franz1.png,Franz10.png,Franz10_svd.png,Franz11.png,Franz11_svd.png,Franz1_svd.png,Franz10_graph.gif,Franz11_graph.gif,Franz1_graph.gif,',
}
