{
    matrix_id: '1960',
    name: 'Franz7',
    group: 'JGD_Franz',
    description: 'Cohomology of various rings, from Matthias Franz, Univ. Konstanz, Germany',
    author: 'M. Franz',
    editor: 'J.-G. Dumas',
    date: '2008',
    kind: 'combinatorial problem',
    problem_2D_or_3D: '0',
    num_rows: '10164',
    num_cols: '1740',
    nonzeros: '40424',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '6',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '1740',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'integer',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Cohomology of various rings, from Matthias Franz, Univ. Konstanz, Germany
From Jean-Guillaume Dumas\' Sparse Integer Matrix Collection,             
http://ljk.imag.fr/membres/Jean-Guillaume.Dumas/simc.html                
                                                                         
Filename in JGD collection: Franz/10164x1740                             
',
    norm: '1.220656e+01',
    min_singular_value: '2.206619e-15',
    condition_number: '5531791974633772',
    svd_rank: '1627',
    sprank_minus_rank: '113',
    null_space_dimension: '113',
    full_numerical_rank: 'no',
    svd_gap: '7432430229820.648438',
    image_files: 'Franz7.png,Franz7_scc.png,Franz7_svd.png,Franz7_graph.gif,',
}
