{
    matrix_id: '1959',
    name: 'Franz6',
    group: 'JGD_Franz',
    description: 'Cohomology of various rings, from Matthias Franz, Univ. Konstanz, Germany',
    author: 'M. Franz',
    editor: 'J.-G. Dumas',
    date: '2008',
    kind: 'combinatorial problem',
    problem_2D_or_3D: '0',
    num_rows: '7576',
    num_cols: '3016',
    nonzeros: '45456',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '3016',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'integer',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Cohomology of various rings, from Matthias Franz, Univ. Konstanz, Germany
From Jean-Guillaume Dumas\' Sparse Integer Matrix Collection,             
http://ljk.imag.fr/membres/Jean-Guillaume.Dumas/simc.html                
                                                                         
Filename in JGD collection: Franz/7576x3016                              
',
    norm: '9.380832e+00',
    min_singular_value: '3.562743e-17',
    condition_number: '263303609695508256',
    svd_rank: '2327',
    sprank_minus_rank: '689',
    null_space_dimension: '689',
    full_numerical_rank: 'no',
    svd_gap: '24514428564422.457031',
    image_files: 'Franz6.png,Franz6_svd.png,Franz6_graph.gif,',
}
