{
    matrix_id: '1957',
    name: 'Franz4',
    group: 'JGD_Franz',
    description: 'Cohomology of various rings, from Matthias Franz, Univ. Konstanz, Germany',
    author: 'M. Franz',
    editor: 'J.-G. Dumas',
    date: '2008',
    kind: 'combinatorial problem',
    problem_2D_or_3D: '0',
    num_rows: '6784',
    num_cols: '5252',
    nonzeros: '46528',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '5252',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'integer',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Cohomology of various rings, from Matthias Franz, Univ. Konstanz, Germany
From Jean-Guillaume Dumas\' Sparse Integer Matrix Collection,             
http://ljk.imag.fr/membres/Jean-Guillaume.Dumas/simc.html                
                                                                         
Filename in JGD collection: Franz/6784x5252                              
',
    norm: '8.602325e+00',
    min_singular_value: '3.947842e-17',
    condition_number: '217899457029796320',
    svd_rank: '3297',
    sprank_minus_rank: '1955',
    null_space_dimension: '1955',
    full_numerical_rank: 'no',
    svd_gap: '67490353868858.882812',
    image_files: 'Franz4.png,Franz4_svd.png,Franz4_graph.gif,',
}
