{
    matrix_id: '1956',
    name: 'Franz3',
    group: 'JGD_Franz',
    description: 'Cohomology of various rings, from Matthias Franz, Univ. Konstanz, Germany',
    author: 'M. Franz',
    editor: 'J.-G. Dumas',
    date: '2008',
    kind: 'combinatorial problem',
    problem_2D_or_3D: '0',
    num_rows: '1280',
    num_cols: '2800',
    nonzeros: '11520',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '1280',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'integer',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Cohomology of various rings, from Matthias Franz, Univ. Konstanz, Germany
From Jean-Guillaume Dumas\' Sparse Integer Matrix Collection,             
http://ljk.imag.fr/membres/Jean-Guillaume.Dumas/simc.html                
                                                                         
Filename in JGD collection: Franz/1280x2800                              
',
    norm: '6.324555e+00',
    min_singular_value: '1.348831e-17',
    condition_number: '468891580057368832',
    svd_rank: '1025',
    sprank_minus_rank: '255',
    null_space_dimension: '255',
    full_numerical_rank: 'no',
    svd_gap: '221750307559870.843750',
    image_files: 'Franz3.png,Franz3_svd.png,Franz3_graph.gif,',
}
