{
    matrix_id: '1964',
    name: 'Franz11',
    group: 'JGD_Franz',
    description: 'Cohomology of various rings, from Matthias Franz, Univ. Konstanz, Germany',
    author: 'M. Franz',
    editor: 'J.-G. Dumas',
    date: '2008',
    kind: 'combinatorial problem',
    problem_2D_or_3D: '0',
    num_rows: '47104',
    num_cols: '30144',
    nonzeros: '329728',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '30144',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'integer',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Cohomology of various rings, from Matthias Franz, Univ. Konstanz, Germany
From Jean-Guillaume Dumas\' Sparse Integer Matrix Collection,             
http://ljk.imag.fr/membres/Jean-Guillaume.Dumas/simc.html                
                                                                         
Filename in JGD collection: Franz/47104x30144bis                         
',
    norm: '7.483315e+00',
    min_singular_value: '2.836008e-229',
    condition_number: '2.638679e+229',
    svd_rank: '20993',
    sprank_minus_rank: '9151',
    null_space_dimension: '9151',
    full_numerical_rank: 'no',
    svd_gap: '29223150340338.699219',
    image_files: 'Franz11.png,Franz11_svd.png,Franz11_graph.gif,',
}
