{
    matrix_id: '1963',
    name: 'Franz10',
    group: 'JGD_Franz',
    description: 'Cohomology of various rings, from Matthias Franz, Univ. Konstanz, Germany',
    author: 'M. Franz',
    editor: 'J.-G. Dumas',
    date: '2008',
    kind: 'combinatorial problem',
    problem_2D_or_3D: '0',
    num_rows: '19588',
    num_cols: '4164',
    nonzeros: '97508',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '4164',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'integer',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Cohomology of various rings, from Matthias Franz, Univ. Konstanz, Germany
From Jean-Guillaume Dumas\' Sparse Integer Matrix Collection,             
http://ljk.imag.fr/membres/Jean-Guillaume.Dumas/simc.html                
                                                                         
Filename in JGD collection: Franz/19588x4164bis                          
',
    norm: '1.743560e+01',
    min_singular_value: '1.373531e-15',
    condition_number: '12693994707086298',
    svd_rank: '3545',
    sprank_minus_rank: '619',
    null_space_dimension: '619',
    full_numerical_rank: 'no',
    svd_gap: '8433671783431.350586',
    image_files: 'Franz10.png,Franz10_svd.png,Franz10_graph.gif,',
}
