{
    matrix_id: '753',
    name: 'pfinan512',
    group: 'Mulvey',
    description: 'Portfolio optim, 512 scenarios, Ed Rothberg, SGI, John Mulvey,Princeton',
    author: 'A. Berger, J. Mulvey, E. Rothberg, R. Vanderbei',
    editor: 'E. Rothberg',
    date: '1997',
    kind: 'duplicate economic problem',
    problem_2D_or_3D: '0',
    num_rows: '74752',
    num_cols: '74752',
    nonzeros: '596992',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '74752',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    notes: 'This matrix is the nonzero pattern of Mulvey/finan512
',
}
