{
    matrix_id: '734',
    name: 'lhr01',
    group: 'Mallya',
    description: 'Light hydrocarbon recovery. OK if illconditioned,from a nonlinear solvr',
    author: 'J. Mallya',
    editor: 'T. Davis',
    date: '1994',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '1477',
    num_cols: '1477',
    nonzeros: '18427',
    num_explicit_zeros: '165',
    num_strongly_connected_components: '21',
    num_dmperm_blocks: '298',
    structural_full_rank: 'true',
    structural_rank: '1477',
    pattern_symmetry: '0.007',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 1477-by-1
',
    norm: '5.970661e+00',
    min_singular_value: '7.169393e-06',
    condition_number: '8.327986e+05',
    svd_rank: '1477',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'lhr01.png,lhr01_dmperm.png,lhr01_scc.png,lhr01_svd.png,lhr01_APlusAT_graph.gif,lhr01_graph.gif,',
}
