{
    matrix_id: '739',
    name: 'lhr07c',
    group: 'Mallya',
    description: 'Light hydrocarbon recovery, corrected version of LHR07',
    author: 'J. Mallya',
    editor: 'T. Davis',
    date: '1997',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '7337',
    num_cols: '7337',
    nonzeros: '156508',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '31',
    num_dmperm_blocks: '672',
    structural_full_rank: 'true',
    structural_rank: '7337',
    pattern_symmetry: '0.017',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.831462e+01',
    min_singular_value: '7.655455e-13',
    condition_number: '2.392362e+13',
    svd_rank: '7336',
    sprank_minus_rank: '1',
    null_space_dimension: '1',
    full_numerical_rank: 'no',
    svd_gap: '5128.120955',
    image_files: 'lhr07c.png,lhr07c_dmperm.png,lhr07c_scc.png,lhr07c_svd.png,lhr07c_APlusAT_graph.gif,lhr07c_graph.gif,',
}
