{
    matrix_id: '743',
    name: 'lhr11c',
    group: 'Mallya',
    description: 'Light hydrocarbon recovery, corrected version of LHR11',
    author: 'J. Mallya',
    editor: 'T. Davis',
    date: '1997',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '10964',
    num_cols: '10964',
    nonzeros: '233741',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '31',
    num_dmperm_blocks: '1192',
    structural_full_rank: 'true',
    structural_rank: '10964',
    pattern_symmetry: '0.008',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.991304e+01',
    min_singular_value: '5.030054e-14',
    condition_number: '3.958811e+14',
    svd_rank: '10961',
    sprank_minus_rank: '3',
    null_space_dimension: '3',
    full_numerical_rank: 'no',
    svd_gap: '18.551520',
    image_files: 'lhr11c.png,lhr11c_dmperm.png,lhr11c_scc.png,lhr11c_svd.png,lhr11c_APlusAT_graph.gif,lhr11c_graph.gif,',
}
