{
    matrix_id: '745',
    name: 'lhr14c',
    group: 'Mallya',
    description: 'Light hydrocarbon recovery, corrected version of LHR14',
    author: 'J. Mallya',
    editor: 'T. Davis',
    date: '1997',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '14270',
    num_cols: '14270',
    nonzeros: '307858',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '31',
    num_dmperm_blocks: '1556',
    structural_full_rank: 'true',
    structural_rank: '14270',
    pattern_symmetry: '0.007',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    norm: '1.991336e+01',
    min_singular_value: '4.940081e-14',
    condition_number: '4.030978e+14',
    svd_rank: '14267',
    sprank_minus_rank: '3',
    null_space_dimension: '3',
    full_numerical_rank: 'no',
    svd_gap: '4.568443',
    image_files: 'lhr14c.png,lhr14c_dmperm.png,lhr14c_scc.png,lhr14c_svd.png,lhr14c_APlusAT_graph.gif,lhr14c_graph.gif,',
}
