{
    matrix_id: '751',
    name: 'lhr71c',
    group: 'Mallya',
    description: 'Light hydrocarbon recovery, corrected version of LHR71',
    author: 'J. Mallya',
    editor: 'T. Davis',
    date: '1997',
    kind: 'chemical process simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '70304',
    num_cols: '70304',
    nonzeros: '1528092',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '121',
    num_dmperm_blocks: '7066',
    structural_full_rank: 'true',
    structural_rank: '70304',
    pattern_symmetry: '0.002',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    image_files: 'lhr71c.png,lhr71c_dmperm.png,lhr71c_scc.png,lhr71c_APlusAT_graph.gif,lhr71c_graph.gif,',
}
