{
    matrix_id: '1846',
    name: 'wikipedia-20070206',
    group: 'Gleich',
    description: 'Wikipedia pages, A(i,j)=1 if page i links to page j (Feb 6, 2007)',
    author: 'D. Gleich',
    editor: 'T. Davis',
    date: '2007',
    kind: 'directed graph',
    problem_2D_or_3D: '0',
    num_rows: '3566907',
    num_cols: '3566907',
    nonzeros: '45030389',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1203340',
    pattern_symmetry: '0.117',
    numeric_symmetry: '0.117',
    rb_type: 'binary',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'For nodenames, see http://www.cise.ufl.edu/research/sparse/aux/Gleich
Pages outside the "Main", "Category" and "Portal" namespace excluded.
',
}
