{
    matrix_id: '1359',
    name: 'Si10H16',
    group: 'PARSEC',
    description: 'Real-space pseudopotential method. Zhou, Saad, Tiago, Chelikowsky, Univ MN',
    author: 'Y. Zhou, Y. Saad, M. Tiago, J. Chelikowsky',
    editor: 'T. Davis',
    date: '2005',
    kind: 'theoretical/quantum chemistry problem',
    problem_2D_or_3D: '0',
    num_rows: '17077',
    num_cols: '17077',
    nonzeros: '875923',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '17077',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '3.692295e+01',
    min_singular_value: '6.554273e-04',
    condition_number: '5.633416e+04',
    svd_rank: '17077',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
