{
    matrix_id: '1363',
    name: 'Si5H12',
    group: 'PARSEC',
    description: 'Real-space pseudopotential method. Zhou, Saad, Tiago, Chelikowsky, Univ MN',
    author: 'Y. Zhou, Y. Saad, M. Tiago, J. Chelikowsky',
    editor: 'T. Davis',
    date: '2005',
    kind: 'theoretical/quantum chemistry problem',
    problem_2D_or_3D: '0',
    num_rows: '19896',
    num_cols: '19896',
    nonzeros: '738598',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '19896',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '5.856094e+01',
    min_singular_value: '8.033738e-03',
    condition_number: '7.289377e+03',
    svd_rank: '19896',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
