{
    matrix_id: '1368',
    name: 'SiO',
    group: 'PARSEC',
    description: 'Real-space pseudopotential method. Zhou, Saad, Tiago, Chelikowsky, Univ MN',
    author: 'Y. Zhou, Y. Saad, M. Tiago, J. Chelikowsky',
    editor: 'T. Davis',
    date: '2005',
    kind: 'theoretical/quantum chemistry problem',
    problem_2D_or_3D: '0',
    num_rows: '33401',
    num_cols: '33401',
    nonzeros: '1317655',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '33401',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '8.431391e+01',
    min_singular_value: '2.408206e-02',
    condition_number: '3.501109e+03',
    svd_rank: '33401',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
