{
    matrix_id: '1874',
    name: 'hvdc1',
    group: 'HVDC',
    description: 'Power simulation matrix, Alex Wang, Manitoba HVDC, Canada',
    author: 'A. Wang',
    editor: 'T. Davis',
    date: '2007',
    kind: 'power network problem',
    problem_2D_or_3D: '0',
    num_rows: '24842',
    num_cols: '24842',
    nonzeros: '158426',
    num_explicit_zeros: '1555',
    num_strongly_connected_components: '7',
    num_dmperm_blocks: '31',
    structural_full_rank: 'true',
    structural_rank: '24842',
    pattern_symmetry: '0.982',
    numeric_symmetry: '0.099',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 24842-by-1
',
    norm: '3.646457e+05',
    min_singular_value: '7.505943e-03',
    condition_number: '4.858093e+07',
    svd_rank: '24842',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'hvdc1.png,hvdc1_dmperm.png,hvdc1_scc.png,hvdc1_svd.png,hvdc1_APlusAT_graph.gif,hvdc1_graph.gif,',
}
