{
    matrix_id: '1955',
    name: 'Franz2',
    group: 'JGD_Franz',
    description: 'Cohomology of various rings, from Matthias Franz, Univ. Konstanz, Germany',
    author: 'M. Franz',
    editor: 'J.-G. Dumas',
    date: '2008',
    kind: 'combinatorial problem',
    problem_2D_or_3D: '0',
    num_rows: '4032',
    num_cols: '4480',
    nonzeros: '21504',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '4032',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'integer',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Cohomology of various rings, from Matthias Franz, Univ. Konstanz, Germany
From Jean-Guillaume Dumas\' Sparse Integer Matrix Collection,             
http://ljk.imag.fr/membres/Jean-Guillaume.Dumas/simc.html                
                                                                         
Filename in JGD collection: Franz/big2sparse                             
',
    norm: '4.475766e+00',
    min_singular_value: '3.691887e-16',
    condition_number: '12123246388985520',
    svd_rank: '2631',
    sprank_minus_rank: '1401',
    null_space_dimension: '1401',
    full_numerical_rank: 'no',
    svd_gap: '87560205673793.968750',
}
