{
    matrix_id: '1961',
    name: 'Franz8',
    group: 'JGD_Franz',
    description: 'Cohomology of various rings, from Matthias Franz, Univ. Konstanz, Germany',
    author: 'M. Franz',
    editor: 'J.-G. Dumas',
    date: '2008',
    kind: 'combinatorial problem',
    problem_2D_or_3D: '0',
    num_rows: '16728',
    num_cols: '7176',
    nonzeros: '100368',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '7176',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'integer',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Cohomology of various rings, from Matthias Franz, Univ. Konstanz, Germany
From Jean-Guillaume Dumas\' Sparse Integer Matrix Collection,             
http://ljk.imag.fr/membres/Jean-Guillaume.Dumas/simc.html                
                                                                         
Filename in JGD collection: Franz/16728x7176                             
',
    norm: '9.380832e+00',
    min_singular_value: '1.382181e-20',
    condition_number: '6.786977e+20',
    svd_rank: '5463',
    sprank_minus_rank: '1713',
    null_space_dimension: '1713',
    full_numerical_rank: 'no',
    svd_gap: '53575965628802.671875',
}
