{
    matrix_id: '1958',
    name: 'Franz5',
    group: 'JGD_Franz',
    description: 'Cohomology of various rings, from Matthias Franz, Univ. Konstanz, Germany',
    author: 'M. Franz',
    editor: 'J.-G. Dumas',
    date: '2008',
    kind: 'combinatorial problem',
    problem_2D_or_3D: '0',
    num_rows: '7382',
    num_cols: '2882',
    nonzeros: '44056',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '2882',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'integer',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Cohomology of various rings, from Matthias Franz, Univ. Konstanz, Germany
From Jean-Guillaume Dumas\' Sparse Integer Matrix Collection,             
http://ljk.imag.fr/membres/Jean-Guillaume.Dumas/simc.html                
                                                                         
Filename in JGD collection: Franz/7382x2882                              
',
    norm: '1.232883e+01',
    min_singular_value: '4.793191e-18',
    condition_number: '2572154707890732032',
    svd_rank: '2229',
    sprank_minus_rank: '653',
    null_space_dimension: '653',
    full_numerical_rank: 'no',
    svd_gap: '35495939348005.429688',
}
