{
    matrix_id: '923',
    name: 'Alemdar',
    group: 'Alemdar',
    description: 'Finite-element matrix from Bulent Alemdar, RAM International.',
    author: 'B. Alemdar',
    editor: 'T. Davis',
    date: '2003',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '6245',
    num_cols: '6245',
    nonzeros: '42581',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '6',
    num_dmperm_blocks: '6',
    structural_full_rank: 'true',
    structural_rank: '6245',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'integer',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'no',
    norm: '6.951878e+01',
    min_singular_value: '3.298621e-03',
    condition_number: '2.107510e+04',
    svd_rank: '6245',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'Alemdar.png,Alemdar_dmperm.png,Alemdar_svd.png,Alemdar_graph.gif,',
}
