{
    matrix_id: '2263',
    name: '12month1',
    group: 'Buss',
    description: '12 months, 12,646 users from digg.com. Steven Buss',
    author: 'S. Buss',
    editor: 'T. Davis',
    date: '2009',
    kind: 'undirected bipartite graph',
    problem_2D_or_3D: '0',
    num_rows: '12471',
    num_cols: '872622',
    nonzeros: '22624727',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '13',
    num_dmperm_blocks: '82',
    structural_full_rank: 'false',
    structural_rank: '12418',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'binary',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'A full year of data from July 2008 to July 12, 2009, representing 12,646
users from digg.com.  Each row is a user, each column is a web page.    
From Steven Buss, for the Connectious project.                          
',
    norm: '1.524136e+03',
    min_singular_value: '0',
    condition_number: 'Inf',
    svd_rank: '12417',
    sprank_minus_rank: '1',
    null_space_dimension: '54',
    full_numerical_rank: 'no',
    svd_gap: '4631121109884.685547',
}
