{
    matrix_id: '2658',
    name: 'specular',
    group: 'Brogan',
    description: 'specular surface reconstruction problem',
    author: 'J. Brogan',
    editor: 'T. Davis',
    date: '2014',
    kind: 'computer vision problem',
    problem_2D_or_3D: '1',
    num_rows: '477976',
    num_cols: '1600',
    nonzeros: '7647040',
    num_explicit_zeros: '576',
    num_strongly_connected_components: '159',
    num_dmperm_blocks: '4',
    structural_full_rank: 'false',
    structural_rank: '1442',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'specular surface reconstruction problem        
Submitted by Joel Brogan, Notre Dame, July 2014
',
    b_field: 'full 477976-by-2
',
}
