{
    matrix_id: '1938',
    name: 'bibd_49_3',
    group: 'JGD_BIBD',
    description: 'Balanced Incomplete Block Design from Mark Giesbrecht, Univ. of Waterloo',
    author: 'M. Giesbrecht',
    editor: 'J.-G. Dumas',
    date: '2008',
    kind: 'combinatorial problem',
    problem_2D_or_3D: '0',
    num_rows: '1176',
    num_cols: '18424',
    nonzeros: '55272',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '1176',
    pattern_symmetry: '0.000',
    numeric_symmetry: '0.000',
    rb_type: 'binary',
    structure: 'rectangular',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Balanced Incomplete Block Design from Mark Giesbrecht, Univ. of Waterloo
From Jean-Guillaume Dumas\' Sparse Integer Matrix Collection,            
http://ljk.imag.fr/membres/Jean-Guillaume.Dumas/simc.html               
                                                                        
Filename in JGD collection: BIBD/bibd_49_3_1176x18424.sms               
',
    norm: '1.187434e+01',
    min_singular_value: '6.708204e+00',
    condition_number: '1.770122e+00',
    svd_rank: '1176',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'bibd_49_3.png,bibd_49_3_svd.png,bibd_49_3_graph.gif,',
}
