{
    matrix_id: '1939',
    name: 'bibd_81_2',
    group: 'JGD_BIBD',
    description: 'Balanced Incomplete Block Design from Mark Giesbrecht, Univ. of Waterloo',
    author: 'M. Giesbrecht',
    editor: 'J.-G. Dumas',
    date: '2008',
    kind: 'combinatorial problem',
    problem_2D_or_3D: '0',
    num_rows: '3240',
    num_cols: '3240',
    nonzeros: '3240',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '3240',
    num_dmperm_blocks: '3240',
    structural_full_rank: 'true',
    structural_rank: '3240',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'binary',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    notes: 'Balanced Incomplete Block Design from Mark Giesbrecht, Univ. of Waterloo
From Jean-Guillaume Dumas\' Sparse Integer Matrix Collection,            
http://ljk.imag.fr/membres/Jean-Guillaume.Dumas/simc.html               
                                                                        
Filename in JGD collection: BIBD/bibd_81_2_3240x3240.sms                
',
    norm: '1',
    min_singular_value: '1',
    condition_number: '1',
    svd_rank: '3240',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'bibd_81_2.png,bibd_81_2_dmperm.png,bibd_81_2_svd.png,bibd_81_2_graph.gif,',
}
