{
    matrix_id: '1199',
    name: 'Hamrle1',
    group: 'Hamrle',
    description: 'Hamrle/Hamrle1 circuit simulation matrix',
    author: 'J. Hamrle',
    editor: 'T. Davis',
    date: '2004',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '32',
    num_cols: '32',
    nonzeros: '98',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '32',
    pattern_symmetry: '0.065',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'sparse 32-by-1
',
    norm: '3.135875e+02',
    min_singular_value: '4.976421e-04',
    condition_number: '6.301466e+05',
    svd_rank: '32',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'Hamrle1.png,Hamrle1_svd.png,Hamrle1_APlusAT_graph.gif,Hamrle1_graph.gif,',
}
