{
    matrix_id: '1200',
    name: 'Hamrle2',
    group: 'Hamrle',
    description: 'Hamrle/Hamrle2 circuit simulation matrix',
    author: 'J. Hamrle',
    editor: 'T. Davis',
    date: '2004',
    kind: 'circuit simulation problem',
    problem_2D_or_3D: '0',
    num_rows: '5952',
    num_cols: '5952',
    nonzeros: '22162',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '5952',
    pattern_symmetry: '0.001',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'sparse 5952-by-1
',
    norm: '1.102767e+02',
    min_singular_value: '1.647870e-03',
    condition_number: '6.692075e+04',
    svd_rank: '5952',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'Hamrle2.png,Hamrle2_svd.png,Hamrle2_APlusAT_graph.gif,Hamrle2_graph.gif,',
}
