{
    name: 'FlowIPM22',
    num_matrices: '11',
    notes: 'FlowIPM22: Laplacians from Newton-Steps of Maxflow Short-step IPM on Chimera Graphs

A collection of matrices arising from solving maximum flow problems on a
diverse collection of graphs (known as Chimeras) using a short-step
interior point method. The Laplacian matrices arise when computing Newton
steps of the interior point method.

The matrices are symmetric graph Laplacians, meaning they are symmetric
diagonally dominant matrices with non-positive off-diagonals and row sums
equal to zero.

Generated by Yuan Gao, Rasmus Kyng, and Daniel Spielman. 2022.

References:

data set: https://www.spe.org/web/csp/datasets/set02.htm

An Algebraic Sparsified Nested Dissection Algorithm Using Low-Rank
Approximations Léopold Cambier, Chao Chen, Erik G. Boman, Sivasankaran
Rajamanickam, Raymond S. Tuminaro, and Eric Darve
SIAM Journal on Matrix Analysis and Applications, vol 41, no 2,
pp 715-746, 2020.  https://epubs.siam.org/doi/10.1137/19M123806X
',

}

