{
    matrix_id: '1212',
    name: 'powersim',
    group: 'LiuWenzhuo',
    description: 'Power simulation matrix from Liu Wenzhuo, EPRI, China',
    author: 'W. Liu',
    editor: 'T. Davis',
    date: '2004',
    kind: 'power network problem',
    problem_2D_or_3D: '0',
    num_rows: '15838',
    num_cols: '15838',
    nonzeros: '64424',
    num_explicit_zeros: '3138',
    num_strongly_connected_components: '3600',
    num_dmperm_blocks: '3600',
    structural_full_rank: 'true',
    structural_rank: '15838',
    pattern_symmetry: '0.591',
    numeric_symmetry: '0.534',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 15838-by-1
',
    norm: '7.500553e+04',
    min_singular_value: '1.627414e-04',
    condition_number: '4.608877e+08',
    svd_rank: '15838',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
