{
    matrix_id: '2655',
    name: 'LeGresley_2508',
    group: 'LeGresley',
    description: 'Power flow analysis of an electrical grid',
    author: 'P. LeGresley',
    editor: 'T. Davis',
    date: '2013',
    kind: 'power network problem',
    problem_2D_or_3D: '0',
    num_rows: '2508',
    num_cols: '2508',
    nonzeros: '16727',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '381',
    num_dmperm_blocks: '381',
    structural_full_rank: 'true',
    structural_rank: '2508',
    pattern_symmetry: '0.838',
    numeric_symmetry: '0.256',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Power flow analyses of electrical grids.           
Submitted by Patrick LeGresley, Stanford, July 2013
',
    b_field: 'full 2508-by-1
',
}
