{
    matrix_id: '2656',
    name: 'LeGresley_4908',
    group: 'LeGresley',
    description: 'Power flow analysis of an electrical grid',
    author: 'P. LeGresley',
    editor: 'T. Davis',
    date: '2013',
    kind: 'power network problem',
    problem_2D_or_3D: '0',
    num_rows: '4908',
    num_cols: '4908',
    nonzeros: '30482',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '192',
    num_dmperm_blocks: '193',
    structural_full_rank: 'true',
    structural_rank: '4908',
    pattern_symmetry: '0.977',
    numeric_symmetry: '0.030',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Power flow analyses of electrical grids.           
Submitted by Patrick LeGresley, Stanford, July 2013
',
    b_field: 'full 4908-by-1
',
}
