{
    matrix_id: '1203',
    name: 'gyro_m',
    group: 'Oberwolfach',
    description: 'Oberwolfach: butterfly gyro, M matrix',
    author: 'D. Billger',
    editor: 'E. Rudnyi',
    date: '2004',
    kind: 'duplicate model reduction problem',
    problem_2D_or_3D: '1',
    num_rows: '17361',
    num_cols: '17361',
    nonzeros: '340431',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '3',
    num_dmperm_blocks: '3',
    structural_full_rank: 'true',
    structural_rank: '17361',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '1.887687e-07',
    min_singular_value: '7.538740e-14',
    condition_number: '2.503983e+06',
    svd_rank: '17361',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
