{
    matrix_id: '1436',
    name: 'inlet',
    group: 'Oberwolfach',
    description: 'Oberwolfach: supersonic engine inlet',
    author: 'K. Willcox, G. Lassaux, D. Gratton',
    editor: 'E. Rudnyi',
    date: '2006',
    kind: 'model reduction problem',
    problem_2D_or_3D: '1',
    num_rows: '11730',
    num_cols: '11730',
    nonzeros: '328323',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '331',
    num_dmperm_blocks: '331',
    structural_full_rank: 'true',
    structural_rank: '11730',
    pattern_symmetry: '0.608',
    numeric_symmetry: '0.000',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    notes: 'Primary matrix in this model reduction problem is the Oberwolfach A matrix
',
    aux_fields: 'E: sparse 11730-by-11730
B: sparse 11730-by-2
C: sparse 1-by-11730
',    norm: '6.573419e+00',
    min_singular_value: '1.693581e-06',
    condition_number: '3.881372e+06',
    svd_rank: '11730',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
