{
    matrix_id: '1205',
    name: 't2dah_e',
    group: 'Oberwolfach',
    description: 'Oberwolfach: micropyros thruster, E matrix',
    author: 'E. Rudnyi',
    editor: 'E. Rudnyi',
    date: '2004',
    kind: 'duplicate model reduction problem',
    problem_2D_or_3D: '1',
    num_rows: '11445',
    num_cols: '11445',
    nonzeros: '176117',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '11445',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '2.286824e-05',
    min_singular_value: '3.163454e-14',
    condition_number: '7.228881e+08',
    svd_rank: '11445',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
