{
    matrix_id: '1211',
    name: 't3dl_e',
    group: 'Oberwolfach',
    description: 'Oberwolfach: micropyros thruster, E matrix',
    author: 'E. Rudnyi',
    editor: 'E. Rudnyi',
    date: '2004',
    kind: 'duplicate model reduction problem',
    problem_2D_or_3D: '1',
    num_rows: '20360',
    num_cols: '20360',
    nonzeros: '20360',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '20360',
    num_dmperm_blocks: '20360',
    structural_full_rank: 'true',
    structural_rank: '20360',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '2.163773e-06',
    min_singular_value: '3.587500e-10',
    condition_number: '6.031422e+03',
    svd_rank: '20360',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
}
