{
    matrix_id: '938',
    name: 'nd12k',
    group: 'ND',
    description: 'ND problem set, matrix nd12k',
    author: 'author unknown',
    editor: 'T. Davis',
    date: '2003',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '36000',
    num_cols: '36000',
    nonzeros: '14220946',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '36000',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    norm: '1.382280e+02',
    min_singular_value: '1.038697e-05',
    condition_number: '1.330782e+07',
    svd_rank: '36000',
    sprank_minus_rank: '0',
    null_space_dimension: '0',
    full_numerical_rank: 'yes',
    image_files: 'nd12k.png,nd12k_svd.png,nd12k_graph.gif,',
}
