{
    matrix_id: '939',
    name: 'nd24k',
    group: 'ND',
    description: 'ND problem set, matrix nd24k',
    author: 'author unknown',
    editor: 'T. Davis',
    date: '2003',
    kind: '2D/3D problem',
    problem_2D_or_3D: '1',
    num_rows: '72000',
    num_cols: '72000',
    nonzeros: '28715634',
    num_explicit_zeros: '0',
    num_strongly_connected_components: '1',
    num_dmperm_blocks: '1',
    structural_full_rank: 'true',
    structural_rank: '72000',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'yes',
    positive_definite: 'yes',
    image_files: 'nd24k.png,nd24k_graph.gif,',
}
