{
    matrix_id: '955',
    name: '2D_54019_highK',
    group: 'Schenk_IBMSDS',
    description: 'Olaf Schenk, Univ. Basel: IBM TJ Watson, Yorktown, semiconductor device',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2003',
    kind: 'semiconductor device problem',
    problem_2D_or_3D: '1',
    num_rows: '54019',
    num_cols: '54019',
    nonzeros: '486129',
    num_explicit_zeros: '510285',
    num_strongly_connected_components: '7157',
    num_dmperm_blocks: '7157',
    structural_full_rank: 'true',
    structural_rank: '54019',
    pattern_symmetry: '0.998',
    numeric_symmetry: '0.190',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 54019-by-1
',
}
