{
    matrix_id: '958',
    name: 'ibm_matrix_2',
    group: 'Schenk_IBMSDS',
    description: 'Olaf Schenk, Univ. Basel: IBM TJ Watson, Yorktown, semiconductor device',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2003',
    kind: 'semiconductor device problem',
    problem_2D_or_3D: '1',
    num_rows: '51448',
    num_cols: '51448',
    nonzeros: '537038',
    num_explicit_zeros: '519572',
    num_strongly_connected_components: '6627',
    num_dmperm_blocks: '6627',
    structural_full_rank: 'true',
    structural_rank: '51448',
    pattern_symmetry: '0.992',
    numeric_symmetry: '0.186',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 51448-by-1
',
}
