{
    matrix_id: '959',
    name: 'matrix_9',
    group: 'Schenk_IBMSDS',
    description: 'Olaf Schenk, Univ. Basel: IBM TJ Watson, Yorktown, semiconductor device',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2003',
    kind: 'semiconductor device problem',
    problem_2D_or_3D: '1',
    num_rows: '103430',
    num_cols: '103430',
    nonzeros: '1205518',
    num_explicit_zeros: '916032',
    num_strongly_connected_components: '4059',
    num_dmperm_blocks: '4059',
    structural_full_rank: 'true',
    structural_rank: '103430',
    pattern_symmetry: '0.997',
    numeric_symmetry: '0.174',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 103430-by-1
',
}
