{
    matrix_id: '960',
    name: 'matrix-new_3',
    group: 'Schenk_IBMSDS',
    description: 'Olaf Schenk, Univ. Basel: IBM TJ Watson, Yorktown, semiconductor device',
    author: 'IBM',
    editor: 'O. Schenk',
    date: '2003',
    kind: 'semiconductor device problem',
    problem_2D_or_3D: '1',
    num_rows: '125329',
    num_cols: '125329',
    nonzeros: '893984',
    num_explicit_zeros: '1784766',
    num_strongly_connected_components: '46658',
    num_dmperm_blocks: '46658',
    structural_full_rank: 'true',
    structural_rank: '125329',
    pattern_symmetry: '0.987',
    numeric_symmetry: '0.283',
    rb_type: 'real',
    structure: 'unsymmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
    b_field: 'full 125329-by-1
',
}
