{
    matrix_id: '1876',
    name: 'kkt_power',
    group: 'Zaoui',
    description: 'Optimal power flow, nonlinear optimization (KKT), Fabrice Zaoui, RTE, France',
    author: 'F. Zaoui',
    editor: 'T. Davis',
    date: '2007',
    kind: 'optimization problem',
    problem_2D_or_3D: '0',
    num_rows: '2063494',
    num_cols: '2063494',
    nonzeros: '12771361',
    num_explicit_zeros: '1841302',
    num_strongly_connected_components: '9611',
    num_dmperm_blocks: '9733',
    structural_full_rank: 'true',
    structural_rank: '2063494',
    pattern_symmetry: '1.000',
    numeric_symmetry: '1.000',
    rb_type: 'real',
    structure: 'symmetric',
    cholesky_candidate: 'no',
    positive_definite: 'no',
}
